Picture improvements
xbmc/xbmc pull request #10484
Opened 2016-09-18 10:41 UTC by garbear

Just some general cleanup in the pictures code. As discussed at devcon, there's lots of low-hanging fruit that is ripe for small improvements. This is a step in that direction.

2016-09-18 11:27 UTC, xhaggi commented on xbmc/pictures/GUIWindowPictures.cpp
> +  if (StringUtils::EqualsNoCase(dir, "plugins") ||
you've changed the implementation from equals to equals no case and not only the readability ;)

2016-09-18 11:27 UTC, xhaggi commented on xbmc/pictures/GUIWindowPictures.cpp
> +  if (StringUtils::EqualsNoCase(dir, "plugins") ||
not sure if we really want it to be changed

2016-09-18 12:30 UTC, garbear commented on xbmc/pictures/GUIWindowPictures.cpp
> +  if (StringUtils::EqualsNoCase(dir, "plugins") ||
Doesn't the `StringUtils::ToLower(lower)` have the effect of a case-insensitive comparison? So this isn't a change in functionality, is it?

2016-09-18 12:41 UTC, xhaggi commented on xbmc/pictures/GUIWindowPictures.cpp
> +  if (StringUtils::EqualsNoCase(dir, "plugins") ||
ohh sorry for the noise, only saw the conditions changed 😀

2016-09-18 14:47 UTC, Montellese commented on xbmc/pictures/GUIWindowPictures.cpp
> +  {
Why the curly braces? That doesn't fit our coding style.

2016-09-18 14:47 UTC, Montellese commented on xbmc/windows/GUIMediaWindow.cpp
> +  {
Same as above with curly braces.

2016-09-18 14:48 UTC, Montellese requested changes
Looks good apart from the cosmetics.

2016-09-18 17:17 UTC, Paxxi commented on xbmc/pictures/GUIViewStatePictures.cpp
> +  if (pictureSources == nullptr)
You do not need the explicit nullptr check, `if(pictureSources) ` is fine

2016-09-18 17:20 UTC, Paxxi requested changes
Add the braces montellese asks for and it should be good

2016-09-18 19:07 UTC, garbear commented on xbmc/pictures/GUIViewStatePictures.cpp
> +  if (pictureSources == nullptr)
i'm an explicit programmer

2016-09-18 19:42 UTC, Paxxi commented on xbmc/pictures/GUIViewStatePictures.cpp
> +  if (pictureSources == nullptr)
Yup, both are fine, just a matter of taste

2016-09-21 14:45 UTC, garbear commented
braces removed. jenkins build this please

2016-09-21 15:40 UTC, merged