[mingwlibs] a set of small fixes for ffmpeg build proc.
xbmc/xbmc pull request #10497
Opened 2016-09-19 09:51 UTC by afedchin

This fixes several issues with ffmpeg build for windows:
- [x] Fixed build ffmpeg via MSVC toolchain
- [x] Fixed build hanging if ffmpeg build failed.
- [x] Added liblzma to dependencies which adds lzma support to ffmpeg.
- [x] Bump gnutls version which speed up build (require upload builded lib to our mirror)

@Paxxi @FernetMenta take a look please.

2016-09-19 09:52 UTC, afedchin commented
jenkins build this please

2016-09-19 10:08 UTC, FernetMenta commented on tools/buildsteps/win32/fmpeg_options.txt
> +--disable-dxva2
@afedchin why do you disable dxva2 here?

2016-09-19 10:09 UTC, fritsch commented on tools/buildsteps/win32/fmpeg_options.txt
> +--disable-dxva2
We use: d3d11va afaik --dxva2 is the old dx9 method, right?

2016-09-19 10:10 UTC, afedchin commented on tools/buildsteps/win32/fmpeg_options.txt
> +--disable-dxva2
actually it's not needed anymore since we switched to d3d11va

2016-09-19 10:15 UTC, afedchin commented on tools/buildsteps/win32/fmpeg_options.txt
> +--disable-dxva2
@fritsch you are right. dxva2 is old dx9 api

2016-09-19 16:10 UTC, Paxxi commented
Got cut of, was doing review on the plane.  Looks good, will try to test it out tomorrow

2016-09-20 07:05 UTC, akva2 commented
probably for later, but wouldn't moving it from buildsteps to main project make more sense now that it builds with msvc? it would maximize the code shared with the other platforms and such.

2016-09-20 07:15 UTC, Paxxi commented
@akva2 yes that is what I think as well, we still need msys2 for building it but can link with our openssl and zlib and such minimizing depends and downloads and speeding up jenkins builds. Other upside is easier debugging with proper pdb  files. 
Should be a goal for v18

2016-09-20 07:35 UTC, akva2 commented
all game add-ons build in a mingw environment orchestrated by cmake. i believe @montellese make it flexible enough to be reused anywhere.

2016-09-20 15:36 UTC, Paxxi requested changes
Seems to have built fine now. Thank you for fixing this.

2016-09-20 15:42 UTC, Paxxi commented
@akva2 right, I didn't mean to get rid of msys or mingw but that we should build ffmpeg with msvc by default. Would probably require splitting make-mingwlibs into two, one for ffmpeg and one for libdvd as they need different compilers and paths set up.

2016-09-21 08:02 UTC, afedchin commented
jenkins build this please

2016-09-21 13:33 UTC, merged

2016-09-24 07:24 UTC, Voyager1 commented
can someone take care of the missing gnutls dependency on the mirror?

2016-09-24 11:35 UTC, afedchin commented
@MartijnKaijser please upload this package https://www.dropbox.com/s/tzizdldyvp0dn7p/i686-gnutls-3.4.14-static.tar.gz?dl=0 to the http://mirror.kodi.tv/build-deps/win32/msys2/locals/

2016-09-24 11:37 UTC, MartijnKaijser commented
@Voyager1 @afedchin done (takes about 30 minutes from now)

2016-09-24 14:34 UTC, Voyager1 commented
thanks!