Check if core_pattern contains a pipe to a program
xbmc/xbmc pull request #10490
Opened 2016-09-18 17:30 UTC by veger

## Description
When kodi crashed I accidentally noticed an error in the terminal which is the result of unexpected content of core_pattern

For Ubuntu 16.04 core_pattern contains `|/usr/share/apport/apport %p %s %c %P`
For Arch Linux core_pattern contains `|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %e`

Both contain a 'pipe to a program' (see http://man7.org/linux/man-pages/man5/core.5.html) and cannot be used.

## Motivation and Context

Besides core_pattern not usable, the error is a result of the `|` character, which is interpreted as a pipe.
The the test lien becomes something like

    [ -d |blahblah ] 

due to the lack of double quotes around `$(dirname blah )`

This PR fixes
* The unusable 'pipe to a program'
* The lack of double quotes to make unexpected situation less error prone

## How Has This Been Tested?

I tested the commands in a terminal (as I cannot let kodi crash on command...)

    $ if [[ "$(cat /proc/sys/kernel/core_pattern)" != \|* ]]; then echo 1; else echo 0; fi
    0

Where 0 means that the test failed and core_pattern is not used to gather a core dump

## Types of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2016-09-18 18:50 UTC, Memphiz commented
Thx for your contribution. Well i tried to read this stuff up and sort of got what the core_pattern is about. In the end i think wsnipex has to do the proper review of it. I think the fix is valid - but i don't know if it results in not have a core dump at all in the end or if just the filename of it is different. Please be a bit patient until wsnipex has some time to review it. Thx.

2016-09-18 19:49 UTC, wsnipex commented on tools/Linux/kodi.sh.in
> +    if [[ "$(cat /proc/sys/kernel/core_pattern)" != \|* ]]; then
please use single [ brackets, [[ is not posix and not supported by dash, which is ubuntus default /bin/sh

2016-09-18 19:53 UTC, wsnipex requested changes
thanks, looks good once the brackets are changed.

btw, you can crash kodi by sending it a SIGSEGV

e.g. kill -SIGSEGV $(pidof kodi.bin)

2016-09-18 21:53 UTC, veger commented
The double brackets were required for (regex) pattern. I have replaced it by a `cut` command that grabs the first char, so we can check it without the regex.

2016-09-19 08:53 UTC, wsnipex approved these changes

2016-09-19 08:56 UTC, wsnipex commented
thanks, looks fine now.

@Memphiz the case that is fixed here is when no core file can be generated, because apport or systemd intercept it. In this case we never get a stack trace, nothing we can do.
Workaround: tell users to stop apport

2016-09-19 11:20 UTC, merged