Fix potential SQL constraint integrity violation in the PVR database
xbmc/xbmc pull request #10507
Opened 2016-09-19 17:57 UTC by Jalle19

Supersedes #8963
Fixes trac #16031
Closes kodi-pvr/pvr.hts#172

This fixes the problem without bumping the database version so it should be more possibly to get it merged for V17.

Basically the code that persists channels has been made smarter. Instead of just blindly looking at the primary key stored in the object we query the database to check if a channel with the unique ID and client ID already exists. If it does, we update that channel, if not we create a new channel. There is more background information in the referenced PRs.

This fix also has the added side-effect that it increases database performance. While a new SELECT statement has been added, we now do an UPDATE instead of a REPLACE INTO which prevents indexes from having to be re-calculated (REPLACE INTO basically does a DELETE followed by an INSERT). This also means we don't need to worry about the channel ID changing after the channel has been updated (which was a side effect of using REPLACE INTO).

@ksooo now's a good time to test that new review feature, @Glenn-1990 can you runtime test this? I tested with your reproducible test case (change a channel's service from TV to radio while Kodi is off) and it seems to fix the issue.

2016-09-19 18:21 UTC, xhaggi commented on xbmc/pvr/PVRDatabase.cpp
> +        channel.ChannelID(), channel.EpgID(), channel.UniqueID(), channel.ClientID());
no need to update iUniqueId and iClientId as they are part of the where condition.

2016-09-19 18:21 UTC, xhaggi requested changes

2016-09-19 18:42 UTC, bkuhls commented
@Jalle19: You referenced pull request 8963 but I think you mean PR 8953, right?

2016-09-19 20:06 UTC, Jalle19 commented
@bkuhls you're right, I meant https://github.com/xbmc/xbmc/pull/8953

2016-09-19 20:07 UTC, Jalle19 commented on xbmc/pvr/PVRDatabase.cpp
> +        channel.ChannelID(), channel.EpgID(), channel.UniqueID(), channel.ClientID());
You're right, that's a left over from when it used REPLACE INTO

2016-09-19 20:16 UTC, Glenn-1990 commented
@Jalle19 thanks for this, now I can remove the "delete pvr database" script from my clients. I will test this tomorrow. :-)

2016-09-19 21:25 UTC, Jalle19 commented on xbmc/pvr/PVRDatabase.cpp
> +        channel.ChannelID(), channel.EpgID(), channel.UniqueID(), channel.ClientID());
Fixed in the latest fixup commit

2016-09-19 21:30 UTC, xhaggi approved these changes
thx

2016-09-20 11:54 UTC, Jalle19 commented
jenkins build this please

2016-09-20 12:41 UTC, Memphiz commented
@Jalle19 i am currently working on new jenkins slave and need the server for some more time. I have canceled your build request and will mail around once i am done.

2016-09-20 12:50 UTC, ksooo commented on xbmc/pvr/PVRDatabase.h
> +    bool ChannelExists(int iClientId, int iUniqueId);
shouldn't this member function be 'const'?

2016-09-20 12:51 UTC, ksooo commented on xbmc/pvr/PVRDatabase.cpp
> +  std::string strQuery = PrepareSQL("SELECT idChannel FROM channels WHERE iClientId = %d AND iUniqueId = %d",
const std::string strQuery(Prepare... ?

2016-09-20 12:53 UTC, ksooo approved these changes
despite from const nitpicking this is looking good to me, though i have not runtime tested it.

2016-09-20 14:38 UTC, Jalle19 commented on xbmc/pvr/PVRDatabase.h
> +    bool ChannelExists(int iClientId, int iUniqueId);
I would like that too, but all database access methods are non-const only.

2016-09-20 14:38 UTC, Jalle19 commented on xbmc/pvr/PVRDatabase.cpp
> +  std::string strQuery = PrepareSQL("SELECT idChannel FROM channels WHERE iClientId = %d AND iUniqueId = %d",
Sure

2016-09-20 14:39 UTC, Jalle19 commented
@Memphiz okay, no problem.

2016-09-20 15:16 UTC, Glenn-1990 commented
@Jalle19 run time tested: reproduced the issue and restarted kodi several times, PVR manager was not starting up, then applied your commits and it came back to life ;-)

2016-09-20 15:19 UTC, Glenn-1990 commented
Btw, do we need the same for channel groups?

2016-09-20 15:22 UTC, Jalle19 commented
I need to check, I've never thought about that scenario.

2016-09-20 15:23 UTC, ksooo commented on xbmc/pvr/PVRDatabase.h
> +    bool ChannelExists(int iClientId, int iUniqueId);
yikes. So, leave it like it is, i'd say.

2016-09-21 12:22 UTC, Jalle19 commented
jenkins build this please

2016-09-21 18:42 UTC, Jalle19 commented
jenkins build this please

2016-09-22 07:20 UTC, Jalle19 commented
@ksooo good to go?

2016-09-22 07:32 UTC, ksooo commented
> Btw, do we need the same for channel groups?

 what about this? supposed to be handled in another PR?

2016-09-22 07:56 UTC, Jalle19 commented
Yeah I'd say so, I'm not even sure if there's an issue in that regard yet.

2016-09-22 08:01 UTC, Jalle19 commented
@ksooo the code for persisting channel groups is very similar to what we had here. I would still prefer to get this merged so I have time to think of a proper solution for the groups part, if that's okay with you?

2016-09-22 08:05 UTC, Jalle19 commented
Actually the persisting of groups cannot have this exact same issue because there's no `UNIQUE INDEX` that could trigger an integrity violation. It still uses `REPLACE INTO` though which is not nice, but the performance impact is much lesser since one can assume that `num(channels) > num(groups)`.

2016-09-22 08:14 UTC, ksooo commented
> Actually the persisting of groups cannot have this exact same issue

 thanks for the update on this.

2016-09-22 08:14 UTC, merged