Create italian.xml
xbmc/xbmc pull request #10545
Opened 2016-09-23 14:09 UTC by emacann

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2016-09-28 08:49 UTC, mak77 commented
which keyboard is this one? it looks different from the usual italian layout (ù position, and missing ,.- keys?)
https://commons.wikimedia.org/wiki/File:Italian_Keyboard_layout.svg

2016-09-28 09:35 UTC, hudokkow commented
ping @phate89 for review

2016-09-28 12:09 UTC, phate89 requested changes
Thanks for your contribution..It's ok excluding minor fixes needed

2016-09-28 12:09 UTC, phate89 commented on system/keyboardlayouts/italian.xml
> +      <row>qwertyuiopèù</row>
The ù is in the wrong place..It's in the row under..

2016-09-28 12:09 UTC, phate89 commented on system/keyboardlayouts/italian.xml
> +      <row>zxcvbnm</row>
you can add also the 3 characters ,.-

2016-09-29 07:44 UTC, Rechi commented on system/keyboardlayouts/italian.xml
> +      <row>1234567890'</row>
maybe replace `'` with `?^`

2016-09-29 07:44 UTC, Rechi commented on system/keyboardlayouts/italian.xml
> +      <row>ASDFGHJKL</row>
maybe add `ç°§`

2016-09-29 07:44 UTC, Rechi commented on system/keyboardlayouts/italian.xml
> +      <row>ZXCVBNM</row>
maybe add `;:_`

2016-10-02 12:40 UTC, phate89 commented
@emacann also rechi points are good..

2016-10-02 12:52 UTC, emacann commented
Yes, I was aware of that but I've had a lot of problems lately. Fixing right now!

2016-10-04 08:22 UTC, merged