Playlistorder spinner
xbmc/xbmc pull request #10594
Opened 2016-09-29 23:51 UTC by phil65

Next one...this time the order-by button in Smartplaylisteditor.
this PR adds the same header file to GUIDialogSmartPlaylistEditor.cpp as https://github.com/xbmc/xbmc/pull/10593, so remind me to update the PR which gets pulled last. :)

2016-09-30 01:31 UTC, phil65 commented
Added another commit which converts two more buttons.
If it helps testing or whatever I could also merge the other PR´s into this one.

2016-09-30 01:35 UTC, MilhouseVH commented
Merge them and I'll include them in test builds - keeping them separate makes that a bit trickier (as they're both patching the same code).

2016-09-30 01:38 UTC, phil65 commented
@MilhouseVH done.

2016-09-30 02:14 UTC, MilhouseVH commented
Thanks, will include in the next build.

2016-09-30 02:37 UTC, phil65 commented
...aaand another commit.

2016-10-01 09:04 UTC, Montellese requested changes
Looks good apart from the minors. This will require all skins to adjust the dialog right?

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistEditor.cpp
> +  else if (item < 0 || item > static_cast<int>(m_playlist.m_ruleCombination.m_rules.size()))
Please move this condition to the top. IMO early returns should always be at the top if there are multiple conditions. Furthermore after an early return you don't need an `else`.

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistEditor.cpp
> +    if (CGUIDialogSmartPlaylistRule::EditRule(rule,m_playlist.GetType()))
Space after `rule,`

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistEditor.cpp
> +  const int limits[] = {0, 10, 25, 50, 100, 250, 500, 1000, -1 };
You can use an `std::vector` to get rid of the awkward `-1` special item and then you can use a ranged `for` loop.

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistEditor.cpp
> +  if (CGUIKeyboardFactory::ShowAndGetInput(name, CVariant{g_localizeStrings.Get(16012)}, false))
You can use `CVariant{ 16012 }` directly. The `CGUIKeyboardFactory::ShowAndGetInput()` knows how to deal with that.

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistEditor.cpp
> +std::vector<CGUIDialogSmartPlaylistEditor::PLAYLIST_TYPE> CGUIDialogSmartPlaylistEditor::GetAllowedTypes(std::string mode)
`const std::string& mode`

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistRule.cpp
> +std::vector<std::pair<std::string, int>> CGUIDialogSmartPlaylistRule::GetValidOperators(CSmartPlaylistRule rule)
`const CSmartPlaylistRule& rule`

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistEditor.cpp
> +  CGUIDialogSelect* dialog = (CGUIDialogSelect*)g_windowManager.GetWindow(WINDOW_DIALOG_SELECT);
Please use `static_cast`.

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistEditor.cpp
> +  CGUIDialogSelect* dialog = (CGUIDialogSelect*)g_windowManager.GetWindow(WINDOW_DIALOG_SELECT);
`static_cast`

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistEditor.cpp
> +  CGUIDialogSelect* dialog = (CGUIDialogSelect*)g_windowManager.GetWindow(WINDOW_DIALOG_SELECT);
`static_cast`

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistEditor.cpp
> +
Unneeded newline

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistEditor.cpp
> +    SET_CONTROL_LABEL2(CONTROL_MATCH, g_localizeStrings.Get(21426));
Could you add comments to these two `SET_CONTROL_LABEL2` lines to know what the new labels are?

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistEditor.cpp
> +  for (auto allowedType: allowedTypes)
Please use curly braces (even though the original code was missing them as well).

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistRule.cpp
> +
Unneeded newline

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistRule.cpp
> +  std::vector<Field> fields = CSmartPlaylistRule::GetFields(m_type);
You could use `const auto` here.

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistRule.cpp
> +  CGUIDialogSelect* dialog = (CGUIDialogSelect*)g_windowManager.GetWindow(WINDOW_DIALOG_SELECT);
`static_cast`

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistRule.cpp
> +  for (unsigned int i = 0; i < fields.size(); i++)
ranged `for` loop.

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistRule.cpp
> +  UpdateButtons();
Please throw in some empty lines in this code block (e.g. before an `if` statement and after the early return). It's hard to read if it's so dense.

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistRule.cpp
> +
Unneeded newline

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistRule.cpp
> +  CGUIDialogSelect* dialog = (CGUIDialogSelect*)g_windowManager.GetWindow(WINDOW_DIALOG_SELECT);
`static_cast`

2016-10-01 09:04 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistRule.cpp
> +  std::vector< std::pair<std::string, int> > labels = GetValidOperators(m_rule);
`const auto`

2016-10-01 17:24 UTC, phil65 commented on xbmc/dialogs/GUIDialogSmartPlaylistRule.cpp
> +  for (unsigned int i = 0; i < fields.size(); i++)
i need `i`... and I would need sth like `for count, element in enumerate(fields)` How do I do that in Cpp? :)

2016-10-01 17:49 UTC, phil65 commented
@Montellese 
addressed all of your comments in a separate commit, except for the loops, see question above.

Yes, this needs some trivial changes for all skins.

2016-10-01 17:53 UTC, phil65 commented on xbmc/dialogs/GUIDialogSmartPlaylistEditor.cpp
> +{
Should I move this method somewhere else? The method is static and perhaps better belongs to CSmartPlaylist?

2016-10-01 18:38 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistRule.cpp
> +  for (unsigned int i = 0; i < fields.size(); i++)
Right it doesn't work with ranged `for` loop. But if you use iterators there's a method called `std::distance()` and you use it like `size_t pos = std::distance(fields.begin(), field);` where `field` is the iterator.

2016-10-02 13:14 UTC, phil65 commented on xbmc/dialogs/GUIDialogSmartPlaylistRule.cpp
> +  for (unsigned int i = 0; i < fields.size(); i++)
does that really make the code easier in this case? :)

2016-10-02 13:33 UTC, Paxxi commented on xbmc/dialogs/GUIDialogSmartPlaylistEditor.cpp
> +  const int limits[] = {0, 10, 25, 50, 100, 250, 500, 1000, -1 };
Ranged for loop works for plain array as well, the requirements are that std:begin and end exists and those are implemented by default

2016-10-02 20:21 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistRule.cpp
> +  for (unsigned int i = 0; i < fields.size(); i++)
It makes it more generic in case something around it changes.

2016-10-02 20:21 UTC, Montellese commented on xbmc/dialogs/GUIDialogSmartPlaylistEditor.cpp
> +  const int limits[] = {0, 10, 25, 50, 100, 250, 500, 1000, -1 };
@Paxxi: correct but the `-1` would have to go in that case as well which is my main point/concern.

2016-10-02 21:16 UTC, phil65 commented
@Montellese switched to using iterators. Anything else?
Thx for reviewing.

2016-10-04 19:21 UTC, phil65 commented
jenkins build this please

2016-10-05 20:33 UTC, phil65 commented
@Montellese 	general skinner´s sentiment was to merge this, even though we´re already in a later beta, since needed skin changes are very trivial and our skinners are quite good in keeping up with these changes.	Are you fine with this?

2016-10-06 17:24 UTC, Montellese commented
Fine with me but don't forget to squash the cleanup commit(s).

2016-10-06 19:49 UTC, phil65 commented
All follow-up stuff squashed into one commit.
jenkins build this please.

2016-10-06 20:59 UTC, merged

2017-01-10 05:46 UTC, jingai commented
Why was the Order button (id=19 in SmartPlaylistEditor.xml) changed from togglebutton to button?  It only toggles between two values.