aarch64 build support
xbmc/xbmc pull request #10659
Opened 2016-10-08 19:19 UTC by peak3d

aarch64 build support

## Description
- upgrade autotools for aarch64 depends build
- add aarch64 to the cmake build process
## Motivation and Context
support aarch64 depends build and kodi cmake build

## How Has This Been Tested?
cross compiled on ubuntu x86-64 14.04 lts

## Types of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

2016-10-08 20:24 UTC, wsnipex approved these changes
imho good to go

2016-10-09 07:53 UTC, wsnipex commented
jenkins build this please

2016-10-09 08:15 UTC, fetzerch requested changes
I think when rebasing, you reverted the fix for cmake detecting wrapper libs (libexif) as always outdated.

2016-10-09 08:15 UTC, fetzerch commented on project/cmake/scripts/linux/Macros.cmake
> -  add_custom_command(OUTPUT ${CMAKE_BINARY_DIR}/${wraplib}-${ARCH}${CMAKE_SHARED_MODULE_SUFFIX}
this reverts https://github.com/xbmc/xbmc/pull/10614

2016-10-09 08:15 UTC, fetzerch commented on project/cmake/scripts/linux/Macros.cmake
> -  add_custom_target(wrap_${libname} ALL DEPENDS ${CMAKE_BINARY_DIR}/${wraplib}-${ARCH}${CMAKE_SHARED_MODULE_SUFFIX})
same

2016-10-09 08:15 UTC, fetzerch commented on tools/buildsteps/android-arm64-v8a/configure-xbmc
> +if [ "$CMAKE_BUILD" = true ]; then
you can drop the non cmake branch, see https://github.com/xbmc/xbmc/pull/10649

2016-10-09 08:15 UTC, fetzerch commented on tools/buildsteps/android-arm64-v8a/make-binary-addons
> +    if [ "$CMAKE_BUILD" = true ]; then
same

2016-10-09 08:15 UTC, fetzerch commented on tools/buildsteps/android-arm64-v8a/make-xbmc
> +if [ "$CMAKE_BUILD" = true ]; then
same

2016-10-09 08:15 UTC, fetzerch commented on tools/buildsteps/android-arm64-v8a/package
> +if [ "$CMAKE_BUILD" = true ]; then
same

2016-10-09 08:15 UTC, fetzerch commented on xbmc/cores/DllLoader/exports/CMakeLists.txt
> +    add_custom_command(TARGET wrapper.def COMMAND echo \"-L${DEPENDS_PATH}/lib/dummy-lib${APP_NAME_LC} -l${APP_NAME_LC}\" >> wrapper.def)
why not `-l$<TARGET_FILE_NAME:${APP_NAME_LC}>` instead `-l${APP_NAME_LC}`

2016-10-09 08:29 UTC, peak3d commented on xbmc/cores/DllLoader/exports/CMakeLists.txt
> +    add_custom_command(TARGET wrapper.def COMMAND echo \"-L${DEPENDS_PATH}/lib/dummy-lib${APP_NAME_LC} -l${APP_NAME_LC}\" >> wrapper.def)
Not working with aarch64 android linker -> full pathnames seem not to work

2016-10-09 08:31 UTC, peak3d commented on xbmc/cores/DllLoader/exports/CMakeLists.txt
> +    add_custom_command(TARGET wrapper.def COMMAND echo \"-L${DEPENDS_PATH}/lib/dummy-lib${APP_NAME_LC} -l${APP_NAME_LC}\" >> wrapper.def)
whats also working is not use dummy-lib, but then only with -L<cmake_binary> -lkodi and not -l<path>libkodi.so

2016-10-09 08:34 UTC, fetzerch commented on xbmc/cores/DllLoader/exports/CMakeLists.txt
> +    add_custom_command(TARGET wrapper.def COMMAND echo \"-L${DEPENDS_PATH}/lib/dummy-lib${APP_NAME_LC} -l${APP_NAME_LC}\" >> wrapper.def)
ah, if the extension is a problem, then leave it as is. sry

2016-10-09 08:37 UTC, wsnipex commented on xbmc/cores/DllLoader/exports/CMakeLists.txt
> +    add_custom_command(TARGET wrapper.def COMMAND echo \"-L${DEPENDS_PATH}/lib/dummy-lib${APP_NAME_LC} -l${APP_NAME_LC}\" >> wrapper.def)
because it is not our target_file, but dummy-libkodi.so in depends

2016-10-09 08:41 UTC, fetzerch commented on xbmc/cores/DllLoader/exports/CMakeLists.txt
> +    add_custom_command(TARGET wrapper.def COMMAND echo \"-L${DEPENDS_PATH}/lib/dummy-lib${APP_NAME_LC} -l${APP_NAME_LC}\" >> wrapper.def)
Sry then i completely missunderstood it. Is it worth to put a comment explaining why we need to link the dummy?

2016-10-09 08:54 UTC, MartijnKaijser commented
@peak3d can you squash this one into the buildstep commit? 
https://github.com/MartijnKaijser/xbmc/commit/c5adda7783b5bdaf1e2c4822337da3e155b58237

2016-10-09 09:27 UTC, wsnipex commented
here is a rebased and fixed branch https://github.com/wsnipex/xbmc/commits/aarch64
I cleaned up and squashed the buildsteps commits there

2016-10-09 09:42 UTC, peak3d commented
Thx, @wsnipex !!!!!!!!!! gimme a few minutes

2016-10-09 09:57 UTC, peak3d commented
git reset --hard wsnipex/aarch64, hope I did it right.....

2016-10-09 11:02 UTC, wsnipex commented
@fetzerch ok now?

2016-10-09 11:47 UTC, MartijnKaijser commented
Runtime tested: 
SATV with ARMv8 (64bit)
Amazon FireTV with ARMv7 (32bit)
All seems ok. Time for merge

2016-10-09 13:49 UTC, merged