Allow multiple content elements in a single container
xbmc/xbmc pull request #10730
Opened 2016-10-19 15:14 UTC by b-pass

## Description
This change adds a new IListProvider, called CMultiProvider, which aggregates several independent &lt;content&gt; blocks (either DirectoryProviders or StaticProviders or both).

## Motivation and Context

DirectoryProviders (dynamically filled &lt;content&gt; blocks) are a powerful feature.  But currently you can only fill a list with a single directory at a time, and you also cannot add other static elements to a dynamic list.  For example, you might like to add some navigational list entries at the top of a list, and have it fill with dynamic content below those static entries.  Or maybe you would like to combine two different directories in one list for some reason.  This was hinted as a potential new feature in 2014, but it seems it never got added: http://forum.kodi.tv/showthread.php?tid=176864

## How Has This Been Tested?

I tested this by trying a few different combinations of multiple &lt;content&gt; blocks.

## Screenshots (if appropriate):

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2016-10-19 15:33 UTC, HitcherUK commented
Nice, thanks.

2016-10-19 18:55 UTC, BigNoid commented
Nice, tested and works great. Thx for this addition!
You can pick https://github.com/BigNoid/xbmc/commit/241de15944ef145150a3a07f190cd5d731d5def4 for Xcode sync

2016-10-19 19:05 UTC, b-pass commented
Picked and Squashed, thanks!

2016-10-19 21:15 UTC, garbear commented on xbmc/listproviders/MultiProvider.h
> +  virtual bool OnContextMenu(const CGUIListItemPtr &item);
can you add the override keyword on these functions?

2016-10-20 11:15 UTC, xhaggi commented
looks good +1

2016-11-18 08:57 UTC, da-anda commented
this would be great for some home screen widgets on Estuary in v17. Are there any major concerns to hold it back for v17 (besides of feature freeze)?

2016-11-18 10:47 UTC, b-pass commented on xbmc/listproviders/MultiProvider.h
> +  mutable std::map<CGUIListItem*, IListProviderPtr> m_itemMap;
The idea is that the MultiProvider needs to know which sub-provider will be sent Click/Info/Context messages so it needs to keep track of which content element belong to which sub-provider.

The only way I see to maintain that mapping is to build it during Fetch().  Unfortunately, Fetch is const in the base class.

I could maybe change that without too much impact on other code.  Would that be preferable to a mutable here?

2016-11-18 23:10 UTC, b-pass commented on xbmc/listproviders/MultiProvider.h
> +  mutable std::map<CGUIListItem*, IListProviderPtr> m_itemMap;
I went ahead and made that change an squashed it in

2017-01-05 03:06 UTC, b-pass commented
Fixed conflicts and squashed

2017-02-09 00:09 UTC, b-pass commented
Is there anything else I need to get this merged?  I don't want it to get forgotten and miss the boat for v19....

2017-02-09 00:26 UTC, ronie commented
jenkins build this please

2017-02-09 08:07 UTC, xhaggi requested changes

2017-02-09 08:07 UTC, xhaggi commented on xbmc/listproviders/MultiProvider.cpp
> + *      http://xbmc.org
Please update the copyright in all files you've touched.

```
*      Copyright (C) 201X-2017 Team Kodi
*      http://kodi.tv
```

2017-02-09 08:15 UTC, tamland commented on xbmc/listproviders/MultiProvider.cpp
> +      m_itemMap[item.get()] = provider;
This doesn't look very safe. There is no guarantee other providers aren't going to kill these items at any time, so you should hold a shared pointer.

2017-02-09 10:45 UTC, b-pass commented on xbmc/listproviders/MultiProvider.cpp
> +      m_itemMap[item.get()] = provider;
I never access the items from the pointers held in this map.  When events come in they have a shared pointer, the map just directs which provider should receive the call.

2017-02-09 10:49 UTC, b-pass commented on xbmc/listproviders/MultiProvider.cpp
> + *      http://xbmc.org
@xhaggi Done.

2017-02-09 10:55 UTC, b-pass commented on xbmc/listproviders/MultiProvider.cpp
> +      m_itemMap[item.get()] = provider;
@tamland I changed the map definition to use a void* for this key, which will help discourage someone from accidentally using the key as a pointer.

2017-02-11 11:49 UTC, tamland commented on xbmc/listproviders/MultiProvider.cpp
> +      m_itemMap[item.get()] = provider;
Well, it's still storing possibly dangling pointer which is being accessed by `.find`. Are you sure this is legal and safe?

2017-02-11 14:04 UTC, Paxxi commented on xbmc/listproviders/MultiProvider.cpp
> +      m_itemMap[item.get()] = provider;
I'm with @tamland on this one. It's a neat trick but it's going to blow up sooner or later, it's also quite non-intuitive to use a pointer address as the key value. There should be a better way to keep track of the items.

2017-02-11 19:08 UTC, b-pass commented on xbmc/listproviders/MultiProvider.cpp
> +      m_itemMap[item.get()] = provider;
@tamland @Paxxi Alright, I've changed it to use a size_t for keys.

2017-02-18 11:34 UTC, tamland commented
jenkins build this please

2017-02-18 15:22 UTC, merged