ListItem.Year - prefer to use the year value from the firstaired date
xbmc/xbmc pull request #10770
Opened 2016-10-25 13:05 UTC by ronie

ListItem.Year currently returns the year taken from the Premiered date.

for seasons/episodes it would be more accurate to use the year from the FirstAired date.

http://forum.kodi.tv/showthread.php?tid=294755

2016-10-25 15:03 UTC, Montellese commented
Recently I've been wondering why we have premiered and first aired. The latter is only used for episodes and the former isn't used for episodes at all. So in CVideoInfoTag it could be merged into one property.

2016-10-25 15:16 UTC, phil65 commented
Shouldnt we better drop year entirely from that confluence infoscreen for episodes? A user might wonder what the difference should be between year and premiered...

2016-10-27 09:46 UTC, phate89 requested changes
You should also add firstaired to HasYear() because it's used to check if we have a valid year...

2016-10-27 12:10 UTC, ronie commented
@phate89 good catch, thx!
should be fixed now.

2016-10-27 12:12 UTC, phate89 approved these changes

2016-10-28 22:11 UTC, MartijnKaijser commented
Jenkins build this please

2016-10-31 21:37 UTC, merged