[PVR] Guide window: Fix responsiveness on first open.
xbmc/xbmc pull request #10814
Opened 2016-10-30 10:08 UTC by ksooo

Under special circumstances -- for example if guide window is set as kodi startup window or if opened very(!) quickly after kodi startup -- the window can be experienced as kinda "unresponsive", because due to the async update of the window which is per default every 5 seconds (to avoid unnecessary flickering and cpu load) , it can happen that first epg data are displayed after 5 seconds.

This PR fixes this glitch by introducing an initial boost for the window update. On very first open, the window updates 10 times every second, after this every 5 seconds.

Second commit just adds some more fail safeness (i once experienced a crash there).

note: pvr.demo + guide window as kodi startup window is nice test setup to test the change.

@xhaggi for review?

2016-10-30 11:02 UTC, Jalle19 commented
Isn't there some way to determine when we can go back to 5 second intervals without having to specify an arbitrary boost parameter?

2016-10-30 13:15 UTC, ksooo commented
> Isn't there some way to determine when we can go back to 5 second intervals without having to specify an arbitrary boost parameter?

 atm, i have no better idea. for instance, if you use async epg transfer (pvr.hts supports this), there you never know when an update starts/ends. there is no fixed interval, progress, ... updates just come in at any time. but ofc i'm open for suggestions.

2016-10-30 16:10 UTC, ksooo commented
@Jalle19 what do you think about this more advanced approach?

2016-10-31 10:32 UTC, Jalle19 approved these changes
+1 if it works

2016-10-31 10:43 UTC, ksooo commented
jenkins build this please

2016-10-31 11:29 UTC, xhaggi requested changes

2016-10-31 11:29 UTC, xhaggi commented on xbmc/pvr/windows/GUIWindowPVRGuide.cpp
> +  static const int BOOSTED_CYCLES_THRESHOLD = 5;
Should we move this constant to the top out of this method.

2016-10-31 11:29 UTC, xhaggi commented on xbmc/pvr/windows/GUIWindowPVRGuide.cpp
> +    if (iUpdatesWithoutChange)
Please compare it to a number instead of use the bool comparator.

2016-10-31 11:29 UTC, xhaggi commented on xbmc/pvr/windows/GUIWindowPVRGuide.cpp
> +    if (iUpdatesWithoutChange)
Same here

2016-10-31 11:31 UTC, ksooo commented on xbmc/pvr/windows/GUIWindowPVRGuide.cpp
> +  static const int BOOSTED_CYCLES_THRESHOLD = 5;
What would be the benefit? It is not used outside this member function?

2016-10-31 11:32 UTC, ksooo commented on xbmc/pvr/windows/GUIWindowPVRGuide.cpp
> +    if (iUpdatesWithoutChange)
Will do.

2016-10-31 11:33 UTC, ksooo commented on xbmc/pvr/windows/GUIWindowPVRGuide.cpp
> +    if (iUpdatesWithoutChange)
Will do.

2016-10-31 11:47 UTC, xhaggi commented on xbmc/pvr/windows/GUIWindowPVRGuide.cpp
> +    if (iUpdatesWithoutChange)
could we save the second check if we change the code to:

```
static const int BOOSTED_CYCLES_THRESHOLD = 5;

int iLastEpgItemsCount = 0;
int iUpdatesWithoutChange = 0;

while (!m_bStop)
{
  if (m_pGuideWindow->RefreshTimelineItems() && !m_bStop)
  {
    CGUIMessage m(GUI_MSG_REFRESH_LIST, m_pGuideWindow->GetID(), 0, ObservableMessageEpg);
    KODI::MESSAGING::CApplicationMessenger::GetInstance().SendGUIMessage(m);
  }

  // in order to fill the guide window asap, use a short update interval until
  // BOOSTED_CYCLES_THRESHOLD times in a row we get no more epg events between two cycles.
  if (iUpdatesWithoutChange < BOOSTED_CYCLES_THRESHOLD)
  {
    int iCurrentEpgItemsCount = m_pGuideWindow->CurrentDirectory().Size();

    if (iCurrentEpgItemsCount == iLastEpgItemsCount)
      iUpdatesWithoutChange++;
    else
      iUpdatesWithoutChange = 0; // reset; we want BOOSTED_CYCLES_THRESHOLD in a row

    iLastEpgItemsCount = iCurrentEpgItemsCount;

    Sleep(1000); // boosted update cycle
  }
  else 
  {
    Sleep(5000); // normal update cycle
  }    
}
```

2016-10-31 13:34 UTC, ksooo commented on xbmc/pvr/windows/GUIWindowPVRGuide.cpp
> +    if (iUpdatesWithoutChange)
@xhaggi just one small change... i wanted 5 calls to refresh without new data in a row, which means 4 times sleep(1000). With your suggested change we would do 5 Sleep(1000). So, the value of the constant needs be changed to 4 now. will change accordingly.

2016-10-31 13:47 UTC, ksooo commented
@xhaggi requested changes are in. good to go now?

2016-10-31 14:16 UTC, xhaggi commented on xbmc/pvr/windows/GUIWindowPVRGuide.cpp
> +    if (iUpdatesWithoutChange)
Thanks looks better now.

2016-10-31 14:27 UTC, ksooo commented
jenkind build this please

2016-10-31 14:27 UTC, ksooo commented
jenkins build this please

2016-10-31 17:47 UTC, merged