[cleanup][pvr] get rid of obsolete guide views
xbmc/xbmc pull request #10838
Opened 2016-11-01 12:00 UTC by xhaggi

As discussed this PR will remove the different guide views "channel", "now" and "next.
Needs to be merged before #10795

@ksooo mind taking a look

2016-11-01 12:03 UTC, xhaggi commented
not sure if we also want to drop the language keys `19030`, `19031`

2016-11-01 15:37 UTC, ronie commented
> not sure if we also want to drop the language keys 19030, 19031

according to the language file, they are used for other stuff as well

2016-11-05 22:44 UTC, ksooo requested changes

2016-11-05 22:44 UTC, ksooo commented on xbmc/pvr/windows/GUIWindowPVRGuide.cpp
> -      GetViewNowItems(items);
Declaration and definition of this member function should be not used anymore and can be dropped as well.

2016-11-05 22:44 UTC, ksooo commented on xbmc/pvr/windows/GUIWindowPVRGuide.cpp
> -      GetViewNextItems(items);
Declaration and definition of this member function should be not used anymore and can be dropped as well.

2016-11-05 22:44 UTC, ksooo commented on xbmc/pvr/windows/GUIWindowPVRGuide.cpp
> -      GetViewChannelItems(items);
Declaration and definition of this member function should be not used anymore and can be dropped as well.

2016-11-05 22:44 UTC, ksooo commented on xbmc/pvr/windows/GUIWindowPVRGuide.cpp
>          return ActionInputChannelNumber(action.GetID() - REMOTE_0);
indentation!

2016-11-30 18:25 UTC, ksooo commented
@xhaggi ping. have you seen my review comments? now that the master is open for v18 development i would like to merge this soon.

2016-11-30 21:56 UTC, xhaggi commented
Yeah will address your comments in the next few days

2016-11-30 22:39 UTC, ksooo commented
Please note that Estuary (Estouchy as well?) seems still to contain refereneces to the removed view types with numerical value 11, 12, 13. Please check and remove (grep output may contain false positives, but all guide and media menu related occurrences seem to be suspicious!).

<pre>
[kai@Kais-Mac-WLAN ~/src/github/ksooo/xbmc/addons/skin.estuary/xml (master)]$ grep -r "(11)" .
./DialogPVRChannelsOSD.xml:							<visible>Control.hasFocus(11)</visible>
./DialogPVRGuideOSD.xml:							<visible>Control.HasFocus(11)</visible>
./DialogPVRGuideOSD.xml:							<visible>!String.IsEmpty(ListItem.Plot) + Control.HasFocus(11)</visible>
./DialogPVRGuideOSD.xml:					<label>$LOCALIZE[19069]$INFO[Container(11).ListItem.StartDate, - ]</label>
./DialogVideoInfo.xml:						<param name="visible" value="System.hasAddon(script.extendedinfo) + String.IsEqual(ListItem.DBType,movie) + !Control.IsVisible(11)" />
./Includes_MediaMenu.xml:				<onright condition="Window.IsActive(MyPVRGuide.xml) + Control.IsVisible(11)">11</onright>
./Includes_MediaMenu.xml:						<onright condition="Window.IsActive(MyPVRGuide.xml) + Control.IsVisible(11)">11</onright>
./VideoOSDBookmarks.xml:				<visible>Integer.IsEqual(Container(11).NumItems,0)</visible>
./VideoOSDBookmarks.xml:							<visible>Control.HasFocus(11)</visible>
[kai@Kais-Mac-WLAN ~/src/github/ksooo/xbmc/addons/skin.estuary/xml (master)]$ grep -r "(12)" .
./Includes_MediaMenu.xml:				<onright condition="Window.IsActive(MyPVRGuide.xml) + Control.IsVisible(12)">12</onright>
./Includes_MediaMenu.xml:						<onright condition="Window.IsActive(MyPVRGuide.xml) + Control.IsVisible(12)">12</onright>
[kai@Kais-Mac-WLAN ~/src/github/ksooo/xbmc/addons/skin.estuary/xml (master)]$ grep -r "(13)" .
./DialogAddonInfo.xml:						<visible>Control.IsEnabled(13)</visible>
./DialogPVRGroupManager.xml:					<label>$LOCALIZE[31089]: [COLOR white]$INFO[Container(13).NumItems][/COLOR]</label>
./Includes_MediaMenu.xml:				<onright condition="Window.IsActive(MyPVRGuide.xml) + Control.IsVisible(13)">13</onright>
./Includes_MediaMenu.xml:						<onright condition="Window.IsActive(MyPVRGuide.xml) + Control.IsVisible(13)">13</onright>
[kai@Kais-Mac-WLAN ~/src/github/ksooo/xbmc/addons/skin.estuary/xml (master)]$ 
</pre>

2016-12-01 02:24 UTC, phil65 commented
Will take core of estuary cleanup.

2016-12-01 07:03 UTC, ksooo commented
Thx @phil65

@xhaggi why must this PR go in before the horizontal epg grid PR? Cannot see a f dependency here.

2016-12-01 08:08 UTC, xhaggi commented
Without you're unable to switch to the custom view type with horizontal epg.

2016-12-01 10:16 UTC, ronie commented
i'll clean up estouchy once this is in.

2016-12-01 12:18 UTC, ksooo commented
thx @ronie

2016-12-01 18:13 UTC, xhaggi commented
@ksooo addressed your comments

2016-12-01 19:03 UTC, ksooo approved these changes

2016-12-01 19:03 UTC, ksooo commented
thanks

jenkins build this please

2016-12-01 19:47 UTC, ksooo commented
@xhaggi does not compile. please fix.

<pre>
/Users/Shared/jenkins/workspace/OSX-64/xbmc/pvr/windows/GUIWindowPVRGuide.cpp:235:9: error: non-void function 'GetDirectory' should return a value [-Wreturn-type]
        return;
</pre>

2016-12-01 20:25 UTC, xhaggi commented
Force-pushed. Jenkins build this please

2016-12-01 22:01 UTC, merged