[cmake] Fun with flags
xbmc/xbmc pull request #10903
Opened 2016-11-09 15:14 UTC by hudokkow

## Description
Change default -O3 flag to -O2 on Linux, OSX, BSD and RBPi and to -Os on droids and iOS for release builds.

## Motivation and Context
Convo in slack channel.

## How Has This Been Tested?
Build/run tested on linux only.

## Screenshots (if appropriate):

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

Original was linux only. I added the other platforms so we could discuss if it's needed/wanted or not.

https://github.com/xbmc/xbmc/commit/7a35049d09a17bc842d37067aa4603d18d495c55 is cosmetics only. It makes reading build info easier on huge logs.

ping @stefansaraev, @wsnipex and @fetzerch

2016-11-09 17:16 UTC, stefansaraev commented
+1. I dont think -O3 is safe for project with big codebase (and lot of depends) like kodi.

btw, my real issue was (and still is) that cmake does not honor my $CXXFLAGS from environment (set by my build scripts). I personaly do prefer -Os on linux, I guess I can work around by appending ${CMAKE_CXX_FLAGS} to CMAKE_CXX_FLAGS_RELEASE :)

2016-11-09 17:27 UTC, hudokkow commented
Can you upload your script? If it's top-secret, I'll be happy with only cmake calls.

2016-11-09 17:29 UTC, fetzerch commented
Can you move it to common/ArchSetup.cmake please? I don't like that we have this code duplication.

2016-11-09 17:38 UTC, stefansaraev commented
@hudokkow 

> Can you upload your script? If it's top-secret, I'll be happy with only cmake calls.

nothing fancy. it just exports CXXFALAGS to environment. on my env it is something like

```
-march=armv8-a -mcpu=cortex-a53 -mabi=lp64 -Wno-psabi -w -pipe -Os
```
OpenELEC and LibreELEC (and maybe other distros?) are doing the same. 

when compiling kodi, -O3 (now -O2 with this PR) was automagicaly appended at the end. rendering my -Os useless. with gcc, whatever -Ox comes last - it is used.

2016-11-09 21:01 UTC, wsnipex commented on project/cmake/CMakeLists.txt
> +message(STATUS "\n-- FUN WITH FLAGS --------------------------------------------------------------")
COMPILER FLAGS please

2016-11-09 21:15 UTC, wsnipex requested changes
I'm ok with setting default cflags to -O2, although we have been building with O3 for a long time without issues that boiled down to cflags.

What's not ok is to overwrite user set flags without reason, if I set my cflags I expect them to be used.

2016-11-09 21:15 UTC, wsnipex commented on project/cmake/CMakeLists.txt
> +  string(TOUPPER ${CMAKE_BUILD_TYPE} BUILD_TYPE)
this var is not really needed

2016-11-09 21:15 UTC, wsnipex commented on project/cmake/CMakeLists.txt
> +  message(STATUS "  ${BUILD_TYPE}")
please move this to the top of final message, but on one line

2016-11-09 22:20 UTC, hudokkow commented
Current (master) flags we're using: http://pastebin.com/8MbAVdkM

2016-11-09 22:20 UTC, hudokkow commented on project/cmake/CMakeLists.txt
> +  message(STATUS "  CMAKE_EXE_LINKER_FLAGS_${BUILD_TYPE}: ${CMAKE_ASM_FLAGS_${BUILD_TYPE}}")
Ah? Not it doesn't. See pastebin below.

2016-11-09 22:21 UTC, hudokkow commented on project/cmake/CMakeLists.txt
> +message(STATUS "\n-- FUN WITH FLAGS --------------------------------------------------------------")
No sense of humor... TBBT? :wink:

2016-11-09 22:23 UTC, hudokkow commented on project/cmake/CMakeLists.txt
> +  string(TOUPPER ${CMAKE_BUILD_TYPE} BUILD_TYPE)
Don't follow.
It's CMAKE_EXE_LINKER_FLAGS_DEBUG, not CMAKE_EXE_LINKER_FLAGS_Debug.

Last time I checked it's case sensitive.

2016-11-09 22:23 UTC, hudokkow commented on project/cmake/CMakeLists.txt
> +  message(STATUS "  ${BUILD_TYPE}")
Okido.

2016-11-09 22:24 UTC, hudokkow commented
@fetzerch, I'll change it to only use common/

2016-11-10 08:08 UTC, wsnipex commented on project/cmake/CMakeLists.txt
> +  message(STATUS "  CMAKE_EXE_LINKER_FLAGS_${BUILD_TYPE}: ${CMAKE_ASM_FLAGS_${BUILD_TYPE}}")
you're right, sorry :)

2016-11-10 08:09 UTC, wsnipex commented on project/cmake/CMakeLists.txt
> +  string(TOUPPER ${CMAKE_BUILD_TYPE} BUILD_TYPE)
afaik cmake should automatically use the correct ones for the build type merged with external passed flags. If it doesn't then we have to merge them ourselves.

2017-07-29 05:47 UTC, MartijnKaijser commented
Still needed?

2017-07-31 08:37 UTC, hudokkow commented
Nope.

2017-07-31 08:37 UTC, closed without merging