[jsonrpc] "added" data for new item *Library.OnUpdate notification
xbmc/xbmc pull request #10916
Opened 2016-11-12 04:07 UTC by rmrector

## Description

This PR adds `"added": true` to JSON-RPC "OnUpdate" notification "data" if it is announced for a newly added* media item.

__*__ "Refreshing" an item generally removes and then re-adds the item, so this change also affects the OnUpdate notification for refreshed items.

This is a thin addition to the existing API (no code should break with a new key: value pair here), but it might be preferable to instead break compatibility and add a new notification "OnAdd"? I could rework it if so.

## Motivation and Context

Consuming add-ons can easily tell if the notification is for a new* item or contains just a change to some of its info if they need to treat them differently. For instance, add-ons could keep additional information in sync with Kodi's database, but it may be able to skip possibly expensive operations if only play count or the title is updated.

## How Has This Been Tested?

Poked through several situations that generate "OnUpdate" notifications, and ensured data includes the "added" key when and only when a new* item has been added.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2016-11-12 12:02 UTC, da-anda commented
ping @Montellese, mind having a look? thanks.

2016-11-14 18:21 UTC, rmrector commented
Small history rewrite because this is not Java: use default value for new parameter of AnnounceUpdate.

2017-02-14 19:26 UTC, MartijnKaijser commented
@Montellese new ping :)

2017-04-17 05:45 UTC, rmrector commented
Popped off the json-rpc version bump for simpler picking, I can add it back if it gets merged.

And maybe a 🤘 🐰 poke @Montellese

2017-04-17 08:42 UTC, Paxxi commented
Sorry about the silence here.
Thank you for your time and patience. 

I believe adding a parameter should also bump the API version. Normally a json deserializer should ignore it or the layer above but there's always the chance that it could break implementations that expects exactly what the schema says and nothing more

2017-04-17 09:32 UTC, Montellese requested changes
Are you sure that you covered all the cases where new items are added to the database? I'd have to check myself but I'd have expected that there are places in `CVideoDatabase` that need to be adjusted as well but I might be wrong.

And as @Paxxi has pointed out please bump the minor version of the API.

2017-04-17 09:32 UTC, Montellese commented on xbmc/interfaces/json-rpc/schema/notifications.json
> +          "added": { "$ref": "Optional.Boolean", "description": "True if the update is for a newly added item." },
Please add the new property at the end.

2017-04-17 09:32 UTC, Montellese commented on xbmc/interfaces/json-rpc/schema/notifications.json
> +          "added": { "$ref": "Optional.Boolean", "description": "True if the update is for a newly added item." },
Same here

2017-04-17 09:32 UTC, Montellese commented on xbmc/music/MusicDatabase.cpp
> +static void AnnounceUpdate(const std::string& content, int id, bool added=false)
Spaces around the `=`

2017-04-17 22:49 UTC, rmrector commented
All updated. I just popped the version off temporarily in case the PR was going to sit here for a while longer, it was out of date anyway.

@Montellese with the myriad ways of playing a media item I had the same thought, "this can't be everything", but Kodi only has the file scanner and import to add new library items, which both call VideoInfoScanner.AddVideo. I also looked through every "OnUpdate" notification generated and the rest were all just updates to data like playcount, title, and fanart.

2017-04-18 16:49 UTC, Montellese approved these changes
Thanks for the changes. Nothing else from me. jenkins build and merge

2017-07-09 14:10 UTC, Rechi commented
@rmrector this needs a rebase

2017-07-17 16:46 UTC, rmrector commented
@Rechi updated. Please don't leave this unmerged until the version goes out of date again.

2017-07-17 19:04 UTC, Rechi commented
@rmrector this PR now contains a merge commit. We don't want them inside a PR to have a clean history.
Please remove it and if necessary rebase on our master branch.
If you need assistance for that task, just ask us.

2017-07-17 19:22 UTC, rmrector commented
@Rechi Ohh, that's what I get for using Github's helpful little editor. I may have missed a switch for that, though. Anyway, fixed.

2017-07-17 19:37 UTC, Rechi commented
@Montellese is this still fine to be merged?

2017-07-18 06:41 UTC, Montellese commented
Still fine with me.

2017-08-02 17:28 UTC, rmrector commented
@Rechi don't forget about this one.

2017-08-02 17:29 UTC, merged

2017-08-02 17:31 UTC, rmrector commented
Thanks machine man Martijn!