Fix upnp iso resume
xbmc/xbmc pull request #11045
Opened 2016-12-03 10:42 UTC by phate89

## Description
Add exporting of playerstate to fix importing of resume point in isos and adds playerstate to upnp to fix resuming of iso via upnp.
@Montellese 

## Motivation and Context
Right now if we export/import a iso resume point it doesn't work anymore. Same for resume point of a iso via upnp

## How Has This Been Tested?
Tested with 2 local upnp libraries and exporting/importing them once.

## Screenshots (if appropriate):

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [X] All new and existing tests passed

2016-12-04 15:11 UTC, Montellese requested changes
What's the format of `playerstate`? Is it a pure string or is it XML or JSON stored in a string?

You certainly need to change the XML namespace of the newly introduced XML tags from `upnp` to `xbmc`.

2016-12-04 15:11 UTC, Montellese commented on xbmc/video/VideoInfoTag.cpp
> +    const TiXmlElement *playerstate = epbookmark->FirstChildElement("playerstate");
Something looks wrong here. Shouldn't it be `resume` instead of `epbookmark`?

2016-12-04 15:11 UTC, Montellese commented on xbmc/video/VideoInfoTag.cpp
> +        m_EpBookmark.playerState << *value;
Shouldn't this be `m_resumePoint` instead of `m_EpBookmark` to match the `Save()` implementation?

2016-12-04 15:11 UTC, Montellese commented on xbmc/network/upnp/UPnP.cpp
> +            curr_value.Append(NPT_String::Format("<upnp:lastPlayerState>%s</upnp:lastPlayerState>",
Is `upnp:lastPlayerState` defined in the UPnP specs? If not you need to use another XML namespace like `xbmc:` (which we use in otherplaces).

2016-12-04 15:11 UTC, Montellese commented on lib/libUPnP/Platinum/Source/Devices/MediaServer/PltDidl.h
> +#define PLT_FILTER_FIELD_LASTPLAYERSTATE            "upnp:lastPlayerState"
See my other comment on the XML namespace.

2016-12-04 15:11 UTC, Montellese commented on lib/libUPnP/Platinum/Source/Devices/MediaServer/PltMediaItem.h
> +    NPT_String last_playerstate;
Please put all Kodi-specific properties into the `PLT_XbmcInfo` structure because the other ones in `PLT_MiscInfo` are defined in the UPnP spec.

2016-12-04 15:18 UTC, phate89 commented
It's an xml stored in a string.. I missed there was the upnp/xbmc distinction.. I'll move them to xbmc

2016-12-05 00:11 UTC, phate89 commented
@Montellese I updated the pr.. thanks for the review.
 looked at the code and it seems it's always xml the playerstate but I'm not 100% sure..
@FernetMenta maybe you know something more? is playerstate always xml or empty in our videoplayer?

2016-12-05 08:12 UTC, Montellese commented
@phate89 If it's XML I have to consult the UPnP specs again. IIRC any XML payload inside the DIDL-Lite elements needs to be encoded for transport but I'm not 100% sure.

2016-12-05 08:12 UTC, Montellese commented on lib/libUPnP/Platinum/Source/Devices/MediaServer/PltMediaItem.cpp
> +    m_XbmcInfo.last_playerstate      = "";
Unnecessary spaces.

2016-12-05 08:13 UTC, Montellese commented on lib/libUPnP/Platinum/Source/Devices/MediaServer/PltMediaItem.cpp
> +
Unnecessary change.

2016-12-05 08:39 UTC, phate89 commented on lib/libUPnP/Platinum/Source/Devices/MediaServer/PltMediaServer.cpp
> +        auto txt = child->GetText();
Yes.. gettext returns a pointer that might be null. If we pass to update the playerstate an empty tag (`<xbmc:lastplayerstate></xbmc:lastplayerstate>`) we get a null from gettext. So With `*child->GetText()` we try to retrieve an object from a null pointer

2016-12-05 08:42 UTC, phate89 commented
@Montellese
If I'm not wrong we already encode the string with `PLT_Didl::AppendXmlEscape`

2016-12-05 11:42 UTC, phate89 commented
fixed latest comments

2016-12-08 19:53 UTC, Montellese commented on lib/libUPnP/Platinum/Source/Devices/MediaServer/PltMediaServer.cpp
> -        tags[child->GetTag()] = *child->GetText();
Would you mind splitting this into a separate commit as it's a fundamental fix independent of any Kodi logic.

2016-12-08 19:54 UTC, Montellese commented
Moving the generic fix into a separate commit would make upstreaming easier. The rest is fine.

2016-12-08 19:55 UTC, Montellese approved these changes

2016-12-08 20:01 UTC, phate89 commented
@Montellese no problem. I have to split only the commit or also the patch and commit patch?

2016-12-08 20:15 UTC, Montellese commented
If you split the commit you also have to redo the patch(es).

2016-12-12 16:42 UTC, phate89 commented
@Montellese udpated with 2 separate patches
jenkins build this please

2016-12-14 10:43 UTC, merged

2016-12-17 09:46 UTC, MartijnKaijser commented
@Montellese that bumps the database.is that something we should still do in beta?

2016-12-17 14:09 UTC, Montellese commented
Personally I probably wouldn't backport a database schema change this close to RC.

2016-12-18 01:05 UTC, phate89 commented
I added the backport needed tag because it's a bug fix and I didn't consider the bump.
The db changes are really small since it only adds a new field in the views..
Otoh it's a bug that's there since forever. I noticed the bug4 months ago looking at the code (not because I actually use this) and I think it's never been reported at all so it's fine by me either way..

2016-12-18 10:43 UTC, MartijnKaijser commented
Thanks for fixing it but lets keep db version as is in Krypton :)