[docs] Update README.osx
xbmc/xbmc pull request #11202
Opened 2016-12-17 22:21 UTC by fetzerch

Explain how to use cmake to generate the xcode project files.

I've also changed the file to markdown. Is that something we want, or should I change it back to plain text? Preview: https://github.com/fetzerch/xbmc/blob/doc_osx/docs/README.osx.md

Will update the others once we agreed on the format and style.

ping: @Memphiz, @hudokkow, @wsnipex

2016-12-18 00:03 UTC, Memphiz commented
I like the markdown - well done with the adaptions imo - thx

2016-12-18 13:43 UTC, fetzerch commented
Thanks. Ok osx, ios fully done.

@Memphiz can you check if the versions in the ios doc are ok? I added sierra and el capitan. From what I understood Xcode 8 is not supported until you PR goes in? Also I removed the line recommending ios sdk 8.1 because the sdk version should match the device people want to build for.

2016-12-18 13:43 UTC, fetzerch commented
Any volunteers for one of the other files? :)

2016-12-18 13:49 UTC, hudokkow commented
I can do linux/Ubuntu/RPi. Just not today probably.

2016-12-18 14:33 UTC, stefansaraev commented
https://github.com/xbmc/xbmc/tree/master/Kodi.xcodeproj seems seems not to used now

2016-12-18 22:53 UTC, Memphiz commented
@fetzerch nope the sdk advise needs to stay. There were issues when people used SDKs that were not the ones i developed for. For example the external screen behavior when using airplay mirroring behaves different when using different SDK versions regardless of the used deployment target (which stayed the same of course). At least that was the case around ios 8.x SDKs (might be no issue with newer SDKs anymore but i didn't check that). So while i never thought that would be the case - Apple developers screwed up at times ;).

2016-12-19 19:56 UTC, fetzerch commented
@Memphiz Thanks for the explaination, added it back. Any other things you'd want me to fix? Otherwise we can get it in.

2016-12-20 17:35 UTC, Memphiz requested changes
Looks good beside my remarks - thx alot for this. I think the next PR would be removing the Xcode project as it has no value now anymore.

2016-12-20 17:35 UTC, Memphiz commented on docs/README.ios.md
> +The minimum version of iOS you need to run(!) Kodi is 5.1.1 atm.
Could you correct this to 6.0 while you are at it?

2016-12-20 17:35 UTC, Memphiz commented on docs/README.ios.md
> +Ensure that you also adapt the Xcode project to use this SDK version.
This one needs to be adapted i guess

2016-12-20 17:35 UTC, Memphiz commented on docs/README.ios.md
> +The toolchain file location differs depending on your iOS and SDK version.
please make it clear that the iphoneos9.3_armv7-target has to be replaced with iphoneos<SDKVERSION>_<CPU>-target ... i fear we get support questions here if its not in baby speech ;).

2016-12-20 17:35 UTC, Memphiz commented on docs/README.ios.md
> +    make -C target/binary-addons
this is out of context now - please ensure that people are in tools/depends before trying to issue this command.

2016-12-20 17:35 UTC, Memphiz commented on docs/README.ios.md
> +    make -C target/binary-addons ADDONS="pvr.hts pvr.dvblink"
same here

2016-12-20 17:35 UTC, Memphiz commented on docs/README.ios.md
> +After the build, you can ether run Kodi for iOS from Xcode.
ether might be either, but "either" without "or" is strange too :)

2016-12-20 17:35 UTC, Memphiz commented on docs/README.ios.md
> +    cmake --build . --config "Debug" -- -verbose -jobs $(sysctl -n hw.ncpu)
we could use getconf _NPROCESSORS_ONLN here aswell then right?

2016-12-20 17:35 UTC, Memphiz commented on docs/README.osx.md
> +are installed using the commands described below (with the latest iOS SDK found
iOS SDK should be MacOS SDK

2016-12-20 17:35 UTC, Memphiz commented on docs/README.osx.md
> +Ensure that you also adapt the Xcode project to use this SDK version.
This needs to be adapted in whatever way this needs to be done now with cmake generation...

2016-12-20 17:35 UTC, Memphiz commented on docs/README.osx.md
> +    make -C target/binary-addons
same out of context problem - we need to ensure users are in tools/depends before trying this ...

2016-12-20 17:35 UTC, Memphiz commented on docs/README.osx.md
> +    make -C target/binary-addons ADDONS="pvr.hts pvr.dvblink"
same here

2016-12-20 17:35 UTC, Memphiz commented on docs/README.osx.md
> +The toolchain file location differs depending on your macOS and SDK version.
spoonfeed what needs to be changed here.

2016-12-20 17:35 UTC, Memphiz commented on docs/README.osx.md
> +    cmake --build . --config "Debug" -- -verbose -jobs $(sysctl -n hw.ncpu)
getconf _NPROCESSORS_ONLN

2016-12-20 23:09 UTC, fetzerch commented
Thanks, I've tried to fix all comments, but i'm not sure with the `--with-sdk`. Need to check if the sdk version is put into the toolchain file and picked up from there automatically or if there's further work needed.

Dropping the xcode project is done in: https://github.com/xbmc/xbmc/pull/11217

2016-12-21 06:32 UTC, Memphiz approved these changes

2016-12-22 14:48 UTC, fetzerch commented
@Memphiz: I've installed the 10.9 sdk now from https://github.com/phracker/MacOSX-SDKs and `--with-sdk` seems to do the trick. cmake picks it up from the toolchain file. Unfortunately it compiles only when generating a make file project. With xcodebuild and xcode i get this. Any idea?

```
=== BUILD TARGET XBMCHelper OF PROJECT kodi WITH CONFIGURATION Release ===

Check dependencies

Ld /Users/jcf/develop/kodi/kodi-build-xcode-old/tools/darwin/runtime/XBMCHelper normal x86_64
    cd /Users/jcf/develop/kodi/kodi
    export MACOSX_DEPLOYMENT_TARGET=10.9
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -L/Users/jcf/develop/kodi/kodi-build-xcode-old/tools/darwin/runtime -F/Users/jcf/develop/kodi/kodi-build-xcode-old/tools/darwin/runtime -filelist /Users/jcf/develop/kodi/kodi-build-xcode-old/build/XBMCHelper/kodi.build/Release/XBMCHelper.build/Objects-normal/x86_64/XBMCHelper.LinkFileList -mmacosx-version-min=10.9 -Xlinker -object_path_lto -Xlinker /Users/jcf/develop/kodi/kodi-build-xcode-old/build/XBMCHelper/kodi.build/Release/XBMCHelper.build/Objects-normal/x86_64/XBMCHelper_lto.o -fobjc-link-runtime -L/Users/Shared/xbmc-depends/macosx10.9_x86_64-target/lib -Wl,-search_paths_first -arch x86_64 -mmacosx-version-min=10.8 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -stdlib=libc++ -Wl,-headerpad_max_install_names -framework IOKit -framework Carbon -framework Cocoa -Xlinker -dependency_info -Xlinker /Users/jcf/develop/kodi/kodi-build-xcode-old/build/XBMCHelper/kodi.build/Release/XBMCHelper.build/Objects-normal/x86_64/XBMCHelper_dependency_info.dat -o /Users/jcf/develop/kodi/kodi-build-xcode-old/tools/darwin/runtime/XBMCHelper
Undefined symbols for architecture x86_64:
  "_objc_readClassPair", referenced from:
      __ARCLite__load() in libarclite_macosx.a(arclite.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **
```

2016-12-22 16:56 UTC, Memphiz commented
No idea - but what is strange ist that deployment target is set to 10.8 in cflags (which is correct) but to 10.9 via export MACOSX_DEPLOYMENT_TARGET (which is wrong). 
Also this error is for XBMCHelper right? I think it has a static xcode project still no? ARC is some sort of automated garbage collection afair...

2016-12-23 07:51 UTC, fetzerch commented
Thanks, sorted it out. Now it's really just building depends with the `--with-sdk` parameter and using the respective toolchain file.

btw: any chance of rebasing https://github.com/xbmc/xbmc/pull/10539 now that krypton is branched?

2016-12-23 11:41 UTC, merged