wait for network after resuming from suspend
xbmc/xbmc pull request #11277
Opened 2016-12-27 11:55 UTC by verybadsoldier

Makes Kodi wait for network connection after resuming from suspend.

## Description
This introduces a function `WaitForNet` in Kodi's power manager which will block (with a timeout) until at least one network interface is initialized and connected. This function is invoked in `OnWake` so it is triggered on every wake up.
This behavior is disabled by default and has to be activated by a new advanced setting:
```
    <suspend>
        <waitnetonwakeup>true</waitnetonwakeup>
    </suspend>
```

This new setting would have to be documented on the Wiki I guess.

## Motivation and Context
When waking the machine from sleep/suspend and directly trying to access network resources (e.g. playing a video or reading from the MySQL DB) then Kodi will fail cause the network has not been initialized yet.
I have experienced and described this issue here:
http://forum.kodi.tv/showthread.php?tid=301976

## How Has This Been Tested?
I tested it on a Intel NUC i5 using LibreELEC 7.02 using a wired network. I tested it by suspending the machine and waking it up again. Then I observed the behavior with and without this setting enabled. With the setting enabled Kodi blocked for several seconds and put something like this in the logfile:

```
12:51:10 T:140441393608768  NOTICE: OnWake: Running resume jobs
12:51:10 T:140441393608768  NOTICE: WaitForNet: Waiting for first network interface to come up
12:51:18 T:140441393608768  NOTICE: WaitForNet: network interface 'eth0' is up after waiting 7400 ms
12:51:18 T:140441393608768  NOTICE: OnWake: Restarting lirc
```

After this I could use Kodi and directly access network resources without issues.

## Types of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2016-12-27 12:04 UTC, FernetMenta commented
no advanced settings. those are only valuable for the very few who know about them. mostly only the developer who implemented it.

2016-12-27 13:29 UTC, verybadsoldier commented
@FernetMenta 
Okay, so it should be a regular setting configurable in the UI? I will try to find out how to do this.

So the general concept is accetable and might get merged if the setting is changed?

2016-12-27 15:59 UTC, FrankHeimes requested changes

2016-12-27 15:59 UTC, FrankHeimes commented on xbmc/powermanagement/PowerManager.cpp
> +    CNetworkInterface* pIface = g_application.getNetwork().GetFirstConnectedInterface();
Consider replacing `CNetworkInterface*` with `const auto * const` if `GetName()` is `const` or `const auto` otherwise.

2016-12-27 15:59 UTC, FrankHeimes commented on xbmc/powermanagement/PowerManager.h
> +  void WaitForNet();
Consider declaring `WaitForNet() const`.

2016-12-27 15:59 UTC, FrankHeimes commented on xbmc/settings/AdvancedSettings.h
> +    bool m_waitForNetAfterWakeUp;
Consider initializing member variable when declaring it: `bool m_waitForNetAfterWakeUp = true;`

2016-12-27 15:59 UTC, FrankHeimes commented on xbmc/settings/AdvancedSettings.cpp
> +  }
`CAdvancedSettings::ParseSettingsFile()` is ridiculously long and should be refactored into local free functions.
That is too much work for a single feature implementation, but not adding more inline code would be a start.

Consider putting lines 1202 - 1206 into a free function
```
namespace {
	bool GetWaitNetOnWakeupFlag(TiXmlElement *rootElement)
	{
		if (!rootElement)
			throw std::invalid_argument("rootElement");

		auto firstChild = rootElement->FirstChildElement("suspend");
		if (!firstChild)
			return true; // Default behavior is to enable waitnetonwakeup

		bool waitForNetAfterWakeUp = true;
		XMLUtils::GetBoolean(firstChild, "waitnetonwakeup", waitForNetAfterWakeUp);
		return waitForNetAfterWakeUp;
	}
}
```
The line `1202: m_waitForNetAfterWakeUp = GetWaitNetOnWakeupFlag();` makes clear that the member is always well defined. Now, this is a lot more code than the original, but it is self-contained. `pRootElement` is checked for NULL, but this happens in line 444, i.e. 750+ lines above. Any (future changes) in between could invalidate it.

BTW.: IMHO, `XMLUtils` should provide function-style Getters, too, that don't require handing over a reference variable.

Yes, I'm new to this group and I do the code review like I do at work. Am I pushing too hard?

2016-12-27 17:48 UTC, MartijnKaijser commented on xbmc/settings/AdvancedSettings.cpp
> +  }
We welcome constructive reviews 👍

2016-12-27 20:03 UTC, FernetMenta commented
@verybadsoldier for what reason should we wait not always for network to be ready?

2016-12-27 22:24 UTC, verybadsoldier commented
@FernetMenta
For me it would be fine if it was just hardwired but I am afraid it could be a problem for systems without network (e.g. no NIC at all or no cable connected). Also there might be users who run Kodi exclusively from local storage and do not care for network connections. 
In both cases an unwanted delay would be introduced on wakeup. In my case it takes about 7 seconds for the network to beccome available.

2016-12-28 01:04 UTC, verybadsoldier commented
Reworked so that this only kicks in if there is at least one network interface. This will prevent waiting for network when there are no network Interfaces in the system. So maybe I really could just remove the advanced setting and make waiting for network after wakeup the standard behavior.

2016-12-28 05:46 UTC, MartijnKaijser commented
Regardless an advancedsettings is out of the question here

2016-12-28 07:50 UTC, t4-ravenbird commented
The original problem that this PR seeks to solve is already possible to fix by enabling the built-in [wake-on-lan](http://kodi.wiki/view/wake%20on%20lan)

That solution works the same when starting up, and when resuming from suspend. There have been MySQL issues in both cases and they are both solved when using wake-on-lan, for instance ;
http://forum.kodi.tv/showthread.php?tid=213321&pid=1879249#pid1879249
http://forum.kodi.tv/showthread.php?tid=173267&pid=1820808#pid1820808

2016-12-28 12:35 UTC, verybadsoldier commented
Okay, removed the advanced settings.

@t4-ravenbird 
Yes, the wake-on-lan feature can help here but to be honest I see it only as a workaround:
- the original problem is not related to WOL, so having to enable the WOL-feature feels a bit "hackish"
- the WOL-wait does not really wait until the network connection is established, according to the code it seems to just wait the configured period of time regardless of the network state
- it only kicks in when the network is actually accessed (which makes sense in the WOL context), but in my opinion Kodi's network itself should be up and working after resuming

2016-12-29 08:35 UTC, t4-ravenbird commented
WOL-wait waits until the correct network interface is available before proceeding (As opposed to just waiting for 1st interface)
Any thread accessing the network resource is held back until it is ready - any other threads are free to run.

2016-12-29 23:22 UTC, verybadsoldier commented
I fiddled around lots with this WOL-wait today and it does not really fix the problem. In some cases it did help but in most cases it did not get triggered when accessing network resources after resuming.

2016-12-30 08:11 UTC, FernetMenta commented on xbmc/powermanagement/PowerManager.cpp
> +  const static int numMaxTries = 50;
those are kind of ugly. I would make them configurable as max waiting time. a value of zero disables this feature.

2016-12-30 09:51 UTC, Jalle19 commented on xbmc/settings/AdvancedSettings.cpp
> +  }
I thought you were a bot at first since the comments were so methodical and clean. +1

2016-12-30 19:25 UTC, verybadsoldier commented
Agreed, I changed the loop and also added a setting which is configurable in the UI under "System -> Power saving".

![image](https://cloud.githubusercontent.com/assets/364469/21571271/f7a9bcc2-cecd-11e6-906c-c4d6786c9f05.png)

2016-12-30 19:28 UTC, MartijnKaijser commented
I think a max of 120 seconds is a bit much. By that time i would have throw it out the window. 30 might be more realistic although still a lot

2016-12-30 19:29 UTC, stefansaraev commented
there is an unwanted mode (0644 -> 755) change in this PR. please chmod everything back to 0644

2016-12-30 19:58 UTC, verybadsoldier commented
Reduced maximum timeout value to 30.

Thanks for pointing out the mode changes, fixed. Sorry for that.

2016-12-30 20:07 UTC, FernetMenta commented
looks good to me
thanks!

2016-12-31 16:10 UTC, MartijnKaijser commented
See my comments about the text. Once those are done we can let it build and merge it in.

2016-12-31 16:11 UTC, MartijnKaijser commented on addons/resource.language.en_gb/resources/strings.po
> +msgid "Set the maximum time to wait for the network to come up after waking up."
"Set the maximum time to wait for the network to come up after starting or waking up. When time has past before network is up startup will continue."
If it indeed also handles a startup (which it should imo)

2016-12-31 16:18 UTC, chewitt commented
@verybadsoldier Does this also handle "wait on startup" ?? if not, could it do both? There's been a long-standing issue for MySQL users where Kodi starts and the network stack isn't ready. LE has a delayed start workaround function that works, but it would be cleaner if Kodi was able to handle it internally.

2016-12-31 17:13 UTC, verybadsoldier commented
Ok, I have changed the wording, thanks for the feedback.

Currently it does only handle the wait when waking up. I will take a look to reuse this feature also on startup. But if possible I would like to finish this first and then do it in a separate PR if that would be ok for. I promise to come back :)

2016-12-31 17:20 UTC, MartijnKaijser commented
👍 might want to remove "starting or" part of the strin then and we're ready to go

2016-12-31 17:40 UTC, verybadsoldier commented
Oh, good point, fixed :D Thanks!

2016-12-31 17:41 UTC, MartijnKaijser commented
jenkins build this please

2016-12-31 20:03 UTC, MartijnKaijser commented
Jenkins build and merge

2016-12-31 21:28 UTC, MartijnKaijser commented
Jenkins build this please

2016-12-31 22:42 UTC, verybadsoldier commented
(Hopefully) fixed header issue for Android/iOS. Would you please trigger Jenkins again to see if it works?
Sorry I cannot test this on my end :(

2016-12-31 23:06 UTC, MartijnKaijser commented
No problem. That why we have jenkins build this please

2016-12-31 23:44 UTC, merged