[PVR] Krypton: Fix PVR Manager crash on startup
xbmc/xbmc pull request #11284
Opened 2016-12-28 11:23 UTC by ksooo

Backport of #11283 

@Jalle19 for review?

2016-12-28 21:48 UTC, ksooo commented
jenkins build this please

2016-12-28 22:52 UTC, FrankHeimes requested changes
Acquiring two locks in a function is error-prone. It can work if the order of aquisition is always the same.
Can you guarantee that neither `Start()` nor `Stop()` is ever called while `m_critSection` is held?

2016-12-28 22:52 UTC, FrankHeimes commented on xbmc/pvr/PVRManager.h
> +    CCriticalSection                m_initMutex; // mutex for protecting pvr manager's start/restart sequence */
`m_startStopMutex` would be a more appropriate name as it serializes only these two function.

2016-12-28 23:18 UTC, ksooo commented
> Can you guarantee that neither Start() nor Stop() is ever called while m_critSection is held?

 As long as I'm maintaining this code and reviewing the patches, yes, because I'm very well aware of this problem.

 But, you are right, this code is not in good shape. The whole pvr manager start/stop logic is subject to complete rework, but not for Krypton.

2016-12-29 08:38 UTC, ksooo commented on xbmc/pvr/PVRManager.h
> +    CCriticalSection                m_initMutex; // mutex for protecting pvr manager's start/restart sequence */
changed. thx

2016-12-29 08:39 UTC, ksooo commented
jenkins build this please

2016-12-29 10:48 UTC, ksooo commented
I think this one is good to go. Well tested etc pp blah blah... (would have merged the respective master PR first, if jenkins would not act up on me currently)

2016-12-29 10:48 UTC, merged