Fix Party Mode and Singles Node missing song information (ticket #17142)
xbmc/xbmc pull request #11286
Opened 2016-12-28 13:01 UTC by DaveTBlake

This fixes Trac ticket #17142
When showing Song Info dialog for items in current playlist in party mode, or in the Singles node, the contributors (control 50) control list is empty. 

This is because the contributor data was not being fetched from the database by `CMusicDatabase::GetRandomSong`, and `CPartyModeManager::AddInitialSongs` was not calling  `CMusicDatabase::GetSongsFullByWhere`. Likewise with `CDirectoryNodeSingles::GetContent`.

This needs to be backported to v17

2016-12-28 21:30 UTC, FrankHeimes requested changes
GetSongsFullByWhere() may return true (line 4286 in MusicDataBase.cpp) before reserving elements in items. In this case, +items[0] in line 5285 causes an invalid access.
Consider testing if items is empty.
(This time, I could not add inline review comments - don't understand why).

2016-12-29 08:21 UTC, DaveTBlake commented
Thanks for taking an interest Frank, and a valid point now fixed (and in backport too).

Not sure about the inline comments thing, nor why your comment has caused a "X" - "changes requested" - in the reviewers list. Mostly the team works using discussion rather than approveal or disapproveal, so the "X" is a little disconcerting.

2016-12-29 11:27 UTC, MartijnKaijser commented
jenkins build this please

2016-12-29 12:06 UTC, FrankHeimes commented
@DaveTBlake I see. I temporarily didn't find the _sweet spot_ in the line that causes the + button to pop up. That's why I couldn't add inline comments. I'll honour your discussion habbits. Still I do find GitHubs code review mechanism practical. _Approvals_ allow to document that the code has been reviewed without comments.

2016-12-29 12:26 UTC, FernetMenta commented
@FrankHeimes 

GitHub's help text for approvals:

```
Submit feedback and approve merging these changes.
```

That means that approvals should only be done by the maintainers of a particular component. Thei finally decide if the PR should get merged or not.

2016-12-29 12:32 UTC, FrankHeimes commented
@FernetMenta OK, got that - thanks!

2016-12-30 08:55 UTC, MartijnKaijser commented
jenkins build this please

2016-12-30 09:51 UTC, merged