Bitstream refactor / VC1Bitstream parser
xbmc/xbmc pull request #11417
Opened 2017-01-10 21:48 UTC by peak3d

Implement VC1-Packet Bitstream parser

## Motivation and Context
VC-1 in mkv container sometimes have only DTS but no PTS values.
AML decoder needs from time to time a secure PTS value wich will be set on I-Frames.

This PR does currently NOT return every I-Frame, but it returns true on recovery points.

## How Has This Been Tested?
Separate test environment

## Types of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2017-01-11 06:32 UTC, FernetMenta commented
looks much cleaner now, thanks
(I have not looked at the details. I assume this has been tested and works)

2017-01-11 07:49 UTC, peak3d commented
jenkins build this please

2017-01-11 08:24 UTC, Rechi commented on xbmc/utils/BitstreamConverter.cpp
> +          rate = 60.0f;
shouldn't this be `static_cast<float>(60000.0 / 1001.0);` like above?

2017-01-11 08:53 UTC, peak3d commented on xbmc/utils/BitstreamConverter.cpp
> +          rate = 60.0f;
ooops :-) Thx!

2017-01-11 08:55 UTC, peak3d commented
jenkins build this please

2017-01-11 09:10 UTC, Rechi commented on xbmc/utils/VC1BitstreamParser.h
> +
add `#include <stdint.h>`
maybe this is also missing in other files

2017-01-11 09:17 UTC, peak3d commented
jenkins build this please

2017-01-11 09:51 UTC, Rechi commented on xbmc/utils/CMakeLists.txt
> +            BitstreamWriter.cpp
maybe you wanted `BitstreamWriter.h` here

2017-01-11 10:18 UTC, peak3d commented on xbmc/utils/CMakeLists.txt
> +            BitstreamWriter.cpp
omg :-) was late yesterday

2017-01-11 10:24 UTC, peak3d commented
jenkins build this please

2017-01-11 12:36 UTC, Rechi requested changes
Since you have moved `BS_WL32` and `BS_RB16` to other files you must include `xbmc/utils/BitstreamReader.h` in `xbmc/cores/VideoPlayer/DVDCodecs/Video/VTB.cpp` and `xbmc/utils/BitstreamWriter.h ` in `xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp`

2017-01-11 12:36 UTC, Rechi commented on xbmc/utils/BitstreamWriter.h
> +  uint8_t   *buf, *buf_ptr, *buf_end;
compiler says `buf_end` is unused

2017-01-11 12:36 UTC, Rechi commented on xbmc/utils/BitstreamWriter.h
> +  int       size_in_bits;
compiler says `size_in_bits` is unused

2017-01-11 12:36 UTC, Rechi commented on xbmc/utils/BitstreamWriter.cpp
> +int       size_in_bits;
is this block needed?

2017-01-13 19:00 UTC, thebrid commented on xbmc/utils/BitstreamReader.cpp
> +  ret = ((ret << i) >> i) >> ((nbytes * 8) - nbits - offbits);
Up to here, this function duplicates ReadBits. Consider moving the common parts to a separate inline function.

2017-01-13 19:06 UTC, thebrid commented on xbmc/utils/VC1BitstreamParser.h
> +
Should this be:

#include <cstdint>

2017-01-14 10:51 UTC, fritsch commented
What I wonder is: if a future android maintainer makes the transition to ffmpeg hwaccel for mediacodec this code would be obsolete? What are the plans here? Is there already an alliance of the willing that make up plans for that future after v17?

2017-01-15 14:30 UTC, MrMC commented
ffmpeg/mediacodec needs much more improvement before DVDVideoCodecAndroidMediaCodec can be replaced. Same for VideoToolBox, close but not quite there. Too many missed corner cases.

2017-01-15 15:30 UTC, fritsch commented
Can you name one?

Am 15.01.2017 3:30 nachm. schrieb "Scott Davilla" <notifications@github.com
>:

> ffmpeg/mediacodec needs much more improvement before
> DVDVideoCodecAndroidMediaCodec can be replaced. Same for VideoToolBox,
> close but not quite there. Too many missed corner cases.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/xbmc/xbmc/pull/11417#issuecomment-272698670>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABCfHVBGdf0kKnfbOR-Y090nO-2d0dA4ks5rSi1-gaJpZM4Lf7qt>
> .
>

2017-01-15 15:52 UTC, MrMC commented
/* TODO: implement surface handling */

2017-01-15 16:04 UTC, MrMC commented
For videotoolbox, here are a few
1) assumes h264 has only one PPS in extra data. There can be more.
2) does not handle kVTInvalidSessionErr correctly and try to reset the session.
3) does not use the correct destinationPixelBufferAttributes for pure surface.
4) does not allow downs scaling at the decoder, needed for 4k/h264 on some devices as they just don't have the memory bandwidth.

2017-01-15 21:00 UTC, peak3d commented on xbmc/utils/BitstreamWriter.cpp
> +int       size_in_bits;
failure , thanks!

2017-01-15 21:15 UTC, peak3d commented
jenkins build this please

2017-01-16 13:55 UTC, MrMC commented
Nice refactor of bitstream utils.They will be useful to replace the current AC3/EAC3/DTS format probing.

2017-01-16 14:31 UTC, peak3d commented
jenkins build this please and don't stop with errors nobody want to see.

2017-01-16 14:51 UTC, peak3d commented
jenkins build this please (I know, it was my fault :-)

2017-01-16 15:36 UTC, peak3d commented
jenkins build the correct commit please

2017-01-16 15:37 UTC, peak3d commented
jenkins build this please

2017-01-16 16:13 UTC, merged

2018-04-01 07:47 UTC, corehack commented
Are these improvements used in Kodi alpha 1 ? I still get audio out of sync problem with most VC-1 files on Minix U9-H (amlogic s912)