[win][platinum] Change GWL_USERDATA to GWLP_USERDATA
xbmc/xbmc pull request #11437
Opened 2017-01-13 10:47 UTC by Rechi

## Description

Replace `GWL_USERDATA` with `GWLP_USERDATA`. They both are defined to the same value on Win32 so no real change on Win32.
Cherry picked witch permission from @Paxxi.

## Motivation and Context

On Win64 `GWL_USERDATA` is undefined and `GWLP_USERDATA` must be used.

## How Has This Been Tested?

Compiled on Windows (Win32 & x64).

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

2017-01-13 12:01 UTC, hudokkow commented
If you're up to it, a patch file is welcome in https://github.com/xbmc/xbmc/tree/master/lib/libUPnP/patches

2017-01-13 12:41 UTC, Montellese commented
A patch file is not only welcome it's mandatory. Otherwise we cannot keep track of changes to external libraries.

2017-01-13 12:41 UTC, Montellese requested changes
A patch file is not only welcome it's mandatory. Otherwise we cannot keep track of changes to external libraries.

2017-01-13 19:49 UTC, Rechi commented
@Montellese added patch file

2017-01-14 07:43 UTC, Montellese approved these changes

2017-01-14 11:35 UTC, merged