add pycryptodome python module
xbmc/xbmc pull request #11477
Opened 2017-01-17 13:23 UTC by peak3d

Add PyCryptoDome python cryptography module

## Description
see title

## Motivation and Context
Add crypto to python addon developing

## Types of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2017-01-17 17:32 UTC, stefansaraev commented
not agains this but here my 2 cents if it matters:

we should avoid adding any native python modules, addons should use as much from python stdlib as they can. pil is more than enough pain, already.

2017-01-17 20:13 UTC, Paxxi commented
@stefansaraev agreed but unfortunately python does not expose the crypto library from openssl, maybe gnutls? So this is one of the bits that makes sense to ship as a binary. 

Writing this it just hit me that maybe we can expose these through Kodi and avoid the python build pain? 

Same goes for pillow but that's a rather large API surface

2017-01-18 17:22 UTC, stefansaraev commented
yea. sure.

anyhow. this should be done as script.module.pil is then - make a new addon, let's say script.module.pycryptodome, add it to addon-manifest.xml, and let 3rdparty addons do ```<import addon="script.module.pycryptodome" version="x.y.z">```

2017-01-19 15:32 UTC, peak3d commented
1.) @stefansaraev looked at the PIL patches and decided aginst such a thing (beside the fact that I don't understand all the mess to move / copy things into an addon-folder)
2.) The current PR uses the concept how python modules are normally installed. The dependency is installed with python --install in site-packages folder (and yes, it feels correct)
3.) I have removed the SelfTest for kod (wich saves 15MB of things wedon't use)
4.) For android packaging this PR renames the .so files using the folder names (Crypto/Hash/test.so will become Crypto_Hash_test.so and resides in androids system/lib path.

@wsnipex any objections?

2017-01-19 16:16 UTC, wsnipex commented
lets see if it builds:
jenkins build this please

2017-01-19 16:35 UTC, peak3d commented
It's at no place triggered, means every build comes for now without crypto stuff

2017-01-19 19:00 UTC, wsnipex commented
you have to add it to depens/target/Makefile

2017-01-19 19:19 UTC, peak3d commented
@stefansaraev what is the difference / benefit to make it "same as PIL" ? Seems that you have at least more background than me about those py things.

2017-01-19 19:35 UTC, peak3d commented
jenkins build this please

2017-01-19 20:29 UTC, stefansaraev commented
@peak3d it has few benefits to not ship in site-packages/ but as a separate addon, and require 3rdparties to explicitly import it:

- that's how it works with all other (non std) python stuff, example: addons dont just import beautifulsoup. they are required to import script.module.beautifulsoup4 in their addon.xml

- it would be clear if a specific addon needs (and uses) pycryptodome, you can identify those addons by simple grep in repo's addons.xml in case you want to remove pycryptodome in future :)

also, there was an effort to force addons not use import from site-packages, but use only modules that are already in the repo (ones we can control), see #5127. there are good reasons to do so. pil (and now pycryptodome) makes this task harder

2017-01-19 21:10 UTC, peak3d commented
Thanks a lot for making this clear, @stefansaraev. Is PIL part of the kodi package?
I haven't found script addons in repo.binary.addon, but PIL is binary, isn't it?

2017-01-19 21:37 UTC, stefansaraev commented
https://github.com/xbmc/xbmc/tree/master/addons/script.module.pil

on linux, it's shipped as addon.xml only, and Pillow package from system is used (example: ubuntu, python-pil is a required runtime dependency, it is automaticaly pulled by apt-get when you install kodi). embedded distros (OE, LE, buildroot based) take care to have it cross-compiled and installed. on non-linux - it is part of the kodi package.

ios
```
seo@x230 ~/Desktop/ios $ ar x ../org.xbmc.kodi-ios_17.0-0-rc3_iphoneos-arm.deb 
seo@x230 ~/Desktop/ios $ tar tf data.tar.lzma | grep Pillow
./Applications/Kodi.app/Frameworks/lib/python2.7/site-packages/Pillow-3.0.0-py2.7-macosx-10.4-x86_64.egg
```

osx
```
seo@x220 ~/Desktop $ 7z l kodi-17.0-Krypton_rc3-x86_64.dmg  | grep Pillow
2017-01-12 18:51:01 .....      1118086      1118208  Kodi/Kodi.app/Contents/Libraries/lib/python2.7/site-packages/Pillow-3.0.0-py2.7-macosx-10.4-x86_64.egg
```

android
```
seo@x230 ~/Desktop $ unzip -l kodi-17.0-Krypton_rc3-armeabi-v7a.apk  | grep -i script.module.pil | pastebinit 
http://sprunge.us/TjIj
```
windows
```
seo@x230 ~/Desktop $ find kodi-17.0-Krypton_rc3/uni_pfatxtv/script.module.pil/ | pastebinit 
http://sprunge.us/hdQf
```

ok. on osx/ios it is in site-packages/ no idea why

2017-01-19 21:47 UTC, peak3d commented
would be  a simple dummy-addon (script.module.pycryptodome) enough?
Wich is generated during the build process currently used?

If pycrypto is not build, the addon is not generated.

Ok, for linux we have to set the same dependencies for kodi install, but to be honest, I don't see the reason why copying (for windows) all the files from a to b. let the things in site_packages, write the dummy-addon and it should work like PIL.

Pls. correct me if it's nit correct.

2017-01-19 21:57 UTC, stefansaraev commented
a dummy addon (on all platforms) + runtime dependency on linux (ubuntu) would be enough yes. on non linux.. honestly, I have no idea if it should be in site-packages or an .egg file inside addon's dir. IMO it should be an .egg in addon's dir, but maybe there are platform limitations, idk, platform devs know better

2017-01-19 22:05 UTC, peak3d commented
The complete addon system is currently reworked by @alwinus, I want to keep work as small as possible ( I hate wasting time for nothing).

My suggestion:
- I'll add an dummy addon
- I'll look why pycryptodome is currently not build for win (is there an other location for deps??)
- I try to figure out where the runtime dep is located (do you have a tipp)??

Then we wait for alwinus to finish his work and figure out a solution wich fits best for both PIL / crypto.
Ok with that?

2017-01-19 22:14 UTC, stefansaraev commented
> The complete addon system is currently reworked by @alwinus, I want to keep work as small as possible ( I hate wasting time for nothing).

afaik, he is working on binary addons, not python suff..

> My suggestion:

> I'll add an dummy addon

a right thing to do, imo.

> I'll look why pycryptodome is currently not build for win (is there an other location for deps??)

idk, cc @Paxxi and other windows people

> I try to figure out where the runtime dep is located (do you have a tipp)??

uh.. none. as said, ios/osx seems to be different than others and I have no idea why.

> Then we wait for alwinus to finish his work and figure out a solution wich fits best for both PIL / crypto.

> Ok with that?

sure, I am ok with everything, I just express an opinion here, before it's too late, my comments are not a requests for change ;)

2017-01-19 22:21 UTC, peak3d commented
Your experience is far better than mine in this area - I appreciate your input a lot!

> afaik, he is working on binary addons, not python suff..
alwinus is also changing much / all of the python concept

2017-01-19 22:24 UTC, stefansaraev commented
btw, if script.module.pycryptodome is not added to addon-manifest.xml, it will (unless somthing has changed recently and I missed it) be added to addondb as "disabled" addon on first run.

2017-01-19 22:27 UTC, peak3d commented
thx,!

2017-01-19 22:55 UTC, Rechi commented
Windows doesn't build any deps under tools/depends. Most of them get downloaded as binary.
Someone needs to compile it for windows, pack it and upload to the mirrors.
>I'll look why pycryptodome is currently not build for win (is there an other location for deps??)

2017-01-19 22:56 UTC, peak3d commented
ok, @Rechi just looked into pillow 7z file, I'll try to prepare such a thing

2017-01-20 10:02 UTC, peak3d commented
jenkins build this please

2017-01-20 11:22 UTC, peak3d commented
@wsnipex there are 2 red once in jenkins build but for me they don't seem to be PR related (tests fail)
If you agree, I'll merge...

2017-01-20 11:37 UTC, Rechi commented
Maybe the change in `tools/depends/target/python27/modules.setup`  causes the Segmentation fault.

2017-01-20 13:12 UTC, MartijnKaijser commented on system/addon-manifest.xml
> +  <addon>script.module.pycryptodome</addon>
This should not be there (PIL shouldn't either). It is not a mandatory addon and any addon that actually requires it should import it like normal dependency which should auto enable it.

2017-01-20 13:15 UTC, MartijnKaijser requested changes

2017-01-20 13:15 UTC, MartijnKaijser commented on tools/depends/target/pythonmodule-pycryptodome/addon.xml
> +    <platform>all</platform>
This is false cause it's not there on Windows

2017-01-20 13:16 UTC, MartijnKaijser requested changes

2017-01-20 13:16 UTC, MartijnKaijser commented on system/addon-manifest.xml
> +  <addon>script.module.pycryptodome</addon>
Also this is not packaged on Windows so it would break starting Windows.

2017-01-20 13:17 UTC, peak3d commented on tools/depends/target/pythonmodule-pycryptodome/addon.xml
> +    <platform>all</platform>
its available on windows, just finished the 7z

2017-01-20 13:29 UTC, ronie commented on system/addon-manifest.xml
> +  <addon>script.module.pycryptodome</addon>
i thought the manifest file decides which addons are enabled by default?
iirc if it's not listed the script.module will be installed, but disabled.

2017-01-20 13:34 UTC, peak3d commented
@ronie afaiu @MartijnKaijser  correct, it will be enabled at the time the first 3rd-party addon requests it.

2017-01-20 14:30 UTC, peak3d commented
jenkins build this please

2017-01-20 16:54 UTC, stefansaraev commented on system/addon-manifest.xml
> +  <addon>script.module.pycryptodome</addon>
yes, that's exactly what it is doing (and you can not disable/unintall those addons), @ronie

2017-01-20 17:25 UTC, peak3d commented
@stefansaraev i read from the (outdated) comment to ronie that we should add pycryptodome to addon-manifest.xml, right?

2017-01-20 17:37 UTC, stefansaraev commented
@peak3d yes, I commented on that yesterday.

agian, in short: every addon that is shipped with the kodi distributionn MUST be added to addon-manifest.xml. it is NOT an optional thing. otherwise addoninstaller would add that addon to addondb in DISABLED state. this was a well-discussed DESIGN decision and I doubt it is going to be changed.

2017-01-20 17:49 UTC, stefansaraev commented
one more thing: it would not only be added as disabled to addondb, but addons of type "xbmc.python.module" are not shown in the addonmanager GUI (addons -> my addons -> all), so user has NO chance to manualy enable it

2017-01-20 18:11 UTC, Rechi commented
`addons/script.module.pycryptodome/*` must be added in `cmake/installdata/common/addons.txt`

2017-01-21 20:46 UTC, peak3d commented
jenkins build this please

2017-01-22 00:15 UTC, merged