[python] add setType() method for edit controls
xbmc/xbmc pull request #11486
Opened 2017-01-18 22:38 UTC by ronie

allow addons to define the edit control type.

@tamland @phil65

2017-01-19 12:45 UTC, tamland commented
The types should be mapped to a constants using the SWIG_CONSTANT2 macro (so they can be read by humans). Also, I would add this parameter to the constructor instead as I don't see why you would want to change the type after creating it.

2017-01-19 17:40 UTC, ronie commented
@tamland i indeed need the functionality to change the input type on the fly.
similar to our smartplaylist editor, where input type depends on the selection made by another control in the same window:
![smartplaylist-rule](https://cloud.githubusercontent.com/assets/687265/22118062/99f197fe-de76-11e6-81d9-8d1cb3f35cf1.jpg)


i've added the constants, as requested

2017-01-21 14:47 UTC, thebrid commented on xbmc/interfaces/legacy/Control.cpp
> +        ((CGUIEditControl *) pGUIControl)->SetInputType((CGUIEditControl::INPUT_TYPE)type, CVariant{heading});
Consider using C++ style casts over C-style.

2017-01-22 14:09 UTC, tamland commented
ok, makes sense (and changes looks good!)

2017-02-14 19:09 UTC, MartijnKaijser commented
ping @ronie :) Not sure if you can also take care of the comment

2017-02-14 19:26 UTC, ronie commented
i can, and i will. just not sure when :-)

2017-05-07 13:55 UTC, Paxxi requested changes
can you make the changes and we'll get this merged

2017-05-07 13:55 UTC, Paxxi commented on xbmc/interfaces/legacy/Control.cpp
> +        ((CGUIEditControl *) pGUIControl)->SetInputType((CGUIEditControl::INPUT_TYPE)type, CVariant{heading});
I agree with you on this one.
this would be `static_cast<CGUIEditControl*>(pGUIControl)->` and same for the type

2017-06-12 12:55 UTC, romanvm commented on xbmc/interfaces/legacy/Control.h
> +      /// | xbmcgui.INPUT_TYPE_PASSWORD_MD5  | (input is masked, return md5 hash of input)
Maybe it's worth using a more secure hash (if possible)?

2018-01-26 20:06 UTC, jenkins4kodi commented
@ronie this needs a rebase

2018-02-14 00:04 UTC, jenkins4kodi commented
@ronie this needs a rebase

2018-03-15 10:13 UTC, Rechi commented
@Paxxi ping

2018-03-23 17:37 UTC, Paxxi approved these changes
I don't really remember what I wanted changed but I think it looks fine

2018-03-23 21:38 UTC, Rechi commented
@ronie ready to get merged?

2018-03-23 21:41 UTC, ronie commented
yup

2018-03-23 21:41 UTC, merged