[PVR] fix timer type display for 'invalid' types
xbmc/xbmc pull request #11753
Opened 2017-02-25 22:43 UTC by metaron-uk

Allows 'invalid' timer types to be correctly displayed in the Timer Settings dialog
(See forum http://forum.kodi.tv/showthread.php?tid=307538)

## Description
Currently a timer type will be 'skipped' when building the list of valid timer types to present in the Timer Settings dialog. The result is that not all timer types are displayed properly.
This change adds the current type to the list if it would otherwise be skipped so the settings can be displayed correctly.

## Motivation and Context
Ensures timers are always displayed correctly.

## How Has This Been Tested?
On x86 (linux) with pvr.mythtv client.

## Screenshots:
Display of an 'Unhandled' timer type
![screenshot062](https://cloud.githubusercontent.com/assets/12870817/23335295/73d4da58-fbaa-11e6-8a75-a691ddd29877.png)
After (How this type should be presented):
![screenshot063](https://cloud.githubusercontent.com/assets/12870817/23335296/7ff1640a-fbaa-11e6-9911-daedc0b86f71.png)
![screenshot064](https://cloud.githubusercontent.com/assets/12870817/23335297/84e0b402-fbaa-11e6-9274-285bc29bc55b.png)
Before (How this type was previously presented):
![screenshot065](https://cloud.githubusercontent.com/assets/12870817/23335317/093bc21e-fbab-11e6-8db0-07a07be42bef.png)
![screenshot066](https://cloud.githubusercontent.com/assets/12870817/23335319/0f467550-fbab-11e6-96d6-0f356ffbf6ec.png)

## Types of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2017-02-26 09:08 UTC, metaron-uk commented
@ksooo - if you like this, let me know and I'll create a backport PR as I think it ought to go in the next Krypton point release as well.
@janbar - have you come across this problem yourself? If so, what do you think of my proposed solution.

2017-02-26 11:34 UTC, ksooo commented
Yes, your patch ensures that it cannot happen anymore that the timer type of the current timer tag is omitted from the timer types list, but could you please explain how it can happen that a tag is given to the dialog that leads to this problem?

2017-02-26 12:38 UTC, metaron-uk commented
* if (type->ForbidsNewInstances()) because only the backend has the necessary UI to create timers of this type, but Kodi can still tweak an existing one (as in the screeshot  example)
* if for some other reason the conditions to create a new rule timer of this type aren't met (although you seem to have fixed a lot of these with your latest PR :-)

2017-02-26 18:10 UTC, ksooo commented
The correct fix for the "forbidsnewinstances" case would be to add  "m_bIsNewTimer &&" in front of the respective if clause in the timer types init member function. Seems I forgot this with my latest PR.

Are there any other real cases? Then we should fix those one by one.

Adding the "golden hammer" like you suggest only hides the actual bugs leading to filtering out a type, imo.

2017-02-26 19:57 UTC, metaron-uk commented
Adding "m_bIsNewTimer &&" in front covers the 'new timer' case, but what about modifying an existing timer rule of another type?
If the client 'ForbidsNewInstances()' of that timer type, then surely it shouldn't be available for selection as an alternative.
In the same way, if type->RequiresEpgTagOnCreate() && !m_timerInfoTag->GetEpgInfoTag() etc... those wouldn't be valid options to select either.
imo, the only time that an 'invalid' type should appear in the list is when the timer already has that type (aka the "golden hammer").

2017-02-26 21:10 UTC, ksooo commented
So, basically you are saying to revert the other "m_bIsNewTimer &&" changes a did in my latest PR and to use the "golden hammer" instead?

2017-02-26 21:23 UTC, metaron-uk commented
That would be my recommendation, yes.

2017-02-26 22:47 UTC, janbar commented
@metaron-uk , I thought "unhandled" was treated as presented here, regarding its declaration:

    PVR_TIMER_TYPE_IS_REPEATING |
    PVR_TIMER_TYPE_FORBIDS_NEW_INSTANCES |
    PVR_TIMER_TYPE_SUPPORTS_PRIORITY |
    PVR_TIMER_TYPE_SUPPORTS_LIFETIME |
    PVR_TIMER_TYPE_SUPPORTS_RECORDING_GROUP

Seems that isn't the case. I have never been able to test it. But your first screenshot "After (How this type should be presented)" is right for me and this is what I expected.

2017-02-27 06:43 UTC, ksooo commented
@metaron-uk you are right. Could you please change this PR to revert my last changes and to implement the "golden hammer"?

2017-02-27 08:14 UTC, ksooo requested changes

2017-02-27 08:14 UTC, ksooo commented on xbmc/pvr/dialogs/GUIDialogPVRTimerSettings.cpp
> +    if (type == m_timerType)
Please change to <code>if (!foundThisType && *type == *m_timertype)</code>.

First is for efficiency, to only compare types if actually needed.
Second is to not compare the timer type pointers but the actual objects.

2017-02-27 08:14 UTC, ksooo commented on xbmc/pvr/dialogs/GUIDialogPVRTimerSettings.cpp
> +  bool foundThisType(false);
I would prefer if you use a type prfix for the variable name => bFoundThisType
We do not do this in a consistent way in our code base, but to follow our coding guidelines we should obey the guideline for new code.

2017-02-27 08:14 UTC, ksooo commented on xbmc/pvr/dialogs/GUIDialogPVRTimerSettings.cpp
> +  if (!foundThisType)
Pleaes insert a blank line above this line.

2017-02-27 22:47 UTC, metaron-uk commented
> @metaron-uk , I thought "unhandled" was treated as presented here, regarding its declaration:
> 
> PVR_TIMER_TYPE_IS_REPEATING |
> PVR_TIMER_TYPE_FORBIDS_NEW_INSTANCES |
> PVR_TIMER_TYPE_SUPPORTS_PRIORITY |
> PVR_TIMER_TYPE_SUPPORTS_LIFETIME |
> PVR_TIMER_TYPE_SUPPORTS_RECORDING_GROUP
>
> Seems that isn't the case. I have never been able to test it. But your first screenshot "After (How this type should be presented)" is right for me and this is what I expected.

@janbar You are right, I have been experimenting...

2017-02-27 22:47 UTC, metaron-uk commented on xbmc/pvr/dialogs/GUIDialogPVRTimerSettings.cpp
> +  bool foundThisType(false);
OK

2017-02-27 22:47 UTC, metaron-uk commented on xbmc/pvr/dialogs/GUIDialogPVRTimerSettings.cpp
> +    if (type == m_timerType)
Good catch.

2017-02-27 22:48 UTC, metaron-uk commented on xbmc/pvr/dialogs/GUIDialogPVRTimerSettings.cpp
> +  if (!foundThisType)
done

2017-02-27 23:11 UTC, metaron-uk commented
@ksooo not sure why github is showing both the commits in your last pull request - I only reverted one of them. Let me know if you want this squashed into one.

2017-02-28 06:38 UTC, ksooo commented
Please rebase to latest master and then squash the changes of the PR to a single commit.

2017-02-28 21:01 UTC, metaron-uk commented
@ksooo - rebased as requested and checked on x86 linux - good to go.

2017-02-28 21:14 UTC, ksooo commented
jenkins build this please

2017-02-28 21:15 UTC, ksooo approved these changes
thanks

2017-02-28 22:41 UTC, merged