[xbmc][win32] Move to using unicode win32 api methods
xbmc/xbmc pull request #11780
Opened 2017-02-28 19:31 UTC by Paxxi

This should have been done a long time ago but
with UWP no longer supporting the ascii versions it's
time to get it done.

The changes in UnrarXLib isn't really tested but it's
about to get dropped from our tree anyway.

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

2017-02-28 19:32 UTC, Paxxi commented
jenkins build this please

maybe @Rechi for review?

2017-03-01 08:15 UTC, Rechi reviewed
haven't tested this yet, only looked at the code changes

2017-03-01 08:15 UTC, Rechi commented on cmake/platform/windows/defines.txt
> +/DTARGET_WINDOWS /DNOMINMAX /D_CRT_SECURE_NO_WARNINGS /D_WINSOCKAPI_
don't think this is needed

2017-03-01 08:15 UTC, Rechi commented on lib/UnrarXLib/suballoc.cpp
> +    OutputDebugString(L"ERROR - had to allocate smaller data than required, extract can very well fail");
with this change every target expect windows fails

2017-03-01 08:15 UTC, Rechi commented on lib/UnrarXLib/win32acl.cpp
>    return;
function returns now on every platform without any code executed
If this is relay wanted remove code below.

2017-03-01 08:15 UTC, Rechi commented on xbmc/platform/win32/CharsetConverter.cpp
> +#if defined(TARGET_WINDOWS) || defined(TARGET_WIN10)
shouldn't this be handled by the build system?

2017-03-01 08:15 UTC, Rechi commented on xbmc/platform/win32/CharsetConverter.h
> +#if defined(TARGET_WINDOWS) || defined(TARGET_WIN10)
shouldn't this be handled by the build system?

2017-03-01 10:32 UTC, Montellese requested changes
Two general observations:
* What is `TARGET_WIN10`? You introduce it in some places but by far not in all.
* Please move the changes to libUPnP into a separate commit and add another commit with the patch of the separate commit to the libUPnP patch set.

2017-03-01 10:32 UTC, Montellese commented on lib/libUPnP/Neptune/Source/System/Win32/NptWin32SerialPort.cpp
> +}
Something went wrong here. The whole file is shown as changed but you probably only changed a few lines.

2017-03-01 17:04 UTC, Paxxi commented on xbmc/platform/win32/CharsetConverter.cpp
> +#if defined(TARGET_WINDOWS) || defined(TARGET_WIN10)
I want to avoid having ifdefs in every file that includes this file so I chose to stick them in here to make calling code a bit cleaner

2017-03-01 17:04 UTC, Paxxi commented on xbmc/platform/win32/CharsetConverter.h
> +#if defined(TARGET_WINDOWS) || defined(TARGET_WIN10)
I want to avoid having ifdefs in every file that includes this file so I chose to stick them in here to make calling code a bit cleaner

2017-03-01 17:05 UTC, Paxxi commented on lib/libUPnP/Neptune/Source/System/Win32/NptWin32SerialPort.cpp
> +}
had some issues with gits autocrlf, thought I caught all of it, redoing the neptune stuff now with the patch file.

2017-03-01 17:09 UTC, Paxxi commented
the introduction of `TARGET_WIN10` here was poorly documented(not at all).
This is the define that will be used for UWP builds, the reason that it's not everywhere is that I've added it only in places I'm quite certain will run on UWP as well.
Discussion about it has been mostly in Slack afaik so easy to miss.

I could as well drop them here as it will be added in a later PR once UWP is nearer anything usable, just thought I'd sneak a few in to make it easier for the people working on the port.

2017-03-01 17:28 UTC, Paxxi commented on cmake/platform/windows/defines.txt
> +/DTARGET_WINDOWS /DNOMINMAX /D_CRT_SECURE_NO_WARNINGS /D_WINSOCKAPI_
reverted this change

2017-03-01 17:29 UTC, Paxxi commented
jenkins build this please

2017-03-02 10:40 UTC, Rechi commented
jenkins build this please

2017-03-02 10:56 UTC, Paxxi commented
the build failures was unrelated, all platforms built fine except rpi which failed to find the git hash

2017-03-02 16:42 UTC, Paxxi commented
@montellese good to go?

2017-03-02 17:19 UTC, Montellese commented
libUPnP looks fine now thanks.

2017-03-02 17:19 UTC, Montellese approved these changes

2017-03-02 17:27 UTC, merged