[cmake][windows] use correct d3dcompiler depending on target architecture
xbmc/xbmc pull request #11798
Opened 2017-03-03 09:26 UTC by Rechi

## Description
Use the correct d3dcompiler depending on the target architecture.

## Motivation and Context
Without this change win32 version of d3dcompiler is also packed in x64 and therefore Kodi can't start.

## How Has This Been Tested?
Tested on win32 and x64.

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2017-03-03 12:09 UTC, Rechi commented
jenkins build this please

2017-03-03 17:00 UTC, Paxxi requested changes
Use https://cmake.org/cmake/help/v3.0/variable/CMAKE_SIZEOF_VOID_P.html to check the bitness instead of trying to compile

2017-03-04 06:55 UTC, wsnipex commented
32/64 bit checks should go into ArchSetup.cmake

2017-03-05 20:29 UTC, Rechi commented
@wsnipex updated
@Paxxi changed as you requested, but documentation for `CMAKE_SIZEOF_VOID_P` says `[...] is determined by a try compile`. So I don't see any advantage on this method.

2017-03-05 20:58 UTC, Paxxi commented
@Rechi it's always done by cmake so it's in reality free but the more important thing for me is that it's the correct way to handle it in cmake. Makes it easier to read and grasp if familiar with cmake from other projects

2017-03-06 08:26 UTC, wsnipex commented
why not move SDK_ARCH to ArchSetup as well? Sooner or later this var might be useful/needed in other places as well

2017-03-06 15:31 UTC, Rechi commented
updated

2017-03-06 18:28 UTC, wsnipex approved these changes

2017-03-06 20:41 UTC, Paxxi approved these changes

2017-03-06 20:41 UTC, merged