[pvr] cleanups in PVR manager
xbmc/xbmc pull request #11887
Opened 2017-03-21 15:13 UTC by xhaggi

Rewrite of announce logic used by PVR manager + some small refactorings.

@ksooo mind taking a look.

2017-03-21 16:46 UTC, ksooo commented
Well, this is not the right approach. @FernetMenta might explain this best, because he introduced the direct pvr manager calls in powermanager for a reason.

2017-03-21 16:51 UTC, xhaggi commented
Okay please let me know why, i didn't noticed it or point me to the discussion. IMO it makes sense to decouple the PVR manager from the PowerManager because the announce is trigger right next to that lines.

2017-03-21 16:53 UTC, ksooo commented
Ask fernet, please. I was not directly involved, and only remember that there was some discussion somewhere leading to a pvr api change and that fernet was involved. Sorry, seems I'm getting old. ;-)

2017-03-21 16:57 UTC, xhaggi commented
The discussion is in #9662 which introduce the sleep/wakeup pvr client stuff.

2017-03-21 17:16 UTC, xhaggi commented
The last commit will drop the announce logic for OnQuit, OnSleep, OnWake and use the methods `OnWake()`, `OnSleep()` and `Deinit()` instead. The methods are called directly like before, but I dropped the `SetWakeCommand()` call from the `PowerManager`. If good I'll squash the commit.

2017-03-21 17:21 UTC, ksooo commented
Yeah, this reads good. Will take a look at the code for the usual nitpicking later, when I'm back home.

2017-03-21 20:24 UTC, ksooo requested changes

2017-03-21 20:24 UTC, ksooo commented on xbmc/pvr/PVRManager.cpp
> +  SaveLastPlayedChannel();
Just cosmetics, but in CPVRManager::Deinit() you are calling these two methods in the the opposite order.

2017-03-21 20:24 UTC, ksooo commented on xbmc/pvr/PVRManager.h
> +     * @brief Save the current playing channel as last played channel
correct English is 'currently' here, imo.

2017-03-21 20:24 UTC, ksooo commented on xbmc/pvr/PVRManager.cpp
> +  if (IsStarted())
I just spotted, that CPVRManager::Announce always() does an IsStarted check before doing anything.

Okay, but then you should add the IsStarted check also to CPVRManager::OnSleep() and CPVRManager::Deinit(), not only to CPVRManager::OnWake()

Finally, the IsStarted check should be removed from CPVRManager::TriggerSearchMissingChannelIcons().

2017-03-21 21:00 UTC, xhaggi commented on xbmc/pvr/PVRManager.cpp
> +  if (IsStarted())
IMO every method should be self-contained. They need to validate the state if necessary. We should drop that check in OnWake.

2017-03-21 21:01 UTC, xhaggi commented on xbmc/pvr/PVRManager.cpp
> +  SaveLastPlayedChannel();
Sure will change the order.

2017-03-21 21:01 UTC, xhaggi commented on xbmc/pvr/PVRManager.h
> +     * @brief Save the current playing channel as last played channel
Okay

2017-03-21 22:13 UTC, ksooo commented on xbmc/pvr/PVRManager.cpp
> +  if (IsStarted())
ok

2017-03-23 10:34 UTC, xhaggi commented
@FernetMenta dropped the commit which removes the switch channel job

@ksooo mind taking another look at it. The last commit drops the globals in PVR manager and use the CServiceBroker instead.

2017-03-23 10:59 UTC, ksooo reviewed
No strong opinion on that, but what's wrong with g_* defines? The only "change" I see here is, that I now have to type more. For me, this is not an improvement, but a drawback.

2017-03-23 11:42 UTC, xhaggi commented
We want to get rid of those globals and it's done now. Later we could think about to detach recordings, clients, timers etc from the PVRManager and provide them by the ServiceManager/ServiceBroker too.

2017-03-23 11:42 UTC, xhaggi commented
jenkins build this please

2017-03-23 11:56 UTC, ksooo commented
Sorry, I don't see the point here. But no -1 from my side. Just asking myself what the benefit/improvement/cleanup is.

2017-03-23 12:01 UTC, ksooo commented
> Later we could think about to detach recordings, clients, timers etc from the PVRManager and provide them by the ServiceManager/ServiceBroker too.

 Haha. This could be done even more simple if we still had the defines.

old: #define g_PVRClients CServiceBroker::GetPVRMananger().Clients()
new: #define g_PVRClients CServiceBroker::GetPVRClients()

A one liner to change everything!

2017-03-23 12:14 UTC, ksooo commented
> We want to get rid of those globals and it's done now.

 My understanding of our goal to "get rid of the gloabls" is not to remove defines, but do architectural changes. Imo, a good approach to "get rid of the globals" is to pass the "owning component" (the PVR Manager for example) to the "owned components" (the PVR recordings for example), so that the owned component knows its owner and can access it, without calling a global method. @FernetMenta what's your take on this?

2017-03-23 13:32 UTC, xhaggi commented
> Imo, a good approach to "get rid of the globals" is to pass the "owning component" (the PVR Manager for example) to the "owned components" (the PVR recordings for example), so that the owned component knows its owner and can access it, without calling a global method.

That was my first thought, but passing the owner to each of them is not a nice approach for a service class. IMO all of them are services. My second thought was "why not detaching them from the PVR manager".  But I don't have a strong option on how to proceed here.

2017-03-23 13:37 UTC, xhaggi commented
BTW passing the owner to the owned services does not really solve your "we have to write more code" issue. Each access to Recordings, Timers etc outside will result in the same call `CServiceBroker::GetPVRManager().GetTimers()`.

2017-03-23 16:58 UTC, xhaggi commented
any objections or ready to merge?

After that I'll create another PR that drops the channel switch job as @FernetMenta suggested.

2017-03-23 17:11 UTC, xhaggi commented
Noticed that the PVRManager still expose a `GetInstance()` method which delegates the call to the `ServiceBroker`. I've added another commit to drop that and use the `ServiceBroker` directly

jenkins build this please

2017-03-23 18:00 UTC, ksooo commented
> Noticed that the PVRManager still expose a GetInstance() method which delegates the call to the ServiceBroker. I've added another commit to drop that and use the ServiceBroker directly

 Nice.

2017-03-23 18:01 UTC, ksooo approved these changes

2017-03-24 07:32 UTC, xhaggi commented
jenkins build this please

2017-03-24 08:38 UTC, xhaggi commented
WIN32 build errors are unrelated.

2017-03-24 08:38 UTC, merged