[music] Fix and optimize C(Set|Clear)Default:IsVisible
xbmc/xbmc pull request #11987
Opened 2017-04-19 07:31 UTC by ksooo

Fixes a regession introduced by #10892.
Details: https://github.com/xbmc/xbmc/pull/10892#issuecomment-293921723 ff

@Razzeee for code review and runtime test, please.
@tamland fyi.

2017-04-19 07:47 UTC, Razzeee commented
Will test this tonight (no other opportunity any sooner, sorry)

2017-04-19 22:07 UTC, razzeee requested changes

2017-04-19 22:07 UTC, Razzeee commented on xbmc/music/ContextMenus.cpp
> +  if (URIUtils::IsMusicDb(item.GetPath()))
This if needs to go the `MUSICDATABASEDIRECTORY` will take care of it even if it's more expensive

2017-04-19 22:19 UTC, Razzeee commented on xbmc/music/ContextMenus.cpp
> +  if (URIUtils::IsMusicDb(item.GetPath()))
Only thing I can find wrong after that is that we need to handle `!item.IsParentFolder()` so that the `...` don't show the context menus.

2017-04-20 05:28 UTC, ksooo commented on xbmc/music/ContextMenus.cpp
> +  if (URIUtils::IsMusicDb(item.GetPath()))
Hmmm, are these comments result of a runtime test or just out of theory? 

I thought parent folders do not have "musicdb" urls and I do not understand why the node type should be checked if the item has no "musicb" url. Doing the latter leads to the problem we're currently facing - namely "set as default" / "clear default" appearing at various wrong places.

2017-04-20 06:18 UTC, ksooo commented on xbmc/music/ContextMenus.cpp
> +  if (URIUtils::IsMusicDb(item.GetPath()))
Okay, just found out that "musicdb" parent folders do havw "musicdb" URLs. I will change the code accordingly.

But I still cannot see why we always should check the node type, even if item has no music db url. Please elaboarte on this.

2017-04-20 07:27 UTC, Razzeee commented on xbmc/music/ContextMenus.cpp
> +  if (URIUtils::IsMusicDb(item.GetPath()))
Result of a runtime test. 
All music nodes seem to have ``library:\\music\xxx` when I checked, so a check for `musicdb:\\` isn't helping us. We could do a new helper checking if the items are music library items.
There is a URIUtils class for checking library already, but it checks for both video, music and something else I've forgotten.
Se we could create `URIUtils::IsMusicLibrary`

2017-04-20 07:36 UTC, ksooo commented
@Razzeee I reintroduced the parentfolder check, as requested. Good to go now?

2017-04-20 11:17 UTC, ksooo commented on xbmc/music/ContextMenus.cpp
> +  if (URIUtils::IsMusicDb(item.GetPath()))
Good idea. I will implement this.

2017-04-20 11:34 UTC, ksooo commented
@Razzeee should be really good to go now. I runtime tested this and could not find any "set as default" or "clear default" menu items.

2017-04-20 12:00 UTC, Razzeee commented
Will test tonight.

2017-04-20 13:38 UTC, ksooo commented
"superseeded" by #11990

2017-04-20 13:38 UTC, closed without merging