reenable mark as watched/unwatched for folders
xbmc/xbmc pull request #12057
Opened 2017-05-05 07:44 UTC by notspiff

this is just a quick hack to reenable mark as watched/unwatched for folders. it works just fine, but i wonder why you went to length to nuiter the functionality so i open this to get the attention.

ref http://forum.kodi.tv/showthread.php?tid=311447&pid=2581701#pid2581701

2017-05-08 06:49 UTC, Jalle19 reviewed
Could you remove the now dead code instead of just adding return statements?

2017-05-08 07:22 UTC, ksooo commented
> Could you remove the now dead code instead of just adding return statements?

 No way. This is not a proper fix (and I think @notspiff knows this; he just wanted to give a heads-up). Returning true for every file item that is a folder results in every folder item having the "mark watched/unwatched" context menu item. We need to identify the "video folder" items properly and *add* this check in addition to the existig ones.

2017-05-08 07:24 UTC, ksooo requested changes
This is not a proper fix. Please refer to my other comment for details.

2017-05-08 07:25 UTC, akva2 commented
Cba to relogin. Yeah what ksooo said. I will do that when and if the explanation for *explicitly* coding the regression makes that the appropriate course of action.

2017-05-09 17:56 UTC, Jalle19 commented
@ksooo you're totally right, I looked at this a bit too sloppily it seems.

2017-05-23 22:26 UTC, gitAnne commented
So now what needs to happen?
Using item.IsVideoDb() instead of the item.m_bIsFolder won't work I presume.
Can you check the content type of a folder item?

2017-07-05 09:10 UTC, krabsheva commented
I dunno the politics involved here, but is someone going to fix this problem? Seems like it would take someone with decent knowledge of the codebase 5 minutes to fix this issue properly.

I have no idea in which cases these menu options need to be removed from a folder context menu, or I would change it myself. Personally, I would be happy with the kludge fix, but I don't use the PVR stuff or library mode for video.

Since it looks like this was broken back in December, perhaps that dev should look into this?

2017-07-05 10:45 UTC, ksooo commented
No, it takes definitely more than 5 minutes. Please refrain from such statements if you have no idea what you are talking about. Thanks

2017-07-05 10:51 UTC, ksooo commented
With old context menu system, the context was given by the window information that wanted to support certain context menu items. 

Now, there us no such context, only a file item and this to my best knowledge currently lacks the information we need - whether the item is a "video folder".

2017-07-05 11:56 UTC, gitAnne commented
When I request the [C]ontext menu of a video folder in the user interface, I can check the Content type and change it if needed. I can only change the content to 1 of the 3 video content types (Movies, TV Series and Music videos). That would mean that the informatie what content type a folder has is available somehow?

With the content type of a folder available it should be possible to add the 'mark as watched' option?

Or am I missing something here?

2017-07-05 12:01 UTC, ksooo commented
Yes, "somehow" the info is available, but nobody showed up here so far with the knowledge, "how" exactly. 

I know the new context menu system and pvr, but unfortunately not the video and music code base of Kodi, sorry.

2017-07-05 23:07 UTC, krabsheva commented
If no one who knows the video side is willing to step in then the kludge is the best solution available. At least you don't continue to err on the side that takes away functionality that has existed for years.

2017-07-06 00:06 UTC, ksooo commented
> If no one who knows the video side is willing to step in then the kludge is the best solution available. 

No way, as it breaks other components, like PVR. -1 from my end.

2017-07-06 23:41 UTC, gitAnne commented
'-1 from my end'
I assume that is a -1 for using a kludge/work around, 
not towards reintroducing the 'mark as watched' functionality for video folders, I hope ;P

This removed functionality really added quite a lot of work and frustration for me. 
I also still don't get why this was broken as it does not seem like it was a conscious decision to remove it.

2017-07-07 07:53 UTC, ksooo commented
>> '-1 from my end'

> I assume that is a -1 for using a kludge/work around,
> not towards reintroducing the 'mark as watched' functionality for video folders, I hope ;P

 Yes, no way to merge the work around as it breaks other stuff.

> This removed functionality really added quite a lot of work and frustration for me.

 Seems that this is a killer feature for you. Why don't you stick with the last version of Kodi that works? Or why don't you switch to library mode? The bug only appears with file mode, right?

> I also still don't get why this was broken 
 
 Simply by accident? Because the dev who changed the implementation to the new context menu system had not enough knowledge (it was not me, btw - so start hating somebody else, please)? OMG.

> as it does not seem like it was a conscious decision to remove it.

 Pffft. Hold yer horses.

> So where do I have to go to to start a voting campaign to get this back?

 As long as no dev gets into the mood to fix it, you can collect millions of votes without any affect. ;-)

2017-07-07 07:59 UTC, ksooo commented
@notspiff is it okay for you if I close this (annoying, tbh) PR? A respective trac ticket should be opened, instead.

2017-07-07 08:05 UTC, gitAnne commented
Yes it's a feature I use quite extensively.
And I'm kind of surprised that not everyone does ;P

I'll investigate how I can find out which version did not have this update and how to roll back to it, because that does seem like a good plan.

So no amount of icecream will be able to help get this feature back I gather? ;P

Thanks for the comments.

2017-07-07 08:07 UTC, ksooo commented
Team Kodi currency is COB (crates of beer).

2017-07-10 12:28 UTC, notspiff commented
@ksooo the only reason this is annoying is that the team is unable to answer my question - then i would code whatever fix you would want. but sure, if its is annoying..

2017-07-10 12:28 UTC, closed without merging