smbclient: cleanup smbclient configuration
xbmc/xbmc pull request #12110
Opened 2017-05-16 17:51 UTC by chewitt

This PR does some overdue cleanup on the smbclient configuration used by Kodi.

## Description

* Removes `socket options` tuning that is not recommended: https://lists.samba.org/archive/samba/2013-February/171836.html

* Removes `client lanman auth` so smbclient can use more secure hash algorithms. This breaks compatibility with Windows 95/98 and pre Samba 2.2 shares (c.2000) that do not support NTLM or NTLMv2.

* Removes `lanman auth` smbd configuration that is irrelevant to smbclient.

* Sets `client max protocol` to SMB3. Without this (and we're not sure why) Kodi never attempts SMB connections using a client protocol newer than NT1 (SMB1). Setting to SMB3 allows smbclient to auto-negotiate the correct protocol with most devices. Some older Windows and Samba versions can require `client max protocol` to be reduced to SMB2 or SMB1 to solve connectivity issues (server side bugs or misconfiguration) so we expose this as a configuration option in Kodi settings. Using SMB3 with smbclient versions below 4.1 that do not support SMB2+ are not affected; older smbclient versions simply negotiate up to what they understand, i.e. NT1. This is part based on https://github.com/koying/SPMC/commit/833aacd4698a7c5af09a94000784c492210959ef from @koying that forces NT1 connectivity.

* Fixes a bug where `smb.conf` was not rewritten if the file was not already present. It is now rewritten on first SMB use after changes have been made. This adapts https://github.com/koying/SPMC/commit/2771cb222d4d09082dac06ce970dba0f6293cd56 from @koying that made rewrite on start user configurable.

## Motivation and Context
Wannacry ransomware attacks have woken people up to the security issues with SMB1 and Kodi refusing to use anything newer forces people to continue using insecure shares. LE plans to use a Krypton version of this with samba 4.6 in a future release to bring SMB2/3 support. NB: This PR is intended as a nip/tuck improvement to the existing regime until someone comes up with a more long-term replacement for smbclient.

## How Has This Been Tested?
Lots of experimentation and detective work from @MilhouseVH. An earlier variant of the max client protocol change and samba 4 have been in his nightly builds for several months and this specific PR will be included shortly. It has not been tested with other Kodi build targets that use smbclient (macOS, Android, etc.) but testing with older smbclient 3.6 on Linux hasn't thrown up any obvious issues.

## Types of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2017-05-16 18:26 UTC, MilhouseVH commented
https://lists.samba.org/archive/samba-technical/2016-November/117005.html

Samba defaults to NT1 client connections unless `client max protocol` is configured, which explains why Kodi is fixated on establishing NT1 connections regardless of what is (or is not) supported by the server.

I've just checked the latest Samba master[1] and the default client connection is still(!) NT1... utter madness.

1. https://github.com/samba-team/samba/blob/7556c20d4bf90bfcc288ba1c82008105eaf8f261/source3/param/loadparm.c#L4529-L4532 <--- current HEAD on master

2017-05-16 18:43 UTC, ksooo requested changes

2017-05-16 18:43 UTC, ksooo commented on addons/resource.language.en_gb/resources/strings.po
> +msgctxt "#1209"
Could you please provide contextual information for the new strings (here and elsewhere). This makes live of translators a lot easier. Thanks.
#. ...
#: ...

2017-05-16 18:45 UTC, MartijnKaijser commented on addons/resource.language.en_gb/resources/strings.po
> +msgctxt "#1209"
Also do not use strings below 10000

2017-05-16 18:52 UTC, koying commented
You probably do not want to force rewrite smb.conf on a plain linux distro. Or do I miss something?

2017-05-16 19:12 UTC, MilhouseVH commented
> Or do I miss something?

The problem is that currently the config isn't updated at all, even if a setting is changed. This currently requires the user to delete the .smb folder before new settings can be applied.

What is the problem with updating `$HOME/.smb/smb.conf` every time Kodi is started - are you concerned about other non-Kodi applications that might be sharing smb.conf?

2017-05-16 22:04 UTC, koying commented
Yes. smb.conf is the standard user libsmbclient config file, so other apps or even the user might have tweaked it on a Linux distro, and we probably should not unconditionally overwrite it. 

But I'll completely trust @wsnipex 's opinion on this.

2017-05-17 06:35 UTC, koying commented
Note that an automagic way to overwrite config could be to calculate the hash of the existing file and compare with a precalculated one of our "old" default. 
If equal, we can assume it's ours and overwrite.

2017-05-17 07:27 UTC, wsnipex commented
We should never overwrite anything outside of our userdata dir.

why don't we use our own smb.conf instead of the standard one? That way there is no problem with overwriting.

And the client max protocol won't work anywhere but linux until we somehow manage to upgrade samba to a more recent version. So this setting should only be visible if supported.

2017-05-17 07:36 UTC, MilhouseVH commented
@wsnipex then this would need run-time detection of the smb library version. I can build Kodi on Ubuntu 16.04 which has support for SMB2 and SMB3 client connections (smb library 4.3.11).

@koying an option to overwrite has been added to this PR overnight - once enabled it allows the WINS and max protocol settings to be changed (and written at next restart or when next new context is established). The overwrite setting will be automatically disabled once the new conf is written. 

Not sure if a magic hash would work as once you change any of the defaults your precalculated "default" hash would no longer match and you'd never update the file again, not even to set it back to current defaults (plus this would make life harder for anyone using appliance.xml etc.). :)

2017-05-17 07:38 UTC, chewitt commented
@wsnipex If you run smbclient from the console you can append `--config /path/to/smb.conf` but there is no equivalent for API calls so we have to work with a potentially shared config.

2017-05-17 07:44 UTC, wsnipex commented
@chewitt https://github.com/samba-team/samba/search?utf8=%E2%9C%93&q=SMB_CONF_PATH&type=

2017-05-23 09:44 UTC, Rechi commented on xbmc/filesystem/SMBFile.cpp
>          fprintf(f, "\tlock directory = %s/.smb/\n", getenv("HOME"));
could you also replace `getenv("HOME")` with `home.c_str()` like you have done above?

2017-05-23 09:45 UTC, Rechi commented
@chewitt this needs to be rebased

2017-05-23 10:03 UTC, chewitt commented
rebased .. do we want to add the home/env hack @koying suggested in Slack?

2017-05-23 10:15 UTC, Rechi commented
With this change `smb.conf` now gets overwrite although it exists already.
To avoid removing / changing some settings a user has set explicitly for the whole os, we should use our own `smb.conf`.

2017-05-23 10:53 UTC, koying commented
The only way I found to have our own smb.conf is:
```
    // HACK!! Force libsmbclient to use our own smb.conf by overriding HOME
    char* truehome = getenv("HOME");
    setenv("HOME", CSpecialProtocol::TranslatePath("special://home").c_str(), 1);

    // setup our context
    m_context = smbc_new_context();

    // HACK!! Restore HOME
    setenv("HOME", truehome, 1);
```

SMB_CONF_PATH didn't work for me

2017-05-23 11:35 UTC, koying commented
Note that, if we go the "own smb.conf" route, CSettings::SETTING_SMB_OVERWRITECONF doesn't make sense anymore

2017-05-23 11:41 UTC, MilhouseVH commented
> Note that, if we go the "own smb.conf" route, CSettings::SETTING_SMB_OVERWRITECONF doesn't make sense anymore

Yes, and no... being able to selectively overwrite would at least allow users to `tune` the smb.conf if they wished. And constant rewriting seems a little unnecessary.

2017-05-23 11:48 UTC, koying commented
1) Fair enough regarding "constant rewriting", but then existing smb.conf might never be updated if we change our own again in the future (this PR will create a new one anyway)
2) Fair enough regarding tuning, but then we might want "overwrite" defaulted to "true" because of 1)

2017-05-23 12:06 UTC, MilhouseVH commented
It is possible to include extra config files, eg. `include = ${HOME}/.smb/extra.conf`, and then automatically overwriting `smb.conf` once per session (at startup) would be totally fine, as any "tweaking" could occur in `.smb/extra.conf` (it doesn't have to exist) which would be under the users control.

2017-05-23 14:09 UTC, MilhouseVH commented
http://sprunge.us/SLBF

@koying the above patch ensures the `smb.conf` settings are written every time before the first (and only the first) connection is initialised. It also adds the `include` setting which allows the user to add their own settings without fear of being overwritten. Tested on Linux (LibreELEC) and it works fine for me.

If you're OK with this as a complete solution then I'll work with @chewitt to remove the overwrite toggle setting and hopefully we can put this to bed. :)

2017-05-23 15:38 UTC, koying commented
@MilhouseVH Not 100% sure "IsFirstInit" does what you think it does.

As CSMB is a global (https://github.com/xbmc/xbmc/blob/8d4a5bba55638dfd0bdc5e7de34f3e5293f99933/xbmc/filesystem/SMBFile.h#L67), it should be inited only once, and m_context is only reset on Deinit, which comes when we exit.

Bottom-line: I'd remove the "IsFirstInit" check.
Besides that, I trust you on the "user.conf" include, but it's not me to approve, really.

Did you confirm the hack is working? I did tests myself, but a second confirmation is welcome.

2017-05-23 15:55 UTC, MilhouseVH commented
> @MilhouseVH Not 100% sure "IsFirstInit" does what you think it does.

I'm sure you're right, although it would be nice if we could limit the rewriting to only when required (directory doesn't exist) and kodi startup.  Is there a better solution for this, maybe an extra/different static boolean?

I do however see Init() being called each time an SMB connection is established - for instance establish a connection and Init() will be executed, wait for the connection to timeout (3 minutes) and then connect again and Init() will be called again (potentially writing out `smb.conf` etc.).

> Did you confirm the hack is working? I did tests myself, but a second confirmation is welcome.

Yes the hack https://github.com/xbmc/xbmc/pull/12110/commits/2f75f1d403a4cebb7c4255822f0d927823123d9c is working fine for me in Linux.

2017-05-23 16:03 UTC, koying commented
> I do however see Init() being called each time an SMB connection is established

It's sure called multiple times, but the call is noop once we have a m_context.
The only reason to not have one is if the "smbc_init_context" fails, but then "IsFirstInit" stays true as well ;)

2017-05-23 17:18 UTC, MilhouseVH commented
Ouch.

I'm just trying a version I built with the "home" hack and I'm trying to install an addon from a zip file that I have in `$HOME/downloads`, and when I drill into "Home folder" in the "Install from zip" dialog:

![s1](http://i.imgur.com/rDoiDhL.png)

I see this, which looks like the contents of the `.kodi` folder and not `$HOME`:

![s2](http://i.imgur.com/7BFFpbz.png)

2017-05-23 17:46 UTC, MilhouseVH commented
> It's sure called multiple times, but the call is noop once we have a m_context.
> The only reason to not have one is if the "smbc_init_context" fails, but then "IsFirstInit" stays true as well ;)

Then something is wrong, or you're not taking multiple shares into account or that connections are removed once they become idle (and maybe the `m_context` along with it?)

I added the following patch to log some extra details in `Init()`: http://sprunge.us/AFUY

I then connected to all 3 of my SMB shares (one each on Windows 7 Ultimate, Ubuntu and FreeNAS) and visited them multiple times - sure enough, just a single `m_context` is created/used as you predicted:
```
18:37:48.283 T:1546122144    INFO: NJM1: Init() called
18:37:48.283 T:1546122144    INFO: NJM2: Init() called with no m_context
18:37:48.297 T:1546122144    INFO: NJM1: Init() called
18:37:48.427 T:1546122144    INFO: NJM1: Init() called
18:37:49.306 T:1855976352    INFO: NJM1: Init() called
18:37:49.315 T:1855976352    INFO: NJM1: Init() called
18:37:49.322 T:1855976352    INFO: NJM1: Init() called
18:38:04.804 T:1783456672    INFO: NJM1: Init() called
18:38:04.807 T:1546122144    INFO: NJM1: Init() called
18:38:09.970 T:1943030224    INFO: NJM1: Init() called
18:38:10.371 T:1472197536    INFO: NJM1: Init() called
18:38:13.119 T:1791845280    INFO: NJM1: Init() called
18:38:15.294 T:1943030224    INFO: NJM1: Init() called
18:38:15.349 T:1472197536    INFO: NJM1: Init() called
18:38:17.153 T:1546122144    INFO: NJM1: Init() called
18:38:18.467 T:1943030224    INFO: NJM1: Init() called
18:38:18.680 T:1472197536    INFO: NJM1: Init() called
18:38:24.543 T:1943030224    INFO: NJM1: Init() called
```
However I then waited a few minutes and then connected again to the Windows share:
```
18:41:02.914 T:1943030224    INFO: NJM1: Init() called
18:41:02.914 T:1943030224    INFO: NJM2: Init() called with no m_context
```
So `m_context` is being nulled at some point and when the next SMB connection is established the whole process of initialising `m_context` is repeated (including, potentially, writing `smb.conf`).

2017-05-23 17:54 UTC, koying commented
Ah, right you are. "CheckIfIdle" does a Deinit.
So yes, your solution is proper, sorry for the noise.

2017-05-23 19:06 UTC, MilhouseVH commented on xbmc/filesystem/SMBFile.cpp
> +    setenv("HOME", truehome, 1);
Apparently this call *is* succeeding (return value is 0) however `errno` is being set to 95 which (according to `strerror(errno)`) means ` Operation not supported`, so it doesn't look like the $HOME variable is being reset to the original value.

Any ideas?

2017-05-23 20:35 UTC, koying commented on xbmc/filesystem/SMBFile.cpp
> +    setenv("HOME", truehome, 1);
Maybe save "truehome" in a std::string.
From what I read, the c-string returned from getenv is not immutable (quite obviously).

2017-05-23 21:00 UTC, MilhouseVH commented on xbmc/filesystem/SMBFile.cpp
> +    setenv("HOME", truehome, 1);
Yes, I've tried that as well but same result.

I added this patch for diagnostics: http://sprunge.us/HbHG
In LibreELEC I get:
```
21:14:10.706 T:1784505248    INFO: NJM3: $HOME is now [/storage/.kodi/]
21:14:10.708 T:1784505248    INFO: NJM4: $HOME needs to be [/storage]
21:14:10.709 T:1784505248    INFO: NJM5: $HOME has been set to [/storage], retcode = 0, errno = 95, error = Operation not supported
```
while in Ubuntu 16.04 it does appear to work:
```
21:57:31.969 T:140159918352128    INFO: NJM3: $HOME is now [/home/neil/.kodi/]
21:57:31.969 T:140159918352128    INFO: NJM4: $HOME needs to be [/home/neil]
21:57:31.969 T:140159918352128    INFO: NJM5: $HOME has been set to [/home/neil], retcode = 0, errno = 2, error = No such file or directory
```
so for now at least it's just an LE issue. Hmmm.

2017-05-24 11:31 UTC, MilhouseVH commented
I've determined the issue with LE (although it probably wasn't LE specific in the end). Not sure why `errno` is returning error 95 but that seems to be a red herring.

The issue is this:
```
void CSMB::Init()
{
  CSingleLock lock(*this);

  // force libsmbclient to use our own smb.conf by overriding HOME
  char* truehome = getenv("HOME");
  setenv("HOME", CSpecialProtocol::TranslatePath("special://home").c_str(), 1);

  if (!m_context)
  {
    ...
    smbc_init(xb_smbc_auth, 0);

    // setup our context
    m_context = smbc_new_context();

    // restore HOME
    setenv("HOME", truehome, 1);
    ...
  }
  m_IdleTimeout = 180;
}
```

Each time a share is initialised we would set `$HOME` to the translated path, but only reset it back to the original value if we have to create `m_context` (which, as we've established, would only happen for the first connection or after an idle connection is `Deinit()`). So if you only had one SMB share, then no problem, but with multiple SMB shares (I have 3) your `$HOME` variable would be left set incorrectly. D'oh!

This [patch](http://sprunge.us/gFEf) will fix it, and switches to `std::string`. Tested in LE9 with multiple SMB shares, working fine now. I've asked @chewitt to update the PR with:

http://sprunge.us/gFEf (`$HOME` bug fix)
http://sprunge.us/SLBF (only write file on startup, adds `include=` support)
http://sprunge.us/IJVB (removes the SMB_OVERWRITE GUI setting)

It would be good to get testing feedback from non-Linux platforms to make sure the `$HOME` hack works for everyone.

2017-06-13 14:47 UTC, MilhouseVH commented
Please rebase.

2017-06-14 03:26 UTC, chewitt commented
@MilhouseVH rebased for changes in xbmc/settings/Settings.cpp - no real-world issues from my side on testing - only the standard BS that you see with browsing when browse master changes in the network. Good to merge?

2017-07-07 19:13 UTC, MartijnKaijser commented
What's gonna happen with this and backport?

2017-07-07 21:05 UTC, MilhouseVH commented
It's been in my LE test builds for several weeks and is working as intended. It will produce an "invalid parameter" warning to stdout for those systems with libsmbclient prior to 4.1. Users with broken/ancient Samba servers that claim to support SMB3 (but don't) will need to configure SMB2 or SMB1 to restore Samba functionality.

Disabling NT1/SMB1 on the server (as recommended by everyone, which is the reason why this PR is becoming necessary) seems to break network browsing but that's an unrelated issue to this PR (and is a core Samba issue rather than Kodi).

2017-07-14 20:48 UTC, koying commented
Is it just me or is `cache directory` somewhat mandatory, now.
Without it, on my droid 4.5.1 build, I get `mkdir failed on directory /home/cbro/spmc17-build/arm-linux-androideabi-21/var/cache/samba: No such file or directory`, `/home/cbro/spmc17-build/arm-linux-androideabi-21` being the default dir from build.

On 3.6, and in the doc, it's clearly stated that `lock directory` should be used, but it seems it's not...

2017-07-18 19:44 UTC, koying commented
I was looking at samba configuration, and stumble across posts suggesting auto-negotiation (no "client max protocol" at all) is the preferred way.
So we might need a default "Default" option, which doesn't set the option at all...

2017-07-20 10:14 UTC, chewitt commented
@koying PR is updated with a small tweak from @MilhouseVH so we default to no config and smbclient autonegotiates.

2017-07-20 17:07 UTC, MilhouseVH commented
@chewitt the default is still [SMBv3](https://github.com/xbmc/xbmc/pull/12110/files#diff-92b91a5c902936f6e9a03f26b054d7d6R1924) which personally I'd keep, but to match the help message (which now says the default is auto-negotiate) this value needs to be changed to 0. The purpose of this PR however is to support better than NT1 and with more servers dropping NT1 (which will continue to be negotiated when the setting is `auto`, and thus not working) I think we should continue to use a default setting of SMBv3 - negotiating a lower protocol should become the exception and only when the user needs it.

2017-07-20 17:27 UTC, koying commented
Is "negotiation" not implying client and server agree on a mutually acceptable level?
I'd assume that if the server does not support a level, that one wouldn't be selected, or I don't see the point ;)
Anyway, I'll try to do tests with various combination this WE and report

2017-07-20 17:55 UTC, MilhouseVH commented
Negotiation will only happen if `client max protocol` is greater than `NT1` (aka `SMBv1`), ie. if `SMBv2` or `SMBv3` is selected.

Without `client max protocol`, libsmbclient will only ever use `NT1` regardless of what the server may support (which may not include `NT1` meaning the client is unable to establish a connection with the server).

Forcing `NT1` should produce the same behaviour as not setting `client max protocol`, but apparently doesn't always, hence the request for a `default/none/auto` option (which I added in a patch to @chewitt and which didn't change the SMBv3 default - it just added a "do nothing" option).

In order for Samba to automatically negotiate a better than `NT1` connection the `client max protocol` should be set to `SMBv3` as the default, and then knocked back (or disabled) by the minority of users with duff servers.

2017-07-20 17:59 UTC, koying commented
Ok, thanks for the clarification.
Thinking out loud, but then shouldn't "Default" (=SMB3) + "SMB1" options be sufficient?

2017-07-20 18:14 UTC, MilhouseVH commented
We thought so, but then you asked for the "do nothing" option!

I guess it's possible that samba.org may flip the default connecting behaviour from "forced `NT1` to "auto-negotiate highest version supported by this client" but until that happens then we have to assume `NT1` will always be negotiated in the absence of a `client max protocol`.

Perhaps the posts you found that suggested not setting anything were either misinformed (you'd expect Samba to auto-negotiate, but that's not what it does by default) or were written from the perspective of ensuring maximum compatibility in an age when every server supported `NT1` (not the case today).

2017-07-20 18:21 UTC, MilhouseVH commented
And apparently it will be auto-negotiate by default with Samba 4.7

https://git.samba.org/?p=samba.git;a=commitdiff;h=1199907cbe2f003a7df6f56e6cf3878d0732344d

2017-07-20 18:32 UTC, koying commented
> We thought so, but then you asked for the "do nothing" option!

Sorry about that ;)
Doing an actual google returns conflicting information on whether not specifying the option default to "NT1" or do auto-negotiation, probably dependent on the samba version.

it was just a suggestion btw, although reading me back might seem more imperative than I intended.

2017-07-21 07:45 UTC, wsnipex commented on xbmc/filesystem/SMBFile.cpp
>      // Create ~/.smb/smb.conf. This file is used by libsmbclient.
path is now ~/.kodi/.smb/smb.conf, correct?

2017-07-21 09:05 UTC, koying commented
I confirm "auto-negotiation" is kind of BS ;)
From droid 4.5.1 to debian 4.2.14, if I disable smb1 on the NAS (with `min protocol = SMB2`) and leave out `max protocol` on the client, I just can't connect.

2017-07-22 12:16 UTC, chewitt commented
The default option and wording is now set to "SMB3" to provide compatibility. Samba <4.1 will still connect using NT1, while Samba 4.1+ will connect using SMB3_11 and should step down to SMB2 if required. The none option (remove config and use Samba defaults) is retained as it does no harm and may be useful with support. The code comment on ~/.kodi/.smb/smb.conf path has been amended.

2017-07-22 12:21 UTC, koying approved these changes
Keeping "None" as an option for the future makes sense.
+1, nice work :)

2017-07-22 16:28 UTC, wsnipex approved these changes
looks good now, thanks :+1:

2017-08-03 08:08 UTC, merged