Libdvd streaming for DVD images
xbmc/xbmc pull request #12158
Opened 2017-05-25 10:01 UTC by Voyager1

LibDvdNav has the option to open DVD images using a streaming API. This is a first step to dropping our library hooking. Currently that is still needed to support physical drive playback or IFO/VOB files playback. As soon as the team 

## Description

Added the streaming API functions and declarations from libdvdnav 5.0.3
Added the necessary callback functions for libdvdnav to access our file system
Added the condition to use streaming API when opening a DVD disc image (ISO or alike)

## Motivation and Context

Not fixing anything, just a step in the direction of library hooking cleanup.

## How Has This Been Tested?

Tested with ISO files on an SMB network share.
Note that the API requires also a "vectored" read callback, which doesn't seem to be called. As a result, that code hasn't been properly tested I'm afraid.

## Screenshots (if appropriate):

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2017-05-25 11:27 UTC, fritsch commented
Thanks very much! Who could review this? @Paxxi @Rechi @ace20022 ?

2017-05-25 12:21 UTC, ace20022 commented on xbmc/cores/VideoPlayer/DVDInputStreams/dvdnav/dvd_reader.h
> +#   include <sys/types.h>
already included in line 33

2017-05-25 17:21 UTC, Rechi commented on xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.cpp
> +    m_pstream = new CDVDInputStreamFile(m_item);
does this need to be destructed somewhere?

2017-05-25 17:25 UTC, Rechi commented on xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.cpp
> +  CDVDInputStreamFile *lpstream = (CDVDInputStreamFile*)p_stream;
use c++ style casting

2017-05-25 17:26 UTC, Rechi commented on xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.cpp
> +  CDVDInputStreamFile *lpstream = (CDVDInputStreamFile*)p_stream;
use c++ style casting

2017-05-25 17:26 UTC, Rechi commented on xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.cpp
> +  CDVDInputStreamFile *lpstream = (CDVDInputStreamFile*)p_stream;
use c++ style casting

2017-05-25 17:27 UTC, Rechi commented on xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.cpp
> +  CDVDInputStreamFile *lpstream = (CDVDInputStreamFile*)p_stream;
use c++ style casts

2017-05-25 17:27 UTC, Rechi commented on xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.cpp
> +  return lpstream->Read((uint8_t *)buffer, i_read);
use c++ style casts

2017-05-25 17:27 UTC, Rechi commented on xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.cpp
> +  const struct iovec* lpiovec = (const struct iovec*)p_iovec;
use c++ style casts

2017-05-25 17:28 UTC, Rechi commented on xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.cpp
> +    p_base = (unsigned char*)lpiovec->iov_base;
use c++ style casts

2017-05-25 17:30 UTC, Rechi commented on xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.cpp
> +  for (i_index = i_blocks; i_index; i_index--, lpiovec++)
incrementing a pointer is a bit hacky, but maybe it's needed here

2017-05-25 17:31 UTC, Rechi reviewed
only looked at code style, can't say anything about the functional changes

2017-05-25 17:46 UTC, Paxxi requested changes
I'd like the comments relating to unique_ptr addressed.
The comments about styling would be nice to have fixed but not a blocker.

looks good to me overall. Thanks!

2017-05-25 17:46 UTC, Paxxi commented on xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.h
> +  CDVDInputStreamFile* m_pstream;
make this a `std::unique_ptr<CDVDInputStreamFile> m_pstream`

2017-05-25 17:46 UTC, Paxxi commented on xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.cpp
> +    m_pstream = new CDVDInputStreamFile(m_item);
then use `m_pstream.reset(new DVDInputStreamFile(m_item);` here

2017-05-25 17:46 UTC, Paxxi commented on xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.cpp
> +  CDVDInputStreamFile *lpstream = (CDVDInputStreamFile*)p_stream;
prefer using c++ style casts `static_cast<CDVDInputStreamFile*>(p_stream);`

2017-05-25 17:46 UTC, Paxxi commented on xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.cpp
> +    if (!m_pstream->Open() || m_dll.dvdnav_open_stream(&m_dvdnav, m_pstream, &m_dvdnav_stream_cb) != DVDNAV_STATUS_OK)
use `m_pstream.get()` here to avoid passing the unique_ptr as it makes the casts easier in the static functions.

2017-05-25 17:46 UTC, Voyager1 commented on xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.cpp
> +    m_pstream = new CDVDInputStreamFile(m_item);
good point! will fix.

2017-05-25 17:47 UTC, Voyager1 commented on xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.cpp
> +  for (i_index = i_blocks; i_index; i_index--, lpiovec++)
the code is correct, it's a vector of iovec structs, so the pointer increments with the struct size. The code was copied from libdvdcss.

2017-05-25 19:35 UTC, Voyager1 commented
I believe all comments have been addressed. 
Note that I also inserted a small bugfix in emu_msvcrt.cpp. In some rare case the close() emulated method was called with a filedescriptor = -1. I guess it's because of the move to streaming API. The additional check solved it.

2017-05-25 19:43 UTC, Rechi commented
@Voyager1 there are still some c style casts left, please change them to c++ style casts

2017-05-25 22:02 UTC, Voyager1 commented
@Rechi - the missed ones should be ok now.

2017-05-26 05:37 UTC, MartijnKaijser commented
jenkins build this please

2017-05-26 07:29 UTC, Paxxi approved these changes

2017-05-26 08:03 UTC, Voyager1 commented
looks like non-Windows builds are failing. Will look into fix.

2017-05-26 08:15 UTC, Voyager1 commented
jenkins build this please

2017-05-26 08:46 UTC, Voyager1 commented
fixed another warning. 
jenkins build this please

2017-05-26 09:06 UTC, Rechi commented
unrelated failures
jenkins build this please

2017-05-26 11:10 UTC, merged

2017-08-03 09:34 UTC, popcornmix commented
@Voyager1 We have a report that DVD ISO over FTP stopped working with the build that first included this PR. Is that expected?
Log file here: https://forum.kodi.tv/member.php?action=profile&uid=169709

2017-08-03 10:08 UTC, Voyager1 commented
Assuming log file is https://pastebin.com/bciwyzDu
The log confirms that it's the new code, so the root cause seems right. However, it's not expected, so I'll have to look into this. I'm thinking it may be a problem with the seek or read function failing on an FTP file.
Can you confirm that it works fine with DVD ISOs on anything else than an FTP url?

2017-08-03 19:36 UTC, Voyager1 commented
@popcornmix - issue confirmed. I'm looking into a solution but it may take a while. Although the same CFile functions get called somehow it fails when called through the libdvd streaming API. I'm debugging but I don't get any indication that the read/seek functions are failing.

2017-08-03 20:28 UTC, Voyager1 commented
@popcornmix - fix is here. https://github.com/xbmc/xbmc/pull/12622
please take a look :-)