Fix for Hangup when viewing recording and pressing next/previous (#17476)
xbmc/xbmc pull request #12162
Opened 2017-05-26 06:15 UTC by hugegreenbug

## Description

The fix skips channel up/down events for saved recordings to prevent the hang
 
## Motivation and Context

Fixes a hang when pressing previous or next while viewing a saved recording

http://trac.kodi.tv/ticket/17476

## How Has This Been Tested?

Tested on MacOS

## Screenshots (if appropriate):

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2017-05-26 06:28 UTC, ksooo commented
What happens now if you press channel up/down? How behave other videos, btw? Should be the same, imo.

2017-05-26 06:41 UTC, FernetMenta commented on xbmc/cores/VideoPlayer/VideoPlayer.cpp
> +  if (pvrStream && !pvrStream->IsSavedRecording())
why don't you use GetCurrentChannel? should be null for recordings.

2017-05-26 06:46 UTC, hugegreenbug commented on xbmc/cores/VideoPlayer/VideoPlayer.cpp
> +  if (pvrStream && !pvrStream->IsSavedRecording())
I didn't know. I can change it.

2017-05-26 06:49 UTC, hugegreenbug commented
@ksooo The channel up and down on saved recording fast forwards/rewinds through the recording. The channel up and down and live channels is the same. There shouldn't be any changes to anything other than the recordings.

2017-05-26 08:09 UTC, ksooo commented
Sorry, not sure I understand what you mean or maybe I wad not clear enough with my question.

My point is not live tv vs saved recordings, it actually is recordings vs movies. what happens, if you press channel up/down on your remote when playing a movie file? Whatever it is, should be the same for recordings, imo. Could you please check this

2017-05-26 08:35 UTC, FernetMenta commented
@ksooo non-pvr streams are untouched by this change

2017-05-26 10:15 UTC, ksooo commented
@FernetMenta I know, but can one of you please do me a favor and just answer my question? Not in theory, but actually try and tell, please. I'm not in front of a computer the next days...

2017-05-26 19:21 UTC, hugegreenbug commented
@ksooo I have tested pressing channel up/down on my remote when playing a movie and a recording with this patch. Both cases behave the same way.

@FernetMenta I have updated the patch to use GetCurrentChannel().

2017-05-26 19:44 UTC, FernetMenta commented on xbmc/cores/VideoPlayer/VideoPlayer.cpp
> +  if (pvrStream && channel != nullptr)
in general shared pointers are tested for being empty with a boolean operator. comparing with nullptr is not necessarily the same.
if (pvrStream && channel)
{

2017-05-26 19:51 UTC, ksooo commented
Thanks for testing. Can you please tell me *how * they do behave? As I said cannot currently test myself..

2017-05-26 20:05 UTC, hugegreenbug commented
@FernetMenta That is what I initially tried, but it did not work correctly
since channel was always a nullptr.

Hugh

On Fri, May 26, 2017 at 1:44 PM, Rainer Hochecker <notifications@github.com>
wrote:

> *@FernetMenta* commented on this pull request.
> ------------------------------
>
> In xbmc/cores/VideoPlayer/VideoPlayer.cpp
> <https://github.com/xbmc/xbmc/pull/12162#discussion_r118776696>:
>
> > @@ -4440,7 +4440,11 @@ bool CVideoPlayer::OnAction(const CAction &action)
>      }
>    }
>
> -  if (dynamic_cast<CDVDInputStreamPVRManager*>(m_pInputStream))
> +  //If the current channel is a nullptr, and this is a PVRStream, then this is a saved recording
> +  CDVDInputStreamPVRManager* pvrStream = dynamic_cast<CDVDInputStreamPVRManager*>(m_pInputStream);
> +  CPVRChannelPtr channel = g_PVRManager.GetCurrentChannel();
> +  // If the pvrStream is not a saved recording, then handle the actions below
> +  if (pvrStream && channel != nullptr)
>
> in general shared pointers are tested for being empty with a boolean
> operator. comparing with nullptr is not necessarily the same.
> if (pvrStream && channel)
> {
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/xbmc/xbmc/pull/12162#pullrequestreview-40604675>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABlFSeJmWjSzraprq5VO6B5KPp6pIOkLks5r9yuKgaJpZM4NnNrj>
> .
>

2017-05-26 20:06 UTC, hugegreenbug commented
@ksooo Pressing up and down seeks a large amount forward and backward.

Hugh

On Fri, May 26, 2017 at 1:51 PM, Kai Sommerfeld <notifications@github.com>
wrote:

> Thanks for testing. Can you please tell me *how * they do behave? As I
> said cannot currently test myself..
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/xbmc/xbmc/pull/12162#issuecomment-304373717>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABlFSW6UgqLNQksgQxjKlpNbeKOpX2yVks5r9y1DgaJpZM4NnNrj>
> .
>

2017-05-26 20:43 UTC, ksooo commented
Sorry, don't want to be annoying, but do you mean up/ down or channel up/ down. This might be a difference.

2017-05-26 21:17 UTC, hugegreenbug commented
@ksooo No problem. I tried up and down on the keyboard and up and down on
the official ios remote. They both produced the result I mentioned in my
last comment.

Hugh

On Fri, May 26, 2017 at 2:44 PM, Kai Sommerfeld <notifications@github.com>
wrote:

> Sorry, don't want to be annoying, but do you mean up/ down or channel up/
> down. This might be a difference.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/xbmc/xbmc/pull/12162#issuecomment-304384010>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABlFSdizCs1bYl2QvvIXQgXA_-qa0ZDbks5r9zmagaJpZM4NnNrj>
> .
>

2017-05-27 02:08 UTC, hugegreenbug commented
@FernetMenta I fixed the way the channel variable was initialized and that allowed me to check whether it was NULL in the if statement.

2017-05-27 05:11 UTC, hugegreenbug commented on xbmc/cores/VideoPlayer/VideoPlayer.cpp
> +  if (pvrStream && channel != nullptr)
fixed now

2017-05-27 05:32 UTC, FernetMenta commented
thanks!
jenkins build this please

2017-05-27 06:51 UTC, ksooo commented
I don't know how to describe it even better, but I well try. 

There are four (!) different keys- up/down and channel up/ down. I'm interested in the behavior of the latter after your change. You did not change behavior of the first, that's clear.

If there is no channel up/down keys on your remote, could you please attach a keyboard and check the behavior of page up/down, which is the same as channel up/ down.

2017-05-27 14:00 UTC, hugegreenbug commented
@ksooo Ok. I tested the page up/down and the behavior. Here is the behavior for the different video types:
1. Movies - page up/page down changes chapters
2. TV Shows - page down starts the video from the beginning and page up doesn't do anything
3. Recordings - same as 2.

2017-05-27 16:03 UTC, ksooo commented
Okay, then we're okay, imo. Thanks for your patience.

2017-05-27 16:09 UTC, Rechi commented
Is this issue Krypton only?

2017-05-27 16:11 UTC, MartijnKaijser commented
Sorry but no merges to krypton!

2017-05-27 16:58 UTC, hugegreenbug commented
It is not Krypton only. Ok.

2017-05-27 17:09 UTC, MartijnKaijser commented
@hugegreenbug please create a PR to master as well and we keep this open in case for a 17.4 version. 
Thank you for fixing this anyway

2017-05-29 09:54 UTC, FernetMenta commented on xbmc/cores/VideoPlayer/VideoPlayer.cpp
> +  if (pvrStream && channel)
@hugegreenbug please check for channel only if it results in switching channels. in current state this change kills commerial skipping (edl)

2017-05-31 06:41 UTC, hugegreenbug commented on xbmc/cores/VideoPlayer/VideoPlayer.cpp
> +  if (pvrStream && channel)
Ok. I updated the patch.

2017-05-31 08:59 UTC, ksooo approved these changes
Needs some more love.

EDIT: Ooops, approved by accident. I actually want you to do changes.

2017-05-31 08:59 UTC, ksooo commented on xbmc/cores/VideoPlayer/VideoPlayer.cpp
> +        if (!channel) {
Please move the curly brace to next line (Kodi coding guidelines!).

No need for the <code>channel</code> variable anymore. You could write <code>if (!g_PVRManager.GetCurrentChannel())</code> instead.

2017-05-31 08:59 UTC, ksooo commented on xbmc/cores/VideoPlayer/VideoPlayer.cpp
> +        if (!channel) {
Same as for the other case:

Please move the curly brace to next line (Kodi coding guidelines!).

No need for the <code>channel</code> variable anymore. You could write <code>if (!g_PVRManager.GetCurrentChannel())</code> instead.

2017-05-31 08:59 UTC, ksooo commented on xbmc/cores/VideoPlayer/VideoPlayer.cpp
> +  CPVRChannelPtr channel(g_PVRManager.GetCurrentChannel());
Remove this line. See my other comment. <code>channel</code> value is no longer needed unconditionally. Calculate it only, if actually needed (performance!).

2017-05-31 08:59 UTC, ksooo commented on xbmc/cores/VideoPlayer/VideoPlayer.cpp
> +  CDVDInputStreamPVRManager* pvrStream = dynamic_cast<CDVDInputStreamPVRManager*>(m_pInputStream);
Revert this +/-, please. <code>pvrStream</code> variable is no longer needed (and the comment can be removed as well, imo).

2017-05-31 08:59 UTC, ksooo commented on xbmc/cores/VideoPlayer/VideoPlayer.cpp
> +  // If the pvrStream is not a saved recording, then handle the actions below
The comment no longer reflects the actual logic. Remove it, please.

2017-05-31 09:00 UTC, ksooo requested changes
Sorry, I accidentally approved this. I actually want you to do some changes. :-/

2017-05-31 13:19 UTC, hugegreenbug commented on xbmc/cores/VideoPlayer/VideoPlayer.cpp
> +        if (!channel) {
I made the changes

2017-05-31 14:03 UTC, ksooo approved these changes

2017-05-31 14:03 UTC, ksooo commented
Thanks. Could you please squash down changes to one commit and to open a separate PR against master branch?

2017-05-31 20:12 UTC, hugegreenbug commented
@ksooo I made the change just one commit now. 

I had trouble getting the binary addons to show up in my v18 build so I could test the patch, which is why I haven't submitted a PR yet. I will work on that again.

2017-05-31 20:14 UTC, MartijnKaijser commented
Could you please give the commit message a meaningful name/description like what it fixes? Thx

2017-05-31 22:16 UTC, hugegreenbug commented
@MartijnKaijser Ok, I just did.

2017-06-03 19:20 UTC, hugegreenbug commented
@ksooo @MartijnKaijser Will this be merged into 17.4? I have made a pull request for v18.

2017-06-04 10:28 UTC, MartijnKaijser commented
jenkins build this please

2017-06-06 06:16 UTC, merged

2017-06-06 06:16 UTC, MartijnKaijser commented
@hugegreenbug changes are merged for 17.4  Thx