[addons] add first step of gui on addon interface
xbmc/xbmc pull request #12202
Opened 2017-05-30 14:35 UTC by AlwinEsch

## Description

This add the first parts of gui related addon callback parts to new
style. There becomes standard functions and the dialogs added.

On next request comes the controls list item and window.

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2017-05-30 15:21 UTC, ksooo requested changes
Epic. Some suggestions and questions, though.

2017-05-30 15:21 UTC, ksooo commented on xbmc/addons/interfaces/GUI/DialogKeyboard.cpp
> +bool Interface_GUIDialogKeyboard::isKeyboardActivated(void* kodiBase)
For consistency reasons, the function name should start with an upper case, like all others do.

2017-05-30 15:21 UTC, ksooo commented on xbmc/addons/interfaces/GUI/DialogOK.cpp
> +                                        __FUNCTION__, addon, heading, text);
Indentation?!

2017-05-30 15:21 UTC, ksooo commented on xbmc/addons/interfaces/GUI/DialogOK.cpp
> +                                        __FUNCTION__, addon, heading, line0, line1, line2);
Indentation?!

2017-05-30 15:21 UTC, ksooo commented on xbmc/addons/interfaces/GUI/General.cpp
> +    case ACTION_ERROR                  : return ADDON_ACTION_ERROR;
Could you please reformat the code to have the case on one line and thne return on the next line - here and in the rest of this source file? I think this is part of Kodi coding guidelines.

2017-05-30 15:21 UTC, ksooo commented on xbmc/addons/kodi-addon-dev-kit/include/kodi/gui/DialogTextViewer.h
> +    ///  "interspersed renderings from classical composers.\n");
Could you please shorten this example string? I guess the usage of this function gets clear without this wall of text. ;-)

2017-05-30 15:21 UTC, ksooo commented on xbmc/addons/kodi-addon-dev-kit/include/kodi/gui/definitions.h
> +  int (*get_current_window_id)(void* kodiBase);
Why do the gui_general function names start with a lower case letter where all other gui function names start with an uppercase letter? This should be consistent.

2017-05-30 15:28 UTC, AlwinEsch commented on xbmc/addons/kodi-addon-dev-kit/include/kodi/gui/DialogTextViewer.h
> +    ///  "interspersed renderings from classical composers.\n");
Was so big to see on example the full functionallity of TextViewer with scroll up and down.

And you know the Wizard of Oz is a big story :-D

2017-05-30 15:30 UTC, AlwinEsch commented on xbmc/addons/interfaces/GUI/General.cpp
> +    case ACTION_ERROR                  : return ADDON_ACTION_ERROR;
In know but with action id's becomes it really long, but I can change it

2017-05-30 15:31 UTC, ksooo commented on xbmc/addons/kodi-addon-dev-kit/include/kodi/gui/DialogTextViewer.h
> +    ///  "interspersed renderings from classical composers.\n");
Okay, you decide on this. :-)

2017-05-30 15:32 UTC, ksooo commented on xbmc/addons/interfaces/GUI/General.cpp
> +    case ACTION_ERROR                  : return ADDON_ACTION_ERROR;
Thanks.

2017-05-30 15:32 UTC, AlwinEsch commented on xbmc/addons/interfaces/GUI/DialogKeyboard.cpp
> +bool Interface_GUIDialogKeyboard::isKeyboardActivated(void* kodiBase)
comes, still working on the gui parts, there are few parts who bring me grey hairs, during improvement ;-)

2017-05-30 15:34 UTC, AlwinEsch commented on xbmc/addons/interfaces/GUI/DialogFileBrowser.cpp
> +        free(path[i]);
Have tried it on other requests and has several times a crash then. Don't know why.

2017-05-31 01:22 UTC, AlwinEsch commented on xbmc/addons/interfaces/GUI/DialogFileBrowser.cpp
> +bool Interface_GUIDialogFileBrowser::ShowAndGetDirectory(void* kodiBase, const char *shares, const char *heading, char &path, unsigned int &maxStringSize, bool writeOnly)
Are changed.

2017-05-31 01:24 UTC, AlwinEsch commented on xbmc/addons/kodi-addon-dev-kit/include/kodi/gui/definitions.h
> +  int (*get_current_window_id)(void* kodiBase);
Is changed, was gone down during move from kodi agile to here.

2017-05-31 01:47 UTC, AlwinEsch commented
Is everything updated, buhh :D

Excuse me for the circumstances, with so many things I do not see the forest in front of loud trees.

2017-05-31 02:23 UTC, AlwinEsch commented on xbmc/addons/kodi-addon-dev-kit/include/kodi/gui/definitions.h
> +
Have someone a good idea about them for action id's?

To do with a separate place bring advantages but also disadvantages.

I remove them now and hope to find a good way to interact with them and kodi and hold also independent.

With the "enum" has made the doxygen output a bit nicer as with a "define". :-)

2017-05-31 10:13 UTC, ksooo requested changes
Still needs some more love. ;-)

2017-05-31 10:13 UTC, ksooo commented on xbmc/addons/kodi-addon-dev-kit/include/kodi/gui/definitions.h
> +  void (*clear_list)(void* kodiBase, char*** path, unsigned int entries);
This function should be renamed to clear_file_list for consistency reasons.

2017-05-31 10:13 UTC, ksooo commented on xbmc/addons/interfaces/GUI/DialogFileBrowser.cpp
> +        free((*path)[i]);
The <code>if ((*path)[i])</code> can be removed. <code>free</code> can be called safely on a nullptr.

2017-05-31 10:13 UTC, ksooo commented on xbmc/addons/interfaces/GUI/DialogFileBrowser.cpp
> +    for (unsigned int i = 0; i < entries; ++i)
Question: Is parameter <code>entries</code> actually needed or can the count of elements be calculated via <code>sizeof</code> here?

2017-05-31 10:13 UTC, ksooo commented on xbmc/addons/interfaces/GUI/DialogFileBrowser.cpp
> +void Interface_GUIDialogFileBrowser::GetVECShares(VECSOURCES& vecShares, std::string strShares, std::string strPath)
<code>const std::string& strShares</code>, <code>const std::string& strPath</code> ?! No reason for pass-by-value, imo.

2017-05-31 10:13 UTC, ksooo commented on xbmc/addons/interfaces/GUI/DialogFileBrowser.cpp
> +    free(*path);
<code>*path = 0;</code> is missing here. Otherwise the caller might operate on a pointer pointing to the woods.

2017-05-31 10:24 UTC, AlwinEsch commented on xbmc/addons/interfaces/GUI/DialogFileBrowser.cpp
> +        free((*path)[i]);
I test it

2017-05-31 10:27 UTC, ksooo commented on xbmc/addons/interfaces/GUI/DialogFileBrowser.cpp
> +        free((*path)[i]);
No need to test, specification is clear on this. ;-)

2017-05-31 10:28 UTC, AlwinEsch commented on xbmc/addons/interfaces/GUI/DialogFileBrowser.cpp
> +    strncpy(path, strPath.c_str(), maxStringSize);
I look what possible, problem on them is that the they become a `[in|out]` as values.
If it use malloc must be in from out different.

2017-05-31 10:40 UTC, ksooo commented on xbmc/addons/interfaces/GUI/DialogFileBrowser.cpp
> +    strncpy(path, strPath.c_str(), maxStringSize);
yeah, easy. Use two params, one for "in" (const char * pathIn), one for "out" (char *** pathOut).

2017-05-31 13:16 UTC, AlwinEsch commented on xbmc/addons/interfaces/GUI/DialogFileBrowser.cpp
> +    for (unsigned int i = 0; i < entries; ++i)
Is needed, the allocated size of them can be different.

2017-05-31 14:01 UTC, AlwinEsch commented
Is updated :)

2017-05-31 15:00 UTC, ksooo reviewed
Last nitpicking, I promise. :-)

2017-05-31 15:00 UTC, ksooo commented on xbmc/addons/interfaces/GUI/DialogFileBrowser.cpp
> +                                                            const char* heading, char*** path, unsigned int* entries,
I would name the variable file_list, not path as it contains a list of several files, not a single path.

2017-05-31 15:00 UTC, ksooo commented on xbmc/addons/interfaces/GUI/DialogFileBrowser.cpp
> +bool Interface_GUIDialogFileBrowser::show_and_get_image_list(void* kodiBase, const char* shares, const char* heading, char*** path, unsigned int* entries)
I would name the variable file_list, not path as it contains a list of several files, not a single path.

2017-05-31 15:00 UTC, ksooo commented on xbmc/addons/interfaces/GUI/DialogFileBrowser.cpp
> +void Interface_GUIDialogFileBrowser::clear_file_list(void* kodiBase, char*** path, unsigned int entries)
I would name the variable file_list, not path as it contains a list of several files, not a single path.

2017-05-31 15:00 UTC, ksooo approved these changes

2017-05-31 16:09 UTC, xhaggi commented on xbmc/addons/interfaces/GUI/DialogContextMenu.cpp
> +    CLog::Log(LOGERROR, "Interface_GUIDialogContextMenu::Open - invalid kodi base data");
Should we use `__FUNCTION__` as well here?

2017-05-31 16:09 UTC, xhaggi commented on xbmc/addons/interfaces/GUI/DialogContextMenu.cpp
> +    CLog::Log(LOGERROR, "Interface_GUIDialogContextMenu::Open - invalid handler data (heading='%p', entries='%p', dialog='%p') on addon '%s'",
same here

2017-05-31 18:33 UTC, ksooo commented
jenkins build this please

2017-05-31 19:36 UTC, merged