[addons] add gui control classes to new addon interface
xbmc/xbmc pull request #12259
Opened 2017-06-07 08:19 UTC by AlwinEsch

## Description

This change alow addons to edit all used controls on his processed window.

For the moment is this mostly the last request to create the global addon
interface function.

Most further requests are to change addon types iself to new style.

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2017-06-07 21:23 UTC, ksooo requested changes
5000+ lines of code to review. That was hard candy. You ow me a beer at next Devcon, @AlwinEsch :-)

2017-06-07 21:23 UTC, ksooo commented on xbmc/addons/interfaces/GUI/controls/SettingsSlider.cpp
> +  // create message
Remove this comment, please. It adds no value.

2017-06-07 21:23 UTC, ksooo commented on xbmc/addons/interfaces/GUI/controls/SettingsSlider.cpp
> +  // send message
Remove this comment, please. It adds no value.

2017-06-07 21:23 UTC, ksooo commented on xbmc/addons/interfaces/GUI/controls/Slider.cpp
> +    return 0;
"return -1;" to indicate error, like done in all (?) other methods returning int?

2017-06-07 21:23 UTC, ksooo commented on xbmc/addons/interfaces/GUI/controls/Spin.cpp
> +  if (!addon || !control)
check "text" for not being nullptr?

2017-06-07 21:23 UTC, ksooo commented on xbmc/addons/interfaces/GUI/controls/Spin.cpp
> +  // create message
remove this

2017-06-07 21:23 UTC, ksooo commented on xbmc/addons/interfaces/GUI/controls/Spin.cpp
> +  // send message
remove this

2017-06-07 21:23 UTC, ksooo commented on xbmc/addons/interfaces/GUI/controls/Spin.cpp
> +void Interface_GUIControlSpin::add_string_label(void* kodiBase, void* handle, const char* label, const char* value)
why "add", not "set"? if only one label is possible, I would use "set".

2017-06-07 21:23 UTC, ksooo commented on xbmc/addons/interfaces/GUI/controls/Spin.cpp
> +void Interface_GUIControlSpin::add_int_label(void* kodiBase, void* handle, const char* label, int value)
"add" vs. "set"?

2017-06-07 21:23 UTC, ksooo commented on xbmc/addons/interfaces/GUI/controls/Spin.cpp
> +    return 0;
"return -1;"?

2017-06-07 21:23 UTC, ksooo commented on xbmc/addons/interfaces/GUI/controls/TextBox.cpp
> +  // create message
this should go

2017-06-07 21:23 UTC, ksooo commented on xbmc/addons/interfaces/GUI/controls/TextBox.cpp
> +  // send message
remove me!

2017-06-07 21:23 UTC, ksooo commented on xbmc/addons/kodi-addon-dev-kit/include/kodi/gui/controls/Edit.h
> +    }
One of my favorites (as you know): "virtual ~CEdit() = default;" ? Here and everywhere in this PR. ;-)

2017-06-07 21:23 UTC, ksooo commented on xbmc/addons/kodi-addon-dev-kit/include/kodi/gui/controls/Rendering.h
> +        kodi::Log(ADDON_LOG_FATAL, "kodi::gui::controls::CRendering can't create control class from Kodi !!!");
Use __FUNCTION__ here and at the other places where you hard coded the funtion name for logging?

2017-06-07 22:17 UTC, AlwinEsch commented on xbmc/addons/kodi-addon-dev-kit/include/kodi/gui/controls/Edit.h
> +    }
New problem becomes changed, is still new for me :-)

2017-06-07 22:26 UTC, AlwinEsch commented on xbmc/addons/interfaces/GUI/controls/Spin.cpp
> +    return 0;
Not sure what's the best, has set it as 0 to have equal with float error return and is normally the default value if nothing becomes set before.

2017-06-07 22:35 UTC, AlwinEsch commented on xbmc/addons/interfaces/GUI/controls/SettingsSlider.cpp
> +  if (!addon || !control)
Not really, this need it and I need a clearer head ;-).

2017-06-07 22:36 UTC, AlwinEsch commented on xbmc/addons/interfaces/GUI/controls/Spin.cpp
> +  if (!addon || !control)
Like above, equal to my head and was lost in memory.

2017-06-07 22:42 UTC, AlwinEsch commented on xbmc/addons/interfaces/GUI/controls/Label.cpp
> +  // send message
Becomes removed. Always this c&p things :-D 
https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/legacy/Control.cpp#L139-L147

2017-06-07 22:48 UTC, AlwinEsch commented on xbmc/addons/interfaces/GUI/controls/Image.cpp
> +void Interface_GUIControlImage::set_filename(void* kodiBase, void* handle, const char* filename, const bool use_Cache)
Thought to have all removed, thank you. It flies out.

With the "use_cache" has I used to have more equal to "C" name style (has wrongly set one character as uppercase).

Only leaved everywhere the "kodiBase" as sign for me that a C++ base is behind.

2017-06-07 22:51 UTC, AlwinEsch commented on xbmc/addons/interfaces/GUI/controls/FadeLabel.h
> +    static void add_label(void* kodiBase, void* handle, const char* label);
It can have more strings in a list, for them is the set_scrolling and reset also used.

2017-06-07 22:55 UTC, AlwinEsch commented on xbmc/addons/interfaces/GUI/Window.cpp
> +  return pAddonWindow->GetAddonControl(control_id, CGUIControl::GUICONTROL_TEXTBOX, "textbox");
If this is not problematic with a static_cast, looks it really better.

2017-06-07 22:56 UTC, AlwinEsch commented
Thanks a lot and the beer is ready.

2017-06-07 23:03 UTC, AlwinEsch commented on xbmc/addons/interfaces/GUI/Window.cpp
> +  return pAddonWindow->GetAddonControl(control_id, CGUIControl::GUICONTROL_TEXTBOX, "textbox");
Forget my comment and becomes changed, thanks a lot!

2017-06-08 06:08 UTC, ksooo requested changes
Just another small nitpick, the rest is looking very good now.

2017-06-08 06:08 UTC, ksooo commented on xbmc/addons/interfaces/GUI/controls/FadeLabel.h
> +    static void add_label(void* kodiBase, void* handle, const char* label);
Ah, okay then.

2017-06-08 07:00 UTC, AlwinEsch commented
jenkins build this please

2017-06-08 07:09 UTC, ksooo approved these changes
Good to go.

2017-06-08 08:26 UTC, merged