[addons] add next step on CAddonInfo to become independent
xbmc/xbmc pull request #12260
Opened 2017-06-07 09:49 UTC by AlwinEsch

## Description

This change all values on CAddonInfo to private and access
them over functions.

Main reason for them is to make the class more safe for next changes
where CAddonInfo is no longer in CAddon, but globally as replacement
for cpluff.

Set of this value becomes in future mainly done from the class constructor
and no more by external parts.

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2017-06-07 15:18 UTC, ksooo reviewed
Some suggestions and questions...

2017-06-07 16:12 UTC, tamland commented on xbmc/addons/Addon.h
> +  TYPE Type() const override { return m_addonInfo.MainType(); }
In the end though there really should be no such thing as an 'addon type', but only addons with N possible extension points (which can have a type). So assuming this is only temporary for legacy code I guess 'MainType' works as to making it clearer..

2017-06-07 16:34 UTC, AlwinEsch commented on xbmc/addons/AddonBuilder.h
> +  const AddonVersion& GetVersion() const { return m_addonInfo.m_version; }
The add of `friend class CAddonBuilder` is only temporarily to allow them to set the values in CAddonInfo, on end create CAddonInfo the values itself by his constructor.

2017-06-07 16:38 UTC, tamland requested changes

2017-06-07 16:38 UTC, tamland commented on xbmc/addons/AddonInfo.h
> +    bool IsUsable() const { return m_usable; }
This doesn't belong to this commit

2017-06-07 16:38 UTC, tamland commented on xbmc/addons/AddonInfo.h
> +    //@}
Same here: not used anywhere. And definitely not used by CAddonDatabase.

2017-06-07 16:38 UTC, tamland commented on xbmc/addons/AddonInfo.h
> +     * The ID is defined in addon.xml but should also equal with add-on path!
This isn't correct. There is no such requirement.

2017-06-07 16:38 UTC, tamland commented on xbmc/addons/AddonInfo.h
> +     */
I find all these getter 'docstrings' very superficial.. It's completely obvious to everyone what all these methods does.

2017-06-07 16:38 UTC, tamland commented on xbmc/addons/AddonInfo.h
> +     * @note this is only be set from add-on browser and not always present!
That's not true. It should be set everywhere except when getting a single addon from addon manager. (And that is just a workaround due to some parts calling GetAddon way too much)

2017-06-07 16:39 UTC, AlwinEsch commented on xbmc/addons/AddonInfo.h
> +    friend class ADDON::CAddonBuilder;
CAddonBuilder is the only class who currently need to set the values on CAddonInfo and only temporarily, the builder becomes on next steps complete removed. See also my other comment,

2017-06-07 16:40 UTC, AlwinEsch commented on xbmc/addons/AddonInfo.h
> +    bool IsUsable() const { return m_usable; }
Can remove it now, but becomes on next commits used the know class construction with read of addon.xml was OK.

2017-06-07 16:45 UTC, ksooo commented on xbmc/addons/AddonInfo.h
> +    friend class ADDON::CAddonBuilder;
Okay, then.

2017-06-07 16:45 UTC, ksooo commented on xbmc/addons/AddonBuilder.h
> +  const AddonVersion& GetVersion() const { return m_addonInfo.m_version; }
Okay.

2017-06-07 16:47 UTC, AlwinEsch commented on xbmc/addons/AddonInfo.h
> +    //@}
Also a part who becomes in future used from CAddonDatabase. Can remove it and add later.

2017-06-07 16:55 UTC, AlwinEsch commented on xbmc/addons/AddonInfo.h
> +     */
Better remove the docs, for me also not really needed?

Thought only that maybe wanted for there.

2017-06-07 17:02 UTC, ksooo commented on xbmc/addons/AddonInfo.h
> +     */
What @tamland said. Remove it. Does  not really add any value.

2017-06-07 17:56 UTC, garbear approved these changes

2017-06-07 18:47 UTC, ksooo approved these changes

2017-06-07 18:50 UTC, ksooo commented
Let's handle documentation issues in a separate PR, once all code changes are in, like agreed before.

2017-06-08 05:56 UTC, AlwinEsch commented
Have removed the comments, but want to leave the "Parts used from ADDON::CAddonDatabase" in. Becomes used on next commits and want them to hold small to see the critical parts.

2017-06-08 06:09 UTC, ksooo commented
Fine by me. Merge it!

2017-06-08 06:48 UTC, AlwinEsch commented
jenkins build this please

2017-06-08 08:27 UTC, merged