VideoPlayerRadioRDS: Revert ResetRDSCache on init
xbmc/xbmc pull request #12274
Opened 2017-06-09 11:20 UTC by popcornmix

## Description

Since this change we have had random crashes on playback of videos.
I believe it is due to calling g_infoManager.SetCurrentItem with an uninitialised CurrentFileItem

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2017-06-09 11:22 UTC, popcornmix commented
The crash is avoided with this line commented out:
https://github.com/popcornmix/xbmc/blob/f4b3dc56068b27922ca0bd6b55c355f11afc4917/xbmc/cores/VideoPlayer/VideoPlayerRadioRDS.cpp#L633

Seg faults like:
Thread 1 (Thread 0x6d0ff3a0 (LWP 1091)):
#0  0x751bc3e4 in std::string::swap(std::string&) () from /usr/lib/libstdc++.so.6
#1  0x00565908 in CVideoInfoTag::operator=(CVideoInfoTag&&) ()
#2  0x005a3180 in CVideoDatabase::GetEpisodeInfo(std::string const&, CVideoInfoTag&, int, int) ()
#3  0x005a516c in CVideoDatabase::LoadVideoInfo(std::string const&, CVideoInfoTag&, int) ()
#4  0x007de254 in CGUIInfoManager::SetCurrentMovie(CFileItem&) ()
#5  0x007de5b8 in CGUIInfoManager::SetCurrentItemJob(std::shared_ptr<CFileItem>) ()
#6  0x007df85c in CSetCurrentItemJob::DoWork() ()
#7  0x0061531c in CJobWorker::Process() ()
#8  0x0065c574 in CThread::Action() ()

and http://sprunge.us/WTiK have been observed.

Ping @FernetMenta @garbear

2017-06-10 17:29 UTC, FernetMenta commented
@AlwinEsch please review

2017-06-10 19:04 UTC, AlwinEsch requested changes
Is not a good way to prevent this crash, without the call is the RDS info not correct and can produce other problems.

Better search the reason inside this function and fix it there.

2017-06-10 19:06 UTC, AlwinEsch commented
Becomes this class now also created if a stream without RDS is started?

2017-06-10 19:09 UTC, popcornmix commented
Yes, this code is called on all files (even without RDS stream).

2017-06-10 22:21 UTC, AlwinEsch commented
Not sure think its wrong then, why need someone to open a RDS stream if it becomes never used.

2017-06-11 10:54 UTC, popcornmix commented
Master is currently broken with random crashes on playback start.
The addition of the ResetRDSCache call (https://github.com/xbmc/xbmc/pull/12084) didn't fix any actual problem (i.e. didn't solve any visible bug).
We should revert this now and any improved solution can come in later.

2017-06-11 11:44 UTC, FernetMenta commented
I wasn't awre that the problem came with #12084 
+1 for this PR

2017-06-11 11:44 UTC, merged

2017-06-11 16:42 UTC, AlwinEsch commented
OK
then also for me +1, Maybe this was also the reason why I not added there on begin? :)