CHG: Allow to (really) disable upnp altogether
xbmc/xbmc pull request #12327
Opened 2017-06-21 09:50 UTC by koying

aka the "@da-anda shitty radio" PR ;)

Currently, there is no way to disable the upnp "listener". This PR implements it.
There are a number of reason why you wouldn't want a daemon like this to run (if you don't need it), but the 1st one would probably be wasted resources.

The side-effect is that it indirectly solves an issue where an ill-behaving upnp device on the network flooding with upnp messages can affect Kodi (ie da-anda shitty radio ;) )

2017-06-21 09:58 UTC, da-anda commented on system/settings/settings.xml
> +        <setting id="services.upnp" type="boolean" label="1270">
like mentioned on Slack, it's the wrong label ID (it's the one from AirPlay). Correct ID is `21358`.

2017-06-21 09:59 UTC, da-anda commented on system/settings/settings.xml
> +        <setting id="services.upnpserver" type="boolean" label="21358" help="36323">
and this setting should probably keep label id `21360`?

2017-06-21 10:14 UTC, da-anda commented
thanks. The correct unofficial PR title would be "fix da-anda shitty radio issue that only occurs on Android", because no other platform running Kodi is having this issue (video/UI freeze while audio continues and Kodi is still responding to keypresses). The root cause might be some libplatinum core issue on Android leading to a scenario that prevents our rendering process to update frames, but no idea on how to hunt this one down.

@Montellese if you'd like to see the network traffic/spam from my UPNP enabled radio I'm happy to provide a Wireshark trace (already have prepared one). My radio basically is sending at least 2 (up to 6) UPNP related messages every second and the screen freezes whenever I play something in Kodi on Android (Kodi17 on SHIELD and Kodi 18 nightly on Nexus10).

2017-06-26 09:30 UTC, Montellese requested changes
Looks ok apart from the minors. It might be worth to check the initialization logic of Platinum SDK in more detail to see if we are already performing certain setup steps before `StartUPnPClient()` or `StartUPnPServer()` is called.

2017-06-26 09:30 UTC, Montellese commented on system/settings/settings.xml
> +        <setting id="services.upnp" type="boolean" label="1270">
And it would be great to also have a description.

2017-06-26 09:30 UTC, Montellese commented on system/settings/settings.xml
> +          <level>1</level>
Why did you change the level from 0 to 1?

2017-06-26 12:05 UTC, koying commented on system/settings/settings.xml
> +          <level>1</level>
The idea is to enable/disable UPnP altogether. As such, it makes sense to me that anything related to UPnP be under the new setting at level 0.

2017-06-26 12:49 UTC, Montellese commented on system/settings/settings.xml
> +          <level>1</level>
Hm maybe you are misinterpreting the term `level`. In this case it means the setting level visibility i.e.
* 0 = Basic
* 1 = Standard
* 2 = Advanced
* 3 = Expert
* 4 = Internal

If you want to have the setting indented under the general "Enable UPnP" setting you need to add the `parent="services.upnp"` attribute on the `<setting>` tag.

2017-06-26 13:04 UTC, koying commented on system/settings/settings.xml
> +          <level>1</level>
Oops, indeed

2017-06-27 08:02 UTC, MartijnKaijser commented
@koying build failed

2017-06-27 08:45 UTC, koying commented
jenkins build this please

2017-06-30 08:02 UTC, MartijnKaijser commented
@Montellese all good?

2017-06-30 09:26 UTC, Montellese approved these changes

2017-07-01 20:26 UTC, merged