Implement basic gameplay persistence (autosave)
xbmc/xbmc pull request #12434
Opened 2017-07-07 01:41 UTC by garbear

This implements a rudimentary autosave/autoload feature. When the game is closed, the state and its metadata are saved to the hard drive. When the game is played again, the state is automatically loaded.

This is called "gameplay persistence" because the game resumes where it was last left off, with no explicit saving/loading action by the user.

Additionally, to guard against power loss, the game is autosaved every 10 seconds.

Savestates and metadata are stored alongside the game by replacing the file extension.

If a different game client is used, Kodi will warn the user that it will overwrite their existing save. This is because savestates are incompatible between emulators, and storing more than a single savestate isn't implemented yet.

## Screenshots (if appropriate):

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2017-07-07 06:52 UTC, Montellese requested changes
Looks good apart from minors. Did you add and commit the two `RPOverlayRendererGL` files on purpose or by accident? They haven't been added to any `CMakeLists.txt` so they aren't built and they also aren't included anywhere else.

2017-07-07 06:52 UTC, Montellese commented on addons/resource.language.en_gb/resources/strings.po
> +msgid "Erase save"
Above you use "savestate" twice but here only "save". Is that intended or should we keep it consistent?

2017-07-07 06:52 UTC, Montellese commented on xbmc/cores/RetroPlayer/RetroPlayerAutoSave.h
> +    virtual ~CRetroPlayerAutoSave() override;
You don't need the `virtual` here and IIR there are compilers who spit out a warning if you combine `virtual` and `override` for a method definition.

2017-07-07 13:17 UTC, garbear commented on addons/resource.language.en_gb/resources/strings.po
> +msgid "Erase save"
I was going for shorter text for the button, but probably best to keep it consistent

2017-07-07 13:39 UTC, garbear commented on xbmc/cores/RetroPlayer/RetroPlayerAutoSave.h
> +    virtual ~CRetroPlayerAutoSave() override;
I've never come across a compiler with this warning, but it can't hurt to remove `virtual`

2017-07-07 17:40 UTC, garbear commented
@Montellese addressed your comments

2017-07-08 08:25 UTC, Montellese commented on xbmc/cores/RetroPlayer/RetroPlayer.cpp
> +          // "Erase save"
This isn't correct anymore. I wouldn't write this here anyway because it can get out of sync quickly.

2017-07-08 21:16 UTC, garbear commented on xbmc/cores/RetroPlayer/RetroPlayer.cpp
> +          // "Erase save"
OK, I'll summarize

2017-07-10 19:59 UTC, garbear commented
I've uploaded builds to the [test builds thread](https://forum.kodi.tv/showthread.php?tid=173361) and attached a screen shot of the warning message.

2017-07-13 02:44 UTC, garbear commented
jenkins build this please

2017-07-13 04:54 UTC, merged