Fix seeking with PTS values exceeding max int
xbmc/xbmc pull request #12442
Opened 2017-07-07 20:14 UTC by rbuehlma

This is a follow up to https://github.com/xbmc/xbmc/pull/12086

I found some additional places where double got pushed into an int.

2017-07-07 20:46 UTC, ksooo requested changes

2017-07-07 20:46 UTC, ksooo commented on xbmc/cores/VideoPlayer/Edl.cpp
> +double CEdl::RestoreCutTime(double iClock) const
If you change the data type, then please also change the variable's name. Prefix "i" stands for "int". Applies also to other places of your commit.

2017-07-07 20:54 UTC, rbuehlma commented on xbmc/cores/VideoPlayer/Edl.cpp
> +double CEdl::RestoreCutTime(double iClock) const
Sure, here we are :)

2017-07-07 21:35 UTC, ksooo requested changes

2017-07-07 21:35 UTC, ksooo commented on xbmc/cores/VideoPlayer/Edl.cpp
> +      dSeek += (double)m_vecCuts[i].end - (double)m_vecCuts[i].start;
please use c++ style casts

2017-07-07 21:53 UTC, rbuehlma commented on xbmc/cores/VideoPlayer/Edl.cpp
> +      dSeek += (double)m_vecCuts[i].end - (double)m_vecCuts[i].start;
I removed the cast. If I understand C++ correctly, the calculation is done in double any way as it expands to dSeek = dSeek + int.
As we calculate here with a double, the int is promoted to a double.
Can you confirm that?

2017-07-07 22:30 UTC, garbear commented on xbmc/cores/VideoPlayer/Edl.cpp
> +      dSeek += (double)m_vecCuts[i].end - (double)m_vecCuts[i].start;
Better include the cast. Windows warns about this conversion:

```
ActiveAE.cpp(1911): warning C4244: 'initializing': conversion from 'int64_t' to 'double', possible loss of data
```

2017-07-08 05:04 UTC, FernetMenta approved these changes

2017-07-08 07:29 UTC, rbuehlma commented on xbmc/cores/VideoPlayer/Edl.cpp
> +      dSeek += (double)m_vecCuts[i].end - (double)m_vecCuts[i].start;
Done. Better now?

2017-07-08 07:56 UTC, MartijnKaijser commented
jenkins build this please

2017-07-08 08:02 UTC, ksooo approved these changes

2017-07-08 08:11 UTC, MartijnKaijser commented
jenkins build this please

2017-07-08 09:04 UTC, merged