FIX: Database debug spew on demand only
xbmc/xbmc pull request #12534
Opened 2017-07-20 12:39 UTC by koying

Be easy on db logging by default

2017-07-20 16:48 UTC, MartijnKaijser commented
Unrelated Linux fail

2017-08-02 07:41 UTC, mkortstiege requested changes
```LOGDEBUG``` output created in ```CVideoDatabase::CleanDatabase``` should be added as well. Other than that it looks good to me.

2017-08-04 18:53 UTC, peak3d commented
Any reason why this is not already merged?

2017-08-07 07:55 UTC, mkortstiege approved these changes

2017-08-10 15:04 UTC, merged