[fix] coverity issues
xbmc/xbmc pull request #12565
Opened 2017-07-24 16:25 UTC by Rechi

## Description
Fix a few coverity issues

## Motivation and Context
reduce coverity issues

## How Has This Been Tested?
build for windows and osx

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

2017-07-24 16:33 UTC, FernetMenta commented on xbmc/cores/AudioEngine/Utils/AEUtil.cpp
> -      if (AE_IS_PLANAR(format))
dropping this looks wrong on first glance. please elaborate

2017-07-24 16:42 UTC, Rechi commented on xbmc/cores/AudioEngine/Utils/AEUtil.cpp
> -      if (AE_IS_PLANAR(format))
`AE_IS_PLANAR = AE_FMT_U8P|AE_FMT_S16NEP|AE_FMT_S32NEP|AE_FMT_S24NE4P|AE_FMT_S24NE4MSBP|AE_FMT_S24NE3P|AE_FMT_DOUBLEP|AE_FMT_FLOATP` and all those are already handled explicitly above.

2017-07-24 17:13 UTC, FernetMenta commented on xbmc/cores/AudioEngine/Utils/AEUtil.cpp
> -      if (AE_IS_PLANAR(format))
if you argue like this, you need to remove entire default but this is not what we want to achive with the default case.
coverity is wrong here.

2017-07-24 17:48 UTC, Rechi commented on xbmc/cores/AudioEngine/Utils/AEUtil.cpp
> -      if (AE_IS_PLANAR(format))
what should I do, drop this change?

2017-07-25 20:40 UTC, Paxxi requested changes
Sdl memset needs fixing rest looks good

2017-07-25 20:40 UTC, Paxxi commented on xbmc/Util.cpp
>  int CUtil::GetRandomNumber()
This method should be removed or switched to using a proper C11 rand

2017-07-25 20:40 UTC, Paxxi commented on xbmc/threads/Thread.h
> +  ThreadOpaque m_ThreadOpaque = { 0 };
This isn't entirely correct. On windows this is a HANDLE which is a pointer type

2017-07-25 20:40 UTC, Paxxi commented on xbmc/video/Teletext.cpp
> +    case 0: do { *_p++ = val;
This is completely broken. What is an unterminated do clause doing here?

2017-07-26 03:27 UTC, FernetMenta commented on xbmc/cores/AudioEngine/Utils/AEUtil.cpp
> -      if (AE_IS_PLANAR(format))
yes, please

2017-07-26 12:01 UTC, Rechi commented on xbmc/video/Teletext.cpp
> +    case 0: do { *_p++ = val;
`} while ( --_n );` is a few lines below
I just replaced the define with a function so behaviour hasn't changed.
The define is an exact copy from libsdl.

2017-07-26 18:48 UTC, garbear commented on xbmc/video/Teletext.cpp
> +    case 0: do { *_p++ = val;
This is known as Duff's device: https://en.wikipedia.org/wiki/Duff%27s_device

2017-07-27 14:20 UTC, notspiff commented
@Rechi please consider if you want to do something about
```
1037: [/home/akva/kode/kodi-cmake/xbmc/threads/platform/win/ThreadLocal.h:45]: (warning) Class ThreadLocal is not safe, destructor throws exception
```

2017-07-27 18:11 UTC, Paxxi commented on xbmc/video/Teletext.cpp
> +    case 0: do { *_p++ = val;
Thanks garbear. Leave loop unrolling to the compiler I say. This code looks horrible

2017-07-27 18:51 UTC, Paxxi approved these changes

2017-07-27 19:43 UTC, merged