[win32] get rif of `TARGET_WIN10` define + cleanups
xbmc/xbmc pull request #12606
Opened 2017-08-01 19:22 UTC by afedchin

this this second try of second phase/wave in preparation for uwp

- introduce new define `TARGET_WINDOWS_DESKTOP`, it's defined for regular window builds (win32|x64)
- drop `TARGET_WIN10` define, please use `TARGET_WINDOWS_STORE` instead if you need specify uwp code
- drop `HAS_DX` where it's not needed
- drop old windows GL code.

2017-08-01 19:38 UTC, afedchin commented
jenkins build this please

2017-08-01 19:51 UTC, MartijnKaijser commented on xbmc/cores/VideoPlayer/Process/windows/ProcessInfoWin.cpp
> +#if defined(TARGET_WINDOWS_DESKTOP)
Shouldn't this be just WINDOWS?

2017-08-01 20:00 UTC, afedchin commented on xbmc/cores/VideoPlayer/Process/windows/ProcessInfoWin.cpp
> +#if defined(TARGET_WINDOWS_DESKTOP)
no, `ProcessInfoWin` is special for desktop app

2017-08-01 20:04 UTC, MartijnKaijser commented on xbmc/cores/VideoPlayer/Process/windows/ProcessInfoWin.cpp
> +#if defined(TARGET_WINDOWS_DESKTOP)
Just checking :) 
Rest looks OK I think

2017-08-01 20:23 UTC, Rechi commented on xbmc/cores/VideoPlayer/Process/windows/ProcessInfoWin.cpp
> +#if defined(TARGET_WINDOWS_DESKTOP)
exclude the file for store builds in cmake instead of this ifdef
do the same for `ProcessInfoWin10.cpp`

2017-08-01 20:24 UTC, Rechi commented on xbmc/cores/VideoPlayer/Process/windows/ProcessInfoWin10.cpp
> +#if defined(TARGET_WINDOWS_STORE)
exclude for desktop build via cmake

2017-08-01 20:51 UTC, afedchin commented
jenkins build this please

2017-08-02 07:29 UTC, Paxxi requested changes
Looks good overall but I think the !defined should be inverted to specifically use DESKTOP now to make it simpler to read

2017-08-02 07:29 UTC, Paxxi commented on xbmc/platform/win32/pch.h
> +#if !defined(TARGET_WINDOWS_STORE)
this should be fixed now that we have the `TARGET_WINDOWS_DESKTOP` define

2017-08-02 07:29 UTC, Paxxi commented on xbmc/rendering/dx/DeviceResources.cpp
> +#ifndef TARGET_WINDOWS_STORE
same for this one

2017-08-02 07:29 UTC, Paxxi commented on xbmc/rendering/dx/RenderSystemDX.cpp
> +#if defined TARGET_WINDOWS_DESKTOP
missing parenthesis, looks weird but just a style issue

2017-08-02 07:29 UTC, Paxxi commented on xbmc/system.h
> +#if !defined(TARGET_WINDOWS_STORE)
invert this one as well

2017-08-02 08:52 UTC, afedchin commented
win32 failure isn't related

2017-08-02 08:53 UTC, merged