CHG: [droid] Adapt to ndk15+ with unified headers
xbmc/xbmc pull request #12624
Opened 2017-08-04 10:33 UTC by koying

As the name says, those are changes to the android build chain so as to adapt to the recent NDK move to an "unified headers" approach, ie. the headers are common to all toolchain/api, vs. headers specific per arch/api as it was before.

Big advantage: large offsets are now (more-or-less) properly handled, so no need to fiddle with off_t/off64_t anymore in coming samaba4 PR.

2017-08-04 11:54 UTC, wsnipex commented on tools/depends/configure.ac
> +AC_ARG_WITH([ndk],
This changes behavior for an existing setting, should we go with api or ndk-version/level instead?

2017-08-04 11:54 UTC, wsnipex commented on tools/depends/configure.ac
> +  [spcify ndk level (optional for android). default is 21])],
specify

2017-08-04 11:58 UTC, koying commented on tools/depends/configure.ac
> +AC_ARG_WITH([ndk],
OTOH it's now symetric with the sdk one.
If you want, we can have ndk-api and sdk-api, which makes sense.

2017-08-04 12:05 UTC, wsnipex commented on tools/depends/configure.ac
> +AC_ARG_WITH([ndk],
yep, ndk-api and sdk-api sound sane

2017-08-04 12:30 UTC, peak3d commented
Can we still build with older ndk (14e for example)?

2017-08-04 12:47 UTC, koying commented
Yep, at least the last time I tried ;)

2017-08-04 12:50 UTC, peak3d commented
Ok, then I'll give it a try here

2017-08-04 13:08 UTC, koying commented
If by "here" you mean jenkins, that won't work as you cannot select the toolchain.

2017-08-04 13:13 UTC, peak3d commented
here on my private system

2017-08-04 14:14 UTC, Memphiz commented on tools/depends/configure.ac
> +    AC_MSG_ERROR("$use_ndki_path is not an NDK directory")
Typo ndki vs ndk

2017-08-04 14:15 UTC, Memphiz commented
Not sure what to review exactly - those depends changes are android only or not?

2017-08-04 14:19 UTC, peak3d requested changes

2017-08-04 14:19 UTC, peak3d commented on tools/depends/configure.ac
>      AC_MSG_ERROR("NDK path is required for android")
would more like AC_MSG_ERROR("--with-ndk-path is required for android")

2017-08-04 15:42 UTC, koying commented
@Memphiz Yes, they are *supposed* to be android-only, but as they touch depends, I prefer to ping you ;)

2017-08-04 15:53 UTC, Memphiz commented
Any runtime checks to carry out with this then?

2017-08-04 16:50 UTC, koying commented
@Memphiz Nothing specific. If it builds for ios/osx, it should be ok.
You can do a generic runtime test if you have time, but I guess a nightly post-merge would do.

2017-08-04 17:57 UTC, Rechi requested changes
rename `--with-ndk` to `--with-ndk-path` is missing in docs/README.android and tools/depends/README
samba fix should be moved ahead of default toolchain bump

2017-08-04 18:23 UTC, koying commented
jenkins build this please

2017-08-04 19:55 UTC, koying commented
https://github.com/android-ndk/ndk/issues/480

I think we can close this one. GCC is really getting end-of-life in NDK.
Next step should be to move to LLVM / libc++, really, if possible.

This patch was intended for easier migration to samba 4.5.1, but it seems there is no consensus on it, so bothering with this one becomes rather pointless

2017-08-05 14:55 UTC, MartijnKaijser commented
you could still merge the ndk/sdk split

2017-08-05 18:25 UTC, koying commented
Probably, yes. Will wait to see if it's relevant to clan, though.

The PIL one is definitely something we want, though.
Currently, we build with the native python options (via sysconfig), so it's a semi-miracle it works at all ;)
e.g., from random arm32 jenkins build:
```
/usr/bin/ccache /home/jenkins/android-dev//android-toolchain-arm-21-r14b/bin/arm-linux-androideabi-gcc -DANDROID -fexceptions -fPIC -DPIC -march=armv7-a -mtune=cortex-a9 -mfloat-abi=softfp -mfpu=neon -Og -g -D_DEBUG -I/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21-debug/include/android-21 -isystem /home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21-debug/include -fPIC -fno-strict-aliasing -I/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/x86_64-linux-gnu-native/include -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -DHAVE_LIBJPEG -DHAVE_LIBZ -I/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21-debug/include/freetype2 -I/home/jenkins/workspace/Android-ARM/tools/depends/target/pythonmodule-pil/arm-linux-androideabi-android-21-debug/libImaging -I/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21-debug/include -I/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21-debug/include/python2.7 -I/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/x86_64-linux-gnu-native/include/python2.7 -c _imaging.c -o build/temp.linux-x86_64-2.7/_imaging.o
```

Some of the options (eg `-I/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/x86_64-linux-gnu-native/include`) come from `http://jenkins.kodi.tv/job/Android-ARM/ws/tools/depends/xbmc-depends/x86_64-linux-gnu-native/lib/python2.7/_sysconfigdata.py`

Note the **_x86_64-linux-gnu-native_** ...

2017-08-14 09:06 UTC, Rechi commented
@koying this needs a rebase

2017-08-15 08:29 UTC, koying commented
Abandonned

2017-08-15 08:29 UTC, closed without merging