Fix: check if we have to show simple menu only after we checked if we have a resume point
xbmc/xbmc pull request #12674
Opened 2017-08-14 15:43 UTC by phate89

## Description
Right now we skip bd simplemenu everytime we ask for a resume doesn't matter if there is. This pr changes that. It will skip simplemenu only if there's really a resumepoint set.

## Motivation and Context
Right now when we start "playdisc" builtin we ask to resume and there's a check in bd simplemenu that skips the menu if there's a resume request.
This means if you add a bd and start it with playdisc (from estuary main page for example) you won't ever get the bd simplemenu even if you set it and it will start to play directly the bluray. It's a problem that already exists in krypton but in leia it will even be worse because instead of loading the default playlist it will try to load the bd menu with different results (not all bd menus works great)

## How Has This Been Tested?
I tested with a couple of bluray and with resume points

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2017-08-14 19:20 UTC, stefansaraev commented
system/lcms2.dll should not be part of this pr :)

2017-08-14 20:26 UTC, phate89 commented
mm it keeps popping up everytime not sure why.. Fixed it :)

2017-08-15 07:51 UTC, ace20022 requested changes

2017-08-15 14:43 UTC, phate89 commented on xbmc/Application.cpp
> +  }
mm locally was fine.. anyway fixed it!

2017-08-15 14:53 UTC, ace20022 approved these changes

2017-08-15 14:54 UTC, ace20022 commented
Looks, good. Thanks for the pr!

2017-08-15 15:18 UTC, phate89 commented
Do you think it's worth it to backport to krypton?

2017-08-16 05:28 UTC, ace20022 commented
I don't have time to test it, but I trust you that it works in all cases. Therefore +1 for a backport.

2017-08-16 20:57 UTC, merged