Use our api to set info on python scrapers
xbmc/xbmc pull request #12857
Opened 2017-09-30 09:34 UTC by phate89

This is a splitup from https://github.com/xbmc/xbmc/pull/12661
I replaced the use of properties with our functions we already use to set info in plugins.
I also added nfo url support that @notspiff original implementation was missing.
I'm not sure if it's worth it in music part since there are only few functions available.
@ronie @DaveTBlake any opinion?

## Motivation and Context
We can use functions we are more familiar with.

## How Has This Been Tested?
Tested with my themoviedb python scraper

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2017-09-30 11:37 UTC, DaveTBlake commented
>I'm not sure if it's worth it in music part since there are only few functions available.

TBH I'm not sure it helps either. For music scraping from NFO, or online, is about getting additional data, hence most of it does not have an equivalent field in CMusicInfoTag. When there is more data to scrape (e.g. I hope to add gender, type and disambiguation to artist) it won't get added to CMusicInfoTag. 

The demo album and artist scrapers are also not how music scraping will work (I have worked on the scrapers you started @ronie but got distracted).

So thank you for considering music @phate89 but I would probably drop that part of it.

2017-10-06 00:02 UTC, rmrector requested changes
Ohh, these Python scrapers are looking wonderful.

There are a couple of small changes needed, and a suggestion to smooth out a part of the API for artwork.

2017-10-06 00:02 UTC, rmrector commented on addons/metadata.demo.tv/demo.py
> +        liz.addAvailableThumb('DefaultBackFanart.png', '1.78')
Like the TV show itself above, the second parameter to `addAvailableThumb` should be an art type, generally 'thumb', or could even something wild like 'clearlogo'.

2017-12-17 07:41 UTC, MartijnKaijser commented
@phate89 @notspiff can we throw this one in and start testing?

2017-12-31 12:06 UTC, jenkins4kodi commented
@phate89 this needs a rebase

2018-01-24 17:59 UTC, phate89 commented on addons/metadata.demo.movies/demo.py
>  elif action == 'getartwork':
The names are the same we use in the xml scraper.. That's probably the reason spiff used those..

2018-01-24 18:05 UTC, phate89 commented
thanks @rmrector for the review..I fixed a couple of your points..
About naming I agree with your naming considerations but the problem is that it's all implemented like it was for xml scraper. addAvailableThumb and setAvailableFanart are really different and they are implemented very differently in kodi core so I preferred not to touch anything and replicate them on python

2018-02-06 22:01 UTC, rmrector commented on addons/metadata.demo.tv/demo.py
> +        liz.addAvailableThumb('DefaultBackFanart.png', '1.78')
The aspect in the line above and below still need adjusted, but otherwise this PR looks good.

2018-02-24 17:01 UTC, phate89 commented
I rebased and renamed some argument like @rmrector suggested. It should be good to go

2018-02-24 20:57 UTC, rmrector commented
Looks good, and I definitely appreciate that you were able to rename that guy. Thanks!

2018-03-12 19:44 UTC, anthonyryan1 commented
I just thought I'd throw out a vote of support for this. I just finished writing a python scraper (not yet published) and this is a significant improvement.

2018-03-12 21:18 UTC, merged