[cmake][windows] avoid linkage against libkodi
xbmc/xbmc pull request #12970
Opened 2017-10-28 15:32 UTC by AchimTuran

My local Windows failed because Visual Studio tried to link against the target libkodi, which is not present for Windows.

2017-10-28 15:32 UTC, AchimTuran commented
jenkins build this please

2017-10-28 16:34 UTC, Paxxi commented
@Rechi is the current champ of cmake on Windows so I think he should have final say.

I haven't seen this cause any issues so to me this feels like a solution to an old/dirty/broken workspace rather than something that should be changed in cmake.

2017-10-28 16:38 UTC, AchimTuran commented
I did a clean build and tried to rebuild. During linking a got the same error.

2017-10-28 17:55 UTC, Paxxi commented
try to wipe the workspace and do a fresh clone or `git clean -xfd && git clean -Xfd` and download deps and such again

2017-10-29 09:10 UTC, notspiff commented
Windows doesnt do the lib prefix. Just link to the target and not the accidentially working lib prefixed target name.

2017-10-29 10:06 UTC, AchimTuran commented
@paxxi same issue with a fresh cloned repository.

2017-10-29 11:03 UTC, Rechi requested changes
I don't know what happened on your system, but that can't work.
The xbmc target you see in Visual Studio is internally called `lib${APP_NAME_LC}` and it has for sure to be linked against `${APP_NAME_LC}`.

2017-10-29 13:00 UTC, AchimTuran commented
Thank you guys for helping to repair my Windows build. The issue was that CMake took the wrong Windows SDK...
You can set the Toolset Version with the following cmake call:
`cmake -G"Visual Studio 14 Win64" -DCMAKE_SYSTEM_VERSION="<specific Windows SDK version>"`

2017-10-29 13:00 UTC, AchimTuran commented
Sorry the PR isn't correct and will never work, which is the reason I will close it now.

2017-10-29 13:00 UTC, closed without merging

2017-10-29 13:43 UTC, Montellese commented
Having to specify the Windows SDK version manually sucks. On my Win7 machine it picks up 8.1 by default. Is there any way we can support both the 8.1 and the 10 version with some ifdefery?

2017-10-29 14:12 UTC, Rechi commented
run cmake with `-DCMAKE_SYSTEM_VERSION="10.0.xxxxx.0"` (`xxxxx` is the SDK 10 version you have installed)

2017-10-29 14:13 UTC, Montellese commented
@Rechi I realize that but it's cumbersome because I have to change it when(ever) I update the SDK

2017-10-29 14:17 UTC, Rechi commented
maybe it is possible to specify a more general version number (`10.0`), but I don't know

2017-10-29 20:45 UTC, Paxxi commented
Never had to specify an sdk version except for building uwp, cmake have automatically picked the newest available. Curious what's different on your systems.

2017-10-29 21:01 UTC, AchimTuran commented
Yes that's super strange. On my machine it always uses the oldest one...