[Music]Information Provider dialog
xbmc/xbmc pull request #12987
Opened 2017-11-01 10:30 UTC by DaveTBlake

Add a new dialog for selection of both artist and album scraper addons, and their settings.

![Information Provider  Dialog](https://i.imgur.com/UUHt7ZW.jpg)

The workflow when adding a music source is improved by making the default music scraper settings readily available, from a "settings" button on the "Add to library" prompt.  This way it avoids cluttering the UI or adding unnecessary complexity for beginners. 

![Add To Library prompt](https://i.imgur.com/yDktiRU.jpg)

Previously if a user wanted to change the music scraping settings (that scanning was about to use) they had to leave the music library, go to System>Media>Music to pick scrapers and then to each addon separately to change any settings. There are few scrapers to choose from, and settings are generally static but much better to be able to do this from where you are adding a music source.

The same dialog is also used to provide the UI for the facility to change information provider for artists and albums separately. This replaces the ugly sub-menu added by #12597 with a select list on the dialog itself.

This is based on a standard dialog so no skin changes needed.
I have had an early test build up and had positive feedback from @karellen and @jjd-uk

2017-11-01 11:05 UTC, jjd-uk approved these changes
+1 Having tested this it's IMHO it's a big improvement to the workflow for adding music to DB. The old way was a right pain in the arse if anything needed changing.

Can't comment on the actual code however.

2017-11-01 11:08 UTC, zag2me commented
This is a nice UI improvement! definitely +1

And I thought you were a database guy... :)

2017-11-01 11:17 UTC, Rechi commented on xbmc/music/windows/GUIWindowMusicNav.cpp
> +    bool result;
variable is sometimes used uninitialized

2017-11-02 13:40 UTC, notspiff requested changes
Just a couple of knee-jerks. The lesson I learn here is that if you just put off things like this for approximately 10 years, somebody eventually cleans up your mess! :D

2017-11-02 13:40 UTC, notspiff commented on xbmc/music/dialogs/GUIDialogInfoProviderSettings.cpp
> +#include "GUIDialogInfoProviderSettings.h"
please include first to avoid potential lacking includes in header.

2017-11-02 13:40 UTC, notspiff commented on xbmc/music/dialogs/GUIDialogInfoProviderSettings.cpp
> +  if (setting == NULL)
nullptr

2017-11-02 13:40 UTC, notspiff commented on xbmc/music/dialogs/GUIDialogInfoProviderSettings.cpp
> +  if (setting == NULL)
nullptr

2017-11-03 08:45 UTC, DaveTBlake commented
Thanks for code review @notspiff. I tend to copy exitsting code, and as styles evolve that is not always a good thing.

2017-11-03 09:01 UTC, notspiff approved these changes

2017-11-04 07:37 UTC, merged