Webserver: HTTPS support
xbmc/xbmc pull request #13165
Opened 2017-12-10 21:00 UTC by wsnipex

Enable HTTPS support in our webserver if available.

## Description

This is kept rather simple, so at least for now there is no gui setting to select certificate and key files.
Instead the user is required to create special://userdata/server.key and special://userdata/server.pem.
Cert creation could be handled in an addon.

## Motivation and Context

Security is always good

## How Has This Been Tested?

used the chorus webinterface via https on ubuntu linux.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Improvement (non-breaking change which improves existing functionality)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

suggestions for a better help text are very welcome ;)

2017-12-10 21:13 UTC, lrusak commented
What about making this mandatory? Can we create certs if they don't exist? It would be nice to avoid adding another setting 😁

2017-12-10 21:42 UTC, Montellese commented
I had this running years ago (see https://github.com/Montellese/xbmc/commits/webserver_https) but back then linux was an old version of microhttpd which didn't support HTTPS yet and it required a special build for win32. These days we can easily get this working on linux but AFAIK (at least a few months ago) the windows version doesn't support SSL/HTTPS.

If you want to support it on at least non-win32 platforms you should adjust the setting so that it is only available if microhttpd supports SSL/HTTPS.

2017-12-11 03:34 UTC, chewitt commented
Making HTTPS mandatory requires self-signed certs to be created, which will result in all users seeing untrusted cert warning messages in their browser, which many will consider to be a step backwards for OOB useability. Services like letsencrypt that provide free trusted certs must be able to query the webserver through public FQDN during cert creation so they are not an option (and exposing Kodi to the internet should be discouraged). Creating self-signed certs also needs an option to set the hostname (cn) attribute and some basic cert management, i.e. regenerate after changing cn, which will add settings clutter. IMHO it's best to support this via as.xml as a first step until we learn what that issues are. GUI can always be added in a later release.

2017-12-11 08:46 UTC, wsnipex commented
re windows: I would have hoped someone was willing to build microhttpd with gnutls support, depends platforms already do that

I really think kodi core should not try to create certificates in any way. If we want to make it easier for users, lets do it in an addon.

2017-12-11 13:29 UTC, Montellese commented
@wsnipex back when I first looked into this I actually built a version of microhttpd with gnutls support using MinGW. Since then @Karlson2k has migrated this to a pure Visual Studio based build which didn't support any kind of SSL / HTTPS last time I checked. Integrating gnutls there will probably be very tricky and require quite some changes to microhttpd itself :-/

2017-12-14 10:41 UTC, notspiff requested changes
looks good apart from the minors

2017-12-14 10:41 UTC, notspiff commented on xbmc/network/WebServer.cpp
> +    std::string keyPem(buf.get(), buf.length());
skey.resize(buf.length());
skey.assign(buf.get());

2017-12-14 10:41 UTC, notspiff commented on xbmc/network/WebServer.cpp
> +    std::string certPem(buf.get(), buf.length());
as above

2017-12-14 10:41 UTC, notspiff commented on xbmc/network/WebServer.cpp
> +  if (skey.size() > 0 && scert.size() > 0)
!skey.empty() && !scert.empty()

2017-12-14 10:41 UTC, notspiff commented on xbmc/network/WebServer.cpp
> +  if (LoadCert(m_key, m_cert) && MHD_is_feature_supported(MHD_FEATURE_SSL) == MHD_YES)
reverse if, no need to load cert if not supported.

2017-12-14 10:41 UTC, notspiff commented on xbmc/network/WebServer.cpp
> +                          NULL,
nullptr

2017-12-14 11:42 UTC, wsnipex commented
thanks, fixed the minors

2017-12-14 11:42 UTC, notspiff commented
afaict you missed the if reversal

2017-12-14 11:46 UTC, wsnipex commented
imho it was already in the 2nd commit from the beginning. If that's not what you mean, then I don't get it

2017-12-14 11:46 UTC, notspiff commented
ah yes. you are right, it is rewritten in second commit.

2017-12-14 11:46 UTC, notspiff approved these changes

2017-12-15 14:58 UTC, afedchin commented
> re windows: I would have hoped someone was willing to build microhttpd with gnutls support, depends platforms already do that

why not use openssl? leave gnutls for GNU systems.

2017-12-15 19:19 UTC, Montellese commented
> why not use openssl? leave gnutls for GNU systems.
because microhttpd only has built-in support for gnutls so you would have to write the openssl integration from scratch and someone manage to support both gnutls and openssl.

2017-12-15 19:47 UTC, afedchin commented
I'll live without https then :)

2017-12-17 06:21 UTC, MartijnKaijser commented
@karlson2k what's your take on this?

2017-12-19 11:12 UTC, wsnipex commented
can someone please test that this doesn't break on windows? The option should be hidden.

2017-12-19 11:27 UTC, Rechi approved these changes
setting doesn't show up on Windows
code also looks good

2017-12-19 23:57 UTC, rmrector commented
I have to suggest this not be added to the GUI. I agree that "exposing Kodi to the internet should be discouraged", but a setting in the GUI to enable SSL (secure communication) for the web server will encourage some users to do just that. Packed away in an advancedsetting, it could be accompanied with a wiki entry that clearly states it's not for external use, and can link to a couple of better options if remote access is needed.

I don't think it's all that useful on many networks that Kodi will be a part of, but if "not for external use" is made more clear then we are good. It should already be separated from a guest network or other public traffic if SMB/NFS, UPNP, or other mildly protected traffic is used.

2017-12-21 11:20 UTC, wsnipex commented
simply enabling this setting is not enough, it requires some knowledge from the user to provide the cert.
And I strongly disagree that not having SSL support is better.

2017-12-22 02:49 UTC, rmrector commented
I guess I'm concerned with the conflation of the SSL "security" provided when a standard user blindly follows the steps to create a cert and leave it unprotected in userdata (for this web server bolted on to an application that is meant for something else entirely) vs the real security that real web servers provide.

Encouraging standard users to click through the big red warnings that browsers present is bad. Not just for usability, but for their security on the internet everywhere, because they don't care about the details and will take that encouragement to other websites.

2017-12-22 09:04 UTC, wsnipex commented
If you have any suggestion on how to improve then let's hear it, but I don't buy the "no security is better" argument.

2018-01-05 12:23 UTC, wsnipex commented
jenkins build this please

2018-01-06 08:06 UTC, merged