sql-client: add support for mariadb-client
xbmc/xbmc pull request #13318
Opened 2018-01-06 00:20 UTC by InuSasha

make it possible to link against mariadb-client instead of mysql

## Description
Search explicit for libmariadb and mysql-header under include/mariadb/.
Additional added a test, to protect against using of mysql & mariadb at the same time 

## Motivation and Context
most distributions switch to mariadb, this follows up.

## How Has This Been Tested?
tested on top of LibreELEC master with MariaDB 10.2 and MySQL 5.7 as sql-server.
test-cases: 
 - database migration from Video108 -> Video109
 - database migration from Music66 -> Music69
 - list movies
 - mark movie as seen

reallife test on top of KRYTON (LE 8.2.2), is started.

## Screenshots (if appropriate):

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2018-01-06 08:51 UTC, Rechi commented
@wsnipex do we want to split MySqlClient and MariaDBClient in two different cmake modules or should they just be handled by a single one?

2018-01-06 08:51 UTC, Rechi commented on xbmc/dbwrappers/mysqldataset.cpp
> +#ifdef HAS_MARIADB
`#elif defined(HAS_MARIADB)`

2018-01-06 08:51 UTC, Rechi commented on xbmc/dbwrappers/mysqldataset.h
> +#ifdef HAS_MARIADB
`#elif defined(HAS_MARIADB)`

2018-01-06 08:51 UTC, Rechi commented on xbmc/dbwrappers/mysqldataset.cpp
> +#include "mariadb/errmsg.h"
`#include <mariadb/errmsg.h>`

2018-01-06 08:51 UTC, Rechi commented on xbmc/dbwrappers/mysqldataset.h
> +#include "mariadb/mysql.h"
`#include <mariadb/mysql.h>`

2018-01-06 09:09 UTC, Paxxi commented
Is it worth keeping mysql at all? The more they diverge the more issues we'll start seeing so might as well drop mysql if the platforms we support have mariadb

2018-01-06 09:16 UTC, wsnipex commented
We should probably prefer mariadb over mysql and use maria if both are found in auto mode(ENABLE_MYSQL != ON).
Otherwise looks good.

@paxxi: supporting both shouldn't really cause any overhead for now, so I'd postpone dropping mysql to v19.

2018-01-06 09:19 UTC, Paxxi commented
Sounds good to me

2018-01-06 12:18 UTC, InuSasha commented
ok, will prefer mariadb over mysql, when auto detect.
abort when both are explicit enabled.
when one is explicit enabled, ignore the other.
right?

2018-01-06 15:33 UTC, InuSasha commented
implement the suggestions

2018-01-07 07:40 UTC, wsnipex approved these changes
thanks

2018-01-07 09:51 UTC, Rechi requested changes

2018-01-07 09:51 UTC, Rechi commented on CMakeLists.txt
> +endif()
This logic has to be adjusted.
If you don't disable any of them at the second cmake run this error message shows up, which shouldn't happen.

2018-01-08 18:55 UTC, InuSasha commented
@Rechi switch to check the MYSQL/MARIADBCLIENT_FOUND. With the ENABLE it is $&%$!
But when you change the client, you have to clean your build path (drop the cached variables).

2018-01-10 08:25 UTC, the-dreamer commented
Will this commit solve the issue that streamdetails is not saved to sql db anymore? it is working when sqlite (local db) is used so there is something wrong on the mysql site. The debug log showed that it is not saved when using mysql by not calling streamdetails function. 

I use myself a mariadb server and only streamdetails is not saved. Watchstates, resume points etc. are saved.

2018-01-10 09:27 UTC, InuSasha commented
@the-dreamer: simple answer, no

2018-01-10 16:10 UTC, jenkins4kodi commented
@InuSasha this needs a rebase

2018-01-12 10:54 UTC, InuSasha commented
after one week as backport on Krypton (LE 8.2.2) all is working fine.
Good to go.

The failed jenkins-build, was a jenkins problem, not a code problem... (maybe i pushed a second rebase, to fast)

2018-01-12 12:59 UTC, Rechi commented
With current code mysql is  the preferred one in autodetection mode instead of mariadb.
Commits need squashing.
The jenkins failure isn't caused by code changes.

2018-01-12 13:25 UTC, InuSasha commented
@Rechi sure, about the preferred?
I tested it, and maria was selected.
When there was an earlier run of cmake (with mysql used), this was cached. In this case, you must clean your build path. Sorry i do not have any solution for it, now.

2018-01-13 09:49 UTC, Rechi commented
Sorry only read the code changes and thought of a case which isn't handled correctly, but tested it now and it works as expected.
Commits still should be squashed.

@wsnipex any comment?

2018-01-13 10:26 UTC, Rechi commented
@InuSasha I found an easier way to handle mariadb and mysq in CMakeLists.txt which also allows changing the client without deleting the cmake build files.

```--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -148,9 +148,9 @@
                   CCache
                   DBus
                   LCMS2
+                  MariaDBClient
                   MDNS
                   MicroHttpd
-                  MySqlClient
                   PulseAudio
                   Python
                   SmbClient
@@ -160,6 +160,10 @@
                   XSLT
                   ${PLATFORM_OPTIONAL_DEPS})
 
+if(NOT MARIADBCLIENT_FOUND)
+  core_optional_dep(MySqlClient)
+endif()
+
 # Required, dyloaded deps. Keep in alphabetical order please
 set(required_dyload ASS
                     Curl)
```

2018-01-13 12:01 UTC, InuSasha commented
@Rechi your solution does not work in case of selecting mysql (only `-DENABLE_MYSQLCLIENT=ON` is set). In this case mariadb is selected, automatically.

2018-01-13 14:56 UTC, Rechi commented
Actually IMO maridb should always be the preferred one, unless you explicitly disable it.

2018-01-13 14:59 UTC, InuSasha commented
or the mysql is enabled explicit. Other way, it is very confusing, for builders.

2018-01-28 17:53 UTC, InuSasha commented
@Rechi: switched to your suggestion. I am no fully agreed with it, but implemented is better the perfect :).

2018-01-30 08:25 UTC, wsnipex commented
Sadly, it's not as simple. You have to consider the user force enabling either mariadb or mysql, which makes it much more complicated.
I'm wondering if having only one mariadb find module, which also checks for mysql libs/includes, might be better. Thoughts?

2018-01-30 08:28 UTC, Rechi commented
@wsnipex you don't like my version where you have to explicitly disable mariadb (if it is installed) to get mysql?

2018-01-30 08:54 UTC, wsnipex commented
not especially, because it's unintuitive and inconsistent with other options.
Also, what about distros that ship mariadb, but with _only_ the mysql compatibility libs (redhat/centos does that for example)

2018-01-30 08:57 UTC, Rechi commented
If mariadb is not found it will check for mysql, so redhat/centos will still work if they did before.

2018-01-30 09:26 UTC, wsnipex commented
imho it is confusing and unintuitive if you have mariadb installed but -DENABLE_MARIADBCLIENT=ON fails. Granted that will only happen for distros that have dubious packaging..
It would be nice if we'd fall back to mysql in this scenario as well.

2018-01-30 16:11 UTC, Rechi commented
@InuSasha @wsnipex and I agreed on the following solution
```--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -152,5 +152,4 @@
                   MDNS
                   MicroHttpd
-                  MySqlClient
                   PulseAudio
                   Python
@@ -180,4 +179,15 @@
 core_optional_dyload_dep(${dyload_optional})
 
+if(ENABLE_MARIADBCLIENT AND NOT ENABLE_MARIADBCLIENT STREQUAL AUTO AND ENABLE_MYSQLCLIENT AND NOT ENABLE_MYSQLCLIENT STREQUAL AUTO)
+  MESSAGE(FATAL_ERROR "You can not use MySql and MariaDB at the same time. Disable one by adding -DENABLE_MYSQLCLIENT=OFF or -DENABLE_MARIADBCLIENT=OFF.")
+elseif(ENABLE_MYSQLCLIENT AND NOT ENABLE_MYSQLCLIENT STREQUAL AUTO)
+  set(ENABLE_MARIADBCLIENT OFF)
+endif()
+
+core_optional_dep(MariaDBClient)
+if(NOT MARIADBCLIENT_FOUND)
+  core_optional_dep(MySqlClient)
+endif()
+
 if(NOT UDEV_FOUND)
   core_optional_dep(LibUSB)
```
Please update the PR with this and squash it into a single commit.

2018-01-30 18:48 UTC, Rechi commented
`core_optional_dep` should have handled that already

2018-01-30 18:55 UTC, InuSasha commented
not in my test. i do not know why... 

```
root@kodi:/home/inu/kodi/mariadb.build# rm -rf *; cmake ../mariadb -DENABLE_MYSQLCLIENT=ON
-- The CXX compiler identification is GNU 7.2.0
...
-- Found MariaDBClient: /usr/lib/x86_64-linux-gnu/libmariadbclient.a (found version "10.2.7")
...
-- MARIADBCLIENT enabled: Yes
...
```

2018-01-31 09:24 UTC, Rechi commented
jenkins build this please

2018-01-31 09:27 UTC, wsnipex commented on CMakeLists.txt
> +if(NOT ENABLE_MARIADBCLIENT STREQUAL OFF)
this is not a proper way to test this. ENABLE_MARIADBCLIENT=1 is also be boolean ON, or any string or number for that matter.

2018-01-31 09:28 UTC, Rechi commented on CMakeLists.txt
> +  set(ENABLE_MARIADBCLIENT OFF)
this has to be an option that you do not need the ENABLE_MARIADBCLIENT check below

2018-01-31 18:10 UTC, InuSasha commented
@Rechi @wsnipex found it :), we have to cache it
```
-  set(ENABLE_MARIADBCLIENT OFF)
+  set(ENABLE_MARIADBCLIENT OFF CACHE BOOL "")
```
dropped my extra check, too

2018-02-05 08:53 UTC, merged

2018-02-05 08:53 UTC, wsnipex commented
thanks for the patience!

2018-02-15 21:31 UTC, HeresJonny commented
Since Milhouse #205 and adamg 8.90.4, this patch was added. Unfortunately, the change now prevents Kodi from starting up (on both builds). The log error is:

21:31:09.745 T:139727820420864   ERROR: SQL: [MyMusic70] An unknown error occurred
                                            Query: SELECT idVersion FROM version
21:31:09.795 T:139727820420864   ERROR: Process error processing job

2018-02-15 21:53 UTC, MilhouseVH commented
> Unfortunately, the change now prevents Kodi from starting up (on both builds)

Are you sure that this "prevents Kodi from starting up" - missing databases don't usually prevent Kodi from starting. Is Kodi now crashing?

The reason your MyMusic70 database has no version is because the migration from your previous MyMusicXX failed - can you enable debug logging, drop MyMusic70 and restart Kodi so that the MyMusicXX migration is attempted once more, then upload the resulting Kodi log to a pastebin site and paste the link.

2018-02-15 22:33 UTC, HeresJonny commented
I dropped MyMusic69. MyMusic70 was created from scratch by scraping.
https://pastebin.com/A9Lm99ws

2018-02-16 05:13 UTC, MilhouseVH commented
> I dropped MyMusic69. MyMusic70 was created from scratch by scraping.
> https://pastebin.com/y6MUKZhu

Did you post the wrong log? Your log shows s a version of Kodi from 25 Dec 2017, so presumably LibreELEC is of the same vintage in which case it doesn't include MariaDB support. The log also doesn't create a MyMusic70 database, in fact it doesn't create any database - it does however find and use an existing MyMusic69 database.

Let's move the conversation to [the forum](https://forum.kodi.tv/showthread.php?tid=298462) - until we know what is wrong this is just noise.

2018-02-16 09:45 UTC, MilhouseVH commented
Update from forum: https://forum.kodi.tv/showthread.php?tid=298462&pid=2704269#pid2704269

This MyMusic70 problem may be caused by the mariadb-connector-c having some sort of incompatibility with MySQL when query cache is enabled (query cache is disabled by default in more recent versions of MySQL Server so maybe not a long-term issue).

2018-02-16 10:18 UTC, InuSasha commented
Solution is to set SET SESSION query_cache_type = OFF; per connection for build against MariaDB client and used MySQL-DB