DVDVideoCodecAmlogic: fix stereoscopic playback
xbmc/xbmc pull request #13395
Opened 2018-01-19 23:29 UTC by afl1

After [#12799](https://github.com/xbmc/xbmc/pull/12799) Stereoscopic manager is unable set stereoscopic mode. Stereoscopic manager inform by PLAYBACK_STARTED message at opening stream.  Attempt to set 3D mode fails as the Amlogic decoder is open after demuxing first video frame.

## Description
At open amlogic decoder DVDVideoCodecAmlogic send GUI_MSG_PLAYBACK_STARTED to ask Stereoscpic manager for action in right moment. 

## Motivation and Context
It's most likely broken 3D mode for other devices.  This PR fixed 3D mode only for Amlogic HW decoding.

## How Has This Been Tested?
It was tested in Amlogic S905/S912 community builds.

2018-01-20 09:21 UTC, da-anda commented
I'm sorry, but this is not the correct fix. I'm aware of the issue but didn't have the time yet to implement the proper fix. The correct way IMO would be to rename the "onPlaybackStarted" method of StereoscopicsManager to "onStreamChange" and call it from https://github.com/xbmc/xbmc/blob/master/xbmc/Application.cpp#L3426 instead. This should ensure that the according logic is triggered when all required info from the decoders is available. Could you give this a try please?

2018-01-20 22:15 UTC, afl1 commented
I rebuild fix under @da-anda recommendations. It looks like it fixed stereoscopic playback commonly for all platforms.

2018-01-21 09:17 UTC, da-anda requested changes
apart from the minor, looks good from my end. Thanks.

2018-01-21 09:17 UTC, da-anda commented on xbmc/guilib/StereoscopicsManager.cpp
> -    OnPlaybackStarted();
mind removing that "case" altogether? Doesn't make much sense to keep it

2018-01-21 12:29 UTC, afl1 commented
I replaced case with if.

2018-01-21 13:02 UTC, da-anda approved these changes

2018-01-21 13:20 UTC, da-anda commented
thanks

@FernetMenta do you see any possible deadlock/threading issues with current approach, or should the StereoscopicsManager be triggered via AppMessenger (or whatever fits for this purpose)? IIRC StereoscopicsManager needs to be triggered from GUI thread, but I could be wrong. It's interacting with:

- GUI, as it can show a select dialog to pick the desired playback mode
- calls `CServiceBroker::GetRenderSystem().SupportsStereo()`
- calls `g_graphicsContext.GetStereoMode();` and `g_graphicsContext.SetStereoMode();`
- calls `g_application.GetAppPlayer().GetVideoStreamInfo(CURRENT_STREAM, videoInfo);` to detect current stereo mode of playing video

thanks.

2018-01-21 14:14 UTC, Rechi commented on xbmc/guilib/StereoscopicsManager.cpp
> +  if ((message.GetMessage() == GUI_MSG_PLAYBACK_STOPPED) || (message.GetMessage() == GUI_MSG_PLAYLISTPLAYER_STOPPED))
no need for the extra brackets around the two equality checks

2018-01-21 17:34 UTC, FernetMenta commented
@da-anda I see no reason why this should run on the gui thred. btw: calling g_application.GetAppPlayer().GetVideoStreamInfo is wrong. see my pr that introduced the new callback.

2018-01-21 17:49 UTC, da-anda commented
@FernetMenta ok, thanks. I only recall threading issues when I implemented builtin actions for 3D stuff. That's why I'm more than cautios now in this regard. And since I'm not a C++ dev I better ask :)

if `g_application.GetAppPlayer().GetVideoStreamInfo()` is still working, I'd delay the proper fix for this to a followup PR, unless @afl1 is willing to also address this

2018-01-21 18:00 UTC, da-anda commented
@afl1 in case you'd like to address the GetVideoStream issue Fernet mentioned, I think you can replace it with `CServiceBroker::GetDataCacheCore().GetVideoStereoMode()`. Might need some additional adjustments (like incluing the CServiceBroker header). Since I don't have a dev env atm, I can only give pointers.

2018-01-21 19:03 UTC, FernetMenta commented
> if g_application.GetAppPlayer().GetVideoStreamInfo() is still working,

it may work by chance and is not reliable. GetVideoStreamInfo provides info for user dialog stream selection. this is not updated at any time later

2018-01-22 21:40 UTC, closed without merging

2018-01-23 08:20 UTC, da-anda commented
@afl1 may I ask why you closed the PR? Is it because of me asking if you'd like to also address the change Fernet mentioned? If it wasn't clear, you didn't have to do it. I just asked if you also wanted to give it a go. If you said no, I would have merged your PR as is.

Are you ok with reopening and merging this PR as is?