[GLES] updates and cleanup
xbmc/xbmc pull request #13406
Opened 2018-01-20 20:16 UTC by lrusak

Mostly taken from the GL changes. Tested on Intel NUC

`glEnable(GL_TEXTURE_2D)` was never needed and was most likely around since the original GL -> GLES port. See, https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glEnable.xml

@FernetMenta with this I think we can get rid of the NV12_RRG shader format

2018-01-21 08:40 UTC, FernetMenta approved these changes
looks ok but should be runtime tested.

2018-01-21 08:43 UTC, FernetMenta commented on system/shaders/yuv2rgb_basic.glsl
> +#elif defined(XBMC_NV12)
I doubt that this path works for sw decoding. gles uses still LUMINANCE and ALPHA_LUMINANCE textures

2018-01-21 08:45 UTC, FernetMenta requested changes
see comment. I think sw path for nv12 is broken with this

2018-01-22 08:55 UTC, lrusak commented
If the last commits don't build then I'll just drop the nv12 changes

2018-01-22 09:03 UTC, lrusak commented
jenkins build this please

2018-01-23 02:44 UTC, lrusak commented
unfortunately it doesn't work. I'll drop the relevant commits
```
18:37:06.402 T:139729138547072   ERROR: glFormatElementByteCount - Unknown format 6403
18:37:06.403 T:139729138547072   ERROR: glFormatElementByteCount - Unknown format 33319
```

2018-01-23 02:45 UTC, lrusak commented
jenkins build this please

2018-01-23 04:11 UTC, lrusak commented
osx build failure unrelated

2018-01-25 06:33 UTC, lrusak commented
ok to go?

2018-01-25 09:56 UTC, FernetMenta commented
I think so

2018-01-25 20:31 UTC, merged