A mass change from http://xbmc.org to http://kodi.tv.
xbmc/xbmc pull request #13422
Opened 2018-01-24 00:38 UTC by kekePower

Change http://xbmc.org to http://kodi.tv

## Description
I used the command
grep --include={\*.cpp,\*.h} -rnl './' -e "http://xbmc.org" | xargs -i@ sed -i 's/http\:\/\/xbmc\.org/http\:\/\/kodi\.tv/g' @
to change every http://xbmc.org to http://kodi.tv in *.cpp and *.h files

## Motivation and Context
I read in a PR once that it was a wish to switch all references to xbmc.org over to kodi.tv.
When I found a great grep/sed command that did the trick in one go, I decided I wanted to give it a try.

A lot of files has been touched, so if you want to reject this PR, I'm fine with it.

## How Has This Been Tested?
No need to test as this only touches references to http://xbmc.org.

## Screenshots (if appropriate):

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2018-01-24 08:40 UTC, notspiff requested changes
RPC change is hard, the others i realize are not your doing but if cba to address them while at it, you get an extra cookie.

2018-01-24 08:40 UTC, notspiff commented on tools/depends/native/JsonSchemaBuilder/src/JsonSchemaBuilder.cpp
> +  out << "  const char* const JSONRPC_SERVICE_ID          = \"http://kodi.tv/jsonrpc/ServiceDescription.json\";" << endl;
remove this change please. affects RPC, needs to verify it won't break things and don't want to apply brain in this pr. you can open a separate pr for it if you cba

2018-01-24 08:40 UTC, notspiff commented on xbmc/platform/Filesystem.h
> +*      http://kodi.tv
a windows eol snuck in.

2018-01-24 08:40 UTC, notspiff commented on xbmc/platform/win32/Filesystem.cpp
> + *      http://kodi.tv
windows eol (nope, not okay in windows files either).

2018-01-24 08:40 UTC, notspiff commented on xbmc/utils/Literals.h
> + *      http://kodi.tv
windows eol

2018-01-24 09:16 UTC, kekePower commented
@notspiff 
I do like cookies :-)

2018-01-24 09:45 UTC, notspiff commented
now to get sugar coating; you should put the json part of the second commit into the first. you know your way around git squashery ?

2018-01-24 10:01 UTC, kekePower commented
@notspiff 
Do you want only the json part or is it OK to sqash the whole second commit?

2018-01-24 10:10 UTC, Rechi commented
wait for #13427 getting merged and then rebase onto master again (and squash to a single commit)

2018-01-24 10:12 UTC, kekePower commented
@Rechi Ok, will wait.

2018-01-24 12:11 UTC, jenkins4kodi commented
@kekePower this needs a rebase

2018-01-24 12:13 UTC, kekePower commented
@notspiff 
No, I guess I really don't know anything about git squash even though I tried to read up on it.

2018-01-24 12:14 UTC, notspiff commented
okay, then i will handle that part. no worries.

2018-01-24 12:16 UTC, kekePower commented
@notspiff Tusen takk :-)

2018-01-24 12:27 UTC, notspiff commented
bare hyggelig.

pushed manually in rebased  form. thanks for your contribution!

2018-01-24 12:27 UTC, closed without merging

2018-01-25 08:28 UTC, da-anda commented
while at it, I guess we should also replace `Team XBMC` with `Team Kodi` :)