Add OnResume, OnAVChange and OnAVStart to jsonRPC notifications
xbmc/xbmc pull request #13726
Opened 2018-04-02 16:00 UTC by Razzeee

## Description
As we did for the python interface I added OnAVChange and OnAVStart and took the liberty to also add OnResume. Which will hopefully offer richer messaging and be easier to handle. Be aware that OnPlay will only be called at start now and not when resuming.
Not 100% sure about the version increase. (as always)

## Motivation and Context

Adds the new events to the jsonRPC and untangled OnPlay useage a bit.

## How Has This Been Tested?

Tested locally on windows 10. See screenshot.

## Screenshots (if appropriate):
![grafik](https://user-images.githubusercontent.com/5943908/38203277-f96b1e5e-369e-11e8-8451-f7f6cfe358f4.png)

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [X] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

2018-04-02 16:20 UTC, FernetMenta commented
thank you very much!

2018-04-02 17:03 UTC, afedchin requested changes
breaks current functionality

2018-04-02 17:03 UTC, afedchin commented on xbmc/Application.cpp
> +  CAnnouncementManager::GetInstance().Announce(Player, "xbmc", "OnResume", m_itemCurrentFile, param);
please add handling new event here please https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/win10/WinEventsWin10.cpp#L618

2018-04-02 17:37 UTC, Razzeee commented
## Learning
If you cmake for one platform Visual Studio will only search those files. So you will have to grep. I recommend ripgrep for that https://github.com/BurntSushi/ripgrep

## This got a whole lot more complicated 😄 
I will have to check if android is still fine with these changes as I decided to call the `onResume` method included in the main android file. Otherwise I only replicate old behavior.

2018-04-02 17:40 UTC, Razzeee commented on xbmc/Application.cpp
> +  CAnnouncementManager::GetInstance().Announce(Player, "xbmc", "OnResume", m_itemCurrentFile, param);
Done, thanks!

2018-04-02 18:49 UTC, afedchin approved these changes

2018-04-02 20:33 UTC, Razzeee commented
I removed the before mentioned call to `onResume` in `xbmcApp.cpp` for android. As the `onResume` method wasn't for playback resuming, but for activity (as in android activity) resuming.

2018-04-02 22:37 UTC, Razzeee commented
OSX build error seems unrelated

2018-04-03 09:29 UTC, DaveTBlake commented
>Not 100% sure about the version increase. (as always)

v 9.2.0 is correct. This is a breaking change and strictly a major verion step (e.g. 10), but rather than have runnaway major version numbers @Montellese advises that the major version only changes with the first breaking change made during alpha, and subsequent ones only step the minor version. 

But it is also important to start the version.txt changing commit title with *[Breaking change]*, to make it easy to spot in the commit history. Remember Git labels don't appear in commit history, the clues need to be in the titles. Please change this.

API consumers like @SyncedSynapse and @joethefox may also like to know that this change is happening. If they are using onPlay announcements after his change they will need to start listening to onResume.

2018-04-05 22:04 UTC, Razzeee commented
@DaveTBlake prefixed the commit msg.

I would like to merge this on friday, if nobody speaks up.

2018-04-08 09:07 UTC, merged

2018-04-08 10:06 UTC, Razzeee commented
Wiki updated https://kodi.wiki/view/JSON-RPC_API/v9#Player_3