[osx] bump minimum version to 10.9
xbmc/xbmc pull request #13949
Opened 2018-05-28 21:25 UTC by Rechi

## Motivation and Context
Get rid of the `IsMavericksOrHigher` by setting Mavericks (10.9) as minimum version.

## How Has This Been Tested?
complete recompile of kodi including depends for osx

## Types of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2018-05-29 07:00 UTC, Memphiz requested changes
Fine by me. Though I would like to see the removal of „IsMavericksOrHigher“ in a separate commit instead of having it buried in the deployment target bump.

Thx for the cleanups :)

2018-05-29 22:00 UTC, Rechi commented
@Memphiz updated

2018-05-30 00:51 UTC, Memphiz approved these changes

2018-05-30 00:52 UTC, Memphiz commented
Thx - fine by me.

2018-05-30 06:34 UTC, FernetMenta commented on xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGL.cpp
> +  std::string rendervendor = CServiceBroker::GetRenderSystem()->GetRenderVendor();
please drop this hack. If PBOs do not work, we have to fix if.

2018-05-30 06:36 UTC, FernetMenta requested changes
please drop the PBO hack. Other than that looks good. Thanks!

2018-05-30 08:03 UTC, Rechi commented
@FernetMenta updated

2018-05-31 06:13 UTC, FernetMenta approved these changes

2018-05-31 09:20 UTC, merged