Refine Video::Autoplay options
xbmc/xbmc pull request #13986
Opened 2018-06-06 11:43 UTC by peak3d

## Description
see title

## Motivation and Context
Users want to have more control in regards of Autoplay.
For example Episodes should be continued, Movies not.

## How Has This Been Tested?
Win10 / amazon addon / enabled Episodes in Settings and:
- played Movise -> No Autoplay
- played Episode -> Autoplay works

## Types of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2018-06-06 12:03 UTC, ksooo requested changes
See comments.

2018-06-06 12:03 UTC, ksooo commented on system/settings/settings.xml
> +        <setting id="videoplayer.autoplaynextitem" type="list[integer]" label="13433" help="36152">
You changed the type of the setting, but not the name. Have you tested what happens if user's settings.xml contains an old (boolean) entry for the setting and kodi is started with the incompatible system settings.xml?

Generates this only a warning or happens something strange/unexpected?

2018-06-06 12:03 UTC, ksooo commented on system/settings/settings.xml
> +        <setting id="videoplayer.autoplaynextitem" type="list[integer]" label="13433" help="36152">
You should adjust the help text (string id 36152) in strings.po to reflect your changes.

2018-06-06 12:03 UTC, ksooo commented on xbmc/settings/SettingsBase.cpp
> +    return nullptr;
This method returns `bool`!

2018-06-06 12:03 UTC, ksooo commented on xbmc/settings/SettingsBase.h
> +  bool FindIntInList(const std::string &id, int value);
IMO, this method could be `const`.

2018-06-06 12:03 UTC, ksooo commented on xbmc/settings/lib/SettingsManager.h
> +  bool FindIntInList(const std::string &id, int value);
This method should be `const`.

2018-06-06 12:03 UTC, ksooo commented on xbmc/view/GUIViewState.cpp
> +  return settingValue >= 0 && CServiceBroker::GetSettings().FindIntInList(CSettings::SETTING_VIDEOPLAYER_AUTOPLAYNEXTITEM, settingValue);
These changes look exactly like the changes in GUIViewStateVideo.cpp. You may want to refactor this in order to avoid the duplicated code.

2018-06-06 12:32 UTC, ksooo commented on xbmc/settings/lib/SettingsManager.cpp
> +  if (setting == nullptr || setting->GetType() != SettingType::List)
`if (!setting || ...`

2018-06-06 12:33 UTC, ksooo commented on xbmc/video/GUIViewStateVideo.cpp
> +  if (m_items.GetContent() == "tvshows")
`else if (...`

2018-06-06 12:33 UTC, ksooo commented on xbmc/video/GUIViewStateVideo.cpp
> +  if (m_items.GetContent() == "episodes")
`else if (...`

2018-06-06 12:33 UTC, ksooo commented on xbmc/video/GUIViewStateVideo.cpp
> +  if (m_items.GetContent() == "movies")
`else if (...`

2018-06-06 12:34 UTC, ksooo commented on xbmc/video/GUIViewStateVideo.cpp
> +  if (m_items.GetContent() == "movies")
Also applies to changes in GUIViewState.cpp (damn, duplicate code) ;-)

2018-06-06 15:31 UTC, da-anda commented
what about file mode by using the "videos" node? This is missing from the select options as far as I have seen (so uncategorised videos)

2018-06-06 18:38 UTC, FernetMenta commented on xbmc/settings/Settings.h
> +  static const int SETTING_AUTOPLAYNEXT_MUSICVIDEOS;
those constants should be located in the component that uses it, not here. see discussion on vaapi we had recently.

2018-06-06 20:17 UTC, peak3d commented
@FernetMenta @ksooo I made some github harikari and have to create a new PR.
You may have noticed, that the PR is not linked to my repo anymore.

Sorry for the double work

2018-06-07 11:56 UTC, peak3d commented
https://github.com/xbmc/xbmc/pull/13992

2018-06-07 11:56 UTC, closed without merging