[VideoLibrary] Do not scan unsupported plugin sources + fix database cleaning
xbmc/xbmc pull request #14210
Opened 2018-07-21 23:15 UTC by AkariDN

Continue #13566:
* Implemented protection: plugins without media library scanning support will not be scanned and refreshed even if they are used as video source
* Fix video library database cleaning for plugin sources
* Other minor fixes

## Description
### [VideoLibrary] Do not scan and refresh unsupported plugin sources
Video library scanning and refreshing is allowed only for plugin URLs that indicated in addon.xml (within extension point "xbmc.python.pluginsource"). These URLs are root paths for specified content. If no URLs are specified, then scanning is completely disabled for such plugin.
```XML
    <extension point="xbmc.python.pluginsource" library="default.py">
        <provides>video</provides>
        <medialibraryscanpath content="movies">movies/</medialibraryscanpath>
        <medialibraryscanpath content="tvshows">tvshows/</medialibraryscanpath>
    </extension>
```
Currently content attribute can be "movies", "tvshows" or "musicvideos".
Path (URL) can be absolute or relative.

```
In the addon.xml example above at following pathes:
plugin://my.favorite.plugin/ - scanning and refreshing is forbidden for any content
plugin://my.favorite.plugin/?mode=movies - forbidden for any content
plugin://my.favorite.plugin/play/movie/123/ - forbidden for any content
plugin://my.favorite.plugin/movies/ - allowed only for movies
plugin://my.favorite.plugin/movies/12345/ - allowed only for movies
plugin://my.favorite.plugin/tvshows/?id=12345 - allowed only for tvshows
plugin://my.favorite.plugin/tvshows/play/?episode_id=777 - allowed only for tvshows
```
In practice, it's desirable that addon developers provide a special plugin url (node), which is intended for scanning, and specify it in addon.xml, so that scanning can be performed only on this special url. For example:
* plugin://my.favorite.plugin/ - standard plugin operation mode
* plugin://my.favorite.plugin/library/ - this path is used only for library scanning and must be added to addon.xml

Note: this is a breaking change. Scanning is disabled by default. All plugins with media library scanning support must have corresponding entries in addon.xml.

### [VideoLibrary] Fix database cleaning for plugin sources
Applies only to plugins that support media library scanning. In order to check existance of some plugin URL, video database cleaner calls plugin at specified path with option "kodi_action=check_exists" and examines result. Plugin must check whether specified path exists (e.g. using cache) and in case of success return any ListItem with setResolvedUrl(). Simplified example:
```Python
if args['kodi_action'] == 'check_exists':
    if check(path):
        xbmcplugin.setResolvedUrl(handle, True, xbmcgui.ListItem())
```
Plugins must correctly handle this mode - just check the existence and don't play video, open dialogs or something else.

### [VideoLibrary] Other minor fixes
* Correctly handle empty hash for tvshow folder (i.e. no episodes) calculated by plugin
* Case insensitive compare for tvshow folder hashes
* Optimize plugin root check in InvalidatePathHash

## Motivation and Context
As tamland said:
> Since plugins are allowed to do anything this will cause all kind of weird and possibly dangerous side-effects... And it's absolutely dangerous because for starters plugins can be unbound, they can open dialog, start playback and whatever as a side-effect of opening directories; and many do. There is no way a user can know this.

## How Has This Been Tested?
* Build tested on Windows and Linux
* Functionality tested with special [test plugin](https://github.com/AkariDN/plugin.video.testlib)

## Types of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Cosmetic change (non-breaking change that doesn't touch code)
- [ ] None of the above (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [ ] All new and existing tests passed

2018-07-22 16:36 UTC, FernetMenta commented on xbmc/video/VideoDatabase.h
> +  std::string GetContentForPath(const std::string& strPath, bool checkTvShows = true);
no default values for parameters parameters

2018-07-22 19:03 UTC, AkariDN commented
Thank you. Fixed.

2018-07-23 07:57 UTC, notspiff requested changes

2018-07-23 07:57 UTC, notspiff commented on xbmc/filesystem/PluginDirectory.cpp
> +bool CPluginDirectory::IsMediaLibraryScanningAllowed(const std::string content, const std::string& strPath)
pass by ref

2018-07-23 07:57 UTC, notspiff commented on xbmc/filesystem/PluginDirectory.cpp
> +bool CPluginDirectory::CheckExists(const std::string content, const std::string& strPath)
pass by ref

2018-07-23 08:38 UTC, AkariDN commented
Thank you. Done.

2018-07-23 10:07 UTC, DaveTBlake commented
Just wondering why the switch to using m_pDS2 in `CVideoDatabase::CleanDatabase`? I thought that the video lib job queue prevented any other changes during cleanup, so thought that using m_pDS1 was fine.

2018-07-23 10:37 UTC, Rechi commented
@AkariDN the fixup commit has to be squashed, we want a clean git history.

2018-07-23 11:08 UTC, AkariDN commented
> why the switch to using m_pDS2

GetScraperForPath() that is called from (!m_pDS->eof()) loop uses the same dataset m_pDS.
> the fixup commit has to be squashed

Done

2018-07-23 11:09 UTC, notspiff approved these changes

2018-07-23 17:38 UTC, DaveTBlake approved these changes
Thanks for clarifying

2018-07-24 05:10 UTC, merged