Added new api EpgEventIcon for ListItem
xbmc/xbmc pull request #14361
Opened 2018-08-26 23:56 UTC by lightglitch

## Description
Added new API to use EPG program images on PVR skins

## Motivation and Context
I want my pvr to show the current program image instead of the channel icon, if exists

## How Has This Been Tested?
I was unable to test it because I was unable to compile kodi (still trying) so help is needed for this .

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2018-08-27 08:53 UTC, ksooo commented
Thanks for your contribution.

> I want my pvr to show the current program image instead of the channel icon, if exists

Looking at the code, I doubt that your approach will work. When creating a `CFileItem ` with an `CPVREpgInfoTag`, the value returned by `CPVREpgInfoTag:Icon` will be preferred and set as icon for the icon. The channel icon is only a fallback:

https://github.com/xbmc/xbmc/blob/master/xbmc/FileItem.cpp#L151

``` c++
  if (!tag->Icon().empty())
    SetIconImage(tag->Icon());
  else if (tag->HasChannel() && !tag->Channel()->IconPath().empty())
    SetIconImage(tag->Channel()->IconPath());
```

Generally, you never should submit untested PRs.

2018-08-27 08:54 UTC, ksooo requested changes
This does not work.

2018-08-27 09:14 UTC, lightglitch commented
I'm closing until I'm able to test it but the goal was to show the program image in the channels list instead of the channel icon.

2018-08-28 16:06 UTC, ksooo commented
Reading the PR description and the code a second time I must admit that I got everything completely wrong. :-)

The code is fine as it is. Thus I will reopen the PR and in case code compiles I will merge it.

Sorry for the noise.

2018-08-28 16:07 UTC, ksooo commented
jenkins build this please

2018-08-28 16:09 UTC, ksooo commented
@ronie here is another new guiinfo label...
@sualfred fyi

2018-08-28 16:10 UTC, ksooo approved these changes

2018-08-28 16:30 UTC, lightglitch commented
@ksooo No problem, glad I could contribute.

2018-08-28 17:15 UTC, enen92 commented on xbmc/GUIInfoManager.cpp
> +///     Returns the thumbnail (if it exists) the epg event associated with the item\, if any
Returns the thumbnail for the epg event associated with the item (if it exists)

2018-08-28 17:56 UTC, merged

2018-08-29 06:50 UTC, sualfred commented
Just for confirmation -> ListItem.EpgEventIcon is working very well.

@lightglitch 
All that is missing is PVR.EpgEventIcon to display the thumb of the currently playing channel in the video osd of the player / fullscreeninfo dialog. Maybe you could also take care of it.

2018-08-29 08:26 UTC, lightglitch commented
@sualfred is this already available in the latest nightly? Because I'm still having issues compiling the source code.

2018-08-29 08:27 UTC, sualfred commented
Yes.