Add PVR_TIMER_TYPE_SUPPORTS_READONLY_DELETE flag
xbmc/xbmc pull request #14507
Opened 2018-10-02 04:00 UTC by djp952

This PR adds a new PVR flag, PVR_TIMER_TYPE_SUPPORTS_READONLY_DELETE, and updates the PVR API to 5.10.3 (compatible with 5.10.0)

## Description
The new flag is intended to allow PVRs to specify timer types that are generally read-only in nature but still allow deletion through Kodi.  The existing PVR_TIMER_TYPE_IS_READONLY flag does not allow deletion when specified as a PVR timer type flag.

## Motivation and Context
Admittedly this is a niche case that may only benefit my PVR client addon (https://github.com/djp952/pvr.hdhomerundvr).  The motivation is that timers/timer rules may be generally read-only in nature in that the user cannot modify the parameters of the timer (rule), but that also excludes them from deleting the timer (rule) in the existing implementation.  This proposed change adds a flag that indicates a read-only timer can still be deleted by the user.

## How Has This Been Tested?
This has been tested using my own PVR client (https://github.com/djp952/pvr.hdhomerundvr) for the HDHomeRun DVR system, on Windows 10 x64 using the latest XBMC code available at the time of the PR.  I set breakpoints at each place the existing PVRTimerType::IsReadOnly() is invoked and made a determination if my proposed function PVRTimerType::SupportsReadOnlyDelete() should be invoked to negate that result.  I only found two places where this would be relevant - when deciding if the "Delete" option should be shown, and again when the Delete Timer operation is invoked.

To unit test the change, I incremented the PVR API to version 5.10.3 and added a handful of MANUAL timers via my PVR.  I confirmed that I did not have to increment the PVR API version in my addon.xml file, and stepped through the aforementioned breakpoints.  The Kodi UI presented me with Delete option(s) that were not available prior to the change, and they worked as expected.  I also confirmed that the Edit option(s) that were now presented display a read-only view of the Timer (Rule) as expected.

It may go without saying, but I recommend ksooo review this PR and decide if it's too much of a niche case for inclusion or if there is a more ambitious plan in the works for future versions that would negate this change or otherwise render it useless.

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2018-10-02 06:01 UTC, ksooo requested changes
just minors to change. functional  changes look good.

2018-10-02 06:04 UTC, ksooo commented
Note: As this is a non-breaking API change it's okay to include it for Leia.

2018-10-02 15:04 UTC, garbear commented on xbmc/pvr/PVRContextMenus.cpp
> +		return  timerType && (!timerType->IsReadOnly() || timerType->SupportsReadOnlyDelete());
This comparison is used twice. Can you factor it out? Also deMorgan would be unhappy that you duplicated the logic but made it unclear that you had done so.

2018-10-02 16:56 UTC, djp952 commented
Requested changes made and squashed.  Thank you for considering this change for inclusion, it helps me out more than one might expect!

2018-10-02 17:42 UTC, ksooo commented
> This comparison is used twice. Can you factor it out? Also deMorgan would be unhappy that you duplicated the logic but made it unclear that you had done so.

 @garbear is right here. Maybe you want to factor out 
```C++
!timerType->IsReadOnly() || timerType->SupportsReadOnlyDelete()
```

to a new member function 

```C++
CPVRTimerType::CanBeDeleted()
```

2018-10-02 17:43 UTC, ksooo commented
> it helps me out more than one might expect!

I would be happy if you could explain this a little bit more.

2018-10-02 19:04 UTC, djp952 commented
I see what you guys want there, will take care of that tonight.  Do you want just CanDelete() or also supplement with things like CanEdit()?  I think just CanDelete() is the least invasive approach, I'd hate to miss something and break stuff on you.

As far as why this helps me out (TLDR warning), in my PVR it's difficult to map Timers and Timer Rules to the HDHomeRun DVR methodology, which is just a set of 'Recording Rules'.  The rules themselves can be edited/deleted/modified, of course, but breaking the different kinds up into both Timers and Timer Rules got weird.  An HDHR "Record Series" operation maps well into PVR_TIMER_TYPE_IS_REPEATING, but the HDHR "Record Once" operation doesn't.  To make the UI work for the users as consistently as I could, I also define "Record Once" as PVR_TIMER_TYPE_IS_REPEATING, which separates the rule and the individual timer it creates out like the series rules.  (The timers themselves are generated from a different backend search that flags EPG entries as having a recording rule).  The catch for me is that the "Record Once" stuff effectively works out such that it doesn't make much sense to allow them to be edited, but you can of course delete them.  With the existing PVR API, the user would need to go into Timers rather than Timer Rules to delete them, since the parent Timer Rule needs to be flagged as read-only and wouldn't allow deletion from Timer Rules.  This proposed change allows the Timer Rule itself to be deleted without allowing editing.

Ultimately this just allows me to present a more consistent set of hacks for the users, they can work the same way for both types of rules I am able to support.  If they want to delete a Recording Rule, they can always do it via Timer Rules rather than needing to know what kind of rule it was.  

In reality with the way the HDHR DVR methodology works it's usually easier to just let it record what it wants and delete it after the fact.  It's a strange beast.

2018-10-02 19:10 UTC, ksooo commented
CanDelete is sufficient, no need for CanEdit

2018-10-02 19:10 UTC, ksooo commented
And thanks for explaining your motivation for this change.

2018-10-03 00:38 UTC, djp952 commented
Refactored to include a CanDelete method and used that where appropriate.  LMK if you guys think "AllowsDelete" might be a better name to match with the existing Forbids/Requires member function names.

2018-10-03 06:14 UTC, ksooo commented
Yeah,  `AllowsDelete`is better.

2018-10-03 11:56 UTC, djp952 commented
Method renamed to AllowsDelete.  Thanks!

2018-10-03 12:12 UTC, ksooo approved these changes
Thanks.

2018-10-03 12:12 UTC, merged

2018-10-03 12:14 UTC, Rechi commented
@ksooo why have you merged the PR before the jenkins build has finished?

2018-10-03 12:16 UTC, ksooo commented
Because I have not seen that it was not finished.

2018-10-03 12:16 UTC, ksooo commented
I feel like we have a Big Brother here. ;-)