LibInputHandler: Don't block shutdown forever
xbmc/xbmc pull request #14537
Opened 2018-10-07 17:51 UTC by fritsch

On Shutdown we would wait forever. This checks if we received an event after max 200 ms.

2018-10-07 18:15 UTC, fritsch commented
Updated - don't want to leak the ePollFD

2018-10-07 18:38 UTC, bacon-cheeseburger commented
The updated fix is working good and resolved the problem here.

2018-10-07 18:48 UTC, fritsch commented
jenkins build this please

2018-10-07 19:32 UTC, lrusak requested changes
You don't need all that. Just change the timeout to 200ms and that's all that's needed.

2018-10-07 19:49 UTC, fritsch commented
As you wish, but it's not good practice to rely on internal behaviour of libinput_dispatch and friends.

2018-10-08 18:03 UTC, fritsch commented
@lrusak something missing here?

2018-10-08 20:27 UTC, lrusak approved these changes

2018-10-08 20:27 UTC, merged

2018-10-08 20:28 UTC, lrusak commented
Thanks! I was away for Canadian thanksgiving so I'm sorry for the late review :turkey: