Allow to use resume offset from within JSON RPC PlaylistPlayer Player.Open
xbmc/xbmc pull request #14590
Opened 2018-10-12 17:13 UTC by lobermann

## Description
Using the already existing position parameter in the JSON Request this allows to also use the resume option when starting a specific item in a playlist.

This enables remotes to resume playback from a certain position when using playlists (for example to resume TV Shows with multiple episodes in the playlist).

@DaveTBlake is a bump for the JSON RPC API version needed for this? As there is no change in the schema.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

2018-10-12 17:14 UTC, ksooo commented on xbmc/interfaces/json-rpc/PlayerOperations.cpp
> +    int playlistStartPosition = (int)parameterObject["item"]["position"].asInteger();
c++ style cast?

2018-10-12 17:15 UTC, ksooo commented on xbmc/interfaces/json-rpc/PlayerOperations.cpp
> +        CServiceBroker::GetPlaylistPlayer().SetSongResume(playlistid, playlistStartPosition, (int)CUtil::ConvertSecsToMilliSecs(ParseTimeInSeconds(optionResume)));
c++ style cast?

2018-10-12 17:15 UTC, ksooo commented on xbmc/interfaces/json-rpc/PlayerOperations.cpp
> +        CServiceBroker::GetPlaylistPlayer().SetSongResume(playlistid, playlistStartPosition, (int)CUtil::ConvertSecsToMilliSecs(optionResume.asInteger()));
c++ style cast?

2018-10-12 17:16 UTC, ksooo commented on xbmc/PlayListPlayer.h
> +  void SetSongResume(int iPlaylist, int iIndex, int iOffset);
how can an offset be negative? int iOffset => unsigned int?

2018-10-16 12:03 UTC, DaveTBlake requested changes
Yes, despite no schema change, a bump to patch number is needed.  In this case it shows JSON consumers that a Kodi build has this new functionality.  See https://github.com/xbmc/xbmc/blob/6c5725e3a26bccebdc431d92db3c20f3ef393006/xbmc/interfaces/json-rpc/schema/methods.json#L34

Since not changing schema, you do need to follow the definition of the resume parameter given in `methods.json`, https://github.com/xbmc/xbmc/blob/6c5725e3a26bccebdc431d92db3c20f3ef393006/xbmc/interfaces/json-rpc/schema/methods.json#L169

2018-10-16 12:10 UTC, DaveTBlake commented on xbmc/interfaces/json-rpc/PlayerOperations.cpp
> +        CServiceBroker::GetPlaylistPlayer().SetSongResume(playlistid, playlistStartPosition, static_cast<int>(CUtil::ConvertSecsToMilliSecs(ParseTimeInSeconds(optionResume))));
Compare with https://github.com/xbmc/xbmc/blob/c91debd97387893c801c8c2f1de28eed0c1e3e34/xbmc/interfaces/json-rpc/PlayerOperations.cpp#L693

Schema says general numbers are `Player.Position.Percentage`  a percentage

2020-03-08 19:47 UTC, phunkyfish commented
PR closed as it appears to be abandoned by the author. 

If the author would like it kept open please just request so on the PR. If you feel there is still merit in merging this PR you can request the label be changed to PR Cleanup: Backburner.

2020-03-08 19:47 UTC, closed without merging