windowing/gbm: add MSAA settings
xbmc/xbmc pull request #14630
Opened 2018-10-17 02:21 UTC by lrusak

This adds the ability to change the msaa buffer level used in the egl config. This is only usable if the egl extension "EGL_KHR_no_config_context" is present.

I'm not a big fan of the way I enumerate the msaa values available and am open to suggestions about how to improve that.

reference [here](https://gitlab.freedesktop.org/mesa/kmscube/commit/9dcce71e603616ee7a54707e932f962cdf8fb20a)

2018-10-17 07:14 UTC, pkerling commented
Out of curiosity: Why do you want to have MSAA in the first place?

2018-10-17 07:21 UTC, yol requested changes
I've given it some thought and I think we should avoid pulling a settings dependency into `CEGLContextUtils` :-/

2018-10-24 16:07 UTC, jenkins4kodi commented
@lrusak this needs a rebase

2020-03-08 20:29 UTC, phunkyfish commented
@lrusak do you want to progress this, close it or to the backburner?

2020-03-21 17:28 UTC, lrusak commented
I'll put this on the backburner for now. I'd like to revisit this eventually.

2020-03-23 16:48 UTC, closed without merging