[database] Replace CREATE TABLE […] AS SELECT […]
xbmc/xbmc pull request #15092
Opened 2018-12-19 09:57 UTC by pkerling

When MySQL is run with `--enforce-gtid-consistency` enabled, the
`CREATE TABLE […] AS SELECT […]` command is not available.
While it is more wordy, use alternatives instead.

Fixes #14893

2018-12-19 09:58 UTC, pkerling commented
Note: There is one command left from a schema update in 2015 that I wouldn't want to touch since it's more complicated. Shouldn't be necessary hopefully.

2018-12-19 17:58 UTC, pkerling commented
jenkins build this please

2018-12-20 07:50 UTC, pkerling commented
jenkins build this please

2018-12-20 08:15 UTC, MartijnKaijser commented
jenkins build this please

2018-12-20 19:03 UTC, kib requested changes
There are several other instances throughout the code that use CREATE ... AS SELECT ...
As far as I can see you can't cleanly install Kodi with `--enforce-gtid-consistency` enabled, even with this patch

2018-12-20 19:11 UTC, kib approved these changes
Never mind, I overlooked that CREATE VIEW... AS SELECT... does _not_ violate `--enforce-gtid-consistency` and should be fine.

2018-12-21 10:46 UTC, kib commented
@pkerling another option might be to instantiate the database with `CREATE TABLE table2 LIKE table1` wqqhich is also fine when using --enforce-gtid-consistency` but saves on the entire CREATE TABLE statement.

2018-12-21 19:38 UTC, Rechi commented
Keep it as is or how would you know which command to execute?

2018-12-23 17:52 UTC, pkerling commented
`dynamic_cast` the db or dataset or add a function to that effect. But I guess for v18 at least we'll just leave it like it is now.

2018-12-23 20:14 UTC, Rechi commented
IMO casting will not make the code easier to read. Although the new sql command contains now more words it is straightforward to read.

2018-12-23 20:42 UTC, pkerling commented
OK, let's keep it like this. Now we only need the verification that it works.

2019-01-03 16:03 UTC, pkerling commented
Confirmed working with a MySQL 8 server and GTID consistency enforced. Merging.

2019-01-03 16:03 UTC, merged