Android: Properly overwrite ProcessInfo and use Deinterlace Half
xbmc/xbmc pull request #15229
Opened 2019-01-10 09:59 UTC by fritsch

YADIF Full is too much for most devices. Use a less CPU hungry default.

This is only used when SW Decoding is active, e.g. für DVD stills and so on.

2019-01-10 15:10 UTC, peak3d requested changes
Where is the call that registers the ProcessInfoAndroid?
Usually registering of components is done in WinSystemAndroid

Edit: Example OSX: https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/osx/WinSystemOSX.mm#L824

Android Registration block:
https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/android/WinSystemAndroid.cpp#L77-L86

2019-01-10 15:47 UTC, fritsch commented
Thanks. Found it and added it.

2019-01-10 16:01 UTC, peak3d approved these changes

2019-01-10 18:01 UTC, fritsch commented
jenkins build this please

2019-01-10 19:31 UTC, CiNcH83 commented
Exactly. And that is why YADIF is not the problem as the progressive DVD also jerks...

2019-01-10 19:32 UTC, fritsch commented
And why do you thhink your device is representative for all Android devices?

2019-01-10 19:32 UTC, CiNcH83 commented
Gut feeling.

2019-01-10 19:33 UTC, fritsch commented
And why do you think reducing the default load is not a good idea? Anything **technical** that speaks against this change?

2019-01-10 19:35 UTC, fritsch commented
Example: http://solidrun.maltegrosse.de/~fritsch/576i50_mpeg2_samples.ts <- you should easily see the difference between yadif full and yadif half. One makes it work without issues on Wetek-Play, the other for sure not.

2019-01-10 19:37 UTC, CiNcH83 commented
You can of course do whatever you want. You Kodi guys are always against dubious workarounds which do not tackle the root cause of a problem. And YADIF isn't the root cause for the jerkyness on Android IMHO. Progressive MPEG-2 and MPEG-4 SD videos also jerk like crazy when SW decoding them.

Plus there is a good reason for double frame rate deinterlacing which is preserving full motion resolution.

2019-01-10 19:39 UTC, fritsch commented
This is not a workaround. It sets a sane default for in general slow ARM chips to increase the chance to not kill them right away when post processing needs to be done on the CPU.

2019-01-10 19:43 UTC, CiNcH83 commented
I currently can't software decode any MPEG-2 or MPEG-4 in SW without massive jerkyness, not even 24p and 25p at SD resolution. So trying your sample does not mean a lot until the root cause for the jerkyness is fixed. Only Jarvis and Krypton seem to be fine in that regard.

But you might be right that a frame doubler might probably be too much burden for those slow ARMs.

2019-01-10 19:51 UTC, fritsch commented
I used the last 10 minutes, installed kodi 18rc on my Huawei P10 Lite. And watched some 576i50 LiveTV with SW decoding and YADIF half.

That worked remarkably good. Is your TV really that slow? Odd.

2019-01-10 19:54 UTC, CiNcH83 commented
Most Android TV devices are either based on Amlogic S905X in case of settop boxes or MediaTek MT5890/MT5891 in case of TVs with pretty slow quad ARM Cortex A53. That's a reality.

2019-01-11 14:16 UTC, da-anda commented
I can check on my Philips AndroidTV which also has a MediaTek chip. I hadn't noticed any issues watching liveTV so far, but I barely watch liveTV these days, especially not SD channels. Just let me know if I should do some testing

2019-01-11 14:18 UTC, CiNcH83 commented
> I hadn't noticed any issues watching liveTV so far

Suppose you are using HW decoding. The problem is with SW decoding...

2019-01-11 14:33 UTC, CiNcH83 commented
I don't. I actually never use it. I just know that SW decoding is in dire straights due to MPEG-4 ASP and DVD which have been decoded in SW until recently. I am fine with the recent changes to accelerate those formats.

Something is wrong with SW decoding nonetheless. A log can be found [here](https://forum.kodi.tv/showthread.php?tid=338489&pid=2807531#pid2807531).

2019-01-11 14:41 UTC, peak3d commented
Is there any sample around which shows the issue? Reading the log without knowing how it looks like is impossible (at least for me)

2019-01-11 14:48 UTC, CiNcH83 commented
[Here](https://paste.kodi.tv/jupuqofiro) is another log taken while playing @fritsch's TS sample posted above. This sample is interlaced though. Mine has been a progressive DVD which also eliminates the impact of YADIF...

2019-01-11 14:55 UTC, CiNcH83 commented
I can actually reproduce the issue with anything I play through SW. So it does not require a specific sample. SW decoding is just not feasible anymore for me. Jarvis and Krypton used to be just fine for stuff that a weak Cortex A53 is supposed to handle in realtime.

2019-01-11 15:16 UTC, CiNcH83 commented
I uploaded a video to YouTube, demonstrating the judder ([CLICK](https://www.youtube.com/watch?v=hHnGZofyKhE)). The iPhone captured it quite well...

2019-01-11 16:16 UTC, fritsch commented
The PTS are totally nuts again here.

2019-01-12 17:00 UTC, CiNcH83 commented
Afraid I can‘t provide it before Monday. Currently on vacation..

2019-01-14 17:00 UTC, CiNcH83 commented
[Here](https://paste.kodi.tv/ahiqibazek) is a log captured while playing the TS sample with deinterlacing forced off.

2019-01-14 18:05 UTC, fritsch commented
Thx much @peak3d do you have an idea why those PTS are so wrong?

2019-01-14 18:10 UTC, fritsch commented
Btw. with "Sync Playback to Display" - same issue right?

2019-01-14 18:13 UTC, CiNcH83 commented
Yes, same jerkyness.

2019-01-14 18:33 UTC, FernetMenta commented
There is nothing that indicates that pts values are wrong. The bottle neck on sw decoding path with gles is rendering. Due to missing PBOs there is a copy from sys mem to gpu mem that blocks cpu/gpu. That is super slow.

2019-01-14 18:35 UTC, CiNcH83 commented
Jarvis and Krypton are doing a good job though...

2019-01-14 19:01 UTC, fritsch commented
CPU copy is not the problem here:

```
fritsch@cubox:~$ time ./copytest.out 

real	0m1.428s
user	0m1.403s
sys	0m0.023s
```

```
#include <string.h>
#include <stdlib.h>

int main()
{
  char* source = (char*) malloc(720*574*3*2);
  char* dest = (char*) malloc(720*574*3*2);
  for (int i = 0; i < 1000; i++)
  {
    memcpy(dest, source, 720*574*3*2);
    source[i] = 5; // just change something
  }
  return 0;
}
```

~ 1000 / 1.48 = 675 fps

2019-01-14 19:06 UTC, fritsch commented
And on those embedded socs: SYSMEM == GPUMEM - the only difference the latter is not cached.

2019-01-14 19:16 UTC, fritsch commented
Uncached version:
```
fritsch@cubox:~$ time ./copytest.out 

real	1m35.967s
user	0m11.894s
sys	1m24.041s
```

```
#include <string.h>
#include <stdlib.h>

int main()
{
  char* source = (char*) malloc(720*574*3*2);
  char* dest = (char*) malloc(720*574*3*2);
  for (int i = 0; i < 10000; i++)
  {
    memcpy(dest, source, 720*574*3*2);
    __builtin___clear_cache(dest, dest + 720*574*3*2);
    source[i] = 5; // just change something
  }
  return 0;
}
```

10000 / 96 = 104.2 fps for progressive frames (not fields) -> still enough, even if implemented in this very slow way.

2019-01-14 19:37 UTC, fritsch commented
I am currently trying to find out which compile flags are used to build Android's ffmpeg - I somehow think that the "intrinsics" are missing ... let's see.

Obviously having PBOs (OpenGLES 3.x) would be nice - but it's not the reason for this problem here.

2019-01-14 20:43 UTC, FernetMenta commented
the problem is not the copy itself but sync of cpu and gpu. It may have worked on earlier versions but systems were close to maxed out. Little issue on the rendering path can cause this issue. If you look at pts, you dig into the wrong place

2019-01-14 20:49 UTC, fritsch commented
Okay. Thx.

I currently look into the build system and it seems Android depends are compiled with Og without optimizations. Currently checking with our cmake guys.

2019-01-14 21:01 UTC, FernetMenta commented
@fritsch you should familiarise yourself with glTexSubImage2D and why it's so bad using it. your test code above is not related to the issue I refer to.

2019-01-14 21:12 UTC, fritsch commented
It is clear why it is bad and it is even more clear why it should be avoided on modern architecture. I was just stating how ARM GPUs are attached to the memory bus and what the CPU needs to do when you copy around frames, blocking CPU and GPU in order to transfer the cached cpu pixels into the uncached GPU memory.

Everything that is SYNC is bad for a GPU and therefore 2 PBOs is the way to - no doubt.

But: In above example we talk about 50 fields, 25 frames in "pixel-sum" ... which btw. every other player on this Android box plays without issues ...

Means: if presenting 25 frames (deinterlacing off) is a problem, e.g. the design is so easily killable then we have a serious problem.

I still think the root cause is something quite trivial.

2019-01-14 21:15 UTC, fritsch commented
@CiNcH83  http://mirrors.kodi.tv/test-builds/android/arm/kodi-20190114-5e4f8076-master-armeabi-v7a.apk <- any changes here? I could not force depends rebuild, but at least it now enabled optimizations for ffmpeg.

Anything better?

2019-01-14 21:43 UTC, CiNcH83 commented
Same high CPU usage and stutter-fest.

2019-01-15 06:19 UTC, fritsch commented
Okay: high cpu usage is per se not a design problem, especially when decoder is running async to rendering - it's even using 6 threads on your machine.

And: glTexture2D also needs cpu for copying the pixels (**one** core).

Means: in general the system is fully loaded cpu wise - **all** cores, all the time?

Hopefully I get ffmpeg reproducably build with neon enabled to compare. That looks like some "combined" performance issue.

Do you get any information about the threads being under full load via adb?

2019-01-15 06:32 UTC, CiNcH83 commented
> Okay: high cpu usage is per se not a design problem, especially when decoder is running async to rendering - it's even using 6 threads on your machine.
>
> And: glTexture2D also needs cpu for copying the pixels (one core).

As you can see in [my comparison of CPU usage](https://forum.kodi.tv/showthread.php?tid=338489), Jarvis has been much more lenient. Probably hasn't been using YADIF at all? But even if I disable deinterlacing entirely, CPU usage in Leia/Krypton is still double that of Jarvis.

Interestingly, Krypton also has the high CPU usage but does not suffer from the stuttering issue.

> Means: in general the system is fully loaded cpu wise - all cores, all the time?

The Linux kernel on my Sony is pretty old (3.10) and the deployed busybox top command does not allow me to see CPU usage per core. The readings inside Kodi are also not that meaningful, as displaying an OSD seems to put quite some additional burden on the CPU.

> Do you get any information about the threads being under full load via adb?

I can check with `top -t` in the evening. But there has not been given enough information in order to identify a specific thread as only the thread ID is displayed.

2019-01-15 07:19 UTC, peak3d commented
Android has a nice tool: systrace. Can be simply started via adb and produces a dynamic html file (display works only in chrome browser IIRC).

@CiNcH83 are you able to record 10 secs systrace while playing a movie?

2019-01-15 07:31 UTC, CiNcH83 commented
I probably can but I currently don't have the tools installed (except for a portable adb).

Am I the only one who experiences those issues?

2019-01-15 07:36 UTC, peak3d commented
Not sure, I don't use s/w decoding on android devices, and tbh., I don't see any priority to fix this asap.
IMO most users are happy with h/w decoding capabilities, so not many will jump and support here.

But this is a personal opinion, Could be wrong though.

2019-01-15 07:45 UTC, CiNcH83 commented
Agree. Kind of. However, given the many problems with HW decoding (see forums), it seems to be a good idea to have a working fallback. Or why else have there been switches for DVD and MPEG-4 ASP SD?

I typically rip DVD/BD main movies to mkv as I can only play stuff from network on my TV. And I do not own any MPEG-4 ASP files apart from some samples.

2019-01-15 07:59 UTC, peak3d commented
Reality is that we have very limited dev power on android side, and android (TV) is stepping forward fast with new functionalities / API level shifting. There is really no time to spend time on corner cases.

Android uses same kernel / render pipelne compared to ARM linux based devices, interesting to know would be to know, if those movies play fine on LibreELEC for example and how resources look there.

But this requests lot of preparation of test scenario, nothing what can be handled from my side currently.

2019-01-15 08:38 UTC, peak3d commented
Good to know, thx, I think we should focus first on Linux ARM because there is a lot expertise / dev power.
I'll try to trigger some ppl there....

2019-01-15 16:58 UTC, CiNcH83 commented
Kodi CPU reading:
![](https://www.dropbox.com/s/7ywe3cejco7vr5h/sw_dec_cpu.jpg?raw=1)

`top -t`:
```
User 62%, System 15%, IOW 0%, IRQ 0%
User 356 + Nice 1 + Sys 90 + Idle 119 + IOW 0 + IRQ 0 + SIRQ 2 = 568

  PID   TID USER     PR  NI CPU% S     VSS     RSS PCY Thread          Proc
31906 32048 u0_a163  20   0  20% R 1410872K 186384K  ta Thread-3        org.xbmc.kodi
31906 20362 u0_a163  20   0   8% R 1410872K 186384K  ta Thread-72       org.xbmc.kodi
31906 20371 u0_a163  20   0   7% R 1410872K 186384K  ta Thread-72       org.xbmc.kodi
31906 20373 u0_a163  20   0   7% R 1410872K 186384K  ta Thread-72       org.xbmc.kodi
31906 20374 u0_a163  20   0   7% R 1410872K 186384K  ta Thread-72       org.xbmc.kodi
31906 20372 u0_a163  20   0   7% R 1410872K 186384K  ta Thread-72       org.xbmc.kodi
31906 20359 u0_a163  20   0   1% S 1410872K 186384K  ta Thread-72       org.xbmc.kodi
31906 20365 u0_a163  20   0   0% S 1410872K 186384K  ta Thread-72       org.xbmc.kodi
31906 20363 u0_a163  20   0   0% S 1410872K 186384K  ta Thread-72       org.xbmc.kodi
31906 20364 u0_a163  20   0   0% S 1410872K 186384K  ta Thread-72       org.xbmc.kodi
31906 20366 u0_a163  20   0   0% S 1410872K 186384K  ta Thread-72       org.xbmc.kodi
31906 20367 u0_a163  20   0   0% S 1410872K 186384K  ta Thread-72       org.xbmc.kodi
31906 31906 u0_a163  20   0   0% S 1410872K 186384K  ta org.xbmc.kodi   org.xbmc.kodi
31906 32070 u0_a163  19  -1   0% S 1410872K 186384K  ta Thread-5        org.xbmc.kodi
31906 32069 u0_a163  20   0   0% S 1410872K 186384K  ta Thread-4        org.xbmc.kodi
```

Here is a 5s systrace captured while playing the above TS sample:
[[DOWNLOAD](https://www.dropbox.com/s/pdv3ywz554ewq2u/trace.zip?dl=1)]

2019-01-15 17:09 UTC, peak3d commented
Do you still have the matching kodi.log file?
The tid:32048 of thread-3 should be written at the beginning of each line and we know what thread it is.

2019-01-15 17:15 UTC, CiNcH83 commented
```
User 71%, System 19%, IOW 0%, IRQ 0%
User 371 + Nice 25 + Sys 110 + Idle 41 + IOW 2 + IRQ 0 + SIRQ 3 = 552

  PID   TID USER     PR  NI CPU% S     VSS     RSS PCY Thread          Proc
11113 11160 u0_a163  20   0  19% R 1345188K 220680K  ta Thread-3        org.xbmc.kodi
11113 11584 u0_a163  20   0   8% S 1345188K 220680K  ta Thread-13       org.xbmc.kodi
11113 11595 u0_a163  20   0   7% S 1345188K 220680K  ta Thread-13       org.xbmc.kodi
11113 11593 u0_a163  20   0   7% S 1345188K 220680K  ta Thread-13       org.xbmc.kodi
11113 11592 u0_a163  20   0   7% S 1345188K 220680K  ta Thread-13       org.xbmc.kodi
11113 11594 u0_a163  20   0   6% S 1345188K 220680K  ta Thread-13       org.xbmc.kodi
11113 11581 u0_a163  20   0   1% S 1345188K 220680K  ta Thread-13       org.xbmc.kodi
11113 11589 u0_a163  20   0   0% S 1345188K 220680K  ta Thread-13       org.xbmc.kodi
11113 11585 u0_a163  20   0   0% S 1345188K 220680K  ta Thread-13       org.xbmc.kodi
11113 11586 u0_a163  20   0   0% S 1345188K 220680K  ta Thread-13       org.xbmc.kodi
11113 11587 u0_a163  20   0   0% S 1345188K 220680K  ta Thread-13       org.xbmc.kodi
11113 11588 u0_a163  20   0   0% S 1345188K 220680K  ta Thread-13       org.xbmc.kodi
11113 11113 u0_a163  20   0   0% S 1345188K 220680K  ta org.xbmc.kodi   org.xbmc.kodi
11113 11175 u0_a163  19  -1   0% S 1345188K 220680K  ta Thread-5        org.xbmc.kodi
```

[LOG](https://paste.kodi.tv/ziradumige)

2019-01-15 17:31 UTC, peak3d commented
Hmm, ok, seems that we write some pointer instead TID into log, will try to fix this first :-(
From systrace Thread-3 includes eglSwapBuffers, so it seems to be our render / main thread.

2019-01-15 17:50 UTC, fritsch commented
Do we know from the log how often it is rendering? e.g. does eglSwapBuffers "block"?
Might adding timestamps before and after the glSubTexture2D shed a light if it's really the load when transfering buffers?

2019-01-15 17:54 UTC, peak3d commented
Unfortunately there are not many GPU traces in systrace.
eglSwapBuffer is non-blocking in android b.t.w.

For ARM devices there are other tools (e.g. MALI GPU trace) but let us first fix ThreadId to see what we're doing

2019-01-15 17:57 UTC, fritsch commented
How do you sync / throttle the Render thread if this does not block?

2019-01-15 18:01 UTC, peak3d commented
@fritsch Choreographer::doFrame sets an event.
@CiNcH83 maybe you can find something like that on your device : https://developer.android.com/studio/profile/inspect-gpu-rendering#profile_rendering

2019-01-15 18:20 UTC, CiNcH83 commented
> @CiNcH83 maybe you can find something like that on your device : https://developer.android.com/studio/profile/inspect-gpu-rendering#profile_rendering

Yes. I have that. Unfortunately the graph disappears into the background when opening Kodi. This doesn't happen with other apps...

I can also profile to `adb shell dumpsys gfxinfo`, [see result](https://www.dropbox.com/s/yybefqkdfvzy3bl/kodi_gfxinfo.txt?dl=0).

2019-01-15 18:23 UTC, fritsch commented
```
Total frames rendered: 472
**Janky** frames: 169 (35.81%)
```
^^

2019-01-15 18:42 UTC, fritsch commented
Concerning: https://developer.android.com/training/testing/performance

What does: adb shell dumpsys gfxinfo <PACKAGE_NAME> framestats 

yield?

2019-01-15 18:47 UTC, CiNcH83 commented
[org.xbmx.kodi framestats](https://www.dropbox.com/s/z5tzw60czsdijb2/kodi_framestats.txt?dl=0)

2019-01-15 18:54 UTC, fritsch commented
Nearly 40% of all frames are either too late or are dropped ... this cannot work :-(

What @FernetMenta pointed out might at the end be the root cause. It might have worked for Krypton / Jarvis where a CPU sleep was used before.

2019-01-15 18:57 UTC, fritsch commented
Does something change if you reduce UI resolution to 720p? Is that possible?

2019-01-15 18:58 UTC, CiNcH83 commented
Can‘t change resolution.

2019-01-15 19:00 UTC, fritsch commented
There is a LimitGUI setting for Android, force it to 720p please.

2019-01-15 19:05 UTC, CiNcH83 commented
Tried that... didn't help.

2019-01-15 19:09 UTC, CiNcH83 commented
```
Total frames rendered: 490
Janky frames: 187 (38.16%)
```

2019-01-15 19:10 UTC, fritsch commented
Okay, you can throw the tool away. So no matter if we render 720p or render 1080p UI changes anything in the stats ... this makes zero sense. Are you sure the UI ran at 1080p before?

2019-01-15 19:17 UTC, CiNcH83 commented
Yes. UI is noticably less sharp with 720 now.

You are right. The stats are useless. They indeed do not count the drawn video frames.

2019-01-15 19:30 UTC, peak3d commented
If jenkins is ready we should have apk's: https://github.com/xbmc/xbmc/pull/15263

2019-01-15 20:02 UTC, CiNcH83 commented
```
User 68%, System 20%, IOW 0%, IRQ 0%
User 402 + Nice 2 + Sys 120 + Idle 61 + IOW 4 + IRQ 0 + SIRQ 4 = 593

  PID   TID USER     PR  NI CPU% S     VSS     RSS PCY Thread          Proc
27653 27700 u0_a163  20   0  19% R 1347412K 228000K  ta Thread-3        org.xbmc.kodi
27653 28183 u0_a163  20   0   8% R 1347412K 228000K  ta Thread-12       org.xbmc.kodi
27653 28193 u0_a163  20   0   6% S 1347412K 228000K  ta Thread-12       org.xbmc.kodi
27653 28192 u0_a163  20   0   6% S 1347412K 228000K  ta Thread-12       org.xbmc.kodi
27653 28191 u0_a163  20   0   6% S 1347412K 228000K  ta Thread-12       org.xbmc.kodi
27653 28194 u0_a163  20   0   6% S 1347412K 228000K  ta Thread-12       org.xbmc.kodi
27653 28179 u0_a163  20   0   1% S 1347412K 228000K  ta Thread-12       org.xbmc.kodi
27653 28186 u0_a163  20   0   0% R 1347412K 228000K  ta Thread-12       org.xbmc.kodi
27653 28187 u0_a163  20   0   0% R 1347412K 228000K  ta Thread-12       org.xbmc.kodi
27653 28188 u0_a163  20   0   0% R 1347412K 228000K  ta Thread-12       org.xbmc.kodi
27653 28184 u0_a163  20   0   0% R 1347412K 228000K  ta Thread-12       org.xbmc.kodi
27653 28185 u0_a163  20   0   0% R 1347412K 228000K  ta Thread-12       org.xbmc.kodi
27653 27732 u0_a163  19  -1   0% S 1347412K 228000K  ta Thread-5        org.xbmc.kodi
27653 27653 u0_a163  20   0   0% S 1347412K 228000K  ta org.xbmc.kodi   org.xbmc.kodi
27653 28182 u0_a163  20   0   0% S 1347412K 228000K  ta Thread-3        org.xbmc.kodi
```

[LOG](http://paste.kodi.tv/etilorovoc)

2019-01-15 20:04 UTC, peak3d commented
Yes, its the main thread which renders the GUI, it's not the decoder job

2019-01-15 20:35 UTC, fritsch commented
Btw. what he prints here is _without_ video decoding actually running. That means on this device we barely can render kodi's UI ...

2019-01-15 20:39 UTC, CiNcH83 commented
Yeah. It is kind of laggy...

2019-01-15 20:42 UTC, fritsch commented
After what I see here I think @FernetMenta is right! This especially makes sense when looking at the SW decoded rendering path. Cause here we are solely on the GUI layer.

Means the stats you showed can directly be linked to the normal GUI rendering with even adding a bit more load as the video frames need to be uploaded.

2019-01-15 20:54 UTC, CiNcH83 commented
I don‘t know whether this means a lot, but the sample plays fine with MediaCodec+EGL (i.e. Surface disabled).

2019-01-15 21:07 UTC, fritsch commented
@CiNcH83 do you use the setting: "Use Limited Range"? 

Could you disable that?

2019-01-15 21:12 UTC, fritsch commented
Mediacodec-EGL uses another path to get the decoded frames to display.

2019-01-15 21:15 UTC, CiNcH83 commented
Can't see this 'Use limited range' setting on Android...

2019-01-16 07:52 UTC, CiNcH83 commented
@fritsch 

Is ffmpeg for Android now built with NEON? What makes you believe that it is not?

2019-01-16 10:04 UTC, peak3d commented
@CiNcH83 I'll provide a PRtoday for the rendering bottleneck.
Still not optimal, but much better. An optimal solution will come with GLES3 implementation.

FFMpeg is compiled with NEON flag for Android.

2019-01-16 10:15 UTC, CiNcH83 commented
Sounds good.

So my BRAVIA might benefit from GLES3 at some point :) . As a sidenote I want to add that all current Amlogic S905 based devices (like Mi Box and quite some Fire TVs) won't benefit from it as the built-in Mali-450 GPU only supports up to GLES2.

2019-01-17 07:49 UTC, CiNcH83 commented
Suppose we will further discuss the rendering bottleneck on the new PR...

Getting back on topic, I compared CPU usage (quad-core ARM Cortex A53@1.1GHz) of several Kodi versions and deinterlacing algorithms using @fritsch's TS sample posted above...

Jarvis (Deint: Off): 17%
Jarvis (Deint: Blend): 20%
Krypton/Leia (Deint: Off): 33%
Krypton/Leia (Deint: YADIF): 65%
Krypton/Leia (Deint: YADIF Half): 55%

While Krypton/Leia increased the basic CPU load quite a bit (compare 'Deint: Off'), it is mainly YADIF that stresses later Kodi versions due to its complex nature. YADIF Half doesn't change that considerably.

YADIF seems to be manageable on my BRAVIA, at least for SD (I will do more thorough testing once @peak3d releases the rendering bottleneck patch). Since you can't SW decode anything at higher resolutions (like some 1080i) on such hardware anyway, that's probably all we need to care about anyway.

So if you want to go ultra low-profile, you might want to consider another deinterlacer altogether.

2019-01-18 14:08 UTC, peak3d commented
Interesting fact is that Jarvis used NEON YUV -> RGBA conversation where we use GPU shader now (this is at least my assumption, if you provide a J log I can verify)

The solution which works for GLES3 does not work for other devices like Wetek HUB, so we're still searching for a more proper solution. Nevertheless I'll push a PR if you want to test.

Looking forward to J log

2019-01-18 15:15 UTC, wrxtasy commented
@peak3d,
I'm running an updated GLES3 on the MINIX U9 - any chance to spit out a test version with your PR ?

2019-01-18 15:31 UTC, peak3d commented
@wrxtasy sure, give me some minutes

2019-01-18 16:37 UTC, CiNcH83 commented
Sorry, no clue what a J log is.

2019-01-18 20:38 UTC, mo123 commented
> Sorry, no clue what a J log is.

A log from Kodi Jarvis 16.

2019-01-19 05:58 UTC, fritsch commented
Just little intermediate news:
- the SubTexImage2D for copying the texture without having to do it linewise cause of the stride not matching is the issue (1)
- Copying the buffer on the CPU before, so that stride matches width -> full 50 fps for playing this video is achievable. (2)
- And _removing_ the yuv2rgb shader to not do 3*width*height texture lookup would also work with (1). (3)

So: Lessons learned: Take care for Shaders on slow 3D GPUs (most embedded socs) and try to not transfer the CPU Image data via linewise SubTexImage2D.

Btw. In Jarvis we even did the yuv2rgb on the CPU with neon ... so this fixed (3)

2019-01-19 06:37 UTC, fritsch commented
Testbuild is upcoming here: https://jenkins.kodi.tv/job/Android-ARM/12622/ has stridegles in name - as it's quite early here chances are good that you will hit an off by one error.

Code is here: https://github.com/fritsch/xbmc/commit/492680baf1fc98ba26985d433b0f6ccdf2e616d3

2019-01-19 07:35 UTC, fritsch commented
Here we go: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20190119-492680ba-stridegles-armeabi-v7a.apk ( wait a bit until mirrors are synced)

Btw. One can missuse the debug overlay to see the fps that are rendererd. This is by far not exact, but it's very good to see the difference between those versions easily.

2019-01-19 09:01 UTC, fritsch commented
Real solution for the "performance issue" on GLES, here: https://github.com/xbmc/xbmc/pull/15286
ProcessInfo change is still valid :-)

2019-01-21 18:06 UTC, merged