[Android] NDK19 support (needs build-tools 27.0.3)
xbmc/xbmc pull request #15415
Opened 2019-02-04 08:12 UTC by peak3d

## Description
NDK19 support

## Motivation and Context
NDK19 is current stable version and may provide fixes.

## How Has This Been Tested?
Compile kodi on Linux x86_64 host

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

2019-02-04 08:21 UTC, peak3d commented
jenkins build this please

2019-02-04 12:20 UTC, Rechi requested changes
Either change the commit message and PR title to what it really does or add the missing changes for real NDK 19 support.

2019-02-04 12:20 UTC, Rechi commented on tools/android/packaging/Makefile.in
> -# https://android.googlesource.com/platform/ndk/+/fe0fe5dc32682d1811d32492c3055becb512c147/build/tools/make_standalone_toolchain.py#308
Why remove this comment? This is still correct for armeabi-v7a and NDK 18.

2019-02-04 12:20 UTC, Rechi commented on tools/android/packaging/Makefile.in
> +  STLLIB=$(TOOLCHAIN)/$(HOST)/lib/libc++_shared.s
```suggestion
  STLLIB=$(TOOLCHAIN)/$(HOST)/lib/libc++_shared.so
```

2019-02-04 12:20 UTC, Rechi commented on tools/depends/target/Toolchain.cmake.in
> +  list(APPEND CMAKE_SYSTEM_LIBRARY_PATH @use_toolchain@/sysroot/usr/lib/@use_host@/@use_ndk_api@)
This is only true for android, but this command is executed on all platforms.

2019-02-04 12:20 UTC, Rechi commented on tools/depends/target/Toolchain_binaddons.cmake.in
> +  list(APPEND CMAKE_SYSTEM_LIBRARY_PATH @use_toolchain@/sysroot/usr/lib/@use_host@/@use_ndk_api@)
This is only true for android, but this command is executed on all platforms.

2019-02-04 13:58 UTC, peak3d commented
@rechi the commit message tells what it does, it should still work with NDK 18, but there should be support for NDK 19 now

2019-02-04 14:21 UTC, Rechi commented
Should or you actually did a complete successful depends rebuild with NDK 19 already?
Here target python fails to build with this PR and NDK 19.

2019-07-19 15:23 UTC, jenkins4kodi commented
@peak3d this needs a rebase

2019-08-26 12:10 UTC, closed without merging