Correct interface documentation for PVR API GetStreamProperties() function
xbmc/xbmc pull request #15480
Opened 2019-02-10 04:24 UTC by djp952

## Description
The PVR interface documentation for GetStreamProperties() is incorrect.  This function is not called by Kodi if bHandlesInputStream is true.  It is only called when bHandlesDemuxing is true.

## Motivation and Context
While it would be great if this function was called when bHandlesInputStream is true as an alternative to GetChannelStreamProperties/GetRecordingStreamProperties, that is not the case.

## How Has This Been Tested?
No testing - interface documentation change only via code comments

## Screenshots (if appropriate):

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [X] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [X] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2019-02-10 12:59 UTC, ksooo approved these changes
Nice find. Thanks.

2019-02-10 13:01 UTC, ksooo requested changes
Please remove the unrelated "close stream" commit from this PR.

2019-02-18 05:03 UTC, djp952 commented
Sorry I didn't see this ksooo .. the offending commit has been removed.  You should see only the header file commit now.  djp952: sucking at git rebase since … forever.

2019-02-18 06:47 UTC, ksooo commented
Thanks.

2019-02-18 06:48 UTC, ksooo approved these changes

2019-02-18 06:48 UTC, ksooo commented
Jenkins error is unrelated.

2019-02-18 06:49 UTC, merged