PVR: Initialize timer info tag with first available timer type from client
xbmc/xbmc pull request #15882
Opened 2019-04-09 01:13 UTC by djp952

Initialize timer info tag with first timer type provided by the PVR client, when available, instead of arbitrarily trying to create a manual one-shot timer type which may not be supported and causes unnecessary errors in the log.

## Description
During construction, the CPVRTimerInfoTag class will attempt to default to a Manual One-Shot timer from the PVR client.  If creation fails, it will fall back to trying to create whatever the first available timer type from any PVR client happens to be.

If the PVR client does not support Manual One-Shot timers, the Kodi log will have a great deal of "PVR::CPVRTimerType::CreateFromAttributes: Unable to resolve timer type (0x1, 0xa, xxxxxxxx)" errors in it, one for every time a CPVRTimerInfoTag instance is created.

While there may have been a historic reason for defaulting to Manual One-Shot, it doesn't appear necessary any longer, making the error messages false-positive.  If Manual One-Shot isn't available, the code already falls back to a default type and continues without error.

The proposed change removes the arbitrary creation of a Manual One-Shot timer and instead, since the PVR client ID is known, retrieves the first available timer type for that client.  The CPVRTimerType::GetFirstAvailableType() method was modified to use the client ID instead of making a new method since this is the only place it's referenced.

## Motivation and Context
This change eliminates the plethora of false positive errors present in the Kodi logs if a PVR client does not support Manual One-Shot timers.  It should have no effect on the operation of the PVR subsystem since it was already falling back into similar code.  The original fallback didn't filter at all (for example PVR_TIMER_TYPE_FORBIDS_NEW_INSTANCES), the proposed change also does not.

## How Has This Been Tested?
Primary testing was on Windows 10, x64 and Win32 using my custom PVR (which does not support Manual One-Shot timers), with secondary testing on Android ARM64 (nVidia Shield).

I had set breakpoints on the offending error message and ran through unit testing of timers -- initial load, add/modify/delete.  All instances were generated from the CPVRTimerInfoTag constructor.  Ran the same unit testing after the modifications and ran into no issues with the same PVR timer operations (add/modify/delete), and verified that the message no longer appeared in the logs.

## Screenshots (if appropriate):

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2019-04-11 06:33 UTC, ksooo requested changes

2019-04-11 06:33 UTC, ksooo commented on xbmc/pvr/timers/PVRTimerType.h
>       * @return A timer type or NULL if none available.
Please add  "@param".

2019-04-11 06:33 UTC, ksooo commented on xbmc/pvr/timers/PVRTimerType.cpp
> +  return CPVRTimerTypePtr();
'return {};'

2019-04-11 06:33 UTC, ksooo commented on xbmc/pvr/timers/PVRTimerType.cpp
> +  if(client)
blank between 'if' and '('

2019-04-11 06:33 UTC, ksooo commented on xbmc/pvr/timers/PVRTimerType.cpp
> +    if(client->GetTimerTypes(types) == PVR_ERROR_NO_ERROR)
blank between 'if' and '('

2019-04-11 08:09 UTC, ksooo commented on xbmc/pvr/timers/PVRTimerType.cpp
> +  return CPVRTimerTypePtr();
I would suggest to rewrite this like:

```c++
const CPVRTimerTypePtr CPVRTimerType::GetFirstAvailableType(int iClientId)
{
  const CPVRClientPtr client = CServiceBroker::GetPVRManager().GetClient(iClientId);
  if (client)
  {
    std::vector<CPVRTimerTypePtr> types;
    if (client->GetTimerTypes(types) == PVR_ERROR_NO_ERROR && !types.empty())
      return *(types.begin());
  }
  return {};
}
```

2019-04-11 22:02 UTC, djp952 commented
Thanks @ksooo, all requested changes have been made.  Rebuilt and (lightly) unit tested.

For consistency in the .cpp file, I also replaced the other two instances of "return CPVRTimerTypePtr()" with "return {};", I'm guessing you would prefer them to all match, LMK if not and I'll undo those.

2019-04-12 05:09 UTC, ksooo approved these changes
Thank you.

2019-04-12 05:12 UTC, merged