New Skin.Name infolabel
xbmc/xbmc pull request #15894
Opened 2019-04-10 15:49 UTC by edit4ever

adds infolabel to return active skin name
useful for addon windows conditional elements based on skin

## Description
adds infolabel to return active skin name
useful for addon windows conditional elements based on skin
also cleans up trailing whitespaces from GUIInfoManager.cpp

## Motivation and Context
Adds the ability to handle conditional includes/visibility dependent on current skin
Useful for making addons compatible with Estuary specific includes/variables

## How Has This Been Tested?
Tested on latest LibreELEC Milhouse builds

## Screenshots (if appropriate):

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2019-04-10 23:19 UTC, scott967 commented
I see you have done a massive cleanup on the documentation for GuiInfoManager
Could you possibly add some missing skin infolabels/bools?  Namely:
label Skin.String(name)
bool Skin.HasSetting(name) Skin.String(name) Skin.String(string1,string2)
I couldn't figure out exactly where these should be inserted in the docs so didn't try to do it myself.

2019-04-11 05:44 UTC, ksooo commented
Could you please split your changes in two  commits - one for the  (massive) withespace cleanup, one for the new info label. Thanks.

2019-04-11 05:46 UTC, ksooo commented
And in case you want to add missing documentation for existing labels, do this on a third commit, please or  in another PR.

2019-04-11 05:50 UTC, ksooo requested changes

2019-04-11 05:50 UTC, ksooo commented on xbmc/GUIInfoManager.cpp
> +///     Returns the current skin name.
Please add  "@skinning_v19" marker.

2019-04-11 05:54 UTC, ksooo commented
@DaVukovic no new features in  v18, please.

2019-04-11 14:30 UTC, edit4ever commented
As requested:
  Split commits for new infolabel and whitespace cleanup
  Added v19 marker **but LibreELEC needs this in 18.2 if possible**

2019-04-11 14:44 UTC, ksooo commented
> Split commits for new infolabel and whitespace cleanup

 Thanks.

> LibreELEC needs this in 18.2 if possible

 For what does LE need this? How could LE need a certain Kodi feature? Kodi runs on LE, not vica versa. ;-)

2019-04-11 14:46 UTC, ksooo approved these changes
Thank you for your contribution.

2019-04-11 14:51 UTC, edit4ever commented
@ksooo Thanks!  Hopefully the discussion on the LE slack channel explained the need for the addition.

BTW - I'm happy to add documentation...but this was my first Kodi PR - so could you point me to where to add that? :-)

2019-04-11 15:23 UTC, ksooo commented
As discussed internally, the label better should be named `skin.id`, not `skin.name`.

2019-04-11 15:43 UTC, enen92 approved these changes
Thanks for the trailing whitespace cleanup and for adjusting the docs while contributing new features.

2019-04-11 16:30 UTC, ksooo commented
Please squash the two functional commits down to one and adapt the PR title.

2019-04-20 11:29 UTC, Rechi commented
jenkins build this please

2019-04-26 13:00 UTC, ksooo commented
@edit4ever despite from the fact that at some point in time this new label might get useful, knowing that we currently have no use case for it I suggest not to merge this until we actually need it. Every piece of code needs to be maintained and increases regression potential. Thus, I'm not a fan of dead code in the "product".

2019-04-26 14:22 UTC, edit4ever commented
No worries - you are correct that there isn't a use case at this point.  It's here if it is ever needed down the road or just to complete the skin infolabel section. (always seemed like this was missing to me)  :-)

2020-03-08 22:55 UTC, phunkyfish commented
PR has merit but will labelled `PR Cleanup: Backburner` and closed for now. Would be a candidate for inclusion down the line if it's required.

If the author would like it kept open please just request so on the PR.

2020-03-08 22:55 UTC, closed without merging