[win10] bump SDK to v10.0.17763.0
xbmc/xbmc pull request #15924
Opened 2019-04-16 08:04 UTC by afedchin

see title

2019-04-16 08:15 UTC, Rechi requested changes
cmake/scripts/windowsstore/ArchSetup.cmake and docs/README.Windows.md has to be updated too.

2019-04-16 09:14 UTC, Rechi approved these changes

2019-04-16 14:34 UTC, afedchin commented
jenkins build this please

2019-04-17 15:57 UTC, afedchin commented
jenkins build this please

2019-04-18 14:22 UTC, merged