Subtitles opacity
xbmc/xbmc pull request #16106
Opened 2019-05-09 08:51 UTC by bostrano

## Description
Add an option to change the opacity of subtitles between 0% and 100%.

## Motivation and Context
Currently, subtitles in Kodi are always fully opaque, i.e. alpha=1.0. Such subtitles cause several problems:

- When viewing HDR content, when bright subtitles appear in dark scenes the brightness difference is very large and [sears the eyes](https://www.reddit.com/r/hometheater/comments/9yr4nn/hdr_has_a_big_problem_that_nobody_seems_to_talk/) ([another reference](https://www.reddit.com/r/OLED/comments/858dd8/lg_c7_netflix_prime_hdrdv_subtitles_too_bright/)).
-  On LCD TV's with local dimming, when a bright subtitle appears over a dark scene it [causes the picture to flash brighter](https://www.reddit.com/r/samsung/comments/9sv6ga/qled_brightness_changes_when_subtitles_appear_on/). In addition, sometimes [blooming appears around the subtitles](https://www.reddit.com/r/bravia/comments/a5aszu/x900f_subtitles_and_blooming/).
- On OLED TV's, subtitles can [cause burn-in over time](https://www.youtube.com/watch?v=nOcLasaRCzY&feature=youtu.be&t=406).

Making subtitles semitransparent solves all of these problems. Netflix already supports semitransparent subtitles, and Kodi should support them as well.

Kodi already has a feature that changes the opacity of the *background* of the subtitles. But the subtitles themselves remain fully opaque when using that feature, so it doesn't solve the problems described above.

It's also possible to change the *color* of the subtitles, e.g. to gray. I tried to do that (change the color instead of the transparency), but changing the color doesn't do a good enough job to solve the problems described above.

## How Has This Been Tested?
I have tested this on Windows 10 64-bit. I viewed subtitles with an opacity of 25-100%. (Setting opacity to 100%, which is the default, disables this feature.)

Go to Settings (as Expert) > Player > Language, and change the "Opacity" slider.

## Screenshots (if appropriate):
![Kodi-subtitles](https://user-images.githubusercontent.com/49862308/57433344-eb242a00-7240-11e9-8a32-503d66ab5433.png)

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2019-05-09 08:52 UTC, bostrano commented
This is a redo of my previous pull request (which I have deleted). It fixes some tabs that should have been spaces. I submitted a new pull request in order to avoid polluting the commit history with commits whose only purpose is to fix these tabs.

2019-05-10 13:37 UTC, notspiff approved these changes
Code is fine, this feature is sane and a clear improvement. I'll merge in a couple of days if nobody says otherwise.

2019-05-10 18:30 UTC, lrusak requested changes
Looks good. Just a small request to change the setting definition location

2019-05-10 18:30 UTC, lrusak commented on xbmc/settings/Settings.cpp
> +const std::string CSettings::SETTING_SUBTITLES_OPACITY = "subtitles.opacity";
can you move this into `OverlayRenderer.h` It can be included in the `OVERLAY` namespace as it doesn't need to be a general `CSetting`

2019-05-10 18:30 UTC, lrusak commented on xbmc/settings/Settings.h
> +  static const std::string SETTING_SUBTITLES_OPACITY;
same thing here

2019-05-13 08:06 UTC, notspiff commented
sorry to be a pain but please squash into original commit.

2019-05-13 11:50 UTC, orenh1 commented
Commit squashed with extreme prejudice.

2019-05-13 12:34 UTC, FernetMenta commented
This PR is incomplete because the new setting has only effect on text subtitles, a type that is hopefully eliminated by @enen92.

2019-05-13 12:56 UTC, notspiff commented
even if incomplete it represents a clear improvement. i have talked with enen92, we will merge this and he'll keep the feature working after his refactor.

2019-05-20 07:14 UTC, merged