[network] remove class NetworkAccessPoint and unused dialog CGUIDialogAccessPoints
xbmc/xbmc pull request #16120
Opened 2019-05-12 17:52 UTC by lrusak

This is legacy and unused code. Let's just get rid of it :rocket:

2019-05-14 09:34 UTC, Rechi requested changes
`CNetworkInterface::GetName`, `CNetworkInterface::IsWireless` and `CNetworkBase::GetInterfaceByName`  are now also unused.

2019-05-16 04:53 UTC, lrusak commented
jenkins build this please

2019-05-17 23:06 UTC, lrusak commented
@Rechi better now?

2019-05-18 14:49 UTC, Rechi reviewed
Better, but `CNetworkInterfaceWin10::m_adaptername`, `CNetworkInterfaceWin10::m_winRT`, `CNetworkInterfaceWin10::m_profile`, `CNetworkInterfaceWin32::m_adaptername` and some includes are obsolete too.

2019-05-18 14:49 UTC, Rechi commented on xbmc/platform/win10/network/NetworkWin10.h
>    std::string m_adaptername;
only assigned, but value is never used

2019-05-18 14:49 UTC, Rechi commented on xbmc/platform/win32/network/NetworkWin32.h
> +
unrelated space change

2019-05-18 18:34 UTC, lrusak commented
> Better, but `CNetworkInterfaceWin10::m_adaptername`, `CNetworkInterfaceWin10::m_winRT`, `CNetworkInterfaceWin10::m_profile`, `CNetworkInterfaceWin32::m_adaptername` and some includes are obsolete too.

I can try but I would only be poking in the dark and would be relying on jenkins. I could use some help here.

2019-05-24 13:24 UTC, Rechi approved these changes

2019-05-24 13:26 UTC, notspiff approved these changes

2019-05-24 13:26 UTC, merged