Always highlight the OK button when installing an add-on
xbmc/xbmc pull request #16802
Opened 2019-10-18 19:48 UTC by gusandrianos

## Description
This solves #16754. 
Admittedly this is somewhat of a personal opinion issue, although I think it is a valid one. It can *probably* be a better fix by highlighting the "cancel" button first, in order to prevent accidental clicks to the "OK" button.

## Motivation and Context

## How Has This Been Tested?
I tested on Linux Mint 19.2

## Screenshots (if appropriate):

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ x ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ x ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ x ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ x ] All new and existing tests passed

2019-10-18 19:53 UTC, a1rwulf commented
Please set Milestone and Labels ;-)
I think it's perfectly fine to set the default selection to OK when you want to install something.
We discussed this at devcon as well.

2019-10-18 19:55 UTC, gusandrianos commented
@a1rwulf I can't recall we did, I will.

2019-10-18 19:57 UTC, a1rwulf commented
Probably you weren't part of the discussion, but @kib and some others talked about the exact same thing.
Highlighting `OK" is ok when you ask for confirmation of an action like installing.
If you want to prevent the user from a mistake, `Cancel` should be the default.
Eg.:
Do you really want to delete this file?

2019-10-18 20:06 UTC, HitcherUK commented
Just to be certain - this only applies when installing addons right?

2019-10-18 20:07 UTC, gusandrianos commented
@HitcherUK AFAIK-tested, yes.

2019-10-18 21:44 UTC, ronie commented
i'm afraid this isn't correct.
afaik the code you've modified is used to set focus to the 'detailed list' when needed.

skins hardcode the focus to the simple list. kodi forces focus to the detailed list in case the detailed list is visible.

you check check it is broken now by going to Settings > Interface > Skin.
it should focus the list of skins, but with this pr the 'get more' button is focused.

2019-10-19 10:34 UTC, da-anda commented
> Probably you weren't part of the discussion, but @kib and some others talked about the exact same thing.
> Highlighting `OK" is ok when you ask for confirmation of an action like installing. If you want to prevent the user from a mistake, `Cancel` should be the default.
> Eg.:
> Do you really want to delete this file?

correct, that's what we decided on during devcon

2019-10-19 11:33 UTC, garbear commented
My comment [here](https://github.com/xbmc/xbmc/issues/16754#issuecomment-541542195) might be of some use

2019-10-24 22:44 UTC, VelocityRa commented on xbmc/dialogs/GUIDialogSelect.h
> +  void SetButtonFocus();
```suggestion
  void SetButtonFocus(bool buttonFocus);
```
so it's consistent with the rest of the setters.

2019-10-25 06:06 UTC, Rechi commented on xbmc/dialogs/GUIDialogSelect.cpp
> +    m_focusToButton(false),
use default member initialization

2019-10-30 23:38 UTC, VelocityRa requested changes

2019-10-30 23:38 UTC, VelocityRa commented on xbmc/dialogs/GUIDialogSelect.h
> +  bool m_focusToButton = {};
```suggestion
  bool m_focusToButton{};
```

2019-10-31 18:23 UTC, VelocityRa approved these changes

2019-11-21 07:57 UTC, gusandrianos commented
Jenkins build this please

2019-11-21 08:51 UTC, DaveTBlake commented
@ronie are you happy with this now?

2019-11-21 16:18 UTC, ronie commented
@DaveTBlake yup, works ok now.

2019-11-21 18:29 UTC, garbear approved these changes

2019-11-21 20:28 UTC, merged

2020-01-01 22:02 UTC, Montellese commented
This breaks the possibility to focus a dependency in the list of dependencies and view its details.

2020-01-01 22:19 UTC, Montellese commented
c3bc22d5aeeffcfa7564b6e06dd2b4a5fffa9570 should fix the issue.

2020-01-01 22:22 UTC, gusandrianos commented
@Montellese This was the intention. If you want to view the details in one of the items, you move to it and you do so. More often than not, you just install the add-on and it makes sense to have "OK" highlighted. This was discussed during this year's devcon and it was a team decision.

2020-01-01 22:24 UTC, ronie commented
> you move to it and you do so

please try that ;-)

i can confirm the issue @Montellese reported.

2020-01-01 22:25 UTC, Montellese commented
I'm perfectly fine with having the OK button pre-select but now it is impossible to move the focus to one of the dependencies in the list because your changes to `CGUIDialogSelect::OnMessage()` prevent the possibility to focus the list at all if `m_focusToButton` has been set. I'm pretty sure that was not the intention.

With my change the OK button is still pre-focused and you can also change the focus to all the other controls in the dialog (including the list of dependencies).

2020-01-01 22:26 UTC, gusandrianos commented
I'll take a look tomorrow, thanks for the heads up, I don't think I noticed it but maybe I didn't look for it to do so (?)

2020-01-01 22:27 UTC, Montellese commented
See #17115 for a PR containing the commit mentioned above.

2020-01-01 22:27 UTC, Montellese commented
@gusandrianos I also only found out by accident that I can select one of the dependencies and navigate to its details.