Added Dialogs for direct Audiostream and Subtitle switching
xbmc/xbmc pull request #16825
Opened 2019-10-24 19:42 UTC by lobermann

## Description
Mentioned this in one of the last PRs I made. This Adds two new dialogs that allow direct switching of audiostream and subtitle.

## Motivation and Context
In order not to have to always navigate through the menu if you want to switch the audiostream or subtitle, this two dialogs can be called directly from the OSD and allow quick and easy change of them. (Similar to how it is on netflix for example).
Looking forward for feedback. Might not find it's way into Estuary (as we will not add any new buttons there) but there might be other skins interested in using it.

## How Has This Been Tested?
Tested on MacOS and LibreElec.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2019-10-24 20:20 UTC, lrusak commented
Would you mind adding some screenshots?

2019-10-24 21:27 UTC, ksooo requested changes
This needs a bit more love and I'm not sure the implementation is correct at all. Implementing a dialog which does nothing than to open another dialog from its `OnInitWindow`override looks strange.

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogAudioSelect.cpp
> +#include "video/VideoDatabase.h"
I doubt that all these headers are actually needed. Example: `utils/log.h` included, but I cannot see any use of `CLog`

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogAudioSelect.cpp
> +  CFileItemList options;
I would define vars where they are actually first used.

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogAudioSelect.cpp
> +  if (dialog == NULL)
`if (dialog == nullptr)` or `if (!dialog)`

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogAudioSelect.cpp
> +    std::string strLanguage;
I would define vars where they are actually first used.

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogAudioSelect.cpp
> +    if (info.name.length() == 0)
`if (info.name.empty())`

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogAudioSelect.cpp
> +    CFileItemPtr item(new CFileItem(strItem.c_str()));
`std::make_shared<CFileItem>(strItem);`

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogAudioSelect.cpp
> +  dialog->SetHeading(g_localizeStrings.Get(STRING_AUDIO_HEADER).c_str());
`.c_str()`not needed.

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogAudioSelect.h
> +class CFileItemList;
These forward decls are not needed.

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogSubtitleSelect.h
> +class CFileItemList;
These forward decls are not needed.

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogSubtitleSelect.h
> +#include <string>
include not needed.

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogAudioSelect.h
> +#include <string>
include not needed.

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogSubtitleSelect.cpp
> +#include "system.h"
I doubt that all these headers are actually needed. Example: `utils/log.h` included, but I cannot see any use of `CLog`

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogAudioSelect.cpp
> +using namespace XFILE;
I don't think you need this using statements.

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogSubtitleSelect.cpp
> +using namespace XFILE;
I don't think you need this using statements.

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogSubtitleSelect.cpp
> +  CFileItemList options;
I would define vars where they are actually first used.

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogSubtitleSelect.cpp
> +    std::string strLanguage;
I would define vars where they are actually first used.

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogSubtitleSelect.cpp
> +  dialog->SetHeading(g_localizeStrings.Get(STRING_SUBTITLES_HEADER).c_str());
`.c_str()`not needed.

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogSubtitleSelect.cpp
> +    CFileItemPtr item(new CFileItem(g_localizeStrings.Get(1223).c_str()));
`std::make_shared<CFileItem>(g_localizeStrings.Get(1223));`

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogSubtitleSelect.cpp
> +    if (info.name.length() == 0)
`if (info.name.empty())`

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogSubtitleSelect.cpp
> +  if (dialog == NULL)
`if (dialog == nullptr)` or `if (!dialog)`

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogSubtitleSelect.cpp
> +    CFileItemPtr item(new CFileItem(strItem.c_str()));
`std::make_shared<CFileItem>(strItem);`

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogAudioSelect.cpp
> +  ShowAudioSelect();
Are you sure it is correct to show the dialog in `OnInitWindow` - while the dialog is not yet fully initialized? Did you copy this pattern from an existing dialog implementation?

2019-10-24 21:27 UTC, ksooo commented on xbmc/video/dialogs/GUIDialogSubtitleSelect.cpp
> +  ShowSubtitleSelect();
Are you sure it is correct to show the dialog in OnInitWindow - while the dialog is not yet fully initialized? Did you copy this pattern from an existing dialog implementation?

2019-10-27 09:36 UTC, da-anda commented
not against such a dialog in general, but aren't skins already able to add such a dialog/feature using currently available infolabels etc? I remember the balloon OSD popup in Confluence that had a similar feature.

And since you mentined Netflix. Netflix uses a combined view to switch audio and subtitle language which I actually like quite a lot. What was your underlying idea for going with two separate dialogs instead of having something like a `LanguageSelectDialog` (or however we might call that)?

2020-05-30 09:13 UTC, jenkins4kodi commented
@lobermann this needs a rebase

2022-04-03 13:48 UTC, lobermann commented
@da-anda @ksooo to follow up on my open PR's, I guess we are not going to merge this one as it is and also it seems that this functionality is also achievable just within the skin. So I guess we can close this?

2022-04-04 16:03 UTC, da-anda commented
strictly by looking at the code, I can't really say if it makes sense to add these dialogs or not. I know for certain that you can cycle through subs and audio streams via builtins that can be triggered by the skin in any way it likes. I however am not sure if skins are currently able to get a list of all available streams/languages for subs, audio tracks and video (in case of multi video stream containers) and then directly select a specific one. This in fact might be a nice addition to have (in case it's currently not yet possible), but I'm not sure if the best/only way to do this will be a new dialog that skins MUST add since it will be new core UI element/dialog that way, or if it would somehow be possible achieve this just by using infolabels and builtins, so that could integrate it in whatever form they like (new dialog or just via a menu that is tightly integrated into the OSD, like in Netflix).

@ronie do you know out of the top of your head if a feature like this would be possible via just infolabels and builtins?

2024-03-02 22:42 UTC, luzpaz commented
any traction here ?

2024-03-03 10:08 UTC, Hitcher commented
Having the ability to open these dialogs directly is a positive imo.

2024-03-03 10:54 UTC, jjd-uk commented
Agreed it would be nice for the skin to be able to directly call the audio and subtitle selection dialogs. Would allow an improved version of https://github.com/xbmc/xbmc/pull/22557 where the toggle buttons are replaced by buttons opening the selection dialogs.

2024-10-18 12:03 UTC, CastagnaIT commented
superseeded by #25762

2024-10-18 12:03 UTC, closed without merging