fixed: trim platform string prior to split
xbmc/xbmc pull request #16943
Opened 2019-11-19 11:00 UTC by notspiff

if not a tag like
<platforms>
  all
</platforms>

will fail to match since the "all" entry will contain a newline

2019-11-19 11:22 UTC, SylvainCecchetto commented
Just tested the OSX build, and I can confirm that I can now install my repo addon (https://repo.cecchettosylvain.fr/zip/repository.catchuptvandmore.krypton-leia.beta-0.0.5.zip) with this commit.
Thank you!

2019-12-04 13:57 UTC, AlwinEsch commented
Have checked and seen this is not enough. It works if only one OS is there, e.g.
```xml
  <platforms>
    all
  </platforms>
```

But e.g. not with this:
```xml
  <platforms>
    windows
    linux
    osx
  </platforms>
```

Also can sometimes tabs inside.

With this it has worked:
```cpp
      if (element && element->GetText() != nullptr)
      {
        std::string platforms = element->GetText();
        StringUtils::Replace(platforms, "\n", " ");
        StringUtils::RemoveDuplicatedSpacesAndTabs(platforms);
        addon->m_platforms = StringUtils::Split(platforms, " ");
      }
```

2019-12-04 14:00 UTC, AlwinEsch requested changes
See my note

2019-12-15 14:23 UTC, AlwinEsch commented
@notspiff how is the state about this?
Is very good to fix and Thanks a lot to find this bug!

2019-12-15 17:44 UTC, notspiff commented
Will see if i find some time tmrw

søn. 15. des. 2019, 15:23 skrev Alwin Esch <notifications@github.com>:

> @notspiff <https://github.com/notspiff> how is the state about this?
> Is very good to fix and Thanks a lot to find this bug!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/xbmc/xbmc/pull/16943?email_source=notifications&email_token=ABMS2YFTQLCUSW6HLERRY63QYY4UPA5CNFSM4JPBSUN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEG42HGQ#issuecomment-565814170>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABMS2YCGIKTRJITXQJZU74TQYY4UPANCNFSM4JPBSUNQ>
> .
>

2019-12-16 09:18 UTC, Rechi commented on xbmc/addons/addoninfo/AddonInfoBuilder.cpp
> +        addon->m_platforms = StringUtils::Split(platforms, " ");
```suggestion
        std::vector<std::string> platforms = StringUtils::Split(element->GetText(), { " ", "\t", "\n", "\r" });
        platforms.erase(
            std::remove_if(platforms.begin(), platforms.end(),
                           [](const std::string& platform) { return platform.empty(); }),
            platforms.cend());
        addon->m_platforms = platforms;
```

2019-12-17 08:22 UTC, Rechi reviewed
carriage return isn't considered
strings staring or ending with white spaces, cause an empty string at the beginning or end of `m_platforms` vector

2019-12-17 09:48 UTC, notspiff commented
arf, the friggan typewriter os strikes again. updated.

2020-01-30 07:14 UTC, SylvainCecchetto commented
Jenkins build this please

2020-03-09 18:13 UTC, phunkyfish commented
@AlwinEsch are you happy with this now?

2020-03-09 18:16 UTC, AlwinEsch approved these changes
I'm happy with them.

2020-03-09 18:22 UTC, phunkyfish commented
@notspiff your button ;)

2020-03-10 07:58 UTC, merged