[clang-format] always use a line per constructor initialiser for longer lines
xbmc/xbmc pull request #16962
Opened 2019-11-24 20:09 UTC by phunkyfish

## Description

Ensures for longer lines that this occurs:

```cpp
MyClass::CMyClass(bool bBoolArg,
                  int iIntegerArg,
                  const std::string& strSomeText,
                  const std::shared_ptr<CMyOtherClass>& myOtherClass)
  : m_bBoolArg(bBoolArg),
    m_iIntegerArg(iIntegerArg),
    m_strSomeText(strSomeText),
    m_myOtherClass(myOtherClass)
{
}
```

But never this:

```cpp
MyClass::CMyClass(bool bBoolArg,
                  int iIntegerArg,
                  const std::string& strSomeText,
                  const std::shared_ptr<CMyOtherClass>& myOtherClass)
  : m_bBoolArg(bBoolArg), m_iIntegerArg(iIntegerArg), m_strSomeText(strSomeText)
{
}
```

I.e. if a constructor lines is longer than `.clang-format` column limit then there will always be one initialiser per line.

This change does not effect constructor lines short than the `.clang-format` column limit.

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2019-11-25 06:00 UTC, garbear approved these changes

2019-11-25 06:07 UTC, Paxxi approved these changes
I'm a bit worried that using such a new option could lead to a lot of churn on constructor formatting depending on the version of clang-format.
Either we accept that and go ahead or we don't use it. If someone has submitted a clang-formatted PR we should never request formatting changes because they used the wrong clang-format version imo.

2019-11-25 06:14 UTC, ksooo commented
>  If someone has submitted a clang-formatted PR we should never request formatting changes because they used the wrong clang-format version imo.

 Why not? We also require them to use other tools with at least  a certain version. I don't see a difference to minimal required SDK version, for example.

2019-11-25 06:19 UTC, Paxxi commented
Linux distros are slow to add newer versions so it could make it a hassle to install the correct version. Is v9 available in any version of Ubuntu right now?

One of the main values with clang-format imo is that it lowers the bar to contribute. If you use the tool your PR should pass formatting guidelines.

2019-11-25 07:28 UTC, Rechi reviewed
- The documentation mentioning `clang-format` has to be updated that at least version 9 is required.
- The server running `git-clang-format` for the whole PR and per commit during a PR build has to be updated.

2019-11-25 07:44 UTC, Paxxi commented
Looking at https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=clang-format&searchon=names it appears that clang-format 9 isn't available in Ubuntu yet. If that's correct it's not feasible to require that they install or have it installed already unless we provide it in our apt repo.

2019-11-25 08:29 UTC, fritsch commented
It's here: https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=clang-format-9&searchon=names but only in eon

2019-11-25 08:52 UTC, Paxxi commented
Oh, I read the (devel) as it not being released yet, sorry about that 😄

2019-11-25 10:39 UTC, fritsch commented
You are right never the less. Many are on 18.04 LTS and will stay there until 20.04

2019-11-25 10:42 UTC, phunkyfish commented
If you run clang-format using the above `.clang-format` but are using clang-format 8 does it give an error or ignore the option?

2020-03-09 18:15 UTC, phunkyfish commented
As 20.04 is out soon maybe this can be revisited soon.

2020-03-09 18:23 UTC, AlwinEsch approved these changes

2020-04-19 11:43 UTC, phunkyfish commented
Ubuntu should be ok now:
```
Package clang-format-9
bionic (18.04LTS) (devel): Tool to format C/C++/Obj-C code [universe]
1:9-2~ubuntu18.04.2 [security]: amd64 i386
bionic-updates (devel): Tool to format C/C++/Obj-C code [universe]
1:9-2~ubuntu18.04.2: amd64 arm64 armhf i386 ppc64el s390x
eoan (19.10) (devel): Tool to format C/C++/Obj-C code [universe]
1:9-2: amd64 arm64 armhf i386 ppc64el s390x
focal (devel): Tool to format C/C++/Obj-C code [universe]
1:9.0.1-12: amd64 arm64 armhf i386 ppc64el s390x
```

@Rechi where and how would I update this on this on the server running git-clang-format for PRs?

2020-04-19 11:47 UTC, Rechi commented
You are missing Ubuntu Xenial and also the correct package for checking versions is clang-format instead of clang-format-<CLANG-VERSION>.

2020-04-19 12:37 UTC, phunkyfish commented
> You are missing Ubuntu Xenial and also the correct package for checking versions is clang-format instead of clang-format-.

Ok, then maybe this waits for kodi 20. I don't follow the mention of `clang-format-`. Did I miss something?

2020-04-19 13:41 UTC, Rechi commented
GitHub hides a part of the comment, I wrote `clang-format-<CLANG-VERSION>`

2020-04-19 14:18 UTC, phunkyfish commented
> GitHub hides a part of the comment, I wrote `clang-format-<CLANG-VERSION>`

Cool, makes sense.

2020-07-15 10:51 UTC, DaveTBlake approved these changes

2020-07-17 09:52 UTC, yol approved these changes

2020-07-17 10:08 UTC, Rechi requested changes
The cmake ClangFormat find module has to check the clang-format version, otherwise building Kodi with an older clang-format version installed will fail.

2020-07-17 11:42 UTC, phunkyfish commented
Ok, cool. Thanks @Rechi

2020-07-19 10:45 UTC, Rechi commented
No, because then CMake looks for `clang-format-9` instead of `clang-format`.

2020-07-19 17:32 UTC, phunkyfish commented
So like this:

```find_program(CLANG_FORMAT_EXECUTABLE
                              NAMES clang-format
                                            clang-format-9)```

2020-07-21 08:44 UTC, Rechi commented
No, because `clang-format` could be version 8.0 or any other version not 9.0 or higher.

2020-07-21 10:23 UTC, phunkyfish commented
Ok, I’ll need a good hint so as I’m of ideas.

Do you have a suggested change?

2021-02-07 19:01 UTC, DaveTBlake commented
This seems to have got forgotten, and clearly isn't happening in v19 code, so bump to v20 and @phunkyfish please pursue it for that.

2021-02-07 19:02 UTC, phunkyfish commented
Will do. Thanks @DaveTBlake

2022-10-04 09:50 UTC, jenkins4kodi commented
@phunkyfish this needs a rebase

2022-10-06 21:13 UTC, phunkyfish commented
Jenkins build this please

2022-10-07 01:37 UTC, fuzzard commented on cmake/modules/buildtools/FindClangFormat.cmake
> +
Can i suggest the following

```
#.rst:
# FindClangFormat
# ----------
# Finds clang-format

find_program(CLANG_FORMAT_EXECUTABLE clang-format)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(ClangFormat REQUIRED_VARS CLANG_FORMAT_EXECUTABLE)

if(CLANGFORMAT_FOUND)

  set(CLANGFORMAT_MINVERSION "9.0")

  execute_process(COMMAND clang-format --version ERROR_QUIET OUTPUT_VARIABLE CLANG_FORMAT_VERSION_OUTPUT)
  string(REGEX MATCH "([0-9]+)\\..*" CLANG_FORMAT_VERSION ${CLANG_FORMAT_VERSION_OUTPUT})
  if(CLANG_FORMAT_VERSION VERSION_LESS_EQUAL ${CLANGFORMAT_MINVERSION})
    message(WARNING "clang-format must be at least version ${CLANGFORMAT_MINVERSION}. The version found is ${CLANG_FORMAT_VERSION}")
    set(CLANGFORMAT_FOUND OFF CACHE BOOL "" FORCE)
    set(CLANG_FORMAT_EXECUTABLE "CLANG_FORMAT_EXECUTABLE-NOTFOUND" CACHE STRING "" FORCE)
  endif()
endif()

mark_as_advanced(CLANG_FORMAT_EXECUTABLE)

```

We only do the version check if clang-format is found. We extract the version number to s single variable (for if/when it needs to be updated).
It also sets the cache variable for CLANGFORMAT_FOUND and CLANG_FORMAT_EXECUTABLE to false/notfound

2022-10-07 06:55 UTC, Rechi requested changes, later dismissed
Version hacking in the find module is wrong.
Use the correct CMake way for checking versions.

2022-10-07 07:12 UTC, fuzzard commented
I dont really understand what you're asking for here @Rechi 

find_program calls do not have any understanding of versioning, and do not make version info available.
Clang-format doesnt provide *ConfigVersion.cmake files to retrieve any version info, there is no pkg-config data provided either.

What exactly is the "Correct Cmake way" for this?

2022-10-16 07:45 UTC, Rechi commented
Read the documentation of [find_package](https://cmake.org/cmake/help/latest/command/find_package.html) and [FindPackageHandleStandardArgs](https://cmake.org/cmake/help/latest/module/FindPackageHandleStandardArgs.html) and how those two commands interact. There is no need to touch the find module.

There is also one dependency of Kodi with a minimum version requirement, where it is done correct.

2022-10-16 08:24 UTC, phunkyfish commented
Which dependency?

2024-08-09 07:37 UTC, phunkyfish commented
@Rechi, as Ubuntu 24.04 is out now could you please suggest the change we need to make to get this in? I’d appreciate it rather that have this PR lie around for another release. Thanks in advance.

2025-08-09 18:06 UTC, garbear commented
Is this still wanted? Now is a good time to get it in.

2025-08-09 20:59 UTC, phunkyfish commented
Yes, I believe so. As an alternative solution has not been offered, and the current one has many approvals I say it should go in.

2025-08-09 21:12 UTC, Rechi commented
As mentioned already, this version hacking in the find module is wrong and has to be removed.
Now there are already 14 general dependencies and 8 platform specific dependencies, which require a minimum version the correct way.

2025-08-10 05:50 UTC, phunkyfish commented
Could you please point to one as an example?

2025-08-10 05:53 UTC, Rechi commented
https://github.com/xbmc/xbmc/blob/af2dae5a49b72fac42bd354ca5d86a816853d0b9/CMakeLists.txt#L233-L283

2025-08-10 07:49 UTC, phunkyfish commented
> https://github.com/xbmc/xbmc/blob/af2dae5a49b72fac42bd354ca5d86a816853d0b9/CMakeLists.txt#L233-L283

Thank you. PR updated. Anything else required @Rechi?

Or should it be optional? Not sure if it's available on all platforms.

2025-08-10 08:21 UTC, phunkyfish commented
Looks like it needs to be optional

2025-08-10 08:48 UTC, Rechi commented on CMakeLists.txt
> +                  ClangFormat>=9.0
clang-format is now in addition a library and no longer only a buildtool?

2025-08-10 09:31 UTC, phunkyfish commented on CMakeLists.txt
> +                  ClangFormat>=9.0
Ah, ok. Moved to build tools section.

2025-08-12 00:35 UTC, garbear approved these changes

2025-08-12 00:35 UTC, garbear commented
Good to go?

2025-08-12 02:31 UTC, merged