StringUtils: define FMT_DEPRECATED to fix windows coverity build
xbmc/xbmc pull request #17291
Opened 2020-01-29 03:45 UTC by lrusak

This fixes the following issue when running coverity on windows. If someone has a better idea I'm all ears.

```
2020-01-25T04:28:58.643972Z|cov-translate|9652|output|> "F:\builds\workspace\WIN-64-CoverityScan\project\BuildDependencies\x64\include\
2020-01-25T04:28:58.643972Z|cov-translate|9652|output|> 
2020-01-25T04:28:58.643972Z|cov-translate|9652|output|>           fmt/core.h", line 544: error #1882: attribute does not apply to any
2020-01-25T04:28:58.643972Z|cov-translate|9652|output|> 
2020-01-25T04:28:58.643972Z|cov-translate|9652|output|>           entity
2020-01-25T04:28:58.643972Z|cov-translate|9652|output|> 
2020-01-25T04:28:58.643972Z|cov-translate|9652|output|>   using parse_context FMT_DEPRECATED_ALIAS = basic_format_parse_context<char>;
2020-01-25T04:28:58.643972Z|cov-translate|9652|output|> 
2020-01-25T04:28:58.643972Z|cov-translate|9652|output|>                       ^
```

2020-01-29 15:47 UTC, Rechi requested changes
This is wrong, correct is the following change.

```diff
--- a/include/fmt/core.h
+++ b/include/fmt/core.h
@@ -142,7 +142,7 @@
 #endif
 
 // Workaround broken [[deprecated]] in the Intel compiler and NVCC.
-#if defined(__INTEL_COMPILER) || FMT_NVCC
+#if defined(__INTEL_COMPILER) || FMT_NVCC || defined(__COVERITY__)
 #  define FMT_DEPRECATED_ALIAS
 #else
 #  define FMT_DEPRECATED_ALIAS FMT_DEPRECATED
```

2020-01-29 17:05 UTC, lrusak commented
@Rechi Thank you for your kind words! They are very much appreciated!

Did you happen to send that patch upstream yet?

2020-01-29 17:12 UTC, Paxxi commented
I guess you could change the ifdef from TARGET_WINDOWS to __COVERITY__ and also add an undef FMT_DEPRECATED to avoid warnings about redefining it.

That should cover Linux as well if for some reason we would hit it there

2020-01-30 08:17 UTC, Rechi requested changes
This is still wrong, don't workaround 3rd party library issues in Kodi code.

2020-01-30 12:24 UTC, Paxxi commented
Did we have a team discussion somewhere where we agreed on this rule?
Yes it's technically cleaner but a lot more work so there would have to be very good reasons for establishing that as a rule

2020-01-30 12:26 UTC, Rechi commented
The reason for the correct fix and not the hacky workaround is, that otherwise it has be added before every fmt header include.

2020-01-30 13:57 UTC, Paxxi commented
Ok, I guess we could put it in https://github.com/xbmc/xbmc/blob/85ba2e50e56d9bc9c9e5102ebffe2cf898d50a64/cmake/scripts/common/ArchSetup.cmake#L109 to avoid that issue. Not sure if it's a big risk that anyone would start using fmt outside of StringUtils though as that's the interface for string related stuff.

2020-01-30 16:47 UTC, lrusak commented
I think it's fine as is until @Rechi submits his patch upstream 😺

2020-01-30 16:53 UTC, Paxxi commented
Agreed

2020-01-30 16:53 UTC, merged