fixed: Unable to mark files not in video db yet as watched
xbmc/xbmc pull request #17414
Opened 2020-02-28 07:43 UTC by arnova

Strange that I/we didn't notice this before....

2020-02-28 17:10 UTC, ksooo commented
Have you tested that this has no bad side effects, like music items showing "mark as watched" now?

2020-02-29 07:39 UTC, ksooo requested changes
This does not work, because it now shows "mark as watched" for non-video items like songs.

![screenshot000](https://user-images.githubusercontent.com/3226626/75603468-e3cf5500-5ace-11ea-8e4c-7009f20b71bd.png)

2020-02-29 08:17 UTC, arnova commented
> This does not work, because it now shows "mark as watched" for non-video items like songs.
> 
> ![screenshot000](https://user-images.githubusercontent.com/3226626/75603468-e3cf5500-5ace-11ea-8e4c-7009f20b71bd.png)

Also updated :-) Should work properly now.

2020-02-29 09:57 UTC, howie-f commented
tbh i cannot reproduce neither in 18 nor 19

2020-04-25 11:08 UTC, ksooo commented on xbmc/video/ContextMenus.cpp
> +    if (item.IsVideo() && (currentWindow == WINDOW_VIDEO_NAV))
No need to make the expensive Servicebroker call if the cheap isvideo call evaluated to false.

2020-04-26 05:45 UTC, DaVukovic commented
@howie-f 

>tbh i cannot reproduce neither in 18 nor 19

I couldn't reproduce as well. It's because you might have set content on your sources but not scanning those items to your library. If you set content to your sources you are easily able to mark those entries as watched. So to reproduce add a source and set content to "none" and you will see that you are not able to mark it as watched. The context menu entry is there, but the icon isn't shown.

2020-04-26 20:49 UTC, phunkyfish commented
@arnova could you provide repro instructions? How exactly do access a video item so it's not in the VideoDB yet? Or is it simply a video item in a source prior to a library scan?

2020-04-27 13:55 UTC, arnova commented
> @arnova could you provide repro instructions? How exactly do access a video item so it's not in the VideoDB yet? Or is it simply a video item in a source prior to a library scan?

@phunkyfish : Browse to a folder in the files section which hasn't been opened before with "extract flags/thumbsnails" enabled is that will automatically add the file item to the video db. And RMB on one of the files there.

@ksooo : It just came to mind that enabling this logic for "Mark as unwatched" makes no sense since any item that is considered watched must already be in the db. Another question: you mentioned that it shouldn't be in IsVisible() but atm I don't see any other location where this should go then. Mind elaborating? Wouldn't it be better to drop is in IsVisible() for now and fixing it up after the refactor?

2020-04-27 14:29 UTC, phunkyfish commented
@arnova woohoo, now I see, thanks!

2020-04-27 14:33 UTC, phunkyfish requested changes

2020-04-27 14:33 UTC, phunkyfish commented on xbmc/video/ContextMenus.cpp
> +    if (currentWindow == WINDOW_VIDEO_NAV))
return  currentWindow == WINDOW_VIDEO_NAV;

2020-04-27 15:27 UTC, ksooo commented
I will not stop saying: Making the visible decision based on the active window is a hack hack hack!

2020-05-09 11:44 UTC, jenkins4kodi commented
@arnova this needs a rebase

2020-07-15 08:54 UTC, DaveTBlake commented
> I will not stop saying: Making the visible decision based on the active window is a hack hack hack!

Then @ksooo how should we prevent items on the context menu that are not wanted on certain windows? Seems to me that sometimes the  window is also part of the context

2020-07-15 08:59 UTC, ksooo commented
Yes, the window can be part of the context, but not for watched/unwatched as watched state is completely unrelated to any window.

2020-07-15 09:03 UTC, ksooo commented
BTW: doesn't fix https://github.com/xbmc/xbmc/pull/18023 fix this issue? Not sure about this.

2020-07-18 08:05 UTC, arnova commented
> BTW: doesn't fix #18023 fix this issue? Not sure about this.

I don't see how that would fix this issue.

2020-07-18 08:23 UTC, ksooo commented
content-less == no db entry?

2020-07-19 08:29 UTC, arnova commented
> content-less == no db entry?

Content-less doesn't mean item can't be in db. Furthermore I believe this change only "allows" marking/unmarking again for content-less sources with items that are also in db rather than enabling it for items NOT in the db.

2020-10-29 16:09 UTC, DaveTBlake commented
@arnova understand this both got bogged down and you have been unable to get back to it. Bumping to v20 since I doubt you will be able to complete for v19. However if you are able to look at this for v19 (as a fix it will be welcome at any point in the cycle) please do and change labels back.

2021-03-29 10:59 UTC, arnova commented
So any ideas how to proceed with this? @ksooo / @DaveTBlake  / ... ?

2025-05-12 19:15 UTC, closed without merging