[PVR] add watched count to grouped recordings list
xbmc/xbmc pull request #17516
Opened 2020-03-18 10:31 UTC by jahutchi

## Description
This adds a watched/total episodes count to the grouped PVR Recordings list view

## Motivation and Context
Showing the watched/total episodes count in the grouped PVR recordings list helps the user to quickly see how many unwatched episodes are in each folder. This also makes the experience more consistent with other areas of the application where the watched/total count is shown (e.g. the TV Shows library view)

## How Has This Been Tested?
With this commit in place I have been into the Grouped recordings view to verify that the counts are now shown. I also double-checked that in the non-grouped view, the Date label (ListItem.Label2) still shows correctly (as this shares the same label)

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/14977362/76950305-c6d5b700-6901-11ea-8a53-e37501946d9f.png)

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [X] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [X] I have added tests to cover my change
- [X] All new and existing tests passed

2020-03-18 18:36 UTC, ksooo commented
@ronie look the skin changes okay for you?

2020-03-18 18:37 UTC, ksooo approved these changes
Nice.

2020-03-18 21:59 UTC, phunkyfish commented
I love this feature, nice one @jahutchi

2020-03-18 22:25 UTC, ronie commented
there's no need to add a workaround in the skin to accomplish this.
Label2 needs to be set by core, depending on the selected sort method.

see: https://github.com/xbmc/xbmc/blob/809e36a24c453c27cbfae05e08c2f2e3951c2e8f/xbmc/pvr/windows/GUIViewStatePVR.cpp#L39-L53

2020-03-20 21:41 UTC, jahutchi commented
> there's no need to add a workaround in the skin to accomplish this.
> Label2 needs to be set by core

Thanks for taking a look...i've updated the commit accordingly

> depending on the selected sort method.

I may be missing something, but the counts are surely the same regardless of the sorth method?

2020-03-20 22:00 UTC, ksooo commented
> the counts are surely the same regardless of the sorth method?

 I think so.

2020-03-20 22:10 UTC, ksooo requested changes

2020-03-20 22:10 UTC, ksooo commented on xbmc/pvr/filesystem/PVRGUIDirectory.cpp
> +        item->GetProperty("watchedepisodes").asString(),
`.asString().c_str()`

2020-03-20 22:10 UTC, ksooo commented on xbmc/pvr/filesystem/PVRGUIDirectory.cpp
> +        item->GetProperty("totalepisodes").asString()));
`.asString().c_str()`

2020-03-20 22:16 UTC, jahutchi commented on xbmc/pvr/filesystem/PVRGUIDirectory.cpp
> +        item->GetProperty("watchedepisodes").asString(),
Done

2020-03-20 22:17 UTC, jahutchi commented on xbmc/pvr/filesystem/PVRGUIDirectory.cpp
> +        item->GetProperty("totalepisodes").asString()));
Done

2020-03-20 22:52 UTC, ronie commented
> I may be missing something, but the counts are surely the same regardless of the sorth method?

what i meant to say that it is possible to make Label2 return a different type of info, depending on the selected sort method.

for instance if you sort by date, Label2 can be set to return the date value.
and if you sort by file, it can be set to return the watched count.

if you want Label2 to always return the watched count, then i guess the current changes are ok.

2020-03-21 06:23 UTC, ksooo requested changes
There is no need for the "watchedepisodes" and "totalepisodes" item properties any more. Please use local variables for the two values.

2020-03-21 06:28 UTC, ksooo commented
> if you want Label2 to always return the watched count

 yes, that's fine.

2020-03-21 12:44 UTC, phunkyfish commented
Are you sure local variables are possible? The count would be per folder so I think it needs to be on the item.

2020-03-21 13:06 UTC, ksooo commented
They are at the item, as Label2.

2020-03-21 13:19 UTC, ksooo commented
```diff
diff --git a/xbmc/pvr/filesystem/PVRGUIDirectory.cpp b/xbmc/pvr/filesystem/PVRGUIDirectory.cpp
index f2d2ec95cf..ceae3c49ae 100644
--- a/xbmc/pvr/filesystem/PVRGUIDirectory.cpp
+++ b/xbmc/pvr/filesystem/PVRGUIDirectory.cpp
@@ -195,6 +195,9 @@ void GetSubDirectories(const CPVRRecordingsPath& recParentPath,
     const std::string strFilePath = recChildPath;
 
     std::shared_ptr<CFileItem> item;
+    int iTotal = 0;
+    int iWatched = 0;
+
     if (!results.Contains(strFilePath))
     {
       item.reset(new CFileItem(strCurrent, true));
@@ -202,8 +205,6 @@ void GetSubDirectories(const CPVRRecordingsPath& recParentPath,
       item->SetLabel(strCurrent);
       item->SetLabelPreformatted(true);
       item->m_dateTime = recording->RecordingTimeAsLocalTime();
-      item->SetProperty("totalepisodes", 0);
-      item->SetProperty("watchedepisodes", 0);
       item->SetProperty("unwatchedepisodes", 0);
 
       // Assume all folders are watched, we'll change the overlay later
@@ -217,7 +218,7 @@ void GetSubDirectories(const CPVRRecordingsPath& recParentPath,
         item->m_dateTime = recording->RecordingTimeAsLocalTime();
     }
 
-    item->IncrementProperty("totalepisodes", 1);
+    iTotal++;
     if (recording->GetPlayCount() == 0)
     {
       unwatchedFolders.insert(item);
@@ -225,11 +226,10 @@ void GetSubDirectories(const CPVRRecordingsPath& recParentPath,
     }
     else
     {
-      item->IncrementProperty("watchedepisodes", 1);
+      iWatched++;
     }
-    item->SetLabel2(StringUtils::Format("%s / %s",
-        item->GetProperty("watchedepisodes").asString().c_str(),
-        item->GetProperty("totalepisodes").asString().c_str()));
+
+    item->SetLabel2(StringUtils::Format("%d / %d", iWatched, iTotal));
   }
 
   // Change the watched overlay to unwatched for folders containing unwatched entries
```

2020-03-21 13:30 UTC, ksooo commented
Sorry for the noise. All good.

2020-03-21 13:30 UTC, ksooo approved these changes

2020-03-21 21:16 UTC, merged

2020-03-21 21:17 UTC, phunkyfish commented
Thanks for the contribution!