[Addons] Ensure addon installation order when migrating to matrix
xbmc/xbmc pull request #17703
Opened 2020-04-19 19:57 UTC by enen92

## Description
Despite our efforts to ensure that every single addon in the matrix branch has a higher version than those stored in lower branches (to ensure they all get updated when migrating from leia to matrix), the reality is that right now almost all of them get disabled and won't update.

This happens because kodi doesn't enforce any control in the order of addon installations. So let's say that you have `plugin.video.foo` and `plugin.video.bar`, and `foo` depends on `bar`, if `foo` gets updated and installed before `bar` it can lead to `foo` getting disabled. This used to work just fine before matrix because if `foo` was updated before `bar`, as the installed version of `bar` was still compatible with kodi (`xbmc.python` was backwards compatible) `foo` was updated and installed and later `bar` was also updated and installed. In matrix, even though `foo` requires a minimum version of `bar` equal to the one installed before starting the migration, `bar` is invalid because it depends on a `xbmc.python` version lower than the minimum supported by kodi matrix - leading to almost any addon with dependencies to get disabled.

So, this PR does the following:
- Ensure that concurrency is avoided in bulk addon updates: if the repo manifest is updated while migrating, it will triggered another round of updates while the first one is still running
- Ensure the `InstallUpdates` function can be configured to wait for each addon to be installed before requesting the installation of another one (using only in the migration phase - first time you run a new kodi version)
- Sort the list of addons to be updated depending on their dependencies. Addons that depend on others should be the last ones to be installed.

Note that this only affects the addon migration, i.e, when running matrix for the first time. All the other updates (after first run) will be exactly the same, the list is sorted but they are installed without any order - this is faster and won't cause any issues since the version being updated is already "new-kodi" compatible.

The only drawback of this approach is that the addon migration is now a bit slower, but I guess we can live with that.

@AlwinEsch for the review
@da-anda @ronie @anxdpanic fyi

Thanks to @yol for the c++ tips

## Motivation and Context
Promote a seamless migration from Leia to Matrix for users despite all the "non-visible" work and fussle introduced with the python2 -> python3 migration

## How Has This Been Tested?
- Install kodi leia
- Install addons in leia that are known to also be in matrix
- close kodi leia
- run matrix
- check none is disabled (and if any is, it's our fault managing the repo)

## Screenshots (if appropriate):
**Leia:**
![Leia](https://i.imgur.com/XpvzYb7.png "Leia")

**Master/Matrix:**
![Matrix](https://i.imgur.com/w1O4DUe.png "Matrix - master")

**PR:**
![Leia](https://i.imgur.com/5lWvI76.png "PR")

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

2020-04-20 02:37 UTC, AlwinEsch approved these changes
From code and work it looks good also was the test OK.
Think there a lot of another parts where need fixed (on other requests), but this is a good first step.
Only a bit of docs and one compile fail fix for Linux needed.

:+1:

2020-04-20 02:37 UTC, AlwinEsch commented on xbmc/addons/AddonInstaller.h
> +  std::atomic<bool> m_updatingAddons{false};
Seen my runtime test, that the atomic makes this and need above the `AddonInstaller.h` a `#include <atomic>` by me on Linux.:
```
In file included from /home/alwin/Development/Kodi/kodi-Matrix/xbmc/games/dialogs/GUIDialogSelectGameClient.cpp:12:
/home/alwin/Development/Kodi/kodi-Matrix/xbmc/addons/AddonInstaller.h:150:21: error: field ‘m_updatingAddons’ has incomplete type ‘std::atomic<bool>’
  150 |   std::atomic<bool> m_updatingAddons{false};
      |                     ^~~~~~~~~~~~~~~~
In file included from /usr/include/c++/9/bits/shared_ptr_atomic.h:33,
                 from /usr/include/c++/9/memory:82,
                 from /home/alwin/Development/Kodi/kodi-Matrix/xbmc/games/GameTypes.h:11,
                 from /home/alwin/Development/Kodi/kodi-Matrix/xbmc/games/dialogs/GUIDialogSelectGameClient.h:11,
                 from /home/alwin/Development/Kodi/kodi-Matrix/xbmc/games/dialogs/GUIDialogSelectGameClient.cpp:9:
/usr/include/c++/9/bits/atomic_base.h:145:12: note: declaration of ‘struct std::atomic<bool>’
  145 |     struct atomic;
      |            ^~~~~~
```

2020-04-20 13:25 UTC, Rechi commented
jenkins build this please

2020-04-20 14:52 UTC, yol commented
I actually think it would be better to always do this. Suppose you update an addon and it requires a newer version of a dependency. Let's say it will fail to load if the dependency is too old (e.g. because it imports a symbol that is not available in the old version) - wouldn't you hit the same problem if the addon gets installed before the dependency has finished installing?

2020-04-20 14:57 UTC, yol requested changes
some minors

2020-04-20 14:57 UTC, yol commented on xbmc/addons/AddonInstaller.cpp
> +      if (!dependencies.empty())
you can leave out the whole if block

2020-04-20 14:57 UTC, yol commented on xbmc/addons/AddonInstaller.cpp
> +          auto comparator = [dep](const std::shared_ptr<ADDON::IAddon> addon) {
```suggestion
          auto comparator = [&dep](const std::shared_ptr<ADDON::IAddon>& addon) {
```

2020-04-20 14:57 UTC, yol commented on xbmc/addons/AddonInstaller.cpp
> +      auto dependencies = addon->GetDependencies();
```suggestion
      const auto& dependencies = addon->GetDependencies();
```

2020-04-20 14:58 UTC, enen92 commented
@yol making this default will certainly avoid issues like that one. Reason I didn't make it default is to try to change as less as possible so it won't cause future issues we can't see right now (seems a classic when doing kodi stuff :) ).

Either way, this needs further work. We shouldn't be guarding the `InstallUpdates` but the migration process instead.

2020-04-20 14:59 UTC, yol commented
@enen92 In general, I agree. I also try to keep changes as local as possible. But not resolving addon installation order correctly (or at all) is a serious flaw that will bite us again. So IMO the benefits outweigh here.

2020-04-20 16:04 UTC, phunkyfish commented
Why not ask @MilhouseVH to put it in a build for a few weeks.

If no issues are raised then it can becomes the standard route for any addon update cycle.

2020-04-20 17:42 UTC, enen92 commented
Made a few changes to the PR:
- We're now guarding the migration process so that the updates doesn't trigger while the migration is happening (and not when updates are hapening like before)
- Made the process of updates ordered by default as per @yol suggestion

Not related to the issue this pr tries to solve:
@AlwinEsch do you think it also makes sense to block addon updates when another process is also updating addons? Kodi triggers addon updates whenever a repo manifest is updated. So (unless in the migration phase were we specifically wait for all) if you have more than 1 repo installed it is not guaranteed that all addons in that repo will be able to update if they contain (incompatible) dependencies to addons in other repos.  To be honest, I'm not even sure if this is a problem we should solve. There have been discussions in the past regarding external repos/addons leeching our infrastructure. Maybe something to be considered in https://github.com/xbmc/xbmc/pull/17677 @matthuisman ?

2020-04-20 18:12 UTC, yol requested changes
minors again :) behavior-wise I have no complaints :+1:

2020-04-20 18:12 UTC, yol commented on xbmc/addons/AddonSystemSettings.cpp
> +bool CAddonSystemSettings::isMigratingAddons() const
```suggestion
bool CAddonSystemSettings::IsMigratingAddons() const
```

always use PascalCase

2020-04-20 18:12 UTC, yol commented on xbmc/addons/AddonSystemSettings.h
> +  bool isMigratingAddons() const;
```suggestion
  bool IsMigratingAddons() const;
```

2020-04-20 20:25 UTC, MilhouseVH commented
> Why not ask @MilhouseVH to put it in a build for a few weeks.

Just being extra cautious, but I'd like to see this bake for another 24 hours and then I'd be happy to include it in `#0421` assuming nobody finds anything of concern etc.

2020-04-20 23:42 UTC, enen92 commented
@MilhouseVH please do not add it yet (and probably also not in 24 hours), I still want to work a bit more on this (note the wip label), and likely will require some refactor pr before continuing this one.

2020-04-20 23:45 UTC, MilhouseVH commented
OK no problem, ping me when you think it's ready!

2020-04-24 13:17 UTC, jenkins4kodi commented
@enen92 this needs a rebase

2020-04-26 05:19 UTC, phunkyfish requested changes

2020-04-26 05:19 UTC, phunkyfish commented on xbmc/addons/Repository.h
> +    void ShouldInstallAddons(const bool install) { m_shouldinstalladdons = install; };
Maybe rename to `SetShouldInstallAddons`? Also, for basic types the const is not really required (but it does no harm).

2020-04-26 05:19 UTC, phunkyfish commented on xbmc/addons/RepositoryUpdater.cpp
> +  CheckForUpdates(false, true);
The second argument forces install to true. Should it use the `install` variable instead?

2020-04-26 12:15 UTC, phunkyfish requested changes

2020-04-26 12:15 UTC, phunkyfish commented on xbmc/addons/AddonManager.h
> +    mutable std::mutex m_installaddonsmutex;
`m_installAddonsMutex`

2020-04-26 12:15 UTC, phunkyfish commented on xbmc/addons/AddonManager.cpp
> +  auto updatesAll = GetAvailableUpdates();
Why not just use `updates` here?

2020-04-26 13:14 UTC, enen92 commented
@MilhouseVH I think it is ready now. Can you include this on the next nightly?

2020-04-26 13:54 UTC, AlwinEsch commented
> @AlwinEsch do you think it also makes sense to block addon updates when another process is also updating addons? 
For now yes, if the blocking not result in a freeze of something. 
In future there maybe it would be better to have a more intelligent processing about, thought about a centralized part/thread where do it and where the others register his works, this then check how is used and inform related places about. And then in makes all changes together at same time.

2020-04-26 14:38 UTC, MilhouseVH commented
> @MilhouseVH I think it is ready now. Can you include this in the next nightly?

Well include in `#0426`.

2020-04-26 20:27 UTC, yol approved these changes

2020-04-26 21:02 UTC, phunkyfish approved these changes
Well done, your first threading c++ badge ;)

2020-04-26 21:20 UTC, Rechi commented on xbmc/addons/AddonManager.h
> +
remove the white space at the end of the line

2020-05-04 10:17 UTC, enen92 commented
@MilhouseVH any complains so far (apart from possible ones caused by halifax downtime)?

2020-05-09 10:33 UTC, merged