[cmake] ADDONS_TO_BUILD exclusion regex
xbmc/xbmc pull request #17755
Opened 2020-04-26 04:52 UTC by fuzzard

## Description
Implements an exclusion match regex to exclude an addon/s from building

example usage
```
ADDONS_TO_BUILD='game.libretro.* -game.libretro.mrboom peripheral.joystick'
```

cmake output
```
-- Exclusion found -game.libretro.2048
-- Addon game.libretro.2048 matches exclusion rule -game.libretro.2048
-- Pattern game.libretro.* matches game.libretro.mrboom, building addon
```
game.libretro.mrboom will not build, but game.libretro and game.libretro.2048 will

## Motivation and Context
Some of the libretro cores can have long build times (eg. game.libretro.mame*).
This allows the ability to build selectively using regex (game.libretro.*) whilst excluding particular addon groups inside that initial regex

## How Has This Been Tested?
ios building kodi-game binary-addon repo and master binary-addon repo

## Screenshots (if appropriate):

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2020-04-26 06:03 UTC, AlwinEsch requested changes
About first way on here
-----

Have tested and works nice :smile:

Was on begin not sure if `if(exclusion MATCHES "^[-]${id}")` handle it correct, in case 2 addons have mostly same name e.g. `visualization.milkdrop` and `visualization.milkdrop2`, but has worked on test.

Documentation
-----
The only reason why I marked with "Request changes" is to add somewhere a documentation about, so that a user know this support.
Thought for here:
- https://github.com/xbmc/xbmc/blob/master/cmake/addons/README.md
- And maybe on them here https://github.com/xbmc/xbmc/tree/master/docs
  - not sure how, maybe by reference to `cmake/addons/README.md`

e.g. this on build docs:
```
(3) Build a specific group of add-ons:

make -j$(getconf _NPROCESSORS_ONLN) -C tools/depends/target/binary-addons ADDONS="pvr.*"

For set available styles of ADDONS you can also look by ADDONS_TO_BUILD on here [Kodi add-ons CMake based buildsystem](../cmake/addons/README.md)
```
Or take direct the text from the `cmake/addons/README.md` and copy to this files.

2020-04-26 06:05 UTC, fuzzard commented on cmake/addons/CMakeLists.txt
> +    STRING(REGEX MATCH "-([^ ]*)"  excluded_addon ${FOUND_EXCLUSION})
yeah, sorry, had a force push to fix it. Came across the exact issue you first mentioned.

Now i save the excluded_addon list as just eg pvr.dvblink;pvr.dvbviewer without the leading -. Makes the match in the actual addon loop simpler.

2020-04-26 06:08 UTC, fuzzard commented on cmake/addons/CMakeLists.txt
> +    STRING(REGEX MATCH "-([^ ]*)"  excluded_addon ${FOUND_EXCLUSION})
the match is just the way i see regex matching. Its very loose, and doesnt require regex terms to explicitly force a regex search. ie. -pvr.dvb will match anything with pvr.dvb. Same goes for actual matching ie games.libretro actually matches games.libretro and all games.libretro.*

Honestly i havent tried to fix that situation.

2020-04-26 06:18 UTC, AlwinEsch commented
Yes e.g. about example 2, it would be better to have them as `-game.libretro.mame*` and to set with `*` that text is behind.
Without it can have problems that a for creation wanted addon can also be excluded.

2020-04-26 06:35 UTC, fuzzard commented
The current matches behaviour hasnt changed with this PR.
At this time, i would see that as out of scope of this PR. I definitely know what you are talking about, but it is also existing behaviour due to the way we use MATCHES

https://github.com/xbmc/xbmc/blob/35641bab4e2d97340269795d0a3a5144aa7538e1/cmake/addons/CMakeLists.txt#L261

The way i see it, you would need to check the supplied string ends in a regex search term (ie. .*), otherwise only do the strict STREQUALS check. Sure it can be done, but it will change current behaviour. Not sure i personally want to get involved in bulk changes, haha.

2020-04-26 20:53 UTC, phunkyfish commented
I think just be sure the docs reflect the actual behaviour and that's ok.

2020-04-27 13:21 UTC, garbear approved these changes
Might not have a chance to review the CMake this week but +1 for general concept

2020-04-28 03:43 UTC, fuzzard commented
@AlwinEsch when you have time could you have a look at https://github.com/fuzzard/xbmc/commit/f479fb7a0fe6ed57c7535f2fc831ebeb8dae2646

Trying to come up with a way to no regex match a generic term (game.libretro, and vis.milkdrop i your scenario)

It works, but im not sure about it. The branch its in is based on this exclusion branch as well, so it provides

-addon regex exclusion
addon exact match (wont do any further regex matching)
addon not an exact match (then is done using regex matching)

some examples can be seen https://github.com/xbmc/xbmc/issues/17773#issuecomment-620359946

it seems like a hack, as i still have to strip * from anything provided to ensure the filter regex doesnt then match the same as its currently done. Just might be a slight input from things going wild.

The only other way (cleanly) i can come up with would be to change so regex arguments are provides as eg +addonregex, to mirror the -addon for the exclusion state in this rule. Anything without a + or - would then be only considered for exact match. Downside to this, it changes current expected behaviour. At least it would then be explicit in what action a user is wanting however.

2020-04-28 10:41 UTC, fuzzard commented
Cleaned it up slightly and made it compatible with cmake 3.5. If/when we do change minimum cmake version to 3.6+, list filters will be handy to change a lot of our looping over to i think.

https://github.com/fuzzard/xbmc/commits/cmake3.5_addonregexmatching

2020-04-29 02:26 UTC, fuzzard commented
jenkins build this please

2020-04-29 06:28 UTC, fuzzard commented
Have added a commit to resolve https://github.com/xbmc/xbmc/issues/17773

Figure best to try to fix everything in the one PR for this.

2020-05-08 09:04 UTC, phunkyfish commented
Are you happy with this on @AlwinEsch ?

2020-05-08 09:49 UTC, AlwinEsch commented
Not really, as the most basic no more works `cmake .. -DADDONS_TO_BUILD="screensaver.*"`.
Also seen a bugs inside, give me a bit to make big checks.

2020-05-08 09:52 UTC, fuzzard commented
Have you tried it since the new commit? Your use case definitely works with the current PR commits. ie https://github.com/xbmc/xbmc/pull/17755/commits/b2a84a842f1c28db0d714aa7d8a41fd9b0a68641

2020-05-09 09:27 UTC, fuzzard commented
@AlwinEsch have updated the commit to your suggested changes. One minor change that just sets ADDONS_TO_BUILD to all if its not set. Save having to check the empty var and string "all" several times

2020-09-26 08:30 UTC, fuzzard commented
Jenkins build this please

2020-09-26 08:42 UTC, AlwinEsch approved these changes

2020-09-26 20:30 UTC, garbear approved these changes

2020-09-26 21:12 UTC, merged