Prevent RTL text from mirrorring around styled characters for on-screen keyboard
xbmc/xbmc pull request #17790
Opened 2020-04-30 11:53 UTC by AhmedAdelAbouzeid

## Description of changes and context

This PR is a follow-up for for #17692 and includes 3 main changes:

1- Revert the character used for cursor blinking for on-screen keyboard to the original as replacing it with a basic space causes text to move sideways during blinking for the default font.

2- Instead of replacing the styled character, BidiTransform() function was re-written such that calls to FriBidi are performed for a complete line at a time rather than breaking it for differently styled sections (RTL text mirroring around styled characters occurred due to this line splitting).
Now, the styling data for the whole line is saved and re-applied after FriBidi call. To support this functionality a mapping is created between logical and visual strings as text that was originally styled may not be in the same location after FriBidi call. The function BidiFlip() was also modified for this purpose.

3- Logical to visual string mapping was added as an optional parameter for functions wrapping FriBidi calls to support functionality needed in point 2.

## How Has This Been Tested?

The changes were tested using Kodi on Windows 10 x64 (1909)
The on-screen keyboard was tested using a RTL language (Arabic) and a LTR language (English) and behave correctly for both languages after the changes.

## Screenshots (if appropriate):
![Kodi_KB_AR_CR](https://user-images.githubusercontent.com/63805744/80705744-3df89080-8ae7-11ea-944c-831e59a0fda2.png)

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2020-04-30 14:08 UTC, phunkyfish commented
@AlwinEsch this PR should solve the issue with the text moving. Do you want to check if it’s ok for you?

2020-04-30 15:03 UTC, AlwinEsch approved these changes
Have checked with different languages and fonts, was ok :+1:

2020-04-30 17:29 UTC, phunkyfish requested changes

2020-04-30 17:29 UTC, phunkyfish commented on xbmc/guilib/GUITextLayout.cpp
> +	unsigned int lineLength = line.m_text.size();
indentation wrong

2020-04-30 17:29 UTC, phunkyfish commented on xbmc/guilib/GUITextLayout.cpp
> +	std::wstring logicalText;
indentation wrong

2020-04-30 17:29 UTC, phunkyfish commented on xbmc/guilib/GUITextLayout.cpp
> +    int* logicalToVisualMap = (int*)malloc((lineLength + 1) * sizeof(int));
Why malloc? is there a reason not to use `new`?

`int* logicalToVisualMap = new int[lineLength + 1];`

2020-04-30 17:29 UTC, phunkyfish commented on xbmc/guilib/GUITextLayout.cpp
> +    if (logicalToVisualMap == NULL)
`nullptr`

2020-04-30 17:29 UTC, phunkyfish commented on xbmc/guilib/GUITextLayout.cpp
> +        styledVisualText.push_back(visualText[j]);
Surrounded by brackets

2020-04-30 17:29 UTC, phunkyfish commented on xbmc/guilib/GUITextLayout.cpp
> +        styledVisualText.push_back(style[logicalToVisualMap[j]] | visualText[j]);
Surrounded by brackets

2020-04-30 17:29 UTC, phunkyfish commented on xbmc/guilib/GUITextLayout.cpp
> +  g_charsetConverter.utf32ToW(utf32visual,visualText);
space after comma

2020-04-30 17:29 UTC, phunkyfish commented on xbmc/guilib/GUITextLayout.cpp
> +    free(logicalToVisualMap);
`delete[] logicalToVisualMap;`

2020-04-30 17:29 UTC, phunkyfish commented on xbmc/guilib/GUITextLayout.cpp
> +std::wstring CGUITextLayout::BidiFlip(const std::wstring &text, bool forceLTRReadingOrder, int* logicalToVisualMap /*=NULL*/)
space after `=`

2020-04-30 17:29 UTC, phunkyfish commented on xbmc/guilib/GUITextLayout.h
> +  static std::wstring BidiFlip(const std::wstring &text, bool forceLTRReadingOrder, int* logicalToVisualMap = NULL);
`nullptr`

2020-04-30 17:29 UTC, phunkyfish commented on xbmc/utils/CharsetConverter.cpp
> +  static bool logicalToVisualBiDi(const std::u32string& stringSrc, std::u32string& stringDst, FriBidiCharType base = FRIBIDI_TYPE_LTR, const bool failOnBadString = false, int* logicalToVisualMap = NU
`nullptr` and line length needs to be less than 100 chars

2020-04-30 17:29 UTC, phunkyfish commented on xbmc/utils/CharsetConverter.cpp
> +bool CCharsetConverter::utf32logicalToVisualBiDi(const std::u32string& logicalStringSrc, std::u32string& visualStringDst, bool forceLTRReadingOrder /*= false*/, bool failOnBadString /*= false*/, int*
Line too long

2020-04-30 17:29 UTC, phunkyfish commented on xbmc/utils/CharsetConverter.cpp
> +  return CInnerConverter::logicalToVisualBiDi(logicalStringSrc, visualStringDst, forceLTRReadingOrder ? FRIBIDI_TYPE_LTR : FRIBIDI_TYPE_PDF, failOnBadString, logicalToVisualMap);
line too long

2020-04-30 17:29 UTC, phunkyfish commented on xbmc/utils/CharsetConverter.h
> +  static bool utf32logicalToVisualBiDi(const std::u32string& logicalStringSrc, std::u32string& visualStringDst, bool forceLTRReadingOrder = false, bool failOnBadString = false, int* logicalToVisualMa
line too long, `nullptr`

2020-04-30 20:01 UTC, AhmedAdelAbouzeid commented
Thanks a lot for reviewing.
I noted and applied the requested code changes. Please re-check, Thanks!

2020-05-01 07:40 UTC, phunkyfish requested changes
Nearly there ;)

Mainly just alignment issues outside of the cast and `!` conditional. Once you add you code in git you can just run `git-clang-format`, add those changes again and then commit if you find that easier than following my review.

The only thing I'm not sure of is how to do the C style cast as a C++ one.

2020-05-01 07:40 UTC, phunkyfish commented on xbmc/guilib/GUITextLayout.cpp
> +    if (logicalToVisualMap == nullptr)
`if (! logicalToVisualMap)`

2020-05-01 07:40 UTC, phunkyfish commented on xbmc/guilib/GUITextLayout.cpp
> +  int* logicalToVisualMap /*= nullptr*/)
align with other arguements, e.g.

```
std::wstring CGUITextLayout::BidiFlip(const std::wstring &text, bool forceLTRReadingOrder,
                                      int* logicalToVisualMap /*= nullptr*/)
```

2020-05-01 07:40 UTC, phunkyfish commented on xbmc/guilib/GUITextLayout.h
> +    int* logicalToVisualMap = nullptr);
Align to other arguments like previous example.

2020-05-01 07:40 UTC, phunkyfish commented on xbmc/utils/CharsetConverter.cpp
> +    int* logicalToVisualMap = nullptr);
Maybe like this, we have enough width to align to the function brackets:

```cpp
static bool logicalToVisualBiDi(const std::u32string& stringSrc,
                                std::u32string& stringDst,
                                FriBidiCharType base = FRIBIDI_TYPE_LTR,
                                const bool failOnBadString = false,
                                int* logicalToVisualMap = nullptr);
```

2020-05-01 07:40 UTC, phunkyfish commented on xbmc/utils/CharsetConverter.cpp
> +  const bool failOnBadString /*= false*/, int* logicalToVisualMap /*= nullptr*/)
Like this. We need to use a 4 space continuance as aligning to the function brackets breaks the 100 char width limit.

```cpp
bool CCharsetConverter::CInnerConverter::logicalToVisualBiDi(
    const std::u32string& stringSrc,
    std::u32string& stringDst,
    FriBidiCharType base /*= FRIBIDI_TYPE_LTR*/,
    const bool failOnBadString /*= false*/,
    int* logicalToVisualMap /*= nullptr*/)
```

2020-05-01 07:40 UTC, phunkyfish commented on xbmc/utils/CharsetConverter.cpp
> +      visual, logicalToVisualMap, NULL, NULL))
Align to other arguments, space on cast and nullptr.

```cpp
if (fribidi_log2vis((const FriBidiChar*) (stringSrc.c_str() + lineStart),
                    lineLen, &baseCopy, visual, logicalToVisualMap, nullptr, nullptr))
```

I have no idea what the correct c++ cast is there. Maybe `reinterpret_cast`? Try it and see.

2020-05-01 07:40 UTC, phunkyfish commented on xbmc/utils/CharsetConverter.cpp
> +  bool failOnBadString /*= false*/, int* logicalToVisualMap /*= nullptr*/)
Alignment:

```cpp
bool CCharsetConverter::utf32logicalToVisualBiDi(const std::u32string& logicalStringSrc,
                                                 std::u32string& visualStringDst,
                                                 bool forceLTRReadingOrder /*= false*/,
                                                 bool failOnBadString /*= false*/,
                                                 int* logicalToVisualMap /*= nullptr*/)
{
  return CInnerConverter::logicalToVisualBiDi(
      logicalStringSrc, visualStringDst, 
      forceLTRReadingOrder ? FRIBIDI_TYPE_LTR : FRIBIDI_TYPE_PDF,
      failOnBadString, logicalToVisualMap);
}
```

2020-05-01 07:40 UTC, phunkyfish commented on xbmc/utils/CharsetConverter.h
> +    bool failOnBadString = false, int* logicalToVisualMap = nullptr);
Alignment:

```cpp
static bool utf32logicalToVisualBiDi(const std::u32string& logicalStringSrc,
                                     std::u32string& visualStringDst,
                                     bool forceLTRReadingOrder = false,
                                     bool failOnBadString = false,
                                     int* logicalToVisualMap = nullptr);
```

2020-05-01 12:31 UTC, AhmedAdelAbouzeid commented
I used clang for formatting and replaced the C style cast with reinterpret_cast, please recheck. Thanks.

2020-05-01 15:24 UTC, phunkyfish commented
It's looking good, can you squash it all down to a single commit matching the PR title?

2020-05-02 07:05 UTC, AhmedAdelAbouzeid commented
All changes are part of a single commit now. Please re-check, Thanks!

2020-05-02 09:21 UTC, phunkyfish approved these changes
Nice, the code is ready. It went into a test build yesterday, let's give a few days and we can ask @MilhouseVH  if there has been any feedback.

Well done!

2020-05-05 04:55 UTC, AhmedAdelAbouzeid commented on xbmc/guilib/GUITextLayout.cpp
> +        styledVisualText.push_back(style[logicalToVisualMap[j]] | visualText[j]);
I just realized that there is a mistake here. I used the value of logicalToVisualMap[j] as index of style[] which is in logical order.  While this works for most cases, it's not correct; it should be visualToLogicalMap[] instead.
```suggestion
        styledVisualText.push_back(style[visualToLogicalMap[j]] | visualText[j]);
```
To correct this I will rename logicalToVisualMap to visualToLogicalMap everywhere it's used and use the respective output from fribidi for it.

2020-05-05 06:08 UTC, AhmedAdelAbouzeid commented
I corrected this (changed logicalToVisualMap to visualToLogicalMap), no other changes were made.

2020-05-05 06:16 UTC, phunkyfish commented
Great, thanks @AhmedAdelAbouzeid

2020-05-07 08:12 UTC, phunkyfish commented
Will merge this tomorrow.

2020-05-08 08:21 UTC, merged

2020-05-23 17:37 UTC, yeahme49 commented
Ran into a possible bug with this commit. Was watching a video using the YouTube addon and after the video finished and it should have brought me back to the search listing page, Kodi crashed. Nothing about the crash in kodi.log but opening the .dmp file with Visual Studio this is what shows up
![crash](https://user-images.githubusercontent.com/58564160/82736843-182f6780-9cf2-11ea-821e-7ed8bb957cb7.PNG)

Any ideas or any other info needed?

2020-05-23 19:09 UTC, AhmedAdelAbouzeid commented
@yeahme49 Is this reproducible ? if so then please share the search string and title of the video that causes the crash. Also, can you please upload the dmp file ?

2020-05-23 19:36 UTC, yeahme49 commented
I was able to reproduce it. If you search 'LTT boiling' there should be a video titled 'CPU Cooling with BOILING LIQUID'. The first time this video shows up in a search, it works fine. But any subsequent times it is in the list, Kodi crashes. The actual title of the video is 'CPU Cooling with BOILING LIQUID 🔥🔥' except the emoji flames don't show up in Kodi. I'm guessing it's the emojis that are causing the issue.
[kodi_crashlog-19.0-ALPHA1 Git_20200521-3f2e051032-20200523-142758.dmp.zip](https://github.com/xbmc/xbmc/files/4672417/kodi_crashlog-19.0-ALPHA1.Git_20200521-3f2e051032-20200523-142758.dmp.zip)

2020-05-24 00:36 UTC, AhmedAdelAbouzeid commented
@yeahme49 Thanks for pointing this out. The emojis indeed triggered the issue leading to the crash.
Fixed in  #17932