only parse CVideoInfoTag::m_strPictureURL if really needed
xbmc/xbmc pull request #17828
Opened 2020-05-09 21:25 UTC by Montellese

## Description
This PR improves the performance of loading the details of video library items from the database.
Right now calling `GetMoviesByWhere()` with e.g. `VideoDbDetailsUniqueID` to also retrieve the unique IDs of the movies is 3 times (or 300%) slower than retrieving all movies without the unique IDs. With the changes in this PR it's only 20% slower.

Apart from refactoring all of `CScraperUrl` to (almost) follow proper object orientation rules the main change involves not automatically parsing the XML contained in `CVideoInfoTag::m_strPictureURL` when loading additional details for video library items from the database. The potential artwork URLs are only really needed when scanning for new content and when opening the "Manage artwork" dialog for a specific video library item. So I've changed the code to only parse the XML contained in `CVideoInfoTag::m_strPictureURL` when it is really needed.

In the end I realized that most of the refactoring of `CScraperUrl` is not really needed so if prefered I can strip this PR down to the minimum which is basically just the last commit (0b6a025b4a6cfda0e809379303de881ace7f7fff).

## Motivation and Context
While looking into loading unique IDs for video library items faster I noticed that in e.g. `CVideoDatabase::GetDetailsForMovie()` we only load the requested details (e.g. unique IDs, ratings, cast, stream details, ...) but we ALWAYS parse the XML contained in `CVideoInfoTag::m_strPictureURL`. There is no way to control it like all the other details.

## How Has This Been Tested?
Manually by making sure that scanning still works and that the potential artwork URLs are still available in the "Manage artwork" dialog for a specific video library item.
The timing measurements have been performed by modifying `CVideoDatabase::GetMoviesByWhere()` to perform the whole movie loading 100 times instead of just once (to get better statistics) and measuring the whole elapsed time. Then I used `VideoLibrary.GetMovies` through JSON-RPC to just retrieve all movies without details and all movies with unique IDs.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

2020-05-10 13:36 UTC, DaveTBlake approved these changes
Looks fine to me, and happy to keep the refactoring of CScraperURL. 

Only question (of no significance whatsoever) is about naming methods using "Url" rather than "URL". I doubt we have a convention, but since class `CURL` is capitals not "CUrl" I kind of expect to see GetURLs(), AddParsedURL() etc. rather than GetUrls(), AddParsedUrl() etc. But honestly a totally trivial observation

2020-05-10 19:07 UTC, Montellese commented
> Only question (of no significance whatsoever) is about naming methods using "Url" rather than "URL". I doubt we have a convention, but since class `CURL` is capitals not "CUrl" I kind of expect to see GetURLs(), AddParsedURL() etc. rather than GetUrls(), AddParsedUrl() etc. But honestly a totally trivial observation

I actually asked myself the same question when I refactored / renamed those methods. But since the class is named `CScraperUrl` and not `CScraperURL` I decided to also go with `Url` in the method names. TBH I find `CURL` a very misleading class name because it looks more like a `#define` to me.

2020-05-11 09:48 UTC, phunkyfish requested changes
I had gotten used to URL being used from kodi but I guess it's preference.

Just one minor.

2020-05-11 09:48 UTC, phunkyfish commented on xbmc/video/jobs/VideoLibraryRefreshingJob.cpp
> +                                   scraperUrl.HasUrls() ? &scraperUrl : NULL,
nullptr

2020-05-11 10:05 UTC, Rechi reviewed
Please follow the [current code guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2020-05-11 10:05 UTC, Rechi commented on xbmc/interfaces/legacy/ListItem.cpp
> +      GetVideoInfoTag()->m_strPictureURL.AddParsedUrl(url, art_type, preview, referrer, cache, post, isgz, season);
> The `ColumnLimit` in `.clang-format` is set to `100` which defines line length [...]

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#3-formatting

2020-05-11 10:05 UTC, Rechi commented on xbmc/music/Album.cpp
> +           thumbUrls.begin()+iThumbCount,
> Conventional operators have to be surrounded by one space on each side.

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#34-whitespace

2020-05-11 10:05 UTC, Rechi commented on xbmc/music/Artist.cpp
> +           thumbUrls.begin()+iThumbCount,
> Conventional operators have to be surrounded by one space on each side.

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#34-whitespace

2020-05-11 10:05 UTC, Rechi commented on xbmc/music/infoscanner/MusicInfoScanner.cpp
> +          CScraperUrl::GetThumbUrl(album.thumbURL.GetFirstUrlByType()), CURL::GetRedacted(album.strPath), EventLevel::Warning)));
> The `ColumnLimit` in `.clang-format` is set to `100` which defines line length [...]

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#3-formatting

2020-05-11 10:05 UTC, Rechi commented on xbmc/music/infoscanner/MusicInfoScanner.cpp
> +          CScraperUrl::GetThumbUrl(artist.thumbURL.GetFirstUrlByType()), CURL::GetRedacted(artist.strPath), EventLevel::Warning)));
> The `ColumnLimit` in `.clang-format` is set to `100` which defines line length [...]

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#3-formatting

2020-05-11 10:05 UTC, Rechi commented on xbmc/music/infoscanner/MusicInfoScanner.cpp
> +      CLog::Log(LOGDEBUG,"-- nfo url: %s", scrUrl.GetFirstThumbUrl());
> Commas have to be followed by one space.

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#34-whitespace

2020-05-11 10:05 UTC, Rechi commented on xbmc/music/infoscanner/MusicInfoScanner.cpp
> +    CLog::Log(LOGDEBUG,"-- nfo url: %s", musicBrainzURL.GetFirstThumbUrl());
> Commas have to be followed by one space.

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#34-whitespace

2020-05-11 10:05 UTC, Rechi commented on xbmc/video/VideoDatabase.cpp
> +std::vector<std::string> GetBasicItemAvailableArtTypes(int mediaId, VIDEODB_CONTENT_TYPE dbType, CVideoDatabase& db)
> The `ColumnLimit` in `.clang-format` is set to `100` which defines line length [...]

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#3-formatting

2020-05-11 10:05 UTC, Rechi commented on xbmc/video/VideoInfoDownloader.cpp
> +      CLog::Log(LOGERROR, "%s: Error getting details from %s", __FUNCTION__, m_url.GetFirstThumbUrl());
> The `ColumnLimit` in `.clang-format` is set to `100` which defines line length [...]

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#3-formatting

2020-05-11 10:05 UTC, Rechi commented on xbmc/video/VideoInfoDownloader.cpp
> +      CLog::Log(LOGERROR, "%s: Error getting episode details from %s", __FUNCTION__, m_url.GetFirstThumbUrl());
> The `ColumnLimit` in `.clang-format` is set to `100` which defines line length [...]

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#3-formatting

2020-05-11 10:05 UTC, Rechi commented on xbmc/video/VideoInfoDownloader.cpp
> +      CLog::Log(LOGERROR, "%s: Error getting episode list from %s", __FUNCTION__, m_url.GetFirstThumbUrl());
> The `ColumnLimit` in `.clang-format` is set to `100` which defines line length [...]

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#3-formatting

2020-05-11 10:05 UTC, Rechi commented on xbmc/video/VideoInfoScanner.cpp
> +        if (!guide->cScraperUrl.GetTitle().empty() && StringUtils::EqualsNoCase(guide->cScraperUrl.GetTitle(), file->strTitle))
> The `ColumnLimit` in `.clang-format` is set to `100` which defines line length [...]

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#3-formatting

2020-05-11 10:05 UTC, Rechi commented on xbmc/video/VideoInfoTag.cpp
> +           thumbUrls.begin()+iThumbCount,
> Conventional operators have to be surrounded by one space on each side.

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#34-whitespace

2020-05-11 10:05 UTC, Rechi commented on xbmc/video/jobs/VideoLibraryRefreshingJob.cpp
> +          CLog::Log(LOGDEBUG, "CVideoLibraryRefreshingJob: user selected item '%s' with URL '%s'", scraperUrl.GetTitle().c_str(), scraperUrl.GetFirstThumbUrl());
> The `ColumnLimit` in `.clang-format` is set to `100` which defines line length [...]

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#3-formatting

2020-05-14 07:39 UTC, Montellese commented on xbmc/video/jobs/VideoLibraryRefreshingJob.cpp
> +                                   scraperUrl.HasUrls() ? &scraperUrl : NULL,
Fixed

2020-05-14 07:51 UTC, Montellese commented on xbmc/interfaces/legacy/ListItem.cpp
> +      GetVideoInfoTag()->m_strPictureURL.AddParsedUrl(url, art_type, preview, referrer, cache, post, isgz, season);
Fixed

2020-05-14 07:51 UTC, Montellese commented on xbmc/video/VideoInfoScanner.cpp
> +        if (!guide->cScraperUrl.GetTitle().empty() && StringUtils::EqualsNoCase(guide->cScraperUrl.GetTitle(), file->strTitle))
Fixed

2020-05-14 07:52 UTC, Montellese commented on xbmc/video/jobs/VideoLibraryRefreshingJob.cpp
> +          CLog::Log(LOGDEBUG, "CVideoLibraryRefreshingJob: user selected item '%s' with URL '%s'", scraperUrl.GetTitle().c_str(), scraperUrl.GetFirstThumbUrl());
Fixed

2020-05-14 07:55 UTC, Montellese commented on xbmc/music/Album.cpp
> +           thumbUrls.begin()+iThumbCount,
Fixed

2020-05-14 07:55 UTC, Montellese commented on xbmc/music/Artist.cpp
> +           thumbUrls.begin()+iThumbCount,
Fixed

2020-05-14 07:56 UTC, Montellese commented on xbmc/music/infoscanner/MusicInfoScanner.cpp
> +          CScraperUrl::GetThumbUrl(album.thumbURL.GetFirstUrlByType()), CURL::GetRedacted(album.strPath), EventLevel::Warning)));
Fixed

2020-05-14 07:56 UTC, Montellese commented on xbmc/music/infoscanner/MusicInfoScanner.cpp
> +          CScraperUrl::GetThumbUrl(artist.thumbURL.GetFirstUrlByType()), CURL::GetRedacted(artist.strPath), EventLevel::Warning)));
Fixed

2020-05-14 07:56 UTC, Montellese commented on xbmc/music/infoscanner/MusicInfoScanner.cpp
> +      CLog::Log(LOGDEBUG,"-- nfo url: %s", scrUrl.GetFirstThumbUrl());
Fixed

2020-05-14 07:56 UTC, Montellese commented on xbmc/music/infoscanner/MusicInfoScanner.cpp
> +    CLog::Log(LOGDEBUG,"-- nfo url: %s", musicBrainzURL.GetFirstThumbUrl());
Fixed

2020-05-14 07:56 UTC, Montellese commented on xbmc/video/VideoInfoDownloader.cpp
> +      CLog::Log(LOGERROR, "%s: Error getting details from %s", __FUNCTION__, m_url.GetFirstThumbUrl());
Fixed

2020-05-14 07:56 UTC, Montellese commented on xbmc/video/VideoInfoDownloader.cpp
> +      CLog::Log(LOGERROR, "%s: Error getting episode details from %s", __FUNCTION__, m_url.GetFirstThumbUrl());
Fixed

2020-05-14 07:57 UTC, Montellese commented on xbmc/video/VideoInfoDownloader.cpp
> +      CLog::Log(LOGERROR, "%s: Error getting episode list from %s", __FUNCTION__, m_url.GetFirstThumbUrl());
Fixed

2020-05-14 07:57 UTC, Montellese commented on xbmc/video/VideoInfoTag.cpp
> +           thumbUrls.begin()+iThumbCount,
Fixed

2020-05-14 07:58 UTC, Montellese commented on xbmc/video/VideoDatabase.cpp
> +std::vector<std::string> GetBasicItemAvailableArtTypes(int mediaId, VIDEODB_CONTENT_TYPE dbType, CVideoDatabase& db)
Fixed

2020-05-14 08:06 UTC, phunkyfish approved these changes
LGTM

2020-05-14 08:08 UTC, Montellese commented
I have addressed all comments. I want to test one more case and then this should be good to go.
jenkins build this please

2020-05-14 15:43 UTC, Montellese commented
OK I checked the case I mentioned and it looks good.

@notspiff You are probably the only one who was involved back when this was introduced. Any inputs or red flags you remember or does this seem ok for you?

2020-05-14 15:57 UTC, notspiff commented
No concerns. In fact this is how it was back when i wrote the code.
Countless refactorings lost this optimization i guess..

tor. 14. mai 2020, 17:43 skrev Sascha Montellese <notifications@github.com>:

> OK I checked the case I mentioned and it looks good.
>
> @notspiff <https://github.com/notspiff> You are probably the only one who
> was involved back when this was introduced. Any inputs or red flags you
> remember or does this seem ok for you?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/xbmc/xbmc/pull/17828#issuecomment-628719525>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABMS2YBMF5SORZXBMUKA4CLRRQGSTANCNFSM4M46XHAA>
> .
>

2020-05-14 18:51 UTC, Montellese commented
@notspiff thanks for the feedback.

2020-05-18 20:48 UTC, merged