[TVOSTopShelf.mm] Use posters before thumbnails
xbmc/xbmc pull request #17846
Opened 2020-05-11 21:30 UTC by scj643

## Description
Use the poster before attempting to use a thumbnail for the top shelf.

## Motivation and Context
To put movies more in line with tv shows in the top shelf.

## How Has This Been Tested?
I have deployed to an Apple TV 4K and it uses the poster icons.

## Screenshots (if appropriate):
![Topshelf](https://user-images.githubusercontent.com/5656510/81613262-20aba800-93ac-11ea-9835-ad9548cf2d6d.jpg)
The artwork on the far right is a thumbnail while the rest are posters.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [X] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2020-05-11 21:39 UTC, scj643 commented
Invalid PR.

2020-05-12 02:42 UTC, fuzzard commented
Can you apply this diff to fix up the whitespace formatting

https://jenkins.kodi.tv/job/BuildMulti-PR/15987/artifact/PR17846-0001-ad058d9e80-Use-poster-before-thumbnail-in-Top.diff

Otherwise looks pretty benign. Should be fine.

2020-05-12 13:24 UTC, enen92 commented
Since this is the second time the same logic is introduced (I did the same in https://github.com/xbmc/xbmc/pull/17797) probably we want a method in utils that (provided the media item) can return a preferred image. Otherwise we spread the same functionality everywhere.

2020-05-14 19:37 UTC, fuzzard approved these changes

2020-05-14 21:49 UTC, kambala-decapitator requested changes
For consistency (and to follow current coding guidelines, if I remember correctly) I suggest to remove curly braces after `if`. To be on the safe side, run `git-clang-format` when your changes are staged for commit.

2020-05-14 23:04 UTC, fuzzard commented
Jenkins doesnt have any diff artifacts, so as it is meets clang formatting guidelines

2020-05-15 22:49 UTC, fuzzard commented
We can clean the cosmetic up later, I know Sylvain has a topshelf pr happening that might rework some of this anyway, I'll talk to him to do the cosmetic.

2020-05-15 22:49 UTC, merged