[Music] Consistently use sorting.foo rather than a mix of sorting and…
xbmc/xbmc pull request #17948
Opened 2020-05-25 11:03 UTC by the-black-eagle

… sortDescription

## Description
The current code has an inconsistent use of `sorting.foo` where sometimes `sorting.foo` is used and sometimes `sortDescription.foo` is used.
The mixing of these two variables means that, for instance, limits or order direction set in filter style nodes are not in fact applied to the results when the nodes are opened.  This is because the current code makes a copy of any sortDescription passed into the getters, modifies it (if applicable) in `GetFilter()` but then inconsistently uses both the (possibly modified) copy _and_ the original.

## Motivation and Context
As stated above, adding a limit and/or sort direction to a filter style node does not make a difference when the node is opened.  No such issue exists however when using a similar smart playlist.  For instance, when adding a simple limit to the album node, it is ignored by the current master and the SQL created is
`GetAlbumsByWhere query: SELECT albumview.* FROM albumview  WHERE albumview.strReleaseType = 'album'`
With the change in this PR, the SQL created is
`GetAlbumsByWhere query: SELECT albumview.* FROM albumview  WHERE albumview.strReleaseType = 'album' ORDER BY albumview.idAlbum LIMIT 50`

This change will also allow library nodes to be filtered by `orderBy` and `orderDirection` rules correctly.
## How Has This Been Tested?
Tested locally by adding a simple limit to the stock album node that is shipped with Kodi.
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<node order="30" type="filter" visible="Library.HasContent(Music)">
	<label>132</label>
	<icon>DefaultMusicAlbums.png</icon>
	<content>albums</content>
	<limit>50</limit>	
</node>
```
Confirmed visually and by debug log entries that the current master ignores the limit set in the node.  Also tested against JSON queries with and without limits to ensure no regression from current behaviour.
This change only affects internal URL's that contain xsp rules.

## Screenshots (if appropriate):

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

2020-05-27 08:49 UTC, DaveTBlake commented
I understand the custom node behaviour that you want to achieve/correct, and it certainly looks like a bit in music was overlooked back in 2012 by https://github.com/xbmc/xbmc/pull/1632 compared to video. However it isn't just a simple matter of "inconsistent use of variables".

Firstly the places that don't need these changes and why:
The JSON getters `GetArtistsByWhereJSON`, `GetAlbumsByWhereJSON`, and `GetSongsByWhereJSON`, apply the sort description passed into them as a const parameter. If the JSON request has filter rules then an "xsp=..." option is appended to the baseDir parameter, this will also include a repeat of the sort description. But since requests don't always have this  "xsp=" e.g.  they can just have a sort description,  the consistent thing is to always use the sort description const parameter.   Hence a dummy _variable_ is passed to `GetFilter` which could change the its value. You may argue that such change never does any harm as  either with or without xsp it returns the same sort description, but IMO it is much clearer to know for sure it is the const parameter that is being applied in these routines. Maybe the `sorting` variable in these routines needs to be called `dummysorting` just to make that it even more obvious it isn't a copy error.

The GUI getters and how sort description is passed to them (or not) by the various calling routes is the real focus of this PR. The change you make is to ensure that the sort description encoded in any "xsp=" option passed in on the baseDir is applied to the data fetched.  That has good consequnces  for filter type custom nodes, and for navigation back to them. It is well spotted and you should really call it a fix of a long standing issue rather than a feature.

2020-05-27 11:22 UTC, jjd-uk commented
@DaveTBlake if you class this as fix, then assuming @the-black-eagle is willing to do the work, would this be a candidate for backporting to Leia? or is it too intrusive for that?

2020-05-27 11:30 UTC, DaveTBlake commented
My initial feeling is probably not to backport this, but others can make a case for it sure.  I know there is much more coming form both @the-black-eagle and myself in this area and so would rather make it all for v19 than leak backwards with it into late point changes in v18.

2020-05-27 11:42 UTC, jjd-uk commented
Ok I've no problem with that.

2020-05-27 14:51 UTC, the-black-eagle commented
@DaveTBlake Added a second commit to revert the changes in the JSON getters.  If it's all OK I will squash it into one.  Hopefully the IOS build won't fail next time although I don't think its related to anything in this PR.

2020-05-27 15:47 UTC, DaveTBlake requested changes
Sorry, seems Clang formatting caught you on lines that you aren't changing

2020-05-27 15:47 UTC, DaveTBlake commented on xbmc/music/MusicDatabase.cpp
>        resultcount = std::min(
Clang has reformated unchanged lines

2020-05-27 15:47 UTC, DaveTBlake commented on xbmc/music/MusicDatabase.cpp
> +          resultcount);
Clang has reformated unchanged lines

2020-05-27 15:47 UTC, DaveTBlake commented on xbmc/music/MusicDatabase.cpp
> +    int iAddedFields = GetOrderFilter(MediaTypeSong, sorting, extFilter);
Leave as was please

2020-05-27 15:47 UTC, DaveTBlake commented on xbmc/music/MusicDatabase.cpp
> +          DatabaseUtils::BuildLimitClause(sortDescription.limitEnd, sortDescription.limitStart);
Clang has reformated unchanged lines

2020-05-27 15:47 UTC, DaveTBlake commented on xbmc/music/MusicDatabase.cpp
> +    int iAddedFields = GetOrderFilter(MediaTypeAlbum, sorting, extFilter);
Leave as it was please

2020-05-27 15:47 UTC, DaveTBlake commented on xbmc/music/MusicDatabase.cpp
> +          resultcount);
Clang has reformated unchanged lines

2020-05-27 15:47 UTC, DaveTBlake commented on xbmc/music/MusicDatabase.cpp
> +      strSQLExtra +=
Clang has reformated unchanged lines

2020-05-27 18:56 UTC, the-black-eagle commented
Hopefully that's all the formatting fixed and the two variables I missed the first time reverted as well.

2020-05-27 19:10 UTC, DaveTBlake commented
Yesp, LGTM. Squash and remember to modify the commit desc to something meaning full i.e. "Apply sort description (order, direction and limits) read from  xsp  option when present"

2020-05-27 19:27 UTC, the-black-eagle commented
All done.  Jenkins failed because I force-pushed the squash after it had started building.

2020-05-28 08:07 UTC, the-black-eagle commented
jenkins build this please

2020-05-29 09:19 UTC, jenkins4kodi commented
@the-black-eagle this needs a rebase

2020-05-29 12:47 UTC, the-black-eagle commented
jenkins build this please

2020-05-29 16:32 UTC, DaveTBlake approved these changes

2020-05-29 16:33 UTC, merged