[Estuary] Improvements to Fullscreen Info/Seekbar for Video & Music
xbmc/xbmc pull request #17976
Opened 2020-05-31 13:57 UTC by jjd-uk

Set of improvement to video fullscreen info, music visualisation and seekbar which are designed to produce a consistent styling across Movies & TV Shows, PVR, and Music.
Out of the 3 different styles currently used, the fullscreen info style for PVR was chosen as the template on which to base the changes for video fullscreen and music visualisation.

**1 Music Visualisation**

The looks for Music has changed the most as it wasn't possible previously to have full fidelity fanart or visualisation as:
**a**. A `colordiffuse="88FFFFFF` was applied to fanart, most likely to aid with contrast for the label text. It also allows visualisations to be seen through the fanart (not sure if this is an intentional feature).
**b.** An overlay from `<include>ColoredBackgroundImages</include>` was always applied.

Changes:
**1.1.** In order to remove the colordiffuse over fanart an overlay was introduced to provide the necessary contrast for text, the texture used is dialogs/dialog-bg-nobo.png which is the same texture for video fullscren info. This is only for when visualisation is not enabled, for the case where a visualisation is enabled colordiffuse was kept to retain the ability to see visualisation through the fanart.
**1.2.** To make it consistent with video fullscren info, a layout of Artwork to the left (cover) and the info to the right of the artwork was chosen.
**1.3** More prominence given to Track No. & Title by making it bold and a larger font that the other details.
**1.4** In Top Bar Overlay adjust location of position of track in playlist count, and add next track details.
 
**2 Movies/TV Video Fullscreen**

**2.1.** Style changes made to match the existing style for PVR which uses with a fullwidth overlay on with the info is placed.
**2.2.** Chapter info was located on the seekbar and only showed the chapter numbers. I wanted to introduce Chapter Names however I felt there would be enough room for long chapter names in this location, so it seemed to me that good location fit would be in the Top Bar Overlay below the Movie/TV Show title.
**2.3.** For TV Shows introduce if the next item in the video playlist is a TV episode then Next info is shown. This added to below the exiting  Top Bar Overlay info. Wasn't sure if a more general next video playlist item info would be wanted, so it's restricted to TV shows only for now. 
**2.4.** Mute icon moved to left of system time in order that the Ends at time can remain in a consistent place on the right.

**3 PVR Video Fullscreen**
As this was the template used for everything else, only very minor dimension changes done to ensure consistent spacing's/margins of 20pt.

**4 Common changes to seekbar**

**4.1.** Removing Chapter info from seekbar allowed moving the media flags to the left. For video the media flags are now present in 2 row, one for video flags and one for audio flags. Part of the reason for this separation is the debate on PR#11693 on whether to use media flags to show video & audio bitrates.
**4.2.** Audio languge media flag introduced.
**4.3.** With media flags moved to the left, the Time Remaining info can now be displayed when fullscreen info is active, previously it would only show when seekbar was active. It is now also shown for music.
**4.4.** Adjustments made to `$VAR[SeekTimeLabelVar]` and `$VAR[SeekLabel] `so the animation to move `$VAR[SeekTimeLabelVar]`  up to show seek status is no longer required

### Screenshots

**Music Info Before**
![image](https://user-images.githubusercontent.com/5781142/83353280-590a2a80-a349-11ea-9cad-6056fae23384.png)

**Music Info After**
![xfYs473](https://user-images.githubusercontent.com/5781142/83353556-5577a300-a34b-11ea-80c3-5576aaf4d767.jpg)

**Music Fullscreen Fanart Before**
![UdJZrP2](https://user-images.githubusercontent.com/5781142/83353654-e2baf780-a34b-11ea-86cc-9c6999c1032d.jpg)

**Music Fullscreen Fanart After**
![3D1BKyH](https://user-images.githubusercontent.com/5781142/83353657-ea7a9c00-a34b-11ea-9763-9a4026afa58a.jpg)

**Movies Before**
![dPEcIWL](https://user-images.githubusercontent.com/5781142/83354044-8dccb080-a34e-11ea-827e-bc80f6b7a0bd.jpg)

**Movies After**
![d5ffOkq](https://user-images.githubusercontent.com/5781142/83353818-e8fda380-a34c-11ea-804f-d9bcd632179b.jpg)

**TV Show Before**
![h2l1KJl](https://user-images.githubusercontent.com/5781142/83353872-5b6e8380-a34d-11ea-8fbe-7204935d2819.jpg)

**TV Show After**
![RM8ZGGF](https://user-images.githubusercontent.com/5781142/83353905-97a1e400-a34d-11ea-8431-e86c87237464.jpg)

**PVR Before**
![hS5Vyfy](https://user-images.githubusercontent.com/5781142/83354076-b0f76000-a34e-11ea-9f3c-a02bb02f9e62.jpg)

**PVR After**
![b1EnFlH](https://user-images.githubusercontent.com/5781142/83353994-48a87e80-a34e-11ea-8304-f1fde7b35376.jpg)

2020-05-31 14:01 UTC, jjd-uk commented
@ksooo @phunkyfish can one of you check PVR please, it should be pretty much unchanged apart from some minor adjustments to standardise on 20pt margin/spacings, but can only test with PVR demo.

@sarbes this will enable you to have the visualisation you developed without any overlays.

2020-05-31 17:39 UTC, ksooo commented
Why have you chosen to put the steam info labels in two rows? Personally, I like one tire more.

And I'm not sure that moving these labels from right to left side does not have any bad side effects. IIRC, for PVR a "currently recording" label is placed on left if you pull up the info OSD for a channel currently recording.

2020-05-31 17:49 UTC, jjd-uk commented
Looks like I indeed missed "currently recording" label over on that side, the other potential conflicts have already been moved. Will need to think of best way forward.

2020-06-01 00:41 UTC, ronie submitted a review, later dismissed
big thumbs up @jjd-uk for revisiting those dialogs and trying to unify them as well.

i've finished the code review and will start with some runtime testing asap.
it would be great if our other team skinners could take it for a spin as well.
pinging @HitcherUK @gade01 @sualfred @jurialmunkey @jeroenpardon

2020-06-01 00:41 UTC, ronie commented on addons/skin.estuary/xml/MusicVisualisation.xml
> +				</control>
indenting

2020-06-01 00:41 UTC, ronie commented on addons/skin.estuary/xml/MusicVisualisation.xml
> +				<visible>!Visualisation.Enabled | [Visualisation.Enabled + String.IsEmpty(Window(Visualisation).Property(ArtistSlideshow.Image))]</visible>
hmm, don't see the reason for this change?
if visualisation is disabled but artistslideshow provides an image, we should display player.fanart i think?

2020-06-01 00:41 UTC, ronie commented on addons/skin.estuary/xml/MusicVisualisation.xml
> +				<visible>Visualisation.Enabled + !String.IsEmpty(Window(Visualisation).Property(ArtistSlideshow.Image))</visible>
don't understand this one either... why only show artistslideshow images when visualisation is enabled?

2020-06-01 00:41 UTC, ronie commented on addons/skin.estuary/xml/MusicVisualisation.xml
> +			<visible>String.IsEmpty(Player.Art(fanart)) | [!Visualisation.Enabled + Skin.HasSetting(hide_background_fanart)] | [Visualisation.Enabled + String.IsEmpty(Window(Visualisation).Property(ArtistSlid
same..don't get the visualisation/artistslideshow dependency.
i'm also unsure if we should take the hide_background_fanart skin setting into account.

this is a tough one to get it right

the condition of the animation below also might need to be updated once we get this visible condition right.
(ie. no point in animation something that isn't visible)

2020-06-01 00:41 UTC, ronie commented on addons/skin.estuary/xml/MusicVisualisation.xml
> +					<left>440</left>
indenting starts to go wrong here

2020-06-01 00:41 UTC, ronie commented on addons/skin.estuary/xml/MusicVisualisation.xml
> -				</control>
... till here

2020-06-01 00:41 UTC, ronie commented on addons/skin.estuary/xml/Variables.xml
> +		<value condition="!player.chaptercount">$INFO[VideoPlayer.Genre]</value>
see previous comment on using player.chaptercount as a visible condition

2020-06-01 00:59 UTC, ronie commented
and now for my personal preferences (and you should take them that way) :-)

1. the mute icon has a consistent place all throughout the skin.
should that be sacrificed for a label thats only visible in the seekbar?

2. i'm not a fan of the double rows for mediaflags, it just doesn't look right to me.
i'd prefer to stick with 5 (or 6 if enough space) flags on a single row.

3. i've reviewed your screenshot above and suffered from a brain crash when trying to process the info shown on the last one...
displaying 11 different time labels in a single window caused an information overload on my end.
![error](https://user-images.githubusercontent.com/687265/83367236-db2f3900-a3b3-11ea-93e0-d4986039bc36.jpg)

2020-06-02 09:21 UTC, walterheisenberg commented
sorry for hijacking
If you are re-thinking PVR, then PVR-OSD should also be rethought.
Here is a screenshot, which shows a IMHO better OSD for PVR:
https://forum.kodi.tv/showthread.php?tid=335735&pid=2932070#pid2932070

PVR is much different from Music or Videos because it has a following program and you should easily see, whats next on this channel and when it begins.
Even this OSD need tweaking e.g. double "time", no weather but this would IMHO be a improvement for all PVR users out there.
If you don't want such a discussion here, please let me know where ;)
CU

2020-06-02 10:28 UTC, ksooo commented
Please keep that discussion on the forum.

2020-06-04 16:57 UTC, jjd-uk commented on addons/skin.estuary/xml/Custom_1109_TopBarOverlay.xml
> +						<visible>player.chaptercount</visible>
This hasn't been changed in what I've done, it how it was done in the previous position https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/xml/DialogSeekBar.xml#L41
and how it's also used elsewhere https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/xml/VideoOSD.xml#L52
https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/xml/VideoOSD.xml#L84

and same goes for Confluence
https://github.com/xbmc/skin.confluence/blob/d9639e012a8c5814e19574edcb47f62ffb76e6e3/720p/DialogSeekBar.xml#L87
https://github.com/xbmc/skin.confluence/blob/master/720p/VideoFullScreen.xml#L77

Further more using `String.IsEmpty(player.chaptercount)` can cause issue. See response to your other comment on this.

2020-06-04 17:20 UTC, jjd-uk commented
@ronie @ksooo Updated and screenshots have been update to show current state.

-  **Mute icon -**  Changed back to how it was. It's only on my dev PC I noticed the slide animation to the left for End Time to make room for the Mute icon so it's not a big deal to me. Besides one of the points of this PR is to introduce more consistency so yes it's probably best to manintain this both in & out of fullscreen playback.

- **Media Flags -** Changed media flags back to single row. The dual rows to split video & audio was something I wanted to try out because of the discussions on https://github.com/xbmc/xbmc/pull/11693 so this would give more room for additional flags.

- **Currently recording/PVR -** For PVR I've now moved the "currently recording" status to the top. To me this makes more sense as every commercial PVR I've used puts the recording status alongside the name of the TV programme being recorded. Other than this and the minor position adjustments, PVR is completely unchanged.

2020-06-04 17:21 UTC, ksooo commented
@jjd-uk  I have seen single line stream info badges in the lower right at other places  in Estuary. Your change to move these badges to lower left for some views would make this inconsistent, I'm afraid. Example:

![screenshot000](https://user-images.githubusercontent.com/3226626/83790465-897afd00-a698-11ea-9717-69b5c7bfbea1.png)

2020-06-05 01:15 UTC, jurialmunkey commented
On the topic of the codec badges and also relevant to Ronie's comment about time labels: 

I think it is overkill to show _both_ "time remaining" and "ends at". To keep skin positioning consistent, I'd drop the time remaining label and move the codecs back to the bottom right. That would leave the bottom left blank, but I think it is important to remember that we don't need to fill every bit of screen realestate - sometimes a bit of breathing room is a good thing!


As a separate point - is there any reason why in PVR the "Next" item is shown in the info panel with the plot but in movies/episodes/music it is shown in the top left? Shouldn't the next item be shown in a consistent position?

I personally would put the "Next" item with the plot (like in the PVR screenshots). That way the top left only relates to what is directly only screen "Now", then the plot box provides information about what is coming "Next" (plot is essentially about the future as it's purpose generally is to describe what _will_ happen in the episode)

2020-06-05 07:16 UTC, howie-f commented
> To keep skin positioning consistent, I'd drop the time remaining label and move the codecs back to the bottom right.

true :+1:  just wanna throw in that IMO removing "time remaining" is not needed then as it never shows up with codec badges at the same time

2020-06-05 10:52 UTC, jjd-uk commented
While I agree with some of the above comments, I was trying to improve what we currently have without doing a radical redesign.

To address all the points would IMHO require a complete redesign, something like a partially done experiment of mine shown below. I've not continued it as I thought it would be too big a change from what we currently have.

![image](https://user-images.githubusercontent.com/5781142/83868218-6bf27580-a722-11ea-9ee7-b378a69abb1d.png)

![image](https://user-images.githubusercontent.com/5781142/83868074-32ba0580-a722-11ea-927e-aab9d803ff65.png)

2020-06-05 14:11 UTC, ksooo commented
I still like best where the stream info badges are located today - lower right.

2020-06-05 14:13 UTC, ksooo commented
Forgive me, but the last PVR screenshot (your experiment) looks quite crowded to me. So much information on such a small space...

2020-06-06 02:22 UTC, jurialmunkey commented
> Forgive me, but the last PVR screenshot (your experiment) looks quite crowded to me. So much information on such a small space...

Yeah I wasn't suggesting anything as drastic as that.

Here's a screenshot of what I was suggesting:

![Honeyview_screenshot004](https://user-images.githubusercontent.com/4618719/83933861-ab3ac800-a7ef-11ea-8fc0-cf36826891c7.jpg)

2020-06-06 06:07 UTC, ksooo commented
> Here's a screenshot of what I was suggesting:

 For PVR, channel number and channel is important information. This must not be removed from the info screen, imo.

2020-06-06 06:50 UTC, jurialmunkey commented
> 
> 
> > Here's a screenshot of what I was suggesting:
> 
> For PVR, channel number and channel is important information. This must not be removed from the info screen, imo.

That screenshot is for tvshows/movies not PVR.

PVR would stay the same as jjd-uk's original, just with codecs moving back to the right.

2020-06-06 15:44 UTC, jjd-uk commented
Updated again, hopefully the final design iteration this time.

2020-06-06 16:04 UTC, phunkyfish commented
So PVR is unchanged? I don’t see a difference in the screenshots now.

2020-06-06 16:35 UTC, jjd-uk commented
> So PVR is unchanged? I don’t see a difference in the screenshots now.

@phunkyfish There was never much change for PVR as I used PVR style as template for all the other changes. 

With latest version the difference from master is even less now, what's left is:

- Standardise a 20pt margin between elements on x axis,
- Next label uses `button_focus` color to fit with other uses of next elsewhere.
- Text color of `currently recording` changed from white to red,

So only thing from PVR point of view that needs double checking, are the the co-ordinate changes to provide for the 20pt margins as I can only test with PVR Demo.

2020-06-06 16:48 UTC, jjd-uk commented
@phunkyfish if you're able to take a look, this bit I had to adjusted blind https://github.com/xbmc/xbmc/blob/bbb838c777d5785d7420adba60837435679b16e7/addons/skin.estuary/xml/DialogSeekBar.xml#L330-L348 as with PVR Demo I don't see anyway to get that PVR.EpgEventIcon. It's only minor adjustments for the left & right co-ordinates.

2020-06-07 23:05 UTC, ronie commented on addons/skin.estuary/xml/Custom_1109_TopBarOverlay.xml
> +						<visible>player.chaptercount</visible>
thx, learned something new today :-)

when the visible condition doesn't match an InfoBool, there's a fallback to using InfoInt:

https://github.com/xbmc/xbmc/blob/f4c303584c8eb6237c55cf19ae7855718adaea92/xbmc/GUIInfoManager.cpp#L10188-L10193

so, ignore my noise.

2020-06-08 00:16 UTC, ronie commented
i think this whole block can be simplified:
https://github.com/xbmc/xbmc/blob/bbb838c777d5785d7420adba60837435679b16e7/addons/skin.estuary/xml/MusicVisualisation.xml#L17-L57

1. the $VAR[MediaFanartVar] image makes no sense ...at least to me?
2. the $INFO[Player.Art(fanart)] image also needs to be visible when !Visualisation.Enabled
3. and 4. no need for two ArtistSlideshow image control, use a fade anim to conditionally fade the image
5. the multiimage can be removed, this was for an old version of the artistslideshow addon

what's left is:
```
<control type="image">
	<aspectratio>scale</aspectratio>
	<fadetime>400</fadetime>
	<animation effect="fade" start="0" end="100" time="400">WindowOpen</animation>
	<animation effect="fade" start="100" end="0" time="300">WindowClose</animation>
	<animation effect="fade" start="100" end="50" time="0" condition="Visualisation.Enabled">Conditional</animation>
	<texture background="true">$INFO[Player.Art(fanart)]</texture>
	<visible>String.IsEmpty(Window(Visualisation).Property(ArtistSlideshow.Image)</visible>
</control>
<control type="image">
	<aspectratio>scale</aspectratio>
	<fadetime>400</fadetime>
	<animation effect="fade" start="0" end="100" time="400">WindowOpen</animation>
	<animation effect="fade" start="100" end="0" time="300">WindowClose</animation>
	<animation effect="fade" start="100" end="50" time="0" condition="Visualisation.Enabled">Conditional</animation>
	<texture background="true">$INFO[Window(Visualisation).Property(ArtistSlideshow.Image)]</texture>
</control>
```

2020-06-08 00:38 UTC, ronie commented
now for the tricky part:
https://github.com/xbmc/xbmc/blob/bbb838c777d5785d7420adba60837435679b16e7/addons/skin.estuary/xml/MusicVisualisation.xml#L59-L63

and i might get it wrong, but i think we should only show ColoredBackgroundImages if:
we have no player fanart AND we have no artistslideshow fanart AND we have no visualisation.

not sure if we want to throw Skin.HasSetting(hide_background_fanart) into the mix as well,
as that would result in a full black screen.

if all that makes sense, the whole block could be simplified to a single line:
```
<include condition="String.IsEmpty(Player.Art(fanart)) + String.IsEmpty(Window(Visualisation).Property(ArtistSlideshow.Image)) + !Visualisation.Enabled">ColoredBackgroundImages</include>
```

2020-06-08 15:48 UTC, jjd-uk commented
@ronie Update, I stupidly pushed the wrong version of musicvisualation.xml in last update so not surprised you were baffled by some things.

I took your suggestion for displaying fanart and artist slideshow images. However when it comes to your suggestion for the `ColoredBackgroundImages` as it results in black background if "Show Fanart backgroud" is disabled or if there's no fanart. This is why the check for `Skin.HasSetting(hide_background_fanart)` needs to be there.

So now I've got:

`<visible>!Visualisation.Enabled + [String.IsEmpty(Player.Art(fanart)) | Skin.HasSetting(hide_background_fanart)]</visible>`

`ColoredBackgroundImages`  needs to be dispayed if:

If both Show Fanart backgroud and Visualisation is disabled
If Show Fanart backgroud is enabled and no Kodi fanart 
If Show Fanart backgroud is enabled and no Artist Slidesshow fanart 

There is no explict check required for images from Artist Slideshow as in this case Player.Art(fanart) is used as a fallback, so only whether an image is returned by Player.Art(fanart) is required.

I don't normally use Artist Slideshow but to ensure all cases are covered I set it up. In this test case only artist Meat Loaf has any images downloaded by Artist Slideshow as shopwn in addondata folder

![image](https://user-images.githubusercontent.com/5781142/84049858-dc102e00-a9a4-11ea-9304-ad92935f3633.png)

The following playlist was used

![image](https://user-images.githubusercontent.com/5781142/84049944-f8ac6600-a9a4-11ea-816b-b2a83f580b36.png)

where:

Pet Shop Boys - Kodi scraped fanart
Levellers - no fanart
Meat Loaf - Artist Slideshow fanart

The below videos show testing the following scenarios:

Fanart disabled & Visualisation disabled
Fanart enabled & Visualisation disabled
Fanart enabled & Visualisation enabled
Fanart disabled & Visualisation enabled

My code https://youtu.be/Fd42AzmzFLs

Works in all cases

Your code https://youtu.be/zZ399PDjeyE

Fanart disabled & Visualisation disabled - Time 00:00-00:56 - Black screen no coloured background as there should be.
Fanart enabled & Visualisation disabled - Time 01:22-01:36 & 01:52- 02:09 - Black screen no coloured background as there should be.

2020-06-08 21:30 UTC, ronie commented
super, the `Skin.HasSetting(hide_background_fanart)` check indeed needs to be included as well.
for the rest, you're right on all accounts, except this:

> There is no explict check required for images from Artist Slideshow as in this case Player.Art(fanart) is used as a fallback, so only whether an image is returned by Player.Art(fanart) is required.

consider this setup:
- player art: no
- hide background fanart: no
- visualisation enabled: no
- artist slideshow art: yes

your code will now display the `ColoredBackgroundImages` (covering the artist slideshow images)

![as](https://user-images.githubusercontent.com/687265/84079552-0c72bf00-a9db-11ea-8549-fedd38228c0d.jpg)

to fix that, change the visible condition to this:
```
<visible>!Visualisation.Enabled + [[String.IsEmpty(Player.Art(fanart)) + String.IsEmpty(Window(Visualisation).Property(ArtistSlideshow.Image))] | Skin.HasSetting(hide_background_fanart)]</visible>
```

i've now runtime tested all of the changes as well and couldn't find any other issues.
thumbs up!

2020-06-10 20:57 UTC, ronie requested changes
just a few cosmetic issues left.
once those are fixed, i'm fine with merging this.

2020-06-12 15:47 UTC, jjd-uk commented
@ronie cosmetics fixed

2020-06-12 16:45 UTC, ronie approved these changes

2020-06-14 20:47 UTC, merged

2020-06-14 20:47 UTC, ronie commented
thx!

2020-06-14 21:18 UTC, ksooo commented
I noticed two things with this (otherwise nice) rework with TV shows info:

![screenshot001](https://user-images.githubusercontent.com/3226626/84604293-41788900-ae95-11ea-93b6-0c82249a7c91.png)

2020-06-14 21:41 UTC, ksooo commented
Regarding the problem with "Next:" I mentioned in my previous comment - forget about it. I was using an inconsistent build. Sorry for the noise.

2020-06-14 21:57 UTC, jjd-uk commented
@ksooo that timestamp for the chapter is returned by core if there's no chapter name, it is exactly the same as it was in Confluence. I don't believe there's any way for me to reduce precision at a skin level.

2020-06-14 22:02 UTC, ksooo commented
which infolabel is that?

2020-06-14 22:08 UTC, jjd-uk commented
It's $INFO[Player.ChapterName]

2020-06-15 07:21 UTC, ksooo commented
@jjd-uk fyi, in my case the chapter title (player.chaptername) comes from ffmpeg - so nothing we can easily fix, because ffmpeg returns this as chapter title.

2020-06-15 07:37 UTC, jjd-uk commented
@ksooo I guess there's some logic somewhere that if there's no chapter name it falls back to the timestamp used for seeking to chapters? so no surprise that timestamp comes from ffmpeg as it's a player infobool, or are you saying it's ffmpeg always used so the callback is in ffmpeg?  Personally I wouldn't mind if we only returned a value if it's string so the timestamps never get displayed, no idea whether that might be possible.

2020-06-15 12:42 UTC, ksooo commented
>  guess there's some logic somewhere that if there's no chapter name it falls back to the timestamp used for seeking to chapters? 

 Yes, and unfortunately this logic seems to be inside ffmpeg, not Kodi code. :-/

> or are you saying it's ffmpeg always used so the fallback is in ffmpeg

 The demuxer is asked for the title, so the value is what the demuxer returns. No logic inside Kodi. This can be different for ffmpeg or inputstream.adaptive, ... ffmpeg demuxer asks ffmepeg for the title, another demuxer will do something else. From Kodi perspective it is just an arbitrary string returned by the demuxer if asked for the chapter name.

2020-06-15 12:55 UTC, jjd-uk commented
Got it.