[Estuary] [OSD] [PVR] New record icons + Player Forward/Next adjustme…
xbmc/xbmc pull request #18261
Opened 2020-08-08 09:56 UTC by jjd-uk

Follow up to https://github.com/xbmc/xbmc/pull/18155

### Record button

In a clean up of `OSDHelpTextVar` prior to merger I missed there was a label for the Record button so it was accidentally removed.

**Record button labelled before PR18155**
![image](https://user-images.githubusercontent.com/5781142/89706968-3ce6c300-d962-11ea-9f38-6435c2d6589a.png)

The Record button is the only Player control button that is labelled (which is why I missed it).  While I don't know for sure  but my guess is the label was only there as it was felt a white dot wouldn't not convey the purpose of the button. The universal button symbol for Record would usually be a red dot, however this is used to convey when recording is active. Rather than re-instate the label my solution is to introduce 2 new Record button textures so a labelled is not require.

For when recording is not active `record-white.png` is now a bigger white do with a central smaller red dot to clearly convey this is the record button without need for a label.

**New record-white.png**
![image](https://user-images.githubusercontent.com/5781142/89707106-2db44500-d963-11ea-8adb-143fb783d829.png)

For when recording is active `record.png` the button becomes all red (I just took the circular boundary of the white portion of `record-white.png` and filled with red).

**New record.png**
![image](https://user-images.githubusercontent.com/5781142/89707303-bb446480-d964-11ea-8990-6eac51df9a2a.png)

### Player Forward/Next controls

In addition after further testing of the changes contained in https://github.com/xbmc/xbmc/pull/18155 it's been seen that using Player.SeekEnabled enables the Player Forward and Next buttons even if it can't seek in the forward direction. It thus seems to make sense that for Live TV to only enable these buttons if in Timeshift mode, so when behind live with the ability to seek forward. Therefore the buttons have been adjusted to use `VideoPlayer.Content(LiveTV) + PVR.IsTimeShift` within their Visibility control.

These changes were discussed with @ksooo on Slack and at the time he was in agreement with these changes.

## Types of change

- [x ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

2020-08-08 10:28 UTC, jjd-uk commented
Just to note I've no problem with re-instating label if it's felt it's needed, it just felt odd to me that it was the only player control labelled, so have tried to be smarter with the button textures.

2020-08-09 00:57 UTC, ronie commented
thanx, i'm fine with PVR.IsTimeShift changes (certainly since @ksooo already approved them).

i'm not really a fan of the new recording buttons. perhaps the current dot should be a little bigger, but not as big as your proposed version... perhaps somewhere in between.

alternatively, another pretty common version of the record icon is a small dot with a circle
![record](https://user-images.githubusercontent.com/687265/89722554-318baa00-d9eb-11ea-930c-8952e8dd2c3d.jpg)

also, my preference would be to keep them plain white in a non-recording state.

2020-08-09 10:44 UTC, jjd-uk commented
**To do:** simplify [VideoPlayer.Content(livetv) + PVR.IsTimeShift] to just `PVR.IsTimeShift` as you can only timeshift with livetv.

2020-08-09 10:48 UTC, jjd-uk commented
@ronie how about a white circle with a transparent hole then the hole gets filled with red when recording is active?

![image](https://user-images.githubusercontent.com/5781142/89730359-d501ac80-da35-11ea-862e-20148e645612.png)

![image](https://user-images.githubusercontent.com/5781142/89730383-f82c5c00-da35-11ea-9777-c3aebbba18ec.png)

![image](https://user-images.githubusercontent.com/5781142/89730387-ffec0080-da35-11ea-92c0-4b47b074a2aa.png)

![image](https://user-images.githubusercontent.com/5781142/89730395-067a7800-da36-11ea-9230-f566ac8656e0.png)

2020-08-09 22:37 UTC, ronie commented
it's the three coloured rings that throws me off..
![rwb](https://user-images.githubusercontent.com/687265/89742090-1d9d8200-da97-11ea-892a-a22877257455.jpg)

might be me, but when i see that, all i can think of is:
![by](https://user-images.githubusercontent.com/687265/89742138-8f75cb80-da97-11ea-8912-24e08d8da28d.jpg)

2020-08-12 09:39 UTC, da-anda commented
as for the recording button. I think a red circle is the most intuitive icon for a recording button. To differentiate between not recording and recording state, we could make the button blink/pulsate/partially fade in/out when a recording is going on. Just as an idea - chances are good that it will suck visually :)

2020-08-12 11:04 UTC, jjd-uk commented
To avoid the tri-colour effect ronie pointed out I see 2 options, out of these I'm currently favouring Option 1.

### Option 1

Recording not active
![image](https://user-images.githubusercontent.com/5781142/90007657-0c20c980-dc93-11ea-900c-cba22d9d4008.png)

Recording active
![image](https://user-images.githubusercontent.com/5781142/90007681-15119b00-dc93-11ea-8754-41f5f13d6e42.png)

### Option 2

Recording not active
![image](https://user-images.githubusercontent.com/5781142/90007681-15119b00-dc93-11ea-8754-41f5f13d6e42.png)

Recording active
![image](https://user-images.githubusercontent.com/5781142/90007759-36728700-dc93-11ea-9e93-15cc53ec3c7c.png)

2020-08-12 22:47 UTC, ronie commented
> The universal button symbol for Record would usually be a red dot

agreed, so changing it to a circle is not really an improvement imo.
my preference would be to leave the record button as is, or make the dot slightly bigger.

2020-08-22 20:35 UTC, ronie requested changes
code looks good to me, apart from the dupe id.
i like the changes to the play button, thumbs up for that!

2020-08-23 12:23 UTC, ronie approved these changes
thx!

2020-08-25 10:48 UTC, merged