[Music][guiinfo] Add new MusicPlayer infolabel and boolean
xbmc/xbmc pull request #18420
Opened 2020-09-14 11:32 UTC by the-black-eagle

## Description
Add new `MusicPlayer.IsMultiDisc` boolean and `MusicPlayer.TotalDiscs` infolabel as discussed on slack.

## Motivation and Context
Provides a method for skinners to hide the disc number in the musicvisualisation window if the album only consists of a single disc.  Can also be used to display f.e `Disc 3 of 5`

## How Has This Been Tested?
Tested with a modified skin to display the number of discs belonging to an album if `MusicPlayer.IsMultiDisc` was true, else to just display the text `Single disc album`.

## Screenshots (if appropriate):

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2020-09-14 20:37 UTC, ronie approved these changes
tested and works as expected, thx!

2020-09-15 17:05 UTC, DaveTBlake commented
Sorry, going to block the way this has been implemented for the music database. Doing an additional  query per row of a query results dataset is very inefficient. It is the underlying query that needs to be changed if a disc count is wanted for every song.

2020-09-15 17:07 UTC, DaveTBlake requested changes

2020-09-15 17:07 UTC, DaveTBlake commented on xbmc/music/MusicDatabase.cpp
> +  }
Not a good way to implement this, will mean an extra query per song when showing the songs node.

2020-09-15 18:00 UTC, DaveTBlake commented
Another thought...
Looking at the Estuary change to make use of this info label I notice that Estuary already shows "Track 1/16". Where does that comes from? Could a similar approach be used for disc number and subtitle? 

An item list of songs does not include how many songs there are on the album it comes from, neither in song table nor songview. Fetching that data for a currently playing song could be done efficiently rather than add it to the data for all songs in an item list.

2020-09-15 18:13 UTC, jjd-uk commented
> Another thought...
> Looking at the Estuary change to make use of this info label I notice that Estuary already shows "Track 1/16". Where does that comes from? Could a similar approach be used for disc number and subtitle?

That is $INFO[Playlist.Length]

2020-09-15 18:38 UTC, DaveTBlake commented
> That is $INFO[Playlist.Position] and $INFO[Playlist.Length]

Oh so not showing track/album information as  I assumed. If I had queued up several albums it could be saying "25/185" when playing track 4 of the 2nd album.

2020-09-15 22:25 UTC, the-black-eagle commented
@DaveTBlake PR updated to use songview to populate the MusicInfoTag.

2020-09-16 07:13 UTC, DaveTBlake reviewed
Thanks @the-black-eagle much better approach since songview alreday has join to album table and hence easy asscess to disc total. 
Small change regarding comment and db bump, and while doing that you could tweak the comment desc to somethinglike "Add disc total to songview and MusicPlayer infolabel and boolean"

2020-09-19 07:41 UTC, the-black-eagle commented
@DaveTBlake Are you OK with this now?

2020-09-19 08:25 UTC, DaveTBlake approved these changes

2020-09-19 11:15 UTC, merged