[platform] Fix 'move to CPlatformXXX' todo
xbmc/xbmc pull request #18435
Opened 2020-09-17 06:51 UTC by sy6sy2

## Description

This PR tries to fix `//! @todo - move to CPlatformXXX` comments from `Application.cpp`.
The goal is to move platform specific initialization stuff in dedicated platform files.

## Motivation and Context

Keep a clean `Application.cpp` file (I guess).

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2020-09-17 06:53 UTC, sy6sy2 commented
@lrusak, before going further, can you check that I am in the right direction and if  I well understand the "todo"?
Thank you!

2020-09-17 14:36 UTC, lrusak commented
> @lrusak, before going further, can you check that I am in the right direction and if I well understand the "todo"?
> Thank you!

tl;dr:
 - don't create more platform specifics (ask "how can I remove these platform ifdefs")
 - generalize the methods as much as possible (even if this means reordering).


long answer:

You have somewhat the right idea but the way you are doing it breaks the design. The whole reason to move to using `CPlatform` is to remove the platform specifics from `CApplication`. This includes the ifdeffery too.

`CPlatform` is constructed and init'd in `CServiceManager::InitStageOne`, this should be earlier enough so that `CPlatform` is alive for any of the calls you need to do.

Ideally we should just be able to put the platform specifics in the `CPlatformXXX::Init` method however this may not hold true and we may need to do things later in the init process. We also shouldn't have to access `CPlatform` through `CApplication` at all. If you need to call a method from `CPlatform` then you should add a method to `CServiceBroker` to get the member from `CServiceManager` (who owns the member) but it's likely that this isn't even needed at all.

2020-09-17 14:54 UTC, sy6sy2 commented
Thank you for taking time to explain me!
With your answer and Fuzzard's answer I understand better the main idea 😉 
I will try something.

2020-09-24 05:43 UTC, wsnipex commented
Looks like this is the same as your xcode PR, branch mixup?

2020-09-24 06:03 UTC, sy6sy2 commented
Oups, force push on the wrong branch...

2020-09-24 06:18 UTC, wsnipex commented
Ah ok, got it now, sorry for the confusion

2020-09-25 20:09 UTC, jenkins4kodi commented
@sy6sy2 this needs a rebase

2020-10-08 15:17 UTC, sy6sy2 commented
@lrusak can I modify signature of `Platform::Init()` to return a `bool` in order to handle error cases or it's a bad idea?
https://github.com/xbmc/xbmc/blob/cc286a397145184ff27458c610bfe839d5c432c7/xbmc/platform/Platform.h#L31-L36

Thank you!

2020-10-08 17:13 UTC, lrusak commented
> @lrusak can I modify signature of `Platform::Init()` to return a `bool` in order to handle error cases or it's a bad idea?
> https://github.com/xbmc/xbmc/blob/cc286a397145184ff27458c610bfe839d5c432c7/xbmc/platform/Platform.h#L31-L36
> 
> Thank you!

sure if it makes sense to do so. Be aware you will have to change it for all platforms though.

2020-10-09 08:13 UTC, sy6sy2 commented
I hope my way is better now? 😇

2020-10-09 22:07 UTC, lrusak requested changes
Looks much better! I've just pointed out some minors.

Also, please use the same copyright header for all new files being added (I think it should be 2005-2020 ???)

2020-10-09 22:07 UTC, lrusak commented on xbmc/ServiceManager.cpp
> +  {
probably don't need the braces (same for all checks)

2020-10-09 22:07 UTC, lrusak commented on xbmc/Util.cpp
> +  if (destname == "")
destname.empty()

2020-10-09 22:07 UTC, lrusak commented on xbmc/platform/overrides/darwin_embedded/PlatformDarwinEmbedded.h
> +  /**\brief C'tor */
doxygen doesn't provide any value here (you can remove it from all similar headers being added)

2020-10-09 22:07 UTC, lrusak commented on xbmc/platform/overrides/darwin_embedded/PlatformDarwinEmbedded.h
> +  /**\brief D'tor */
same with this

2020-10-09 22:07 UTC, lrusak commented on xbmc/platform/overrides/windows/PlatformWin32.cpp
> +      true); // enable independent locale for each thread, see https://connect.microsoft.com/VisualStudio/feedback/details/794122
ugly line break (just move the comment)

2020-10-09 22:07 UTC, lrusak commented on xbmc/platform/overrides/windowsstore/PlatformWin10.cpp
> +      true); // enable independent locale for each thread, see https://connect.microsoft.com/VisualStudio/feedback/details/794122
same thing here

2020-10-27 06:06 UTC, fuzzard commented
Did a runtime test of this on Android-arm64, seems fine. 
@KarellenX  did a test on win64, and said it seemed ok.

Any linux folks able to test it on that front?

2020-10-27 06:09 UTC, fuzzard approved these changes

2020-10-27 20:22 UTC, jenkins4kodi commented
@sy6sy2 this needs a rebase

2020-10-27 22:22 UTC, sy6sy2 commented
I did the rebase, I hope I did not break anything concerning what @lrusak did on #18534 😕

2020-10-28 10:15 UTC, sy6sy2 commented
Jenkins build this please

2020-10-29 02:28 UTC, lrusak approved these changes
Looks good. Great work!

I'll likely submit a PR after this to clean up some stuff and remove the weird /overrides directory. We shouldn't really be using wildcards to add source files to the cmake build.

2020-10-29 03:39 UTC, merged