Fix tests
xbmc/xbmc pull request #18434
Opened 2020-09-16 23:46 UTC by basilgello

## Description

Fixes #18299 on Linux and amends #18011 

## Motivation and Context

Building Debian package requires full testsuite to pass unless "-notest" CLI switch is given.
However, official builds include testsuite runs and having even one failing test results in
a whole failed build.

## How Has This Been Tested?

Built Debian package on Debian sid / unstable.

## Screenshots (if appropriate):

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

2020-09-16 23:46 UTC, basilgello commented
@phunkyfish @lrusak

2020-09-17 16:11 UTC, phunkyfish requested changes
It would make sense to run git-clang-format on your changes. You may want to switch clang-format off /on for the char array.

2020-09-17 16:11 UTC, phunkyfish commented on xbmc/platform/linux/test/TestSysfsPath.cpp
> +      KODI::UTILS::RandomAlphaNumString(12);
Why two lines?

2020-09-17 16:11 UTC, phunkyfish commented on xbmc/utils/Random.cpp
> +char_array alnum_charset()
`AlnumCharset`

2020-09-17 16:11 UTC, phunkyfish commented on xbmc/utils/Random.cpp
> +    return char_array(
`charArray`

2020-09-17 16:11 UTC, phunkyfish commented on xbmc/utils/Random.cpp
> +  std::uniform_int_distribution<> dist(0, charset.size()-1);
Space before and after `-1`

2020-09-17 16:11 UTC, phunkyfish commented on xbmc/utils/Random.h
> +typedef std::vector<char> char_array;
Do we really need a typedef here?

2020-09-17 17:14 UTC, lrusak commented
I feel like adding a whole new class just for tests is a bit overkill. Other changes are probably fine. This will all be wiped out hopefully when I finish the work to use std::chron/std::date

2020-09-18 13:30 UTC, basilgello commented
> I feel like adding a whole new class just for tests is a bit overkill. Other changes are probably fine. This will all be wiped out hopefully when I finish the work to use std::chrono/std::date

It is not a class but a separate file to make ld.gold happy about "duplicate definition" at link-time.
I can make this function a part of TestSysfsPath.cpp and leave Random.h intact but I thought we
might need a standard random string generator as part of KODI::UTILS. Do we need it?

I want to know this before resolving issues @phunkyfish mentioned.

2020-09-18 13:55 UTC, phunkyfish commented
I think make it local to the test currently as that is the only place it is used. If we need to generalise it later as we have another use case we can do that then.

2020-09-18 14:29 UTC, lrusak commented
you could always just use the uuid generator instead of implementing something new. See, https://github.com/xbmc/xbmc/blob/master/xbmc/utils/StringUtils.h#L312

2020-09-18 14:38 UTC, basilgello commented
Makes sense, thanks! Fixed!

2020-09-18 15:16 UTC, phunkyfish approved these changes

2020-09-18 16:35 UTC, lrusak approved these changes
thanks for the great work! LGTM

2020-09-19 07:24 UTC, merged