assorted cppcheck warning fixups
xbmc/xbmc pull request #18472
Opened 2020-09-29 09:51 UTC by fuzzard

## Motivation and Context
Fix assorted warnings raised by cppcheck build @lrusak ran recently https://jenkins.kodi.tv/view/Reports/job/LINUX-64-Static-Analysis/lastSuccessfulBuild/cppcheck/

## How Has This Been Tested?
compile/runtime tested osx

## Screenshots (if appropriate):

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2020-09-29 15:24 UTC, lrusak commented on xbmc/guilib/GUITexture.h
> +  void Render(float left, float top, float right, float bottom, float u1, float v1, float u2, float v2, float u3, float v3)
whoopsie

2020-09-29 15:50 UTC, ksooo commented on xbmc/platform/darwin/osx/XBMCHelper.cpp
> +      char real_path[2*MAXPATHLEN];
`2 * MAXPATHLEN` (blank before and after *)

2020-09-29 15:50 UTC, ksooo commented on xbmc/platform/darwin/osx/network/NetworkOsx.cpp
> +    char* buf = (char*)malloc(needed);
`static_cast<char*>`

2020-09-30 03:01 UTC, garbear approved these changes

2020-09-30 14:07 UTC, phunkyfish approved these changes

2020-09-30 14:13 UTC, lrusak requested changes
You have a couple diffs to apply from jenkins. May I suggest using some clang-format hooks? :wink: https://github.com/barisione/clang-format-hooks

2020-09-30 17:13 UTC, fuzzard commented
I'll be honest, i think both of those clang changes are ugly, but I'll do them later today

2020-10-06 22:14 UTC, merged