[Estuary] Optional poster for musicvideo widgets
xbmc/xbmc pull request #18479
Opened 2020-10-01 06:40 UTC by DaVukovic

## Description

This change adds a setting to choose which kind of artwork is shown at the Estuary home screen for the musicvideo widgets..

## Motivation and Context

As I'm using the "musicvideo" section for concert DVDs/BRs I thought it might be a good idea to also be able to see the posters for those videos. Others might use this section differently, hence I created a setting for it so there's no change for those users

## How Has This Been Tested?

Tested with latest master

## Screenshots (if appropriate):
Before:
![image](https://user-images.githubusercontent.com/7235787/94776029-3bb19f80-03c1-11eb-8bc7-fed9a887d2da.png)

After:
![image](https://user-images.githubusercontent.com/7235787/94776093-5d128b80-03c1-11eb-8aeb-82ad780a3cea.png)

The setting:
![image](https://user-images.githubusercontent.com/7235787/94776148-774c6980-03c1-11eb-92d3-28ef649e2b79.png)

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2020-10-01 07:16 UTC, howie-f commented
i‘d just move the setting to artwork, but that‘s my personal preference

2020-10-01 09:07 UTC, gade01 commented
The changed look great.
But I think @howie-f is correct to move the setting to artwork.

2020-10-01 09:16 UTC, DaVukovic commented
Sure, that's not a problem. Will change that

2020-10-01 09:29 UTC, DaVukovic commented
done:

![image](https://user-images.githubusercontent.com/7235787/94792515-61e33980-03d9-11eb-9693-1c99239991f3.png)

2020-10-01 10:20 UTC, ronie commented
changes look good to me, thx!

if you don't mind me asking, why only the homescreen widgets instead of extending it throughout the rest of the skin?

2020-10-01 10:30 UTC, DaVukovic commented
>if you don't mind me asking, why only the homescreen widgets instead of extending it throughout the rest of the skin?

good question where I don't have an answer for ;)
I just haven't thought about that, tbh. Will have a look if I can get it managed for the specific views and will amend them to this PR if I get it working

2020-10-03 18:50 UTC, scott967 commented
just throwing this out there -- would it be possible to open a select dialog with the available arttypes?  Thought is if users define a "cover" arttype as an alternative for "poster".

2020-10-04 05:23 UTC, DaVukovic commented
@scott967 tbh, I don't see the difference between a "cover" and a "poster" and AFAICT, "cover" is not available as an arttype:

https://kodi.wiki/view/Artwork_types

For Estuary and the section I changed, there are only "WdgetListPoster" and "WidgetListEpisodes" available and each are referring to either "ListItem.Art(poster)" for the poster or "ListItem.Icon" for the thumb. So either I misunderstood your request or I can't see where we might have "cover" as an available arttype.

2020-10-04 06:45 UTC, DaveTBlake commented
Re "cover" verses "poster", I would expect ratio differences - poster being portrait (e.g. DVD case) and cover being (almost) square (e.g. CD case). A music video can have a related album in the music library, and that album will have a cover in art type "thumb". No idea if that artwork is availlable to the widget or what type used.

Also users can add custom art types (with nice GUI settings to do that in v19 rather than whitelist in as.xml), so could add "cover" as a music video art type. 

Not saying anything needs to be done here @DaVukovic , just explaining what Scott may have meant.

2020-10-04 07:24 UTC, DaVukovic commented
@DaveTBlake ok, thanks for explaining. I see

@ronie In the meantime I've updated this PR to be able to show either poster or thumbs for some viewtypes (wall and infowall. I expect viewtypes like "Shift" or "Widelist" to always show the poster. Hence I haven't touch them. Please tell me if we should make this possible as well. 
Also would like to hear what you think of those changes ;)

2020-10-04 12:43 UTC, ronie commented
i don't think it's needed to add a new itemlayout/focuslayout to wall & infowall views?
unless i missed something, it's as simple as changing the visible conditions like this:
https://github.com/ronie/xbmc/commit/78f6e5d7454ddd9b8b3a362b4ae8821deb80797b

you also need a change in the video info dialog:
https://github.com/ronie/xbmc/commit/1416d9c953d26c6ed59a16976a81bf86256bee81

and finally, this change to fix the icon in the contentpanel in the widelist/infowall views:
https://github.com/ronie/xbmc/commit/dbc88278a523da8b95bd1dd5fde91b14e970d92e

also, please update the skin setting string, as the setting no longer applies to widgets only.

2020-10-04 12:45 UTC, ronie requested changes

2020-10-04 12:45 UTC, ronie commented on addons/skin.estuary/xml/Home.xml
> +						<include content="WidgetListEpisodes" condition="Library.HasContent(musicvideos)+ !Skin.HasSetting(show_musicvideoposter)">
please add a space before the + sign

2020-10-04 12:45 UTC, ronie commented on addons/skin.estuary/xml/Home.xml
> +						<include content="WidgetListEpisodes" condition="Library.HasContent(musicvideos)+ !Skin.HasSetting(show_musicvideoposter)">
here as well

2020-10-04 12:45 UTC, ronie commented on addons/skin.estuary/xml/Home.xml
> +						<include content="WidgetListEpisodes" condition="Library.HasContent(musicvideos)+ !Skin.HasSetting(show_musicvideoposter)">
and here

2020-10-05 04:49 UTC, DaVukovic commented
>i don't think it's needed to add a new itemlayout/focuslayout to wall & infowall views?
unless i missed something, it's as simple as changing the visible conditions like this:

Very true. This was pretty stupid from my side. Did the requested changes

2020-10-05 04:49 UTC, DaVukovic commented on addons/skin.estuary/xml/Home.xml
> +						<include content="WidgetListEpisodes" condition="Library.HasContent(musicvideos)+ !Skin.HasSetting(show_musicvideoposter)">
done

2020-10-05 04:49 UTC, DaVukovic commented on addons/skin.estuary/xml/Home.xml
> +						<include content="WidgetListEpisodes" condition="Library.HasContent(musicvideos)+ !Skin.HasSetting(show_musicvideoposter)">
done

2020-10-05 04:50 UTC, DaVukovic commented on addons/skin.estuary/xml/Home.xml
> +						<include content="WidgetListEpisodes" condition="Library.HasContent(musicvideos)+ !Skin.HasSetting(show_musicvideoposter)">
done as well

2020-10-05 16:49 UTC, ronie approved these changes
looks good to me, thx!

2020-10-05 19:33 UTC, scott967 commented
> 
> 
> @scott967 tbh, I don't see the difference between a "cover" and a "poster" and AFAICT, "cover" is not available as an arttype:
> 
> https://kodi.wiki/view/Artwork_types
> 
> For Estuary and the section I changed, there are only "WdgetListPoster" and "WidgetListEpisodes" available and each are referring to either "ListItem.Art(poster)" for the poster or "ListItem.Icon" for the thumb. So either I misunderstood your request or I can't see where we might have "cover" as an available artt


The thought was a more general case that would need additional support via probably a skin setting vice toggle to store arttype and variables to display based on arttype.  The general reason is that musicvideo as a video type seems to have a range of use cases that makes it difficult to use a set visual design.  Certainly providing "poster" option helps where the use case is concerts so the intent of this PR is a good improvement on the existing UX.

No objection to this solution.

2020-10-05 21:05 UTC, DaVukovic commented
@scott967 yeah, maybe we can extend it at some point ;)

2020-10-06 10:09 UTC, merged