[POC] allow multiple windowing systems on linux
xbmc/xbmc pull request #18534
Opened 2020-10-07 01:30 UTC by lrusak

It's been a thorn in the side for a while to provide 6 linux binaries per architecture (which we don't even have CI for them all).

This will reduce the burden down to 2 linux binaries per architecture (one for each render system).

I've done this pretty quickly but to sum up the changes:
 - add a windowing system registration system (based on which windowing systems are built).
 - allow cmake to build multiple windowing platforms together (1, 2, or all 3).
 - change to use `APP_RENDER_SYSTEM` for linux builds
 - remove platform specific settings and move them into the linux.xml. The reason for this is that the platform settings are needed during windowing init. It's also not possible to remove settings once they are loaded.
 - add a command switch `--windowing=` for linux to specify the windowing to use (kodi will try all the window systems in order if not specified).
 - the app binary suffix will only be applied if one window system is being built

Areas that need improvement:
 - The cmake change to `CORE_PLATFORM_NAME_LC` now makes it a list. This is a bit ugly but I didn't want to add another cmake variable.
 - The `CEGLContextUtils` changes are a bit ugly but the old types are just typedefs anyways.
 - The `CPlatformLinux` changes look a bit ugly with all the ifdefs but I don't see any other way to keep the build flexible.

to build all windowing systems you need to use:
```
cmake -DCORE_PLATFORM_NAME="x11 wayland gbm" -DAPP_RENDER_SYSTEM="gles" ..
```

The help text will show the windowing systems that are available (built in)
```
$ ./kodi.bin --help
Usage: kodi [OPTION]... [FILE]...

Arguments:
  --windowing=<system>  Select which windowing method to use.
                                Available window systems are: wayland x11 gbm
```

2020-10-09 14:06 UTC, wsnipex commented
works great for me on x11 and gbm, didn't have a change to test wayland yet.

issues:
- kodi.bin --windowing=wayland|x11|gbm on an "incorrect windowing env" crashes or locks keyboard input
  i.e. when on X11 kodi.bin --windowing=wayland crashes
- cmake output doesn't look nice(my original cmake patch fixed this):
```-- #---- CONFIGURATION ----#
-- Platforms: X11
-- WAYLAND
-- GBM
```

2020-10-09 18:37 UTC, wsnipex commented
I thought so as well, but it is not fixed

2020-10-10 19:57 UTC, yol approved these changes
Really nice :sunglasses:

2020-10-11 22:55 UTC, garbear commented on xbmc/windowing/X11/VideoSyncOML.h
> +  CWinSystemX11GLContext* m_winSystem;
I prefer `CWinSystemX11GLContext& m_winSystem` for safety against pointer dereferences. If polymorphism is what you're after, both `*` and `&` hit the vtable. If `*` is preferred, then deference safety can be increased with:

```c++
CWinSystemX11GLContext* const m_winSystem;
```

2020-10-11 23:13 UTC, jenkins4kodi commented
@lrusak this needs a rebase

2020-10-13 20:48 UTC, lrusak commented
rebased after the latest set of merges

2020-10-14 06:01 UTC, wsnipex commented on docs/README.Linux.md
> +Or configure build with any combination of the three:
```suggestion
Or configure build with any combination of the three (default is "x11 wayland gbm"):
```

2020-10-15 00:55 UTC, lrusak commented
updated with suggested changes and fixed the GL build

2020-10-15 11:15 UTC, wsnipex approved these changes
great stuff

2020-10-15 12:29 UTC, yol requested changes

2020-10-15 12:29 UTC, yol commented on xbmc/CompileInfo.h
> +  static const std::vector<std::string> GetAvailableWindowSystems();
```suggestion
  static std::vector<std::string> GetAvailableWindowSystems();
```

Don't return `const`

2020-10-15 12:29 UTC, yol commented on xbmc/CompileInfo.cpp.in
> +const std::vector<std::string> CCompileInfo::GetAvailableWindowSystems()
```suggestion
std::vector<std::string> CCompileInfo::GetAvailableWindowSystems()
```

Don't return `const`

2020-10-15 12:29 UTC, yol commented on xbmc/windowing/WindowSystemFactory.cpp
> +    std::function<std::unique_ptr<CWinSystemBase>()> createFunction, const std::string name)
```suggestion
    std::function<std::unique_ptr<CWinSystemBase>()> createFunction, const std::string& name)
```

2020-10-15 12:29 UTC, yol commented on xbmc/windowing/WindowSystemFactory.cpp
> +std::unique_ptr<CWinSystemBase> CWindowSystemFactory::CreateWindowSystem(std::string name)
```suggestion
std::unique_ptr<CWinSystemBase> CWindowSystemFactory::CreateWindowSystem(const std::string& name)
```

2020-10-15 12:29 UTC, yol commented on xbmc/windowing/WindowSystemFactory.h
> +  static std::unique_ptr<CWinSystemBase> CreateWindowSystem(std::string name);
```suggestion
  static std::unique_ptr<CWinSystemBase> CreateWindowSystem(const std::string& name);
```

2020-10-15 12:29 UTC, yol commented on xbmc/windowing/WindowSystemFactory.h
> +                                   std::string name = "default");
```suggestion
                                   const std::string& name = "default");
```

2020-10-24 17:04 UTC, lrusak commented
Probably worth a review now from all involed @wsnipex @yol @a1rwulf @fritsch

2020-10-24 19:31 UTC, lrusak commented
jenkins build this please

2020-10-24 20:46 UTC, lrusak commented
jenkins build this please

2020-10-24 20:48 UTC, lrusak commented
jenkins build this please

2020-10-24 20:52 UTC, lrusak commented
jenkins build this please

2020-10-25 10:24 UTC, wsnipex commented
due to GBM changes before this PR I can't test it on my nvidia prime notebook anymore, cause it only tries to init /dev/drm/card1, which is nouveau instead of /dev/drm/card0
Also reported on slack some days ago

2020-10-27 15:08 UTC, lrusak commented
I'll have to adjust jenkins to get this to build properly. Any other thoughts?

2020-10-27 15:12 UTC, lrusak commented
I've kicked off some test builds if we could have some people test windows, osx, android, etc https://jenkins.kodi.tv/view/Automation/job/BuildMulti-PR-Manually/399/

2020-10-27 17:56 UTC, lrusak commented
jenkins build this please

2020-10-27 19:24 UTC, lrusak commented
merge? :smile_cat:

2020-10-27 20:16 UTC, merged

2020-10-27 20:16 UTC, lrusak commented
Thanks all involved in this one :) it took a bit of effort after all but will be nice to have for V19

2020-10-28 21:20 UTC, basilgello commented
Anyone experiences inability to shut PC down / reboot after this fix? The "Selected logind/UPower as PowerSyscall" message is no more present in kodi.log, and the "Power Settings" menu contains only "Exit" regardless of polkit overrides. My system is Debian 10.

2020-10-28 21:30 UTC, howie-f commented
i experience the same like @basilgello on debian 10. no power down / restart on the menu. not sure if it is this pr but presumably

2020-10-28 21:41 UTC, fritsch commented
Open an issue, please - with a debuglog. For now two times Debian 10 affected, that needs tracking.

2020-10-29 07:35 UTC, wsnipex commented
it's no debian only, happens on ubuntu as well. From a quick glance, it seems as if the power settings are not loaded or too late.

2023-11-02 07:55 UTC, stsichler commented
Hi Irusak,
thank you for that feature!

How do think about also allowing the "app render system" to be defined by a command line switch in the same way "windowing"  can now  be set?

I have the problem here that the standard Debian package of Kodi for arm(/64) is set to GL rendering, but it would be very nice if it used GLES instead on platforms like RasPi or Odroid.
So this may be another step in order to have a unified package for all Linux platforms, now that DRMPRIME allows hardware acceleration out-of-box without patched sources (but currently requiring GLES on these platforms to work).

So, the `APP_RENDER_SYSTEM` build variable could be set to `"gl gles"` to pull in both dependencies and selection could be done at runtime.
But I'm not sure whether it would be better to merge that into the "--windowing" switch (like `--windowing=gbm-gles`) or provide a seperate switch "--rendering".

What do you think?

2023-11-02 23:00 UTC, stsichler commented
Hm, you're right. At least [xbmc/system_gl.h](https://github.com/xbmc/xbmc/blob/9f6c9b15c3ed911a5673a531e3968683f3a3940d/xbmc/system_gl.h#L4) that currently includes either GL oder GLES mutually exclusive seems to cause a little include mess then. Not sure whether it is possible to change that to support both GL and GLES at the same time.

Another point to think about are surely the resulting blown up binary and package dependencies: 
The current `kodi.bin` binary and hence the Debian package already depends on _all_ of `libgbm1`, `libwayland*` _and_ `libx11` at the same time. By default, it also depends on `libgl1`. If we now add `libgles2`, it is further blowing up. This may not be desireable, especially on embedded platforms.
So, if we add such feature, I think it may be useful to make these package dependencies alternatives to each other, ie. the package depending on  `( libgbm1 | libwayland* | libx11)` and `(libgl1 | libgles2 )`. Of course, that would only make sense if the code would load these libraries at runtime using `dlopen()' instead of statically linking to them at build time.

2023-11-02 23:44 UTC, lrusak commented
@stsichler see this PR -> https://github.com/xbmc/xbmc/pull/20604

That PR alone doesn't allow rendering system selection but it does the ground work for it.

The rendering system selection is implemented in this branch -> https://github.com/lrusak/xbmc/commits/gl-gles-prototypes-pr-2

As you can see it's a lot of work. Ultimately I think we decided against it at last devcon because there was a lot of overhead (generated headers) with not much gain (switching render systems isn't very practical and only benefits Linux).

So as much as I would like to do it I don't think it's something we will push for it.

It was a fun technical accomplishment though.

2023-11-04 13:44 UTC, stsichler commented
What I shame! But I now do understand the decision against it. :-/

Hm, perhaps it makes more sense then to take a step back here and again offer different binaries and/or packages for GL and GLES on Linux, as was previously the case with X11, GBM and Wayland.
I think that could be a good idea, since with the introduction of DRMPRIME it seems usually no longer necessary to build a patched binary to get hardware acceleration.
But this is surely the same question as it was with kodi-x11, kodi-gbm and kodi-wayland.

2023-11-04 14:05 UTC, basilgello commented
@stsichler I'd not call it a shame. In Debian, for example, I can pick whatever patchset I want (and rebase it, but it is another story!) If there is really strong demand from Arm users, every decision can be revisited.

2023-11-04 17:00 UTC, lrusak commented
What feature do you think is missing from GLES compared to GL and vice versa?

2023-11-04 17:05 UTC, basilgello commented
@lrusak GL does not work with HW acceleration on NanoPi-R5C and the platform I could not identify from this PR: https://salsa.debian.org/multimedia-team/kodi-media-center/kodi/-/merge_requests/10

2023-11-04 17:09 UTC, lrusak commented
> @lrusak GL does not work with HW acceleration on NanoPi-R5C and the platform I could not identify from this PR: https://salsa.debian.org/multimedia-team/kodi-media-center/kodi/-/merge_requests/10

AFAIK drm prime can be added to the GL builds. The direct-to-plane method is only available on GBM. Wayland and x11 would have to use the EGL method.

2023-11-05 22:31 UTC, stsichler commented
> @lrusak GL does not work with HW acceleration on NanoPi-R5C 
It's the same problem for me on my RPi4B and currently the only reason for me to rebuild Kodi from Sources instead of using the default armhf Debian package.

2023-11-23 12:35 UTC, amazingfate commented
> > @lrusak GL does not work with HW acceleration on NanoPi-R5C and the platform I could not identify from this PR: https://salsa.debian.org/multimedia-team/kodi-media-center/kodi/-/merge_requests/10
> 
> AFAIK drm prime can be added to the GL builds. The direct-to-plane method is only available on GBM. Wayland and x11 would have to use the EGL method.

If kodi is built wih GL, in gbm session there is  also no drm prime setting. If direct-to-plane mode does't depend on EGL it should be possible to enable it even in a GL build.
Arm platforms are all having better GLES support than GL. Although some opensource drivers like panfrost and freedreno do support OpenGL, but they can't enable drm prime. I don't know much about x86 platform drm prime, do x86 platforms use GL for drm prime?