tools/depends: allow building GLES lib for x11 and wayland
xbmc/xbmc pull request #18543
Opened 2020-10-08 21:06 UTC by lrusak

This is a precursor to the multi-windowing stuff #18534 

This allows building the GLES library when using x11 or wayland

wayland version bump is needed because it now provides `wayland-egl-backend` needed by mesa

This also changes so that the libva library is built for all platforms.

2020-10-09 23:23 UTC, lrusak commented
jenkins build this please

2020-10-10 19:19 UTC, wsnipex commented
It doesn't make sense to build 3 different versions of nesa and libva that will even overwrite eaxh other. Why not build it once with support fir all platforms?

2020-10-11 15:31 UTC, lrusak commented
> It doesn't make sense to build 3 different versions of mesa and libva that will even overwrite each other. Why not build it once with support for all platforms?

That is the direction I will be moving when we support multi windowing. One step at a time :smiley:

2020-10-12 10:45 UTC, wsnipex commented
this does not depend on multi-windowing. Please explain why you can't build it once with all options enabled.

2020-10-12 11:42 UTC, lrusak commented
> this does not depend on multi-windowing. Please explain why you can't build it once with all options enabled.

I didn't say it depends on multi-windowing. We can support building all the platforms together when multi-windowing comes. This is just a precursor to get GLES building for each platform 😊

2020-10-12 11:46 UTC, wsnipex commented
I'm talking about dependencies, not kodi. It's wrong to build mesa and libva with different options, depending on the chosen windowing system.
Just always build those with support for all windowing platforms.

2020-10-12 12:05 UTC, a1rwulf commented
> I'm talking about dependencies, not kodi. It's wrong to build mesa and libva with different options, depending on the chosen windowing system.
> Just always build those with support for all windowing platforms.

I don't really agree.
Why would you want to build mesa with X11 dependencies when you want to build for GBM?

2020-10-12 12:22 UTC, wsnipex commented
the reason is simple: depends install to 1 target dir. 
If you first build kodi with x11, you'd end up with mesa and libva only supporting X11.
Now you want kodi wayland, but you'll have to rebuild depends instead of just kodi.
GBM? Rebuild depends once more . . .

Just look at how distros do it: They enable all options and the user/downstream lib uses what it needs.

2020-10-12 12:24 UTC, wsnipex requested changes
depends must not be built for specific windowing systems only

2020-10-12 12:35 UTC, a1rwulf commented
Still, if you are on a system with wayland only, you cannot even compile the depends then, because you need to install X11 to do that - which you most likely don't want.
Anyway, just my 2c - I'm not using the depends build - so I'll let you argue about it with lrusak.

2020-10-12 16:04 UTC, lrusak commented
> depends must not be built for specific windowing systems only

But we already do this, I haven't changed the behaviour here.

2020-10-13 17:39 UTC, lrusak commented
So what's the path forward here? Do we not allow the flexibility of building for each platform individually? I plan on implementing the ability to build depends for all window systems together with the multi-windowing PR.

2020-10-14 17:02 UTC, wsnipex commented
if you want to avoid adding X11 to depends you could also just get rid of the windowing specific disables for mesa and libva.
Just let them autodetect what's available.
And add a note to docs that you need X11 headers **on your build machine** if you want X11 support.

2020-10-16 04:06 UTC, garbear commented on tools/depends/native/pugixml/Makefile
> +CMAKE_OPTIONS := -DCMAKE_TOOLCHAIN_FILE= -DCMAKE_C_COMPILER="$(CC_BINARY_FOR_BUILD)" -DCMAKE_CXX_COMPILER="$(CXX_BINARY_FOR_BUILD)" -DCMAKE_C_FLAGS="$(NATIVE_CFLAGS)" -DCMAKE_CXX_FLAGS="$(NATIVE_CXXF
```suggestion
CMAKE_OPTIONS := -DCMAKE_TOOLCHAIN_FILE= \
  -DCMAKE_C_COMPILER="$(CC_BINARY_FOR_BUILD)" \
  -DCMAKE_CXX_COMPILER="$(CXX_BINARY_FOR_BUILD)" \
  -DCMAKE_C_FLAGS="$(NATIVE_CFLAGS)" \
  -DCMAKE_CXX_FLAGS="$(NATIVE_CXXFLAGS)" \
  -DCMAKE_EXE_LINKER_FLAGS="$(NATIVE_LDFLAGS)" \
  -DCMAKE_INSTALL_LIBDIR=lib $(CMAKE_OPTIONS)
```

2020-10-16 06:06 UTC, wsnipex commented on tools/depends/native/Makefile
> +waylandpp-scanner: cmake pugixml
```suggestion
waylandpp-scanner: cmake expat pugixml
```

2020-10-16 06:17 UTC, wsnipex commented
looks like wayland-scanner can't find expat, which installs it's pc file to x86_64-linux-gnu-native/lib/pkgconfig
Either we have to fix it's install libdir or set PKG_CONFIG_PATH for wayland-scanner

2020-10-17 02:32 UTC, garbear commented on tools/depends/native/pugixml/Makefile
> +APP=$(PLATFORM)/build/libpugixml.a
To match the other makefiles this should be `LIBNAME` I think, or something with `LIB` instead of `APP`

2020-10-18 00:59 UTC, lrusak commented
This finally builds again, however, I've had to disable x11 in mesa for arm builds (I'll have to cross compile the x11 libs or something, meh).

I've also included a few other various commits that fix some depends issues. If desired I can split them out into another PR.

2020-10-18 09:17 UTC, wsnipex approved these changes

2020-10-18 22:20 UTC, merged