Android: Drop everything below Version 24
xbmc/xbmc pull request #18592
Opened 2020-10-18 13:43 UTC by fritsch

Android Version 24 was released August 2016 (Android 7)
Android Version 23 was released November 2015 (Android 6)

With this PR, we drop backwards compatibility for version 23 (Android 6 in the code) and require at least Android 7.

No hard feelings here, if someone steps up and wants to keep it, totally fine with me.

As you see in the code: Most problems we have in Audio-Part, as the old version did not have the blocking attribute

2020-10-19 08:27 UTC, Rechi requested changes
There are API version changes missing at `tools/android/packaging/xbmc/AndroidManifest.xml.in`, `tools/android/packaging/xbmc/build.gradle.in`, `tools/buildsteps/defaultenv` and `tools/depends/configure.ac`.

2020-10-19 17:27 UTC, fritsch commented
Thanks much @Rechi - I am bit unsure with the NDK version in the file you pointed out, fixed the simultaneously. Btw. this PR is not meant to be merged right now. I just want to "show" where in the code we still have workarounds and versioning to decided if we want to drop it or not.

2020-10-19 19:14 UTC, fuzzard commented on tools/depends/configure.ac
>    [specify ndk level (optional for android), default is 21.])],
I guess for completeness this needs to be changed to 24 as well

2020-10-19 19:17 UTC, Rechi commented on tools/depends/configure.ac
>    [specify ndk level (optional for android), default is 21.])],
```suggestion
  [specify ndk level (optional for android), default is 24.])],
```

2020-10-19 19:17 UTC, Rechi commented on xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp
> +    default:; // do nothing
```suggestion
      case AVCOL_PRI_BT709:
        mediaformat.setInteger(XMEDIAFORMAT_KEY_COLOR_STANDARD, 1);
        break;
      case AVCOL_PRI_BT2020:
        mediaformat.setInteger(XMEDIAFORMAT_KEY_COLOR_STANDARD, 6);
        break;
      default:; // do nothing
```

2020-10-19 19:17 UTC, Rechi commented on xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp
> +    default:; // do nothing
```suggestion
      case AVCOL_TRC_LINEAR:
        mediaformat.setInteger(XMEDIAFORMAT_KEY_COLOR_TRANSFER, 1); // COLOR_TRANSFER_LINEAR
        break;
      case AVCOL_TRC_SMPTE170M:
        mediaformat.setInteger(XMEDIAFORMAT_KEY_COLOR_TRANSFER, 3); // COLOR_TRANSFER_SDR_VIDEO
        break;
      case AVCOL_TRC_SMPTE2084:
        mediaformat.setInteger(XMEDIAFORMAT_KEY_COLOR_TRANSFER, 6); // COLOR_TRANSFER_ST2084
        break;
      case AVCOL_TRC_ARIB_STD_B67:
        mediaformat.setInteger(XMEDIAFORMAT_KEY_COLOR_TRANSFER, 7); // COLOR_TRANSFER_HLG
        break;
      default:; // do nothing
```

2020-10-19 19:17 UTC, Rechi commented on xbmc/cores/AudioEngine/Sinks/AESinkAUDIOTRACK.cpp
> +    written = m_at_jni->write(m_shortbuf, 0, (sizeInBytes - offsetInBytes) / sizeof(int16_t), CJNIAudioTrack::WRITE_BLOCKING);
```suggestion
    written = m_at_jni->write(m_shortbuf, 0, (sizeInBytes - offsetInBytes) / sizeof(int16_t),
                              CJNIAudioTrack::WRITE_BLOCKING);
```

2020-10-19 19:17 UTC, Rechi commented on xbmc/cores/AudioEngine/Sinks/AESinkAUDIOTRACK.cpp
> +    written = m_at_jni->write(m_charbuf, 0, sizeInBytes - offsetInBytes, CJNIAudioTrack::WRITE_BLOCKING);
```suggestion
    written =
        m_at_jni->write(m_charbuf, 0, sizeInBytes - offsetInBytes, CJNIAudioTrack::WRITE_BLOCKING);
```

2020-10-19 20:17 UTC, Tolriq commented
Jumping in to remind you all that targetSdkVersion 28 must be updated to targetSdkVersion 29 before November 2nd to be able to push any APK to Play Store after that date. This change have quite a few impacts that need to be addressed before doing so. (at least requestLegacyExternalStorage)

For the record 21 to 24 is removing about 20% of active Android users.

2020-10-19 21:17 UTC, fritsch commented
Thanks again @Rechi  and @fuzzard  - I currently have issues with my nice vim indirectly, after I resetted my gome-settings completely, it seems the fonts are too small for me old man.

@Tolriq thanks very much. These numbers are based on your famous app, right? That's exactly the feedback I was looking for. Yeah it's not on me to decide what we do here. From the "smallish diff" as seen in here, it's not much of a burdon to just keep it. This might change obviously, when we add new features that need big amount of casing.

I will try to add the 29 bump separately.

2020-10-20 05:55 UTC, Tolriq commented
@fritsch Those are the official Google numbers.

For target 29, requires tons of test on Android 10 as many impacts.

2020-10-20 07:39 UTC, Rechi commented
Devices with Android 5, 5.1 and 6 are currently 10% of all devices having Kodi installed according to Google Play Console.

2020-10-26 21:50 UTC, lherschi commented
Kodi is very popular on Fire TV. With the change, Kodi will no longer run first and second generation Fire TVs. They don't even appear in the Google Play statistics.

2020-10-27 04:48 UTC, fritsch commented
Noted. Remember: While amazon does not care to update their firmware, kodi's Leia will continue to run there until world's end ...

2020-10-30 21:36 UTC, jenkins4kodi commented
@fritsch this needs a rebase

2020-11-17 10:44 UTC, jenkins4kodi commented
@fritsch this needs a rebase

2022-03-05 12:56 UTC, Pentaphon commented
> Kodi is very popular on Fire TV. With the change, Kodi will no longer run first and second generation Fire TVs.

I don't think anybody has those anymore as of this post. They are stuck on 5.1. It's on a matter of time before they become absolutely useless and end up being traded for Amazon credit. Everybody with a FireTV that I know has a FireOS 6 (7.1 box) and those will work fine for another 5 years minimum.

2022-03-07 08:22 UTC, lherschi commented
I still have my Firetv-Stick 2 and my friends and acquaintances still use these devices. And the devices are far from useless, but still work very well. Recently, even the new interface was distributed to these devices. So it doesn't look at all like Amazon is going to drop these devices.

2023-01-16 18:35 UTC, closed without merging