[subtitles][ass] fix/extend detection of font attachments (mimetype)
xbmc/xbmc pull request #18869
Opened 2020-11-26 20:59 UTC by enen92

## Description
For some mkvs that include ASS subtitles and font attachments, kodi was skipping the extraction of the fonts because the demuxer doesn't flag them as `AV_CODEC_ID_TTF` or `AV_CODEC_ID_OTF`. This leads libass to load the incorrect font and, consequently, to the likelihood of overflowing the defined overlay margins in some cases.
Other players that also use libass (f.e. mpv) also look into the attachment mimetype to decide if it is a font and should be loaded into memory.

You can find similar implementations in:
https://gitlab.websupport.sk/peter.kovar/ffmpeg-mvc/commit/7e6b3ad6930c2f1daa5c4831bbeda3fb931921e6
https://github.com/mpv-player/mpv/blob/91ce87bd89940b8b83d1bd044288008182cf3a2e/sub/sd_ass.c#L98-L109

While looking into this also noticed that in https://github.com/xbmc/xbmc/pull/18794 a mistake was made and `strPath` was in the wrong place. So basically `ass_set_fonts_dir` was receiving the default font file instead of the font folder. Fixing this broke the setting again :) So this PR also includes a fix for the setting.

## Motivation and Context
Fixes an issue reported in irc by _xD, sample file: https://anonfiles.com/Z5j9b9tdp8/clip_bug_tar 

## How Has This Been Tested?
Using the sample files and also all the ass samples in the ftp server

## Screenshots (if appropriate):

**master:**
![mastert](https://i.imgur.com/5frwN89.png "master")

**pr:**
![pr](https://i.imgur.com/E8EvRra.png "pr")

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

2020-11-26 21:57 UTC, phunkyfish requested changes
Just one minor and some cosmetics.

2020-11-26 21:57 UTC, phunkyfish commented on xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp
> +    //  so translate the path before calling into libass
Two spaces after comment, should be one.

2020-11-26 21:57 UTC, phunkyfish commented on xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp
> +  strPath = URIUtils::AddFileToFolder(strPath, forcedFont);
Same again the line above this (although it's not in scope as it's not changed in this PR

2020-11-26 21:57 UTC, phunkyfish commented on xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp
> +    std::string mimeType(dict->value);
`const std::string mimeType = dict->value;`

Can be const (I think) and I try to avoid the direct construction. It's less confusing using `=`.

2020-11-26 22:34 UTC, enen92 commented
Jenkins build this please

2020-11-27 00:27 UTC, fuzzard commented
jenkins build this please

2020-11-27 00:29 UTC, fuzzard commented
Jenkins build this please

2020-11-27 08:23 UTC, phunkyfish approved these changes
LGTM

2020-11-27 10:22 UTC, DaveTBlake commented
Going to excuse my self from review, I really don't have any knowledge of subtitle functionality at all not even as a user. All I can do is appreciate that you are working on it @enen92 and fixing bugs :)

2020-11-27 10:36 UTC, enen92 commented
jenkins build this please

2020-11-27 11:47 UTC, phunkyfish approved these changes
LGTM

2020-11-27 11:49 UTC, merged

2022-03-11 07:45 UTC, ymj0424 commented
@enen92 
There's a bug in Chinese font. I attached a chinese font to a mkv file, which was also used in the ASS subtitle. But the kodi just didn't show the subtitle any more.
Here's the [font file](https://drive.google.com/file/d/1lCZGoaY66qKLHnazQRUx26HNLYhhNXuw/view?usp=sharing). I also tried other Chinese fonts, but still have the same issue.

2022-03-11 11:55 UTC, enen92 commented
@ymj0424 this PR only makes the demuxer extract the font attachment to the font temporary folder. If the font is not processed is an unrelated problem.
I'd recommend you to try kodi nexus instead (not clear if you're using v19 but I guess so)