input/locale: split hardware and virtual keyboard setting in strings.po
xbmc/xbmc pull request #18976
Opened 2020-12-23 07:10 UTC by Portisch

## Description

Split hardware and virtual keyboard setting in strings.po.
Using the same string for both "Keyboard layouts" for both is just confusing.

## Motivation and Context

Clean keyboard layout settings

## How Has This Been Tested?

On CoreELEC 19 Matrix with Kodi Matrix 19.0 beta2

## Screenshots (if appropriate):

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [x] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2021-08-11 11:05 UTC, CvH commented
any news about this ?
8 months and nobody even looked at it !?

2021-08-11 12:14 UTC, Portisch commented
almost same here:
https://github.com/xbmc/xbmc/pull/18975

23.12.2020, tested and used since 04.2019.
Maybe with Kodi 30.

no wonder that the PRs become less every year...

2021-08-11 13:45 UTC, howie-f commented on addons/resource.language.en_gb/resources/strings.po
> +msgid "Hardware keyboard layout"
plural here? `Hardware keyboard layouts`

2021-08-11 13:45 UTC, howie-f commented on addons/resource.language.en_gb/resources/strings.po
> +#. Description for setting #407: "Keyboard layouts"
please also adjust the description: Hardware keyboard layouts

2021-08-11 18:04 UTC, enen92 approved these changes

2021-08-11 18:53 UTC, howie-f requested changes
sorry @Portisch, don't want to bother you. an oversight.
i think we need to change the label from old `310` to new `407` in
```
system/settings/freebsd.xml
system/settings/settings.xml (not sure here)
```

2021-08-16 07:12 UTC, Portisch commented
> system/settings/freebsd.xml

This is a link to `linux.xml` and there it's already changed as it's the #407 for virtual keyboard.
And #310 for `settings.xml` should be correct as it's for the hardware keyboard description.

2021-08-16 07:48 UTC, howie-f approved these changes
thanks for your contribution

2021-08-16 07:48 UTC, merged