[linux] fix drm object build with gcc-4.9
xbmc/xbmc pull request #19020
Opened 2021-01-04 22:09 UTC by bkuhls

## Description
Fixes build error introduced by PR 18858

```
kodi/xbmc/windowing/gbm/drm/DRMObject.cpp: In member function 'std::tuple<bool, long unsigned int> KODI::WINDOWING::GBM::CDRMObject::GetPropertyValue(const string&, const string&) const':
kodi/xbmc/windowing/gbm/drm/DRMObject.cpp:103:39: error: converting to 'std::tuple<bool, long unsigned int>' from initializer list would use explicit constructor 'constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = bool; _U2 = long long unsigned int&; <template-parameter-2-3> = void; _T1 = bool; _T2 = long unsigned int]'
     return {true, prop->enums[j].value};
```
Fix was suggested by garbear: https://github.com/xbmc/xbmc/pull/19015#issuecomment-753724865

## How Has This Been Tested?
build-tested using gcc version 4.9.1 (Sourcery CodeBench Lite 2014.11-95) 

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

2021-01-04 22:24 UTC, lrusak requested changes
please use `std::make_tuple`

2021-01-04 22:24 UTC, lrusak commented on xbmc/windowing/gbm/drm/DRMObject.cpp
> +    return std::tuple<bool, uint64_t>{true, prop->enums[j].value};
#
```suggestion
    return std::make_tuple(true, prop->enums[j].value);
```

2021-01-05 06:48 UTC, bkuhls commented on xbmc/windowing/gbm/drm/DRMObject.cpp
> +    return std::tuple<bool, uint64_t>{true, prop->enums[j].value};
done

2021-01-05 06:49 UTC, bkuhls commented
@lrusak Please kick-off a new Jenkins cycle, I broke it by force-pushing too fast, sorry.

2021-01-05 17:32 UTC, lrusak commented
jenkins build this please

2021-01-05 22:55 UTC, garbear approved these changes

2021-02-13 18:34 UTC, bkuhls commented
@DaveTBlake Another candidate for v19?

2021-03-02 07:10 UTC, bkuhls commented
rebased for master

2021-03-02 08:52 UTC, DaveTBlake commented
Sorry @bkuhls this was over looked for the v19.0 release, lacking labels and lurking from Jan.

@lrusak happy with this now? As a fix any reason not to backport to Matrix for 19.1?

2021-03-02 15:59 UTC, lrusak approved these changes

2021-03-02 15:59 UTC, lrusak commented
> Sorry @bkuhls this was over looked for the v19.0 release, lacking labels and lurking from Jan.
> 
> @lrusak happy with this now? As a fix any reason not to backport to Matrix for 19.1?

LGTM

2021-03-08 10:11 UTC, merged