[SmartRedraw] Fix for dialog kai toast notifications not being marked…
xbmc/xbmc pull request #19156
Opened 2021-02-01 22:02 UTC by smf007

… as Dirty, Issue #15354

## Description
In issue #15354 (issue #18391 appears to be the same) it is seen that toast notifications break when using SmartReDraw.  The source of this appears to be that the dialog windows are not marked as dirty.

## Motivation and Context
Issue #15354 
Issue #18391 
[Kodi Forum thread report](https://forum.kodi.tv/showthread.php?tid=359240&pid=3011002#pid3011002)

I'm not sure if toast notifications are the only dialog windows that should be marked dirty, so I've marked all dialog windows as dirty.

## How Has This Been Tested?
Tested on Ubuntu 20.04 x86-64.  Enabled and disabled smartredraw.

## Screenshots (if appropriate):

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2021-02-10 02:53 UTC, smf007 commented
Is there anyone with experience in this area that could review this?  SmartRedraw was @peak3d IIRC.  @ksooo has touched the kai toast, but might not have the background with regard to SmartRedraw.

2021-02-10 04:57 UTC, fuzzard commented
Not really. As it touches all windows, not sure anyone wants to merge into v19 in case theres some large fallout.

Probably more likely to merge after 19 release and N branched, see if theres any issues in nightlies, and then backport to a point release.

2021-02-10 07:35 UTC, ksooo commented
> As it touches all windows, not sure anyone wants to merge into v19 in case theres some large fallout.

 Too risky for v19. Unfortunately, we do not really oversee possible negative side effects.

2021-02-10 13:48 UTC, smf007 commented
> > As it touches all windows, not sure anyone wants to merge into v19 in case theres some large fallout.
> 
> Too risky for v19. Unfortunately, we do not really oversee possible negative side effects.

I do realize that, and agree with it.

I guess I should have clarified that I'm more looking for someone with knowledge of the areas to give guidance on this.  As the objective is to minimize the amount of screen flagged as dirty, this is probably too greedy and flags too much as dirty.

2021-02-10 15:03 UTC, ksooo commented
> this is probably too greedy and flags too much as dirty.

 yep, that's also my feeling - but it's only feeling. :-/

2021-03-31 20:30 UTC, ghen2 commented
Can this be reconsidered now v19 is out?

2021-09-09 16:13 UTC, smf007 commented
@fuzzard @ksooo  any chance of someone taking a look at this proposed fix?  Thanks

2021-09-21 21:23 UTC, enen92 commented
I think this might defeat the whole purpose of smartredraw. We likely want to go over every single issue and try a self-contained/conservative fix instead of applying the sledgehammer method :)

2021-09-25 10:44 UTC, enen92 requested changes
I played a bit with this and there is nothing wrong with the dialognotification. The logic is correct, the dialog doesn't close because the fadelabelcontrol doesn't scroll. So, any fix to solve the issue should be restricted to that control

2021-09-27 13:54 UTC, enen92 commented
@smf007 are you able to check if the following patch solves your use-case?

```
From bf11f37cb5152be6c7c7ea5946a66c3f2ad3cd0d Mon Sep 17 00:00:00 2001
From: enen92 <92enen@gmail.com>
Date: Mon, 27 Sep 2021 14:52:38 +0100
Subject: [PATCH] Fadelabel test

---
 xbmc/guilib/GUIFadeLabelControl.cpp | 1 +
 1 file changed, 1 insertion(+)

diff --git a/xbmc/guilib/GUIFadeLabelControl.cpp b/xbmc/guilib/GUIFadeLabelControl.cpp
index 237ac37771..f92cd33b91 100644
--- a/xbmc/guilib/GUIFadeLabelControl.cpp
+++ b/xbmc/guilib/GUIFadeLabelControl.cpp
@@ -151,6 +151,7 @@ void CGUIFadeLabelControl::Process(unsigned int currentTime, CDirtyRegionList &d
     if (m_scroll)
     {
       m_textLayout.UpdateScrollinfo(m_scrollInfo);
+      MarkDirtyRegion();
     }
 
     CServiceBroker::GetWinSystem()->GetGfxContext().RemoveTransform();
-- 
2.33.0
```

It fixes python error notifications for me, so I guess it might apply as well for other situations

2021-09-27 14:54 UTC, smf007 commented
@enen92  was just re-setting up my build environment and looking over that.  A quick test, and it does appear to fix my issue.  It makes sense too.  I have another specific plugin I would like to double check though.

2021-09-27 15:35 UTC, closed without merging