Hide the toggle audio stream when there's only one
xbmc/xbmc pull request #19198
Opened 2021-02-08 22:19 UTC by joseluismarti

## Description
Hide **Toggle audio stream** in Settings dialog when there's only one audio stream in the video that is playing.

Create a new boolean InfoLabel (_VideoPlayer.HasManyAudios_) to control the skin visibility of the toggle.

## How Has This Been Tested?
Works fine, the toggle is visible if the playing video has more than one audio stream.

Build and test on Linux x64.

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2021-02-08 22:23 UTC, ksooo commented
For flexibility reasons, I'd prefer a new GUI info int, returning the number of audio streams.

2021-02-08 22:31 UTC, garbear commented
I'd also prefer an audio stream count function that basically exposes `g_application.GetAppPlayer().GetAudioStreamCount()` to the GUI

2021-02-08 22:32 UTC, ksooo commented
> I'd also prefer an audio stream count function that basically exposes g_application.GetAppPlayer().GetAudioStreamCount() to the GUI

 Yep, that's exactly what I proposed. 👍

2021-02-08 22:39 UTC, joseluismarti commented
Ok, I'll change it

2021-02-09 09:58 UTC, ksooo requested changes
Needs a bit more love. :-)

2021-02-09 09:58 UTC, ksooo commented on xbmc/guilib/guiinfo/VideoGUIInfo.cpp
> +      return true;
Implementation must return an int, thus belongs into `CVideoGUIInfo::GetInt`. Your Estuary changes are correct. `Integer.IsGreater(...) is what we want.

2021-02-09 09:58 UTC, ksooo commented on xbmc/GUIInfoManager.cpp
> +///                  _string_,
`_integer_`

2021-02-09 09:58 UTC, ksooo commented on xbmc/GUIInfoManager.cpp
> +                                  { "audiostreamcount", VIDEOPLAYER_AUDIOSTREAMCOUNT }
Please add a comma at the end of the new line. This avoids a two-line diff when next item is added.

2021-02-09 11:58 UTC, ronie approved these changes

2021-02-09 12:20 UTC, ksooo requested changes
Add the default label, squash down everything to a single commit and we are ready to go.

2021-02-09 12:20 UTC, ksooo commented on xbmc/guilib/guiinfo/VideoGUIInfo.cpp
> +  }
Please add 

```c++
default:
  break;
```

to avoid compiler warnings.

2021-02-09 13:00 UTC, enen92 commented on xbmc/GUIInfoManager.cpp
> +///     @note If the video contains no audio stream return 0.
```suggestion
///     @note If the video contains no audio streams it returns 0.
```

2021-02-09 15:48 UTC, ksooo commented
@joseluismarti  Please squash down the 9 commits to one and we are done with this PR.

2021-02-09 18:03 UTC, enen92 approved these changes

2021-02-09 18:48 UTC, ksooo approved these changes
Thank you very much for your contribution.

2021-02-09 19:11 UTC, garbear approved these changes
Excellent new feature, and well implemented. Thank you!

2021-02-27 01:51 UTC, merged