Add default select action for Episodes
xbmc/xbmc pull request #19236
Opened 2021-02-15 12:21 UTC by tielis

## Description
Add option to chose the "default select action for episodes"

## Motivation and Context
It makes sense having the info window coming up  for movies before playing. But I believe not many users want that for episodes.

https://forum.kodi.tv/showthread.php?tid=343371

## How Has This Been Tested?
Windows 10 x64

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2021-02-15 12:37 UTC, arnova commented
IMO this is too "niche"....

2021-02-15 14:50 UTC, ksooo requested changes

2021-02-15 14:50 UTC, ksooo commented on addons/resource.language.en_gb/resources/strings.po
> +#: system/settings/settings.xml
Please add a verbal description of the use case for the new string, to give the translators the chance to understand and find the best translation.

Syntax: `#. descriptive text`

2021-02-15 14:50 UTC, ksooo commented on addons/resource.language.en_gb/resources/strings.po
> +#: system/settings/settings.xml
Please add a verbal description of the use case for the new string, to give the translators the chance to understand and find the best translation.

Syntax: `#. descriptive text`

2021-02-15 14:50 UTC, ksooo commented on addons/resource.language.en_gb/resources/strings.po
> +msgid "Default select action - Movies & others"
Not sure the `&` is correct English. I'd go with a classical `and`.

2021-02-15 14:50 UTC, ksooo commented on xbmc/listproviders/DirectoryProvider.cpp
> +            && OnInfo(item))
Coding guidelines! This line is way to long. Use clang-format to get the formatting right.

2021-02-15 14:50 UTC, ksooo commented on xbmc/listproviders/DirectoryProvider.cpp
> +            && OnInfo(item))
Coding guidelines! This line is way to long. Use clang-format to get the formatting right.

2021-02-15 14:50 UTC, ksooo commented on xbmc/video/windows/GUIWindowVideoBase.cpp
> +      return OnFileAction(iItem, CServiceBroker::GetSettingsComponent()->GetSettings()->GetInt(CSettings::SETTING_MYVIDEOS_SELECTACTION), "");             // Movies and others
Coding guidelines! This line is way to long and indentation is wrong. Use clang-format to get the formatting right.

2021-02-15 14:50 UTC, ksooo commented on xbmc/video/windows/GUIWindowVideoBase.cpp
> +            selectAction = (VideoSelectAction)CServiceBroker::GetSettingsComponent()->GetSettings()->GetInt(CSettings::SETTING_MYVIDEOS_SELECTEPISODEACTION);
Coding guidelines! This line is way to long. Use clang-format to get the formatting right.
And please replace the c-style cast with a c++ static cast.

2021-02-15 14:50 UTC, ksooo commented on xbmc/video/windows/GUIWindowVideoBase.cpp
> +            selectAction = (VideoSelectAction)CServiceBroker::GetSettingsComponent()->GetSettings()->GetInt(CSettings::SETTING_MYVIDEOS_SELECTACTION);
Coding guidelines! This line is way to long. Use clang-format to get the formatting right.
And please replace the c-style cast with a c++ static cast.

2021-02-15 14:50 UTC, ksooo commented on xbmc/video/windows/GUIWindowVideoBase.cpp
> +      return OnFileAction(iItem, CServiceBroker::GetSettingsComponent()->GetSettings()->GetInt(CSettings::SETTING_MYVIDEOS_SELECTACTION), "");             // Movies and others
How about streamlining this code a bit:

```c++
int iSelectAction = item->GetVideoInfoTag()->m_type == MediaTypeEpisode ? CSettings::SETTING_MYVIDEOS_SELECTEPISODEACTION : CSettings::SETTING_MYVIDEOS_SELECTACTION;
return OnFileAction(iItem, CServiceBroker::GetSettingsComponent()->GetSettings()->GetInt(iSelectAction), "");
```

2021-02-15 14:50 UTC, ksooo commented on xbmc/video/windows/GUIWindowVideoBase.cpp
> +            selectAction = (VideoSelectAction)CServiceBroker::GetSettingsComponent()->GetSettings()->GetInt(CSettings::SETTING_MYVIDEOS_SELECTACTION);
How about streamlining this code a bit?

```c++
int iSelectAction = item->GetVideoInfoTag()->m_type == MediaTypeEpisode ? CSettings::SETTING_MYVIDEOS_SELECTEPISODEACTION : CSettings::SETTING_MYVIDEOS_SELECTACTION;
selectAction = CServiceBroker::GetSettingsComponent()->GetSettings()->GetInt(iSelectAction);
```

2021-02-15 14:50 UTC, ksooo commented on xbmc/listproviders/DirectoryProvider.cpp
> +            && OnInfo(item))
How about streamlining this code?

```c++
int iSelectAction = fileItem.GetVideoContentType() == VIDEODB_CONTENT_EPISODES ? Settings::SETTING_MYVIDEOS_SELECTEPISODEACTION : CSettings::SETTING_MYVIDEOS_SELECTACTION;
if (CServiceBroker::GetSettingsComponent()->GetSettings()->GetInt(iSelectAction) == SELECT_ACTION_INFO
    && OnInfo(item)
  return true;
```

2021-09-24 18:07 UTC, jenkins4kodi commented
@tielis this needs a rebase

2022-12-29 13:55 UTC, ksooo commented
No reaction from submitter for more than half and a year. closing.

2022-12-29 13:55 UTC, closed without merging