[Estuary] center the PVR Radio banner tiles
xbmc/xbmc pull request #19282
Opened 2021-02-25 14:49 UTC by joseluismarti

## Description
As described in the issue #19281, in the PVR Radio section, the banner tiles at the top are not centered.

## How Has This Been Tested?
Titles are now displayed centered. Tested adding a new recording and/or a new timer.

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [X] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2021-02-25 16:59 UTC, ksooo requested changes
This, to make it 100% the same as the TV widgets.

```diff
diff --git a/addons/skin.estuary/xml/Home.xml b/addons/skin.estuary/xml/Home.xml
index 7ec09db8ef..c022e58264 100644
--- a/addons/skin.estuary/xml/Home.xml
+++ b/addons/skin.estuary/xml/Home.xml
@@ -455,12 +455,12 @@
                                                <pagecontrol>13010</pagecontrol>
                                                <control type="grouplist" id="13855">
                                                        <height>390</height>
-                                                       <left>25</left>
+                                                       <left>0</left>
+                                                       <right>0</right>
                                                        <top>36</top>
                                                        <orientation>horizontal</orientation>
-                                                       <align>right</align>
-                                                       <width>1360</width>
                                                        <visible>PVR.IsRecordingRadio | PVR.HasNonRecordingRadioTimer</visible>
+                                                       <align>center</align>
                                                        <control type="group">
                                                                <width>680</width>
                                                                <visible>PVR.IsRecordingRadio</visible>
```

2021-02-25 18:29 UTC, ksooo reviewed
Please squash down to a single commit and we're done.

2021-02-25 20:23 UTC, howie-f approved these changes
works as expected at runtime, thanks

2021-02-25 20:26 UTC, ksooo approved these changes
lgtm

2021-02-26 04:29 UTC, djp952 commented
Thank you @joseluismarti!

2021-02-26 15:13 UTC, howie-f commented
would you like to backport this to the Matrix branch to make the recording screen there pretty again? :satisfied:

2021-02-26 15:14 UTC, merged

2021-02-26 17:33 UTC, joseluismarti commented
Add backport to Matrix #19295, is it ok?