Resolution: Try double refreshrate and pulldown also when no whitelist set
xbmc/xbmc pull request #19353
Opened 2021-03-07 18:20 UTC by fritsch

This restores the alltime behaviour, that if you don't do anything that kodi then will search:
- Higher resolutions with exact match (width, height)
- Refreshrates that are either 3:2, direct or double matches

2021-03-07 19:02 UTC, lrusak commented
I think those settings are tied to the whitelist being enabled.

2021-03-07 19:05 UTC, fritsch commented
Exactly and that's why their code is not run if there is only the default whitelist.

2021-03-07 19:48 UTC, Portisch commented
Thank you that you took a second look to this issue. We temporary merged the commit so the affected users will be able to test it on their media/setup.

https://github.com/CoreELEC/CoreELEC/commit/b0235e759d6aae67fb4a2306642a49b15c89c8cb

2021-03-07 21:13 UTC, lrusak approved these changes
LGTM

2021-03-09 07:48 UTC, bossanova808 requested changes
This also needs the `noWhiteList ||` as above

2021-03-09 10:44 UTC, fritsch commented
I had assumed the desktop resolution is already contained in the whitelist I enumerate from scratch if none is existent. Is it not the case?

2021-03-09 10:52 UTC, fritsch commented
I take it back. You are right ... poor 1280 x 720 :-).

This code is far too complicated there and touching it every time is a headache. This is exactly what happens if one tries to fix it for all and everyone :-)

2021-03-09 18:46 UTC, fritsch commented
Update. I hope this time nothing was forgotten.

2021-03-10 05:50 UTC, fritsch commented
Did this work? I did not look at the time when the last issue comment was posted and thought there is still some hidden feature :-) shooting at usability.

2021-03-10 05:54 UTC, bossanova808 commented
I will try in a few hours and report back - I just needed to wait for the coreelec nightly to be built (and to get home!).  Should be able to report in a few hours.

2021-03-10 06:08 UTC, fritsch commented
No hurry thanks that you help us understanding our software :-)

2021-03-10 07:19 UTC, bossanova808 commented
Happy to confirm this fix now works - for a 1280 * 720 @ 25 file, it reports:

```
2021-03-10 18:15:08.997 T:4684    DEBUG <general>: [WHITELIST] Searching for a desktop resolution with double the refresh rate
2021-03-10 18:15:08.997 T:4684    DEBUG <general>: [WHITELIST] Matched a desktop resolution with double the refresh rate 1920x1080 @ 50.00 - Full Screen (32)
2021-03-10 18:15:08.997 T:4897    DEBUG <general>: CVideoPlayer::ProcessVideoData size:50947 dts:7.000 pts:7.200 dur:40.000ms, clock:-0.183 level:81
2021-03-10 18:15:08.997 T:4684     INFO <general>: Display resolution ADJUST : 1920x1080 @ 50.00 - Full Screen (32) (weight: -39912667225260032.000)
```

.i.e. it plays the file at 1920 * 1080@50 which is as desired & expected.

Thanks!

(I presume this, as a fix,  gets back-ported to Matrix as well?)

2021-03-10 11:20 UTC, fritsch commented
Finally. Yes, I marked it as Backport needed. Will do after jenkins is happy, tonight.

Thanks again!

2021-03-11 17:22 UTC, fritsch commented
jenkins build this please (if you might have forgotten)

2021-03-14 09:38 UTC, merged