SystemInfo: Cleanup and make some items conditional
xbmc/xbmc pull request #19396
Opened 2021-03-11 22:51 UTC by lrusak

This updates the video and hardware systeminfo screens.

1) Remove some redundant info (we already show cpu usage and memory usage below)
2) Make some items conditional (some are platform specific and if they are empty they shouldn't be shown
3) Add a couple extra locations for information on linux arm platforms

I've made some items static as to only be initialised once (there is no need to constantly read the cpu info)

This affects all platforms so they should all be tested to make sure nothing is completely broken (it's only info anyways)

I've attached some screenshots to show the difference (before on left, after on right)

x86 linux:
![x86-hw](https://user-images.githubusercontent.com/1616460/110865449-7bd25380-8278-11eb-8886-99751e29bb0e.jpg)
![x86-video](https://user-images.githubusercontent.com/1616460/110865450-7c6aea00-8278-11eb-8f00-831a6cd9d30f.jpg)

----

arm linux:
![arm-hw](https://user-images.githubusercontent.com/1616460/110865517-9a384f00-8278-11eb-8a8d-4a74b0c3deeb.jpg)
![arm-video](https://user-images.githubusercontent.com/1616460/110865518-9ad0e580-8278-11eb-9d3b-ed64f346f973.jpg)

2021-03-12 09:01 UTC, da-anda commented
isn't it up to the skins if they show the CPU+RAM info below or not? For that reason I would keep the info in the upper panel, since core can not know how it is shown.

2021-03-12 21:57 UTC, lrusak commented
> isn't it up to the skins if they show the CPU+RAM info below or not? For that reason I would keep the info in the upper panel, since core can not know how it is displayed.

I was wondering about this. It does seem silly to list it twice though

2021-03-12 21:59 UTC, fuzzard commented
If the skins choose not to show it, why do we want to enforce it be shown anyway? Isn't the point of the skins to cater their views to whatever they want?

2021-03-13 13:26 UTC, etrax79 commented
Let me add two comments, based on my [LibreELEC PR](https://github.com/LibreELEC/LibreELEC.tv/pull/5171)
- The information collected from '/sys'-fs in the upper part of CPUInfoLinux.cpp will be replaced with the info collected from the /proc/cpuinfo listing at the bottom of the script. (or at least on my Cubox it is working this way)
- Under certain circumstances reading from '/sys'-fs is giving strings containing NULL (or '\0'). So string.length() is 1 and string.empty() is false...

@chewitt proposed to delegate the sourcing of system-info to userspace similar to how "cputemp" and "gputemp" are handled.

2021-03-13 14:07 UTC, chewitt approved these changes
I tested with some Amlogic (on modern kernel) and RPi4 hardware. LGTM.

2021-03-13 18:57 UTC, etrax79 requested changes
The collected data for Hardware, Revision and Serial at this point will later be replaced with the data collected by reading /proc/cpuinfo (lines 230-260).
As long as it has entries for them, these will replace the values read from /sys.
(i.e. nice serial read from /sys is replaced with '0000000000000000' from cpuinfo)

I would suggest to write to variables at the /proc/cpuinfo-part only if they are 'empty'.

2021-04-07 21:00 UTC, lrusak commented
any objections on behalf of the skins deciding if they want to show cpu usage and memory info?

2021-04-22 18:45 UTC, gade01 commented
Looking great.
No reason to display the info 2 times.

2021-04-27 18:18 UTC, merged