[Subtitles][ASS] Support both user defined fonts and extracted fonts
xbmc/xbmc pull request #19535
Opened 2021-04-08 09:15 UTC by enen92

## Description
This PR improves font handling for ASS subtitles. In kodi we allow users to add new fonts for subtitles (see 5.1 in https://kodi.wiki/view/Subtitles) by placing them into .kodi/media/Fonts. When using external subtitles that require the use of external fonts, the user should be able to place the fonts there for kodi/libass to find and use.

The main issue here is that libass only supports a single folder for storing additional fonts (see `ass_set_fonts_dir`) and we currently use the temp folder (.kodi/temp/Fonts) - the demuxer is configured to extract fonts to this directory (for muxed subs).

Due to the limitation, this PR changes the implementation and makes the demuxer extract subtitles to the user font directory by appending a known prefix to the files "tmp.font.*. This prefix is later used to cleanup temporary files, just like today (`ClearTempFonts`). This way we can support external fonts for subtitles and muxed fonts with libass.

## Motivation and Context
Improve font handling for ASS subtitles. Feature pairity between ASS and other subtitle formats (so that we can work towards a future conversion).
Fixes https://github.com/xbmc/xbmc/issues/16209

## How Has This Been Tested?
This was runtime tested on Linux, Android (TV), Windows and OSX with the samples available on the team ftp server. Furthermore, external subtitles (with missing fonts) were tested using the sample provided in https://forum.kodi.tv/showthread.php?tid=361545&pid=3024983#pid3024983

## Screenshots (if appropriate):

**Before (segoeprb.ttf in media/Fonts):**
![alt text](https://i.imgur.com/NKwmKh4.png "Before")

**After (segoeprb.ttf in media/Fonts)**
![alt text](https://i.imgur.com/JHTWFIn.png "After")

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

2021-04-08 10:17 UTC, enen92 commented
Jenkins build this please

2021-04-08 13:51 UTC, phunkyfish commented
jenkins build this please

2021-04-08 13:54 UTC, phunkyfish requested changes
Just some minors.

2021-04-08 13:54 UTC, phunkyfish commented on xbmc/Util.cpp
> +  std::string searchPath = "special://home/media/Fonts/";
`const` std::string

2021-04-08 13:54 UTC, phunkyfish commented on xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp
> +  std::string strPath = "special://home/media/Fonts/";
`const` std::string

2021-04-08 17:16 UTC, phunkyfish approved these changes
LGTM

2021-04-10 07:59 UTC, enen92 commented
Jenkins build and merge

2021-04-10 08:43 UTC, merged