add riscv compile defines
xbmc/xbmc pull request #20087
Opened 2021-08-29 05:06 UTC by heitbaum

## Description

Update Kodi to allow compile to complete on RISC-V

Add `defined(__riscv)` so as to:
- Disable `USE_LDT_KEEPER`
- Enable `DISABLE_MATHUTILS_ASM_ROUND_INT`

## Motivation and context

The defined(__riscv) is used by a number of the architectures to disable/enable functionality not available on the architecture.

## How has this been tested?

Full test compile has been done using LibreELEC/LibreELEC.tv:master. Further work continuing to further bring up LE with __riscv.

## What is the effect on users?

No impact on users. This change is only to allow the Kodi source to be compiled for RISC-V

## Screenshots (if appropriate):
As per the guidelines below - vaclidate that `__riscv` is the correct **define**.
https://github.com/xbmc/xbmc/blob/8d098aee94781c9fad5c383f69242a69984bb69a/xbmc/utils/MathUtils.h#L20-L22
```
$ ./gcc-riscv64-unknown-linux-gnu/bin/riscv64-unknown-linux-gnu-gcc -dM -E - < /dev/null | grep -i risc
#define __riscv 1
#define __riscv_atomic 1
#define __riscv_cmodel_medlow 1
#define __riscv_fdiv 1
#define __riscv_float_abi_double 1
#define __riscv_mul 1
#define __riscv_muldiv 1
#define __riscv_xlen 64
#define __riscv_fsqrt 1
#define __riscv_m 2000000
#define __riscv_a 2000000
#define __riscv_c 2000000
#define __riscv_d 2000000
#define __riscv_f 2000000
#define __riscv_i 2000000
#define __riscv_zicsr 2000000
#define __riscv_compressed 1
#define __riscv_flen 64
#define __riscv_arch_test 1
#define __riscv_div 1
#define __riscv_zifencei 2000000
```

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2021-08-29 05:32 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR20087-0001-2551f232a1-add-riscv-compile-defines.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/19863/artifact/PR20087-0001-2551f232a1-add-riscv-compile-defines.diff)
 - [PR20087.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/19863/artifact/PR20087.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2021-08-29 05:42 UTC, heitbaum commented
> I've made some formatting changes to meet the current code style. The diffs are available in the following links:
> 
> * [PR20087-0001-2551f232a1-add-riscv-compile-defines.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/19863/artifact/PR20087-0001-2551f232a1-add-riscv-compile-defines.diff)
> * [PR20087.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/19863/artifact/PR20087.diff)
> 
> For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

Updated to meet style.

2021-08-29 05:49 UTC, fuzzard commented
Bummer, I would have left it as is, haha.

2021-08-29 05:57 UTC, heitbaum commented
> Bummer, I would have left it as is, haha.

:-) Got it

2021-08-29 07:04 UTC, heitbaum commented
Given the jump the gun at the format changes - I have taken the opportunity to update the sort order of the defined().

2021-08-29 07:28 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR20087-0001-02394ad0c3-add-riscv-compile-defines.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/19865/artifact/PR20087-0001-02394ad0c3-add-riscv-compile-defines.diff)
 - [PR20087.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/19865/artifact/PR20087.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2021-08-29 07:47 UTC, howie-f commented
> I’ve made some formatting changes to meet the current code style. …..

honestly i‘d wrap this with `// clang-format off/on` 🙄

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#37-exceptions-to-the-formatting-rules-for-better-readability

2021-08-29 23:06 UTC, fuzzard requested changes
I think going back to your original submission, and adding the clang-format on/off is the better way to go.
To me, it really is easier to read and understand at a glance.

2021-08-30 12:54 UTC, heitbaum commented
> I think going back to your original submission, and adding the clang-format on/off is the better way to go.
> To me, it really is easier to read and understand at a glance.

I like it better that way tool 👍 updated and sort order fixed.

2021-08-30 18:49 UTC, fuzzard approved these changes

2021-08-30 19:21 UTC, howie-f approved these changes
nice

2021-08-30 19:50 UTC, merged

2021-08-30 20:00 UTC, lrusak commented
Just an FYI as this may allow Kodi to compile it won't allow the depends build to compile as that requires other changes.

2021-08-30 20:09 UTC, fuzzard commented
Baby steps as always

2021-08-30 22:01 UTC, heitbaum commented
> Just an FYI as this may allow Kodi to compile it won't allow the depends build to compile as that requires other changes.

quite right. Still working through my pthread issue. A long road ahead for riscv - but hopefully the little bits an pieces of pre-work will help it on it journey :-)
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000003fd8ff261a in start_thread (arg=0x3fd86e1d20) at pthread_create.c:422
  422       if (__glibc_unlikely (atomic_exchange_acq (&pd->setxid_futex, 0) == -2))
[Current thread is 1 (LWP 148)]
```