[JSON] add ActivateScreenSaver
xbmc/xbmc pull request #20110
Opened 2021-09-05 09:57 UTC by DaVukovic

## Description

This changes introduces the option to activate the currently used screensaver. 
It's already available as a Python built-in and I thought it might be a good idea to have that as well. 

If this is not the correct way to implement that, then please let me know how to do it correct. For example, I'm not so sure if the version number I`m using is correct of if it should be 12.5.0
So please let me know if anything is wrong or could be done better.

## Motivation and context

solves: #20088

## How has this been tested?

I did a few tests with Kodi on Linux and also tried with an additionally installed screensaver add-on (bing fotos of the week). 

## What is the effect on users?

At least nothing negative ;). Users are simply able to activate the screensaver via a JSON call. It doesn't break anythin. 

## Screenshots (if appropriate):

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2021-09-05 10:23 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR20110-0001-ad1e842806-JSON-add-ActivateScreenSaver.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/19905/artifact/PR20110-0001-ad1e842806-JSON-add-ActivateScreenSaver.diff)
 - [PR20110.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/19905/artifact/PR20110.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2021-09-06 05:45 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR20110-0001-0997e9ebcc-JSON-add-ActivateScreenSaver.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/19922/artifact/PR20110-0001-0997e9ebcc-JSON-add-ActivateScreenSaver.diff)
 - [PR20110.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/19922/artifact/PR20110.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2021-09-07 09:16 UTC, Tolriq commented
Should be 12.5.0 as API change :) Beware that as soon as there's JSON divergence with Matrix future JSON patch won't be able to be backported so maybe it should be backported too as simple to keep backports opened.

About "namespace" is this really System and not more GUI? I suppose this would be a no-op on a future GUI less Kodi. (The built in does not have System.ActivateScreenSaver it's just labelled as that in the Wiki.

BTW if you are in adding the missing stuff here's the biggest one that can't be used from JSON and still require Event Server to run the built in.
```
PlayerControl(tempoup)
PlayerControl(tempodown)

CECActivateSource
CECStandby
CECToggleState

PlayDisc
RipCD
```

2021-09-07 16:03 UTC, garbear commented
BTW, the commit without whitespace changes is easier to review, here: https://github.com/xbmc/xbmc/commit/9b9db66af648e79dd807ca515a00b31a7105764b?w=1 (appended `?w=1` to raw commit)

2021-09-09 22:26 UTC, DaVukovic commented
@Tolriq 
Thanks for your input

>About "namespace" is this really System and not more GUI? I suppose this would be a no-op on a future GUI less Kodi. (The built in does not have System.ActivateScreenSaver it's just labelled as that in the Wiki.

True. My bad. I thought one needs to trigger it via `System.ActivateScreenSaver`. But `ActivateScreenSaver` is what one needs to call. So I will change that to GUI-Operations. 

Will do a backport of that for sure if it gets accepted. 

@garbear 
>BTW, the commit without whitespace changes is easier to review, ....

That was a mistake by me. I force-pushed without commiting ;). Hence the commit. Please ignore that. I'll do an update of this PR anyway.

2021-09-09 23:54 UTC, garbear commented
> That was a mistake by me. I force-pushed without commiting ;). Hence the commit. Please ignore that. I'll do an update of this PR anyway.

If you are a git-fu master, you'll do a "cleanup" commit first and a "meaty" commit after, so that the meaty commit has exactly what needs to be reviewed ;)

2021-09-10 00:00 UTC, DaVukovic commented
> If you are a git-fu master

Well, I'm not ;)

I've just pushed the latest changes. If this PR is hard to review, I'll happily close it and create a new one.

2021-09-10 00:40 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR20110-0001-e05f9f13f6-JSON-add-ActivateScreenSaver.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/19952/artifact/PR20110-0001-e05f9f13f6-JSON-add-ActivateScreenSaver.diff)
 - [PR20110.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/19952/artifact/PR20110.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2021-09-10 19:49 UTC, garbear approved these changes
[Link to new commit](https://github.com/xbmc/xbmc/pull/20110/commits/e05f9f13f6e4c6b0d8cd676aea1a6e9a77607998). I'm not sure about the version number, if you should bump the minor or the patch. But otherwise this looks like a clean addition of a feature that makes sense.

2021-09-11 22:16 UTC, Montellese reviewed
Looks good apart from the unnecessary whitespace changes in `JSONServiceDescription.cpp`.

2021-09-12 08:37 UTC, DaVukovic commented
Yeah, that's what Jenkins suggests

2021-10-06 06:43 UTC, lrusak commented
@DaVukovic would it be possible for you to split out the clang-format changes for `CJSONServiceDescription::m_methodMaps` into a pre commit? This way your commit changes exactly what is needed.

2021-10-06 07:40 UTC, DaveTBlake requested changes
Unhappy with having whitespace changes throughout JSONServiceDescription.cpp in this PR. 
Since it is part of our coding standard to allow additional whitespace in code for readability of things like data structures, I would suggest that the necessary `// clang-format on` `// clang-format off` are added for this instead of stripping whitespace. Otherwise the addition of the method is fine.  

Note merging this will mark the end of fixes to JSON API in Matrix. There are several other API changes waiting to merge that have been delayed for this reason. Perhaps we should merge them in order of creation rather than give this priority? The only reason to do this one first would be if we also backport it to v19? Any opinions?

2021-11-11 06:17 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR20110-0001-f0856da232-JSON-add-ActivateScreenSaver.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/20698/artifact/PR20110-0001-f0856da232-JSON-add-ActivateScreenSaver.diff)
 - [PR20110.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/20698/artifact/PR20110.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2021-11-11 06:26 UTC, howie-f commented on xbmc/interfaces/json-rpc/JSONServiceDescription.cpp
> +// clang-format off
only need to move this line above `JsonRpcMethodMap…` and we‘re done. thanks

2021-11-22 06:22 UTC, DaVukovic commented
@howie-f 

Obviously something got totally mixed up as I tried to squash commits and revert old clang-stuff. I hope I've done everything correct now. At least it builds fine for me and I can use this method.

2021-11-22 09:48 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR20110-0001-65e0465971-JSON-add-ActivateScreenSaver.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/20849/artifact/PR20110-0001-65e0465971-JSON-add-ActivateScreenSaver.diff)
 - [PR20110.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/20849/artifact/PR20110.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2021-11-22 20:14 UTC, howie-f approved these changes
nice 👍

2022-04-08 11:32 UTC, jenkins4kodi commented
@DaVukovic this needs a rebase

2023-09-26 22:16 UTC, DaVukovic commented
Missed that one totally. I'll have a look soon and will probably rebase it. If not, I'll close this one

2023-12-04 21:51 UTC, closed without merging

2023-12-04 22:20 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [null](https://jenkins.kodi.tv/job/BuildMulti-PR/28417/artifact/null)
 - [...]