Upstreamed Debian patches
xbmc/xbmc pull request #20331
Opened 2021-10-17 10:53 UTC by basilgello

## Description

Upstream the Debian patch after `s390x` support was added in 19.0.

## Motivation and context

I forgot to add one patch to relevant issue 19109. After @aurel32 upstreamed his riscv64 patch,
I decided that other patches can follow.

## How has this been tested?

Built 19.2 on 12 architectures and 20.0 nightly on 3.

## What is the effect on users?

It is mostly for package maintainers.

## Screenshots (if appropriate):

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

2021-10-17 10:58 UTC, basilgello commented
The only question left from previous review in #19109 (and the reason why I did not upstream patch no.4) is the cross-compilation enablement.

2021-10-19 13:40 UTC, wsnipex requested changes

2021-10-19 17:26 UTC, wsnipex approved these changes

2021-10-19 20:42 UTC, AlwinEsch approved these changes

2021-10-20 10:04 UTC, merged