Added ETC1/ETC2/ASTC texture support for GL/GLES
xbmc/xbmc pull request #20376
Opened 2021-10-23 23:11 UTC by sarbes

## Description
This PR adds initial support for ETC/ETC2/ASTC compression on GL and GLES.

Textures can now be supplied via the file extensions ".etc1" (PKM 10), ".etc2" (PKM 20) and ".astc" (ASTC). https://developer.arm.com/tools-and-software/graphics-and-gaming/mali-texture-compression-tool can create such textures.

## Motivation and context
Low end platforms are usually pretty memory bandwidth bound, and rendering large RGBA textures (like the background textures of Estuary) is very costly. ETC1 compression is available on virtually every device, so at least RGB textures can be used there. ETC2 and ASTC feature better compression and alpha channel support.

Ideally, some logic to select the most suitable texture will have to be put in place. In this state, only textures explicitly defined in the skin can be used.

Also, the texture packer needs to be updated to include such textures in the .xbt file format.

## How has this been tested?
On my main PC with an RX 570, it ran fine. ETC1/2/ASTC were displayed properly. The latter format is decoded by Mesa before it had been send to the GPU, as AMD features no hardware support for it.
On a Raspberry Pi 4, ETC1/2 displayed correctly too. ASTC is not supported.

## What is the effect on users?
Effects should be none, as no such textures were used before.

## Screenshots (if appropriate):

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

2021-10-24 00:27 UTC, lrusak requested changes
I like the way you broke the logic into similar chunks for both new classes.

First round of review looks good with some small improvements suggested.

I tried to only comment once for each change type but some changes are applicable in multiple locations.

2021-10-25 17:49 UTC, AlwinEsch requested changes
On the whole, the request looks good to me, only a few places that need to be cleaned up.

2021-11-07 07:15 UTC, jenkins4kodi commented
@sarbes this needs a rebase

2024-08-05 22:37 UTC, jenkins4kodi commented on xbmc/TextureCacheJob.cpp
> +      CLog::Log(LOGDEBUG, "Not caching image '%s'", CURL::GetRedacted(image).c_str());
Please update to the current log standards using `{}`.

For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

2024-11-15 21:24 UTC, sarbes commented
This PR has been superseded. Thanks everybody for your time!

2024-11-15 21:24 UTC, closed without merging