[Linux][udisks] Always mount optical media by default
xbmc/xbmc pull request #20840
Opened 2022-01-11 19:43 UTC by enen92

## Description
Currently the experience for optical discs (e.g. physical DVDs) is far from optimal on Linux. By default, once you insert a physical disc on your drive the default skin will show you have a DISC with options to play or eject:

![image](https://user-images.githubusercontent.com/7375276/149007966-0aa93faf-c4b0-47c2-85b3-36140149b3d1.png)

However, to be able to play the disc **you have to mount it manually on your desktop environment**. This is only true is Kodi is not running standalone (e.g. without providing the `--standalone` arg or running kodi-standalone.sh). If running standalone, the [handlemounting](https://kodi.wiki/view/Advancedsettings.xml#handlemounting) advanced setting will be set to `true` automatically and any discs will be automounted by kodi (all of them, including DVDs/BRs). While I understand the reason for this distinction so distros like Libreleec that run kodi standalone can handle generic disc mounting (while modern DEs automatically mount media for us) I think that by default Kodi should have an exception for optical discs. DEs like gnome, for example, do not automount DVDs by default without further settings/configs by the user.

IMHO if kodi, as a GUI application, shows in the UI that a disc is available for playback, it should be able to play it. It should handle the mounting of the optical disk on behalf of the user. This behaviour should be default... and at most... advanced users could disable it via an advancedsetting (not the opposite). 

That's what this PR does, by default Kodi (udisks and udisks2 storage providers) mounts optical media unless "automountopticalmedia" advanced setting is set to false. "handleautomounting" bypasses this setting since it mounts ALL discs (optical or not).

## Motivation and context
Improve UX, make it simpler for users to watch their media without having to dive into the code or read 1500 wikis and forum posts :). For example the handlemounting advanced setting was not even documented anywhere.

2022-01-13 08:53 UTC, DaVukovic commented
I've tested this PR and it does what it should ;-)

DVDs are mounted automatically and are not mounted if I set advancedsettings.xml to: 

```
<advancedsettings>
  <automountopticalmedia>false</automountopticalmedia>
</advancedsettings>
```

Just as a suggestion. The "Disc" menu option is still shown if I set the advancedsettings.xml to not automount it. I'm not too sure if this is something we can cover with this PR, but for me it would make sense if that disc menu is only shown if Kodi has successfully mounted the disc. Otherwise you can't do anything with that menu. 

The rest is fine and a :+1: from my side

2022-01-13 08:54 UTC, DaVukovic approved these changes

2022-01-13 09:20 UTC, enen92 commented
You can eject it :)

2022-01-13 15:32 UTC, howie-f commented on xbmc/platform/linux/storage/UDisksProvider.cpp
>      device->Mount();
maybe wrap this with `{}`

2022-01-13 15:32 UTC, howie-f commented on xbmc/platform/linux/storage/UDisksProvider.cpp
>        device->Mount();
```
const auto advancedSettings = CServiceBroker::GetSettingsComponent()->GetAdvancedSettings();

if (!mounted && device->m_isOptical)
{
  if (advancedSettings->m_handleMounting || advancedSettings->m_autoMountOpticalMedia)
  {
    device->Mount();
  }
}
```
should be a bit easier, hopefully it does the same :)

2022-01-13 16:45 UTC, howie-f requested changes
an accident

2022-01-13 17:10 UTC, howie-f approved these changes
lgtm, thanks

2022-01-13 17:31 UTC, enen92 commented
jenkins build this please

2022-01-16 14:06 UTC, merged

2023-11-21 22:18 UTC, KarellenX commented
@enen92 

I assume this needs to be added to the advancedsettings.xml in here... https://kodi.wiki/view/Advancedsettings.xml#File_system_settings ?

And is it as follows for the default setting?
```
<advancedsettings version="1.0">
  <automountopticalmedia>true</automountopticalmedia>
</advancedsettings>
```

While I am at it, I note that `detectasudf` and `handlemounting` don't have the code added to the wiki page.
Same as the above example, but using `<detectasudf>` and `<handlemounting>` instead?

2023-11-21 22:57 UTC, KarellenX commented
>I also plan to kill it at some point.

Near future? If yes, I'll just leave it out. If no, I'll add it but if you can remember to add the wiki needed tag when you kill it.

I'll make note its for Linux only.
Thanks.

2023-11-21 22:59 UTC, enen92 commented
> > I also plan to kill it at some point.
> 
> Near future? If yes, I'll just leave it out. If no, I'll add it but if you can remember to add the wiki needed tag when you kill it.
> 
> I'll make note its for Linux only. Thanks.

Definitely not for v21 so please add it. Thanks for looking into this :)