[addons] add CStructHdl operator= support for 'A = A'
xbmc/xbmc pull request #21627
Opened 2022-07-01 13:12 UTC by repojohnray

This change fixes the issue described here:
https://github.com/kodi-pvr/pvr.vdr.vnsi/pull/186

2022-07-02 20:41 UTC, ksooo commented
> the templated operator= should be guarded in the same way

 That's right. => `if (m_cStructure && m_cStructure == right) return *this;`
 
 > so IMHO the return type of both operators should be changed to CStructHdl&
 
  Not sure about this.  What would this change improve or fix?
  
 > could be a bit beautified with blank lines :)
 
  I agree.

2022-07-02 20:50 UTC, ksooo requested changes
See my comments.

2022-07-03 05:32 UTC, howie-f commented
> > so IMHO the return type of both operators should be changed to CStructHdl&
> 
> Not sure about this. What would this change improve or fix?

it would make our class CStructHdl behave more like the standard types. for example it would no longer prevent expressions like `(A = B).nonConstMember();` which is also valid c++. (a different question if it would ever get used this way)

since this pr is all about `heap-use-after-free` i suggest to @repojohnray : please fix both operators=, address 1. + 3. of my comment and this should be good to go. we can fix the return type later if we want to

2022-07-03 20:34 UTC, repojohnray commented
Both operators= are updated as requested. This works fine on my configuration.

2022-07-03 20:50 UTC, ksooo approved these changes
LGTM

2022-07-03 21:03 UTC, repojohnray commented
This should be applied to Matrix as well.

2022-07-03 21:22 UTC, ksooo commented
Not sure about Matrix as from my point of view this is more a theoretical problem. Or do we have evidence for a real crash produced by this bug?

2022-07-03 21:54 UTC, repojohnray commented
This issue is happening on Matrix, the code generating "A = A" from pvr.vdr.vns is identical on both branches.

2022-07-04 05:52 UTC, ksooo commented
> This issue is happening on Matrix, the code generating "A = A" from pvr.vdr.vnsi is identical on both branches.

Okay, then please open a backport PR for Matrix.

2022-07-04 05:53 UTC, merged