[upnp] Fix crash due to lack of thread-safety
xbmc/xbmc pull request #22154
Opened 2022-11-16 15:51 UTC by enen92

## Description
This is not easy to explain but Kodi is crashing a lot on startup if you start navigating in the interface quickly after start (e.g. using the mouse on estuary) to focus items. Or just if you happen to have `upnp://` items on the homescreen.
This happens specially in debug mode if UPnP is enabled (although it's also reproducible in release) and gets really annoying when developing (usually 3/4 startups until you can, luckily, avoid the crash...)

When kodi starts up, network services ask for the start of the UPnP server. At the same time, if you have items with upnp:// paths jobs are started to get the thumbnail of the items, asking for the startup of the UPnP server as well. Starting the server 
 should be innocuous and avoid the creation of `m_MediaBrowser` (returning early) but you might get into a race case where `m_MediaBrowser` is created multiple times.
Internally this adds multiple control points in libUpnp (https://github.com/xbmc/xbmc/blob/2b1626dcb1a208c411e5c42e3e20deca66aa382e/lib/libUPnP/Platinum/Source/Core/PltCtrlPoint.cpp#L345).

Problem happens when actual UPnP results are to be processed: https://github.com/xbmc/xbmc/blob/2b1626dcb1a208c411e5c42e3e20deca66aa382e/lib/libUPnP/Platinum/Source/Devices/MediaServer/PltSyncMediaBrowser.cpp#L144
Processing the result deletes the userdata void* that is a member of `PLT_CtrlPointListenerOnActionResponseIterator` https://github.com/xbmc/xbmc/blob/2b1626dcb1a208c411e5c42e3e20deca66aa382e/lib/libUPnP/Platinum/Source/Core/PltCtrlPoint.cpp#L92 that, again, due to the timings each object is created can refer to the exact same object...leading to the crash.

This PR just lock-protects the UPnP server startup (and stop just for the sake of it), ensuring we don't end up creating multiple control points for no reason. It doesn't really have any side effects, upnp thumbnails will just wait for the server to be created before attempting to load. Can also be fixed in libupnp but I'd like to avoid adding patches to it - and kodi is wrong anyway.

PS: diff is a bit bigger than it needs to be because of auto clang-format. I don't intend to change the indented lines to our code guidelines.

2022-11-16 17:30 UTC, enen92 commented
jenkins build this please

2022-11-16 20:40 UTC, Montellese requested changes
LGTM apart from the two comments.

2022-11-16 20:40 UTC, Montellese commented on xbmc/network/upnp/UPnP.h
> +    mutable CCriticalSection m_lock;
I prefer locks with meaningful names like `m_lockMediaBrowser`.

2022-11-16 20:40 UTC, Montellese commented on xbmc/network/upnp/UPnP.h
> +    mutable CCriticalSection m_lock;
Why is this `mutable`? It's only used in non-`const` methods.

2022-11-16 22:03 UTC, Montellese approved these changes

2022-11-17 10:05 UTC, howie-f reviewed
as a non-UPnP-user i've never faced this issue. but looks reasonable

2022-11-17 10:54 UTC, merged