Disabled 'move' option from windows system menu on pressing Alt + Spa…
xbmc/xbmc pull request #22628
Opened 2023-01-29 22:17 UTC by ljn7

## Description
Fixes [#16571](https://github.com/xbmc/xbmc/issues/16571)

## Motivation and context
To stop end users from being able to move the app.

## How has this been tested?
Haven't tested this on my end. If anyone could test and confirm this, it would be great.

## What is the effect on users?

## Screenshots (if appropriate):

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2023-01-29 23:30 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR22628-0001-29e4d3ce44-Disabled-move-option-from-windows-.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25118/artifact/PR22628-0001-29e4d3ce44-Disabled-move-option-from-windows-.diff)
 - [PR22628.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25118/artifact/PR22628.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-01-30 09:51 UTC, thexai requested changes
Unfortunately this is not correct: some users use Kodi in windowed mode and want to move the window to a corner of the screen. With this PR it is not possible because not only the menu disappear but also the window cannot be moved by dragging the title bar.

2023-01-30 09:58 UTC, thexai commented
See: https://forum.kodi.tv/showthread.php?tid=360960

Users are now happy because can move window position and remember its position persistently.

2023-01-31 09:31 UTC, ljn7 commented
I tried to implement it in different way but to test that I've to compile kodi, but while compile ffmpeg for windows I'm receiving openssl not found. My machine is Windows 11 and I've installed openssl binaries too. If anyone could help me get through this, will be appreciated.

2023-01-31 10:36 UTC, thexai commented
See https://github.com/xbmc/xbmc/pull/22649 this should work but not tested yet.

2023-01-31 11:20 UTC, thexai commented
> for Windows UWP x64

This issue is in x64 desktop. 

Native UWP build only are used in Xbox. The open issue mentions Windows Store but when download to use in desktop is a "port" of same x64 desktop code. Then the same issue is in Windows Store version for desktop or regular x64 desktop (no store).

Xbox is not affected and only supports full screen.

2023-01-31 12:58 UTC, ljn7 commented
> See #22649 this should work but not tested yet.

 I didn't know that store version same x64 build. Exactly same approach I wanted to implement, I guess it fixes this issue.

2023-02-02 10:12 UTC, thexai commented
Closing this as fix is already tested and merged

2023-02-02 10:12 UTC, closed without merging