[GUI][GUIInfoLabel] Add support for complex expressions on the fallba…
xbmc/xbmc pull request #22735
Opened 2023-02-09 19:20 UTC by enen92

…ck label

## Description
Currently fallback labels cannot use complex expressions like the combination of infolabels or simple localized strings. This PR improves the status by unifying the logic of the main label and the fallback label (all elements supported in label are now available to the fallback as well).

Closes https://github.com/xbmc/xbmc/issues/22728

@scott967 can you runtime test if this solves your needs?

2023-02-10 00:02 UTC, scott967 commented
I did a test on my Windows dev and the results for fallback=
"19055" pass (works as existing)
"some text" pass
"$LOCALIZE[19055]" pass
"$NUMBER[19055]" pass
"$VAR[defined variable value]" fail (nothing rendered)
"$INFO[defined infolabel] fail (nothing rendered)

From the commit I thought the last two cases should work?
The new documentation in the header seems OK, though I would probably use "tokens" rather than "info portions"
At least in my use case that fails in Kodi 20 that is fixed.

2023-02-10 00:16 UTC, scott967 requested changes
See previous comment

2023-02-10 18:02 UTC, enen92 commented
thanks @scott967, this was valuable feedback. Can you please test again? Think I've found the issue.

I did validate the INFO this time but didn't look into variables as it would require me a bit of time to setup an example (although the code is the same so they should work). Can you repeat your tests confirming that the same values that potentially don't work (e.g $VAR[defined variable value]) on the fallback actually work if set on the main label instead?

Cheers

2023-02-10 21:15 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR22735-0001-8c9a789eb1-GUI-GUIInfoLabel-Add-support-for-c.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25330/artifact/PR22735-0001-8c9a789eb1-GUI-GUIInfoLabel-Add-support-for-c.diff)
 - [PR22735.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25330/artifact/PR22735.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-02-11 08:37 UTC, fuzzard commented
Jenkins build this please

2023-02-11 09:52 UTC, scott967 approved these changes
Ok retested and all pass.  In addition, I tested $ADDON[] and that passed as well.  Could do some more complex expressions, but at this point I say it's good from my perspective.

2023-02-11 10:30 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR22735-0001-8c9a789eb1-GUI-GUIInfoLabel-Add-support-for-c.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25343/artifact/PR22735-0001-8c9a789eb1-GUI-GUIInfoLabel-Add-support-for-c.diff)
 - [PR22735.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25343/artifact/PR22735.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-02-11 10:35 UTC, enen92 commented
Thank you, adjusted clang-format now and plan to push if jenkins gets a green. 

Regarding tokens vs portions (in the docs) I totally agree token/tokenizer is way better. However note most of those methods are private to the class and don't even show in the doxy page.
I think it is preferable that is is done later as follow up (would require renaming variables as well which I don't really want to deal with at this point). If you can do this after the PR gets in it it'd be greatly appreciated though and definitely an improvement.

2023-02-11 14:09 UTC, enen92 commented
jenkins build this please

2023-02-11 21:28 UTC, enen92 commented
jenkins build this please

2023-02-12 11:40 UTC, merged