CPipewireGlobal: add class to help with registry globals
xbmc/xbmc pull request #22820
Opened 2023-02-18 22:02 UTC by lrusak

This PR splits the pipewire `global` out into a separate class `CPipewireGlobal`. This helper class adds getters/setters that IMO help with readability.

No functional changes are present.

This also includes a couple other QOL improvements such as using references and structured bindings.

2023-02-18 23:27 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR22820-0006-b27f7377b0-CAESinkPipewire-use-structured-bin.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25495/artifact/PR22820-0006-b27f7377b0-CAESinkPipewire-use-structured-bin.diff)
 - [PR22820.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25495/artifact/PR22820.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-02-22 01:02 UTC, neo1973 requested changes
Looks good with the exception of the `CPipewireGlobal` interface. `const uint32&` as parameter and return value looks strange.

I would also change all instances of `const std::string&` parameters to `std::string_view` in preparation of the [style guide update](https://github.com/xbmc/xbmc/pull/22639).

<details>
<summary>Proposed change</summary>

```diff
diff --git a/xbmc/cores/AudioEngine/Sinks/pipewire/PipewireGlobal.h b/xbmc/cores/AudioEngine/Sinks/pipewire/PipewireGlobal.h
index 452a36cc92..e749d0b56c 100644
--- a/xbmc/cores/AudioEngine/Sinks/pipewire/PipewireGlobal.h
+++ b/xbmc/cores/AudioEngine/Sinks/pipewire/PipewireGlobal.h
@@ -8,6 +8,7 @@
 
 #include <memory>
 #include <string>
+#include <string_view>
 
 #include <pipewire/properties.h>
 
@@ -29,7 +30,7 @@ public:
   CPipewireGlobal() = default;
   ~CPipewireGlobal();
 
-  CPipewireGlobal& SetName(const std::string& name)
+  CPipewireGlobal& SetName(std::string_view name)
   {
     m_name = name;
     return *this;
@@ -37,7 +38,7 @@ public:
 
   const std::string& GetName() const { return m_name; }
 
-  CPipewireGlobal& SetDescription(const std::string& description)
+  CPipewireGlobal& SetDescription(std::string_view description)
   {
     m_description = description;
     return *this;
@@ -45,23 +46,23 @@ public:
 
   const std::string& GetDescription() const { return m_description; }
 
-  CPipewireGlobal& SetID(const uint32_t& id)
+  CPipewireGlobal& SetID(uint32_t id)
   {
     m_id = id;
     return *this;
   }
 
-  const uint32_t& GetID() const { return m_id; }
+  uint32_t GetID() const { return m_id; }
 
-  CPipewireGlobal& SetPermissions(const uint32_t& permissions)
+  CPipewireGlobal& SetPermissions(uint32_t permissions)
   {
     m_permissions = permissions;
     return *this;
   }
 
-  const uint32_t& GetPermissions() const { return m_permissions; }
+  uint32_t GetPermissions() const { return m_permissions; }
 
-  CPipewireGlobal& SetType(const std::string& type)
+  CPipewireGlobal& SetType(std::string_view type)
   {
     m_type = type;
     return *this;
@@ -75,7 +76,7 @@ public:
     return *this;
   }
 
-  const uint32_t& GetVersion() const { return m_version; }
+  uint32_t GetVersion() const { return m_version; }
 
   CPipewireGlobal& SetProperties(
       std::unique_ptr<pw_properties, PipewirePropertiesDeleter> properties)
```
</details>

2023-02-22 03:49 UTC, lrusak commented
> Looks good with the exception of the `CPipewireGlobal` interface. `const uint32&` as parameter and return value looks strange.
> 
> I would also change all instances of `const std::string&` parameters to `std::string_view` in preparation of the [style guide update](https://github.com/xbmc/xbmc/pull/22639).
> 

Yep updated, Thanks!

2023-02-22 06:41 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR22820-0006-b27f7377b0-CAESinkPipewire-use-structured-bin.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25565/artifact/PR22820-0006-b27f7377b0-CAESinkPipewire-use-structured-bin.diff)
 - [PR22820.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25565/artifact/PR22820.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-02-22 18:57 UTC, neo1973 approved these changes
You're now using `std::string_view` in more places than I initially anticipated but looking at it I guess it should work as all strings should be valid at least as long as the global exists 🙂

2023-02-23 04:52 UTC, jenkins4kodi commented
@lrusak this needs a rebase

2023-02-23 05:32 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR22820-0005-1a5f15417b-CPipewireGlobal-add-class-to-help-.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25589/artifact/PR22820-0005-1a5f15417b-CPipewireGlobal-add-class-to-help-.diff)
 - [PR22820-0006-e739e7402a-CAESinkPipewire-use-structured-bin.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25589/artifact/PR22820-0006-e739e7402a-CAESinkPipewire-use-structured-bin.diff)
 - [PR22820.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25589/artifact/PR22820.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-02-23 07:16 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR22820-0005-5e18bd7304-CAESinkPipewire-use-structured-bin.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25591/artifact/PR22820-0005-5e18bd7304-CAESinkPipewire-use-structured-bin.diff)
 - [PR22820.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25591/artifact/PR22820.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-03-04 18:06 UTC, merged