[macOS] set NSApplicationActivationPolicyRegular if NSApplicationActi…
xbmc/xbmc pull request #22846
Opened 2023-02-22 10:42 UTC by enen92

…vationPolicyProhibited (unbundled executable)

## Description

## Motivation and context

## How has this been tested?

## What is the effect on users?

## Screenshots (if appropriate):

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2023-02-22 11:12 UTC, stevehartwell requested changes
Please enclose within #ifdef _DEBUG #endif.

2023-02-22 13:27 UTC, ksooo commented
@enen92 confirming the fix working.

@stevehartwell may I ask why the `#ifdef _DEBUG`is needed? What's the problem with being able to directly start a release executable, without a bundle?

2023-02-22 17:08 UTC, stevehartwell commented
> @enen92 confirming the fix working.
> may I ask why the `#ifdef _DEBUG`is needed? What's the problem with being able to directly start a release executable, without a bundle?
While you assure us that the "fix works", it seems unlikely that would be exhaustive testing in release mode, and no guarantee of future breakage.  I think that current state of the app is unstable enough as it is.

2023-02-22 17:10 UTC, ksooo commented
>  I think that current state of the app is unstable enough as it is.

 By what measure you come to this conclusion? And how does the `#ifdef`help to improve this unstability?

2023-02-22 17:37 UTC, stevehartwell commented
> By what measure you come to this conclusion?
It crashes a lot, hides my cursor outside of its window, goes haywire in tiling mode.
> And how does the `#ifdef`help to improve this unstability?
If you have a valid use case for this, please let us know.  But adding stuff that "seems to work" is not a good basis for future development.

2023-02-22 17:45 UTC, enen92 commented
My suggestion is to keep it as is (ifdef'd) if for some reason some other use case appears that requires to relax it we can do it later. For me it serves my needs (development on xcode). FWIW i've tried running the release target and it behaved the same.

Contributions are welcome, we have a strong lack of devs for macOS atm (and I don't even consider myself one :) ).

2023-02-22 18:00 UTC, ksooo commented
Sorry, but i don’t get it. why do we need a “hack” in the code to be able to start, use our app from inside the debugger and to DEBUG it? How do other apps deal with this problem? Our is it something special for Kodi? If so, why?

2023-02-22 18:34 UTC, stevehartwell commented
> How do other apps deal with this problem?

Well, ok.  I assumed that the review who would approve the change would be a Mac dev.

So, you can absolutely do what you want here as long as you build the `bundle` target and launch Kodi.app/Contents/MacOS/Kodi instead of kodi.bin.

Why?  Because Mac UI apps are managed by a subsystem called Launch Services (LS), which needs the `Info.plist` in the root of the .app bundle to set up the activation state.  As you have observed it's possible to launch without an Info.plist, but  LS assigns it a different activation state used for background UI widgets such as the ones running in the right side of the menu bar.

With my change introducing `NSApplicationMain()` to `main()`, launching now requires an accessible Info.plist.  The reason the Xcode debugger doesn't need this is that it injects a debugging dynamic library which among other things presumably provides a minimal one, plus setting up `@rpath` to point to your build directory instead of finding them in the app bundle in ./Libraries folder.

But Xcode doesn't change the activation state, because debugging those types of apps (with no dock icon, etc) is a perfectly valid use case.  But not Kodi.app's.

Adding the force-activation policy in `main()` will force the application state into something different than Launch Services sees it as (it sees it as a background UI app).

And that runtime inconsistency could be bug-inducing, current or future.

p.s. I can describe the valid use case of setting the application policy to Normal if you want, but this reply is already too long.

2023-02-22 19:06 UTC, ksooo commented
@kambala-decapitator do you have an opionion on this?

2023-02-22 19:26 UTC, ksooo commented
@stevehartwell thanks for the explanation. Now I'm starting to understand, I hope. So, instead of introducing the code hack like done in this PR, we should get used to build and run the `bundle`target. What needs to be done to get this a bit more convenient is to automate the scheme changes you were describing in the original PR. Setting the run target, changing the run options. Any idea how to do this from cmake, @fuzzard @kambala-decapitator maybe?

2023-02-22 19:38 UTC, stevehartwell commented
I agree enthusiastically about improving the Xcode project generated by cmake.  I don't know cmake but am willing to learn a little about it.

It might be a good idea to open an issue for this and then ask @fuzzard, who I see has done several enhancements for improving the Xcode project generation, or others with this domain expertise, for some pointers about how to proceed.  I would be willing to participate in making the changes.

2023-02-23 12:21 UTC, kambala-decapitator commented
We don't have any real / professional macos dev on the team. I only have strong ios / tvOS / objc experience.

If release build works fine, then I think it's OK to have the ifdef. I'm only not sure where the underscored version comes from as xcode defines DEBUG traditionally.

If the bundle target works out of the box, then we should use it, just probably give it a better name. Adjusting scheme settings from cmake should be possible, just not sure in which cmake version it was introduced and to which extent it can be done. (Manual adjusting every time is bad of course)

2023-03-20 10:32 UTC, enen92 commented
seems like we concluded the way to go is to improve the xcode generation. Marking this PR as abandoned.

2023-03-20 10:32 UTC, closed without merging