[skin, gui] Look for <fontset> definitions in xml files in /fonts directory
xbmc/xbmc pull request #22993
Opened 2023-03-16 17:11 UTC by smfontes

Modified SettingOptionsSkinFontsFiller in addons/Skin.cpp to get the names of available fontsets from any xml files in the skin's /fonts directory, along with from the Font.xml file. Modified LoadFonts in guilib/GUIFontManager to look for fontset definitions from any xml file in the skin's /fonts directory along with from the Font.xml file.

## Description

This change allows new fontsets to be defined without having to edit a skin's Font.xml file.
New fontsets can be defined by adding xml files to the skin's /fonts directory. 

When searching for available fontsets to display for selection in

Settings->Interface->Skin->Fonts

the code will now also look in any xml files in the skin's /fonts directory for the names of 
available fontsets. The names of the fontsets included for selection will correspond to any &lt;fontset&gt; definitions found in the xml files.

When searching for fontset definitions to load, the code will now also look in any xml files in
the skin's /fonts directory and load the fonts defined by the selected fontset.

The new xml files must follow the same xml format as the existing Font.xml file. 

## Motivation and context

When creating new themes for a skin it is possible to define new graphic elements by providing
a file in the skin's /media directory, for example media/ThemeName.xbt. 

It is also possible to define new color definitions for your
theme by providing a file in the skin's /colors directory, for example colors/ThemeName.xml. 

Currently, if you want to define a fontset definition for your theme, you must edit the skin's Font.xml file, so typically a theme creator will not go to the trouble of providing theme specific fonts. 

With this change, a theme creator will be able to provide a fontset definition by providing a file in the skin's /fonts directory, for example fonts/ThemeName.xml. The theme creator must also provide the specific font files needed by the defined fontset. 

So, for example, a complete theme for a skin could now be provided in a zip file with content like:
 - media/ThemeName.xbt
 - colors/ThemeName.xml
 - fonts/ThemeName.xml
 - fonts/ThemeNameFont1.ttf
 - fonts/ThemeNameFont2.ttf
 - ...

## How has this been tested?

Tested on Windows 10 with xbmc/master. 

Used the metropolis skin to test theme changes.

1. Added ThemeName.xml file to Kodi/addons/skin.metropolis/fonts. Contents of fonts/ThemeName.xml had a &lt;fontset&gt; definition named ThemeName. The &lt;fontset&gt; included &lt;font&gt; definitions that required 
new ttf files. The new ttf files were added to the /fonts directory.
2. From Settings->Interface->Skin->Fonts made sure that 'ThemeName' was now one of the available options.
3. Selected 'ThemeName' from the selection list and made sure that the correct fonts were loaded.
4. Made sure that &lt;include&gt; directives work in the xml files that are in the /fonts directory.
5. Tested error paths
	- Bad xml file in /fonts does not cause errors in looking for or loading fonts.
	- Deleting or corrupting xml file in /fonts directory after fontset is selected results in default fontset being used.

## What is the effect on users?

Made it easier to customize kodi by allowing new fontsets to be defined in separate files.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

## Notes
The Skin page in the wiki would need to be updated:
[https://kodi.wiki/view/Settings/Interface/Skin](https://kodi.wiki/view/Settings/Interface/Skin)

The section on 'Theme' and 'Fonts' would need some new content. 

For the 'Theme' section, add the line:

If a fontset matching the theme name is available, this will also be applied when changing themes.

For the 'Fonts' section, add the line:

Adding an xml file to the skin's Font folder will enable you to add to the fontsets available to the skin. The new xml file must follow the same format as the skin's Font.xml file.

2023-03-16 17:48 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR22993-0001-94681295a5-Look-for-fontset-definitions-in-xm.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25912/artifact/PR22993-0001-94681295a5-Look-for-fontset-definitions-in-xm.diff)
 - [PR22993.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25912/artifact/PR22993.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-03-16 18:36 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR22993-0001-b9129cf811-Look-for-fontset-definitions-in-xm.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25913/artifact/PR22993-0001-b9129cf811-Look-for-fontset-definitions-in-xm.diff)
 - [PR22993.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25913/artifact/PR22993.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-05-10 22:11 UTC, enen92 commented on xbmc/addons/Skin.cpp
> +        if (idAttr != nullptr)
```suggestion
        if (idAttr)
```

You do the same below, so please try to stick with the same style

2023-05-10 22:13 UTC, enen92 reviewed
Cool feature. My only suggestion is to try to work it a bit more to avoid the duplicate code in Skin.cpp. it seems most of it can be moved to some new reusable method.

2023-05-15 22:40 UTC, smfontes commented
Made code style formatting changes per Jenkins

2023-05-16 13:53 UTC, smfontes commented
Looks like the build failed due to running out of disk space. Hopefully one of you guys know what to do about that :-)

2023-05-29 19:01 UTC, enen92 requested changes

2023-05-29 19:01 UTC, enen92 commented on xbmc/addons/Skin.cpp
> +void CSkinInfo::GetFontsetsFromFile(const std::string fontsetFilePath,
Check https://github.com/xbmc/xbmc/commit/2b322c4e4b06f9b3d7d59b1bcb3e0b71f717a926

2023-06-07 17:01 UTC, enen92 commented
Ping @smfontes

2023-06-15 19:28 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR22993-0001-f69b9132d7-Look-for-fontset-definitions-in-xm.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26821/artifact/PR22993-0001-f69b9132d7-Look-for-fontset-definitions-in-xm.diff)
 - [PR22993.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26821/artifact/PR22993.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-06-15 21:36 UTC, enen92 commented
Jenkins build this please

2023-06-15 21:54 UTC, enen92 approved these changes

2023-06-21 00:28 UTC, smfontes commented
Is there anything I have to do to get this to build again? Last build failed due to an ffmpeg missing error - nothing to do with this code.

2023-06-21 05:08 UTC, enen92 commented
Jenkins build this please

2023-06-21 07:44 UTC, merged

2023-06-21 07:46 UTC, enen92 commented
@smfontes mind sharing the new feature in https://forum.kodi.tv/showthread.php?tid=372280 ? Usually we use these threads to spread the news. It doesn't require anything fancy just a small note