[UPnP] Add extensions to libplatinum mimetypes
xbmc/xbmc pull request #22996
Opened 2023-03-17 18:17 UTC by enen92

## Description
This PR adds a new map that allows kodi to define mimetype extensions (or to override existing ones) to those already defined by libplatinum. This map takes precedence over all the others.
Libplatinum lacks the mapping for m2ts which leads external clients not to recognise the item.

## Motivation and context
Fixes https://github.com/xbmc/xbmc/issues/22994

## How has this been tested?
Kodi as server, philips tv default file browser as client

## What is the effect on users?
Better support for upnp

## Screenshots (if appropriate):

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

2023-03-17 19:05 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR22996-0001-c76328e18b-UPnP-Add-extensions-to-libplatinum.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25920/artifact/PR22996-0001-c76328e18b-UPnP-Add-extensions-to-libplatinum.diff)
 - [PR22996.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25920/artifact/PR22996.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-03-18 02:56 UTC, fuzzard commented on xbmc/network/upnp/UPnPInternal.cpp
> +        mime = "";
Worthwhile just dropping the isempty check and putting this block inside the previous isempty check after the for loop?

2023-03-18 02:57 UTC, fuzzard approved these changes
Seems like a clean way to extend an otherwise forgotten lib

2023-03-18 08:37 UTC, Montellese requested changes
Looks good apart from the proposed changes.

2023-03-18 08:37 UTC, Montellese commented on xbmc/network/upnp/UPnPInternal.cpp
> +      for (const NPT_HttpFileRequestHandler_DefaultFileTypeMapEntry& mimeTypeEntry :
Maybe use `std::find_if()` instead of writing the loop yourself.

2023-03-18 10:23 UTC, enen92 commented
thanks for the review, should be fixed in the last iteration.

2023-03-18 10:49 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR22996-0001-16b33b4592-UPnP-Add-extensions-to-libplatinum.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25933/artifact/PR22996-0001-16b33b4592-UPnP-Add-extensions-to-libplatinum.diff)
 - [PR22996.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25933/artifact/PR22996.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-03-18 21:54 UTC, Montellese approved these changes
Looks good apart from the suggestions.

2023-03-18 21:54 UTC, Montellese commented on xbmc/network/upnp/UPnPInternal.cpp
> +      auto KodiOverrideMimeType = std::find_if(
Can be `const`. And shouldn't all local variables start with a lower case letter?

2023-03-18 21:54 UTC, Montellese commented on xbmc/network/upnp/UPnPInternal.cpp
> +          [&](const NPT_HttpFileRequestHandler_DefaultFileTypeMapEntry& mimeTypeEntry) {
```suggestion
          [&](const auto& mimeTypeEntry) {
```

2023-03-18 22:34 UTC, garbear approved these changes
LGTM

2023-03-19 01:07 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR22996-0001-d7a49f2445-UPnP-Add-extensions-to-libplatinum.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25956/artifact/PR22996-0001-d7a49f2445-UPnP-Add-extensions-to-libplatinum.diff)
 - [PR22996.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/25956/artifact/PR22996.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-03-19 10:23 UTC, merged