[Buildsteps] Use xcode 14.2 and relevant SDK's for Apple platforms
xbmc/xbmc pull request #23348
Opened 2023-05-30 06:37 UTC by fuzzard

## Description
Bump default xcode and sdk's for Apple platforms

## Motivation and context
Bump default xcode and sdk's for Apple platforms

## How has this been tested?
Lets go Jenkins!

## What is the effect on users?
N/A

## Screenshots (if appropriate):

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2023-05-30 12:49 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR23348-0001-6af5734ef6-fix-variable-message-set-but-not-u.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26719/artifact/PR23348-0001-6af5734ef6-fix-variable-message-set-but-not-u.diff)
 - [PR23348-0002-4e5da97c66-osx-fix-sprintf-is-deprecated.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26719/artifact/PR23348-0002-4e5da97c66-osx-fix-sprintf-is-deprecated.diff)
 - [PR23348-0005-9916af9eaf-pictures-fix-sprintf-is-deprecated.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26719/artifact/PR23348-0005-9916af9eaf-pictures-fix-sprintf-is-deprecated.diff)
 - [PR23348-0009-13b4babfdd-network-cddb-fix-sprintf-is-deprec.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26719/artifact/PR23348-0009-13b4babfdd-network-cddb-fix-sprintf-is-deprec.diff)
 - [PR23348-0010-cc3581fe40-xbmc-utils-httpresponse-fix-sprint.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26719/artifact/PR23348-0010-cc3581fe40-xbmc-utils-httpresponse-fix-sprint.diff)
 - [PR23348-0011-af4f2b73f3-xbmc-utils-ScraperParser-fix-sprin.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26719/artifact/PR23348-0011-af4f2b73f3-xbmc-utils-ScraperParser-fix-sprin.diff)
 - [PR23348.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26719/artifact/PR23348.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-05-31 04:39 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR23348-0001-ffac8d3b94-fix-variable-message-set-but-not-u.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26725/artifact/PR23348-0001-ffac8d3b94-fix-variable-message-set-but-not-u.diff)
 - [PR23348-0002-af0f2ef461-fix-sprintf-is-deprecated.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26725/artifact/PR23348-0002-af0f2ef461-fix-sprintf-is-deprecated.diff)
 - [PR23348.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26725/artifact/PR23348.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-05-31 04:57 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR23348-0001-ffac8d3b94-fix-variable-message-set-but-not-u.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26726/artifact/PR23348-0001-ffac8d3b94-fix-variable-message-set-but-not-u.diff)
 - [PR23348-0002-d2e27e7c3d-fix-sprintf-is-deprecated.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26726/artifact/PR23348-0002-d2e27e7c3d-fix-sprintf-is-deprecated.diff)
 - [PR23348.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26726/artifact/PR23348.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-05-31 05:27 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR23348-0001-ffac8d3b94-fix-variable-message-set-but-not-u.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26727/artifact/PR23348-0001-ffac8d3b94-fix-variable-message-set-but-not-u.diff)
 - [PR23348-0002-c16c07312d-fix-sprintf-is-deprecated.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26727/artifact/PR23348-0002-c16c07312d-fix-sprintf-is-deprecated.diff)
 - [PR23348.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26727/artifact/PR23348.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-05-31 08:04 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR23348-0001-ffac8d3b94-fix-variable-message-set-but-not-u.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26728/artifact/PR23348-0001-ffac8d3b94-fix-variable-message-set-but-not-u.diff)
 - [PR23348-0002-c16c07312d-fix-sprintf-is-deprecated.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26728/artifact/PR23348-0002-c16c07312d-fix-sprintf-is-deprecated.diff)
 - [PR23348-0003-8d15aa31a2-ios-audioengine-sink-Replace-some-.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26728/artifact/PR23348-0003-8d15aa31a2-ios-audioengine-sink-Replace-some-.diff)
 - [PR23348.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/26728/artifact/PR23348.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-05-31 12:56 UTC, Rechi requested changes
Whit this PR three new warning appear.

```
xbmc/filesystem/BlurayDirectory.cpp:286:5: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
    sprintf(tmp.data() + (i * 2), "%02x", buf[i]);
    ^
```


```
xbmc/platform/darwin/peripherals/Input_Gamecontroller.mm:234:48: warning: capturing 'controller' strongly in this block is likely to lead to a retain cycle [-Warc-retain-cycles]
              withplayerIndex:static_cast<int>(controller.playerIndex)];
                                               ^~~~~~~~~~
```


```
xbmc/platform/darwin/peripherals/Input_Gamecontroller.mm:442:14: warning: 'controllerPausedHandler' is deprecated: first deprecated in macOS 10.15 - controllerPausedHandler has been deprecated. Use the Menu button found on the controller's profile, if it exists. [-Wdeprecated-declarations]
  controller.controllerPausedHandler = ^(GCController* controller) {
             ^
```

2023-05-31 22:48 UTC, fuzzard commented
Well aware. As it stands i dont have solutions/time for them, so as its under the warning threshold's i'll let them through as is and circle back later possibly. The ~60 other warning fixes resolved in this PR already was all i had time for currently.

If you have fixes for them, feel free to PR, or push to this commit

2023-06-02 21:42 UTC, kambala-decapitator approved these changes

2023-06-03 17:10 UTC, merged