Acb (pre-webOS 5.0) support
xbmc/xbmc pull request #23834
Opened 2023-09-27 16:02 UTC by mariotaku

## Description

On webOS 4.0, MediaPlayerAPIs has to be used with AcbAPI instead of exported window. This PR adds feature to use that when  exported window feature is not available.

## Motivation and context
To make Kodi support webOS 4.x

## How has this been tested?
Compiled app has been tested on webOS 5 TV and webOS 4 TV, both can perform video playback without issue.

## What is the effect on users?
webOS 4 users can now play videos

## Screenshots (if appropriate):

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2023-09-27 16:28 UTC, sundermann commented
Thank you for polishing up the work on libacb!

I do see a small problem during packaging:
```
-- Installing: /home/jenkins/jenkins-root/workspace/webos-dockerlinux_webosgles/build/tools/webOS/packaging/lib/libatomic.so.1
-- Installing: /home/jenkins/jenkins-root/workspace/webos-dockerlinux_webosgles/build/tools/webOS/packaging/lib/libatomic.so.1.2.0
-- Installing: /home/jenkins/jenkins-root/workspace/webos-dockerlinux_webosgles/build/tools/webOS/packaging/lib/libcrypt.so.1
-- Installing: /home/jenkins/jenkins-root/workspace/webos-dockerlinux_webosgles/build/tools/webOS/packaging/lib/libcrypt-2.12.2.so
-- Installing: /home/jenkins/jenkins-root/workspace/webos-dockerlinux_webosgles/build/tools/webOS/packaging/lib/libdrm.so.2
-- Installing: /home/jenkins/jenkins-root/workspace/webos-dockerlinux_webosgles/build/tools/webOS/packaging/lib/libdrm.so.2.4.0
-- Installing: /home/jenkins/jenkins-root/workspace/webos-dockerlinux_webosgles/build/tools/webOS/packaging/lib/libshairplay.so.0
-- Installing: /home/jenkins/jenkins-root/workspace/webos-dockerlinux_webosgles/build/tools/webOS/packaging/lib/libshairplay.so.0.0.0
```

The shim library `libacb` from `webos-userland` is not installed making kodi fail to launch on webOS 5+. A bit more context on this matter: webOS 5+ uses a different mechanism and thus does not bundle the deprecated libacb anymore. On webOS 5+ no acb functions are actually called so bundling the shim libraries from `webos-userland` is not a problem. This works because the jailed environment is set up in a way that system libraries will take precedence over any custom bundled ones. So bundling `libacb` is needed to make kodi able to resolve the library/functions on startup. Just add `libacb` [here](https://github.com/webosbrew/xbmc/blob/feature/webOS/cmake/scripts/webos/Install.cmake#L31)

2023-09-27 16:57 UTC, sundermann requested changes

2023-09-27 16:57 UTC, sundermann commented on xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecStarfish.cpp
> +  AcbAPI_setDisplayWindow(acbId, 0, 0, hints.width, hints.height, true, nullptr);
Unfortunately, this has to happen in `CRendererStarfish`. I'd suggest adding a field for `acbId` in the `StarfishVideoBuffer`. Then calling the function in `ManageRenderArea`. Also, videos may not always run fullscreen. For instance, if you display a SBS 3D video as 2D. There is some logic inside the renderer that calculates the target display coordinates. There's another catch here though. The target coordinates can be negative which the API will not accept. You can test this when a video partly goes offscreen, i.e. when using a zoom option > 1.

2023-09-27 16:57 UTC, sundermann commented on xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecStarfish.cpp
> +        m_starfishResource->StartPlaying();
Is this here placed correctly? I could imagine that it'd be better placed when a `PF_EVENT_TYPE_STR_STATE_UPDATE__LOADCOMPLETED` or `PF_EVENT_TYPE_STR_STATE_UPDATE__PLAYING` is received. Maybe also call `AcbAPI_setState(acbId, APPSTATE_FOREGROUND, PLAYSTATE_PAUSED, NULL);` when `PF_EVENT_TYPE_STR_STATE_UPDATE__PAUSED` is received.

2023-09-28 14:49 UTC, sundermann requested changes

2023-09-28 14:49 UTC, sundermann commented on xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererStarfish.cpp
> +    if (!AcbAPI_initialize(m_acbId, PLAYER_TYPE_MSE, getenv("APPID"), AcbCallback))
This is probably also better happening in the decoder

2023-09-28 14:49 UTC, sundermann commented on xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererStarfish.cpp
> +  (void)acbId;
Also why do you need to cast all of these to `void`? Avoiding unused parameter warnings?

2023-09-28 14:49 UTC, sundermann commented on xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecStarfish.cpp
> +  auto buffer = dynamic_cast<CStarfishVideoBuffer*>(m_videobuffer.videoBuffer);
```suggestion
  auto buffer = static_cast<CStarfishVideoBuffer*>(m_videobuffer.videoBuffer);
```

2023-09-28 15:00 UTC, mariotaku commented on xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererStarfish.cpp
> +  (void)acbId;
Yes exactly. I'll ad some logging instead.

2023-09-28 18:17 UTC, Danar435 commented
You have my sincerest gratitude

2023-09-28 23:15 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR23834-0003-3fa1b31b98-webos-always-clip-video-renderer-t.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/27687/artifact/PR23834-0003-3fa1b31b98-webos-always-clip-video-renderer-t.diff)
 - [PR23834-0004-ff4379e3cc-Updated-according-to-code-review.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/27687/artifact/PR23834-0004-ff4379e3cc-Updated-according-to-code-review.diff)
 - [PR23834.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/27687/artifact/PR23834.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-09-29 06:54 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR23834-0003-3fa1b31b98-webos-always-clip-video-renderer-t.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/27691/artifact/PR23834-0003-3fa1b31b98-webos-always-clip-video-renderer-t.diff)
 - [PR23834.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/27691/artifact/PR23834.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-09-29 10:49 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR23834-0003-3fa1b31b98-webos-always-clip-video-renderer-t.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/27693/artifact/PR23834-0003-3fa1b31b98-webos-always-clip-video-renderer-t.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-09-29 13:13 UTC, yol commented on xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecStarfish.cpp
> +      AcbAPI_setMediaVideoData(m_acbId, logstr.c_str());
`if (m_acbId)` missing?

2023-09-29 14:05 UTC, sundermann requested changes

2023-09-29 15:06 UTC, sundermann approved these changes

2023-09-29 20:52 UTC, sundermann commented
Can you squash the fixups?

2023-09-29 22:50 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR23834-0003-3fa1b31b98-webos-always-clip-video-renderer-t.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/27701/artifact/PR23834-0003-3fa1b31b98-webos-always-clip-video-renderer-t.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2023-09-30 12:14 UTC, sundermann commented
Jenkins build this please

2023-10-01 14:23 UTC, DannAberHardt commented
Tested on LG C8 and picture and sound is working :-)
Audio Passthrough does not work on arc for me.

2023-10-02 20:52 UTC, sundermann commented
It is possible the passthrough starfish sink needs a similar acb integration as the video decoder.

2023-10-03 20:49 UTC, merged

2023-10-03 21:15 UTC, sundermann commented
@DannAberHardt Maybe you can test #23866 build once it's available?