Fix bug - if art is changed through Choose Art button in Information Dialog then thumbnail isn't updated when return to library.
xbmc/xbmc pull request #24176
Opened 2023-12-03 15:30 UTC by 78andyp

## Description

As part of #24131 I found that the thumbnail in the library wasn't updated when art was changed in the video information dialog.

This is also true using the existing Choose Art button.

## Motivation and context

Before

Art Changed
![image](https://github.com/xbmc/xbmc/assets/99039295/377b24bd-5e9e-43d9-989e-9b548c81046a)
![image](https://github.com/xbmc/xbmc/assets/99039295/967735fd-e7b7-415a-97ba-0a820e711185)

... but not reflected in library upon return.
![image](https://github.com/xbmc/xbmc/assets/99039295/68a842c7-4bc6-4b17-b588-83b87bcd4531)

After - change is reflected
![image](https://github.com/xbmc/xbmc/assets/99039295/c21080d9-9bb2-441e-b0c4-88bafeaa11c7)

## How has this been tested?

Windows 11 x64

## What is the effect on users?

Art thumbnail correctly shown on library screen (without having to exit library and re-enter)

## Screenshots (if appropriate):

As above.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2023-12-03 16:19 UTC, CastagnaIT commented
please amend your commit title its too much long and should follow the project contributing guidelines:
https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md

e.g. [GUIWindowVideoBase] Reflect update of xyz...

2023-12-09 21:07 UTC, neo1973 requested changes
Works as expected, thanks. But please update the commit description as CastagnaIT requested.

2023-12-09 22:00 UTC, 78andyp commented
> Works as expected, thanks. But please update the commit description as CastagnaIT requested.

Done. Apologies, I misread and thought he meant the title of this post.

2023-12-09 23:08 UTC, enen92 commented
Looking at the code it seems refresh is to be called later. Doesn't pDialog->needsrefresh() return true? If not maybe the issue should be fixed there instead. Or is this returning earlier on other place?

2023-12-10 14:08 UTC, 78andyp commented
> Looking at the code it seems refresh is to be called later. Doesn't pDialog->needsrefresh() return true? If not maybe the issue should be fixed there instead. Or is this returning earlier on other place?

I tried that - setting it on `OnGetArt()`  - but it doesn't refresh the thumbnail.

2023-12-15 14:42 UTC, 78andyp reviewed
Changed commit title.

2024-01-01 02:02 UTC, CrystalP commented
I gave it a try, Refresh(true) was not needed, Refresh() was enough?

Placement: it looks like `ShowInfo` has two main cases, either info is already available, it will go in the branch that @78andyp modified (`if (bHasInfo)` block), or the info is not available (or a refresh was requested), then it goes to the other big logical block with the do while loop.

The logic to refresh the list is only executed after the second big block (the `if (listNeedsUpdating && IsActive())` block), so we need to either:
- have the flow to reach and activate that  `if (listNeedsUpdating && IsActive())` block instead of returning early in `if (bHasInfo)`  - without uglyfying the function too much...
- or extract the content of the `if (listNeedsUpdating && IsActive())` block into a function, called both from the `if (bHasInfo)` and its original place.

BTW looks to me like both `pDlgInfo->HasUpdatedThumb())` and `pDlgInfo->HasUpdatedUserrating())` should cause a refresh.

2024-01-01 16:13 UTC, 78andyp commented
> I gave it a try, Refresh(true) was not needed, Refresh() was enough?
> 
> Placement: it looks like `ShowInfo` has two main cases, either info is already available, it will go in the branch that @78andyp modified (`if (bHasInfo)` block), or the info is not available (or a refresh was requested), then it goes to the other big logical block with the do while loop.
> 
> The logic to refresh the list is only executed after the second big block (the `if (listNeedsUpdating && IsActive())` block), so we need to either:
> 
> * have the flow to reach and activate that  `if (listNeedsUpdating && IsActive())` block instead of returning early in `if (bHasInfo)`  - without uglyfying the function too much...
> * or extract the content of the `if (listNeedsUpdating && IsActive())` block into a function, and call it from the `if (bHasInfo)` and its original place.
> 
> BTW looks to me like both `pDlgInfo->HasUpdatedThumb())` and `pDlgInfo->HasUpdatedUserrating())` should cause a refresh.

Thanks. I'll have a look at the second option and report back.

2024-01-01 18:54 UTC, 78andyp commented
> * if (listNeedsUpdating && IsActive())

Thanks for the analysis. I'm really not clued up on the GUI side of things.

Looking at the `bool CGUIWindowVideoBase::ShowInfo(const CFileItemPtr& item2, const ScraperPtr& info2)` block there are multiple `return` statements - and it looks like a `return true` means a `Refresh()` is needed and a `return false` means it is not.

But the return status never gets acted upon - perhaps they should be.

THe only reason I used `Refresh(true);` was because that's what's used in the code if you edit art through the context menu.

I've updated the PR - do you think this is any better??

2024-01-01 20:33 UTC, CrystalP commented on xbmc/video/windows/GUIWindowVideoBase.cpp
> +
That change is not exactly equivalent (hasupdateduserrating = true with needsrefresh = false) but not needed here when handling in caller anyway.

However the part at the bottom of the loop has to move into the caller as well.

2024-01-01 20:54 UTC, CrystalP commented
Return codes in action/message handling tend to mean "action/message handled", not "need a refresh" but handling in the immediate parent works. With the appropriate comment on the meaning of the return code.

Looking at the code history, that's how it was done before PR #23674, which broke art refresh for movies inadvertently.
In addition, before that PR movie set art refresh was already broken.

However ignoring some of the existing code is not OK:
```C++
  if (IsActive()) // since we can be called from other windows (music, home) we need this check
  {
    int itemNumber = m_viewControl.GetSelectedItem();
    Refresh();
    m_viewControl.SetSelectedItem(itemNumber);
  }
```

There was nothing in the movie set path but it doesn't seem to hurt from what I tested?

2024-01-01 22:22 UTC, CrystalP commented
Since I did this for testing, might as well share it. Works for me.

[0001-video-Refresh-art-in-library-list-after-changing-mov.patch](https://github.com/xbmc/xbmc/files/13806150/0001-video-Refresh-art-in-library-list-after-changing-mov.patch)

Ironically the "Choose art" dialog (the one with art type Poster, Fanart, Banner, etc), is broken and doesn't reflect changes to art through "Poster" for example, but the info dialog underneath does...

2024-01-01 22:33 UTC, 78andyp commented
> Since I did this for testing, might as well share it. Works for me. edit: v2 for const-ification and {} initialization
> 
> [0001-video-Refresh-art-in-library-list-after-changing-mov.patch](https://github.com/xbmc/xbmc/files/13806165/0001-video-Refresh-art-in-library-list-after-changing-mov.patch)
> 
> Ironically the "Choose art" dialog (the one with art type Poster, Fanart, Banner, etc), is broken and doesn't reflect changes to art through "Poster" for example, but the info dialog underneath does...

Thanks. I think we've both done similar things (your patch v. my attempt 3) but yours saves duplication with the additional function.

I'll apply your patch.

2024-01-01 23:07 UTC, CrystalP commented
OK but the formatting of the `if (rc && IsActive())` is... not good, please move the comment on its own line.

There is another difference, at the end of ShowInfo, `return true` vs `return listNeedsUpdating`
I think the `return true` was a  mistake of the previous PR, the original code had `return listNeedsUpdating` at the end of `ShowIMDB()`. Would you agree?

2024-01-01 23:16 UTC, 78andyp commented
I've used `return listNeedsUpdating` - I agree with you.
If Jenkins doesn't fix the comment then I will.

2024-01-01 23:35 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR24176-0001-01bc9fa94f-GUIWindowVideoBase-Library-thumbna.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/28805/artifact/PR24176-0001-01bc9fa94f-GUIWindowVideoBase-Library-thumbna.diff)
 - [PR24176.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/28805/artifact/PR24176.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2024-01-02 00:51 UTC, CrystalP commented
Due to the comment length, clang format does this weird not very readable thing.
So please move the comment to its own line, and slightly alter it to
// IsActive() since we can be called from other windows (music, home) we need this check

2024-01-02 01:05 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR24176-0001-01bc9fa94f-GUIWindowVideoBase-Library-thumbna.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/28806/artifact/PR24176-0001-01bc9fa94f-GUIWindowVideoBase-Library-thumbna.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2024-01-02 12:28 UTC, 78andyp commented
> Due to the comment length, clang format does this weird not very readable thing. So please move the comment to its own line, and slightly alter it to // Test IsActive() since we can be called from other windows (music, home) we need this check

All done.

2024-01-02 15:01 UTC, CrystalP approved these changes
Good usability improvement, looks good to go.

2024-01-02 15:03 UTC, CrystalP commented
@enen92 are you OK with the solution now?

2024-01-02 15:04 UTC, neo1973 approved these changes

2024-01-02 20:30 UTC, enen92 commented
From a code standpoint looks correct. I wonder if we shouldn't do the following:

- Move the current `ShowInfo` to a private method and rename it as `ShowInfoInternal()`
- Make the new `ShowInfoAndRefresh` the new public `ShowInfo`.

Would this be fine?

2024-01-02 20:37 UTC, 78andyp commented
> From a code standpoint looks correct. I wonder if we shouldn't do the following:
> 
> * Move the current `ShowInfo` to a private method and rename it as `ShowInfoInternal()`
> * Make the new `ShowInfoAndRefresh` the new public `ShowInfo`.
> 
> Would this be fine? It simplifies the interface (less public overloads) and also clarifies the method with a single purpose regardless of whatever it's doing internally.

Sure, will do.

2024-01-02 23:53 UTC, CrystalP commented
sure that's what I was going to do next to address #24378.

2024-01-03 00:56 UTC, 78andyp commented
> From a code standpoint looks correct. I wonder if we shouldn't do the following:
> 
> * Move the current `ShowInfo` to a private method and rename it as `ShowInfoInternal()`
> * Make the new `ShowInfoAndRefresh` the new public `ShowInfo`.
> 
> Would this be fine? It simplifies the interface (less public overloads) and also clarifies the method with a single purpose regardless of whatever it's doing internally.

Pushed an update. I've left the public one as `ShowInfoAndRefresh` as it looks like it will be helpful in the future to know a `Refresh()` happens there.

2024-01-03 01:21 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR24176-0001-75653317a6-GUIWindowVideoBase-Library-thumbna.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/28835/artifact/PR24176-0001-75653317a6-GUIWindowVideoBase-Library-thumbna.diff)
 - [PR24176.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/28835/artifact/PR24176.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2024-01-03 11:23 UTC, enen92 approved these changes
LGTM

2024-01-03 14:38 UTC, merged

2024-01-03 15:27 UTC, 78andyp commented
Thanks for your support in getting it right. Happy to look.