[Estuary] Hide next if conditions for next don't met
xbmc/xbmc pull request #24270
Opened 2023-12-18 11:45 UTC by enen92

## Description
Estuary shows the next button on the side panel when a video/music is playing regardless of meeting the conditions for triggering next (e.g. a single video with no chapters, scene markers, playlist count == 1, etc). This is wrong since hitting next does nothing.
This actually sets the visible condition on this button for the cases it makes sense.

## Motivation and context
Found while working on other stuff.

## How has this been tested?
Runtime tested, single item vs playlist vs item with chapters.

## What is the effect on users?
Next icon is hidden if it doesn't have any effect.

## Screenshots (if appropriate):

**Playing a single item (no next)**
![image](https://github.com/xbmc/xbmc/assets/7375276/91da82bd-fbdc-4927-b0a5-9ef5141a4d69)

**Playing playlist (after queuing a new video)**
![image](https://github.com/xbmc/xbmc/assets/7375276/c5ab86a6-ce55-4baf-92e3-7bd604a09df8)

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

2023-12-18 17:13 UTC, jjd-uk commented
I think `Integer.IsLess(Playlist.Position(video), Playlist.Length(video))` and `Integer.IsLess(Playlist.Position(music), Playlist.Length(music))` would be better as you don't want the next button displayed when on last item in playlist since there is no next item here either.

2023-12-18 17:15 UTC, jjd-uk commented
So:

`<param name="visible" value="Integer.IsLess(Playlist.Position(video), Playlist.Length(video)) | Integer.IsLess(Playlist.Position(music), Playlist.Length(music)) | MusicPlayer.HasNext" />`

2023-12-18 17:20 UTC, jjd-uk requested changes
So:

`<param name="visible" value="Integer.IsLess(Playlist.Position(video), Playlist.Length(video)) | Integer.IsLess(Playlist.Position(music), Playlist.Length(music)) | MusicPlayer.HasNext" />`

2023-12-18 19:06 UTC, enen92 commented
@jjd-uk thanks, it makes sense :)

2023-12-18 19:59 UTC, HitcherUK commented
Also `Integer.IsLess(Playlist.Position(music), Playlist.Length(music))` and `MusicPlayer.HasNext` do the same thing don't they?

2023-12-18 20:10 UTC, jjd-uk commented
I did wonder that as well. How do PVR radio recordings identify themselves?

2023-12-18 22:34 UTC, enen92 commented
> Also `Integer.IsLess(Playlist.Position(music), Playlist.Length(music))` and `MusicPlayer.HasNext` do the same thing don't they?

Yeah just checked the implementation and it's the same. So I dropped the more complex condition in the last push. Thanks.

2023-12-18 22:43 UTC, HitcherUK commented
Odd that there's no equivalent (`VideoPlayer.HasNext`) for the video player.

2023-12-18 22:51 UTC, enen92 commented
> Odd that there's no equivalent (`VideoPlayer.HasNext`) for the video player.

Honestly I think this is more in the scope of the playlist (Playlist.HasNext) rather than the individual players.

2023-12-19 09:51 UTC, jjd-uk approved these changes

2023-12-19 10:19 UTC, merged