[VideoDB] restore compatibility with MariaDB < 10.5.2
xbmc/xbmc pull request #24505
Opened 2024-01-14 10:07 UTC by andred

Migrating the database fails when the database is on a remote MariaDB instance < 10.5.2:
    2024-01-14 08:13:48.448 T:1461     info <general>: Old database found - updating from version 121 to 129
    2024-01-14 08:14:04.686 T:1461     info <general>: Attempting to update the database kodi-video-main129 from version 121 to 129
    2024-01-14 08:14:11.105 T:1461    error <general>: SQL: [kodi-video-main129] Undefined MySQL error: Code (1064)
                                                       Query: ALTER TABLE videoversion RENAME COLUMN mediaType TO media_type

    2024-01-14 08:14:11.106 T:1461    error <general>: Exception updating database kodi-video-main129 from version 121 to 129
    2024-01-14 08:14:11.106 T:1461    error <general>: Error updating database kodi-video-main129 from version 121 to 129
    2024-01-14 08:14:11.118 T:1461    error <general>: Unable to open database: kodi-video-main120 [1049](Unknown database 'kodi-video-main120')
This means no access to the videos is possible.

As per https://mariadb.com/kb/en/alter-table/#rename-column support for rename column was only added in 10.5.2.

Rewrite the statement to support older versions as well.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2024-01-14 10:09 UTC, andred commented
Note that e.g. Synology Diskstations are still on the MariaDB 10.3.x branch. This change makes it possible to keep using those.

2024-01-14 10:43 UTC, the-black-eagle requested changes
Unfortunately, that's not compatible with sqlite3.  To be cross-compatible with everything, I suggest creating a temporary table, copying all the data across, dropping the original table, recreating it with the new column names and then copying the data back.  There are plenty of examples in the music database where this is done, eg https://github.com/xbmc/xbmc/blob/master/xbmc/music/MusicDatabase.cpp#L8995 onwards

2024-01-14 22:03 UTC, andred commented
Thank you @the-black-eagle, I believe the new version implements what you asked for, and it works fine for me as well, having forced xbmc to redo my db migration.

2024-01-15 07:19 UTC, the-black-eagle commented
Jenkins build this please

2024-01-15 08:39 UTC, the-black-eagle approved these changes
LGTM now

2024-01-20 20:20 UTC, CrystalP commented
Is there anything holding this up?

@andred if you wouldn't mind trying my PR #24538 on your older MariaDB version, the last commit uses an SQL extension that works at least in sqlite and MariaDB 11 but I'm not sure about MariaDB 10 and didn't find the relevant documentation.
The query is used whenever versions are displayed with their art (version choose dialog, versions folder, manage versions/extras dialogs)

2024-01-20 21:18 UTC, the-black-eagle commented
If you're not totally sure, might be good to ask @DaveTBlake for an opinion.

2024-01-20 22:41 UTC, CrystalP commented
This PR is a trivial change and I have no doubts. Just wondering why you didn't push the button.

2024-01-21 06:33 UTC, the-black-eagle commented
Fair.  I was expecting you to push it actually, but all good.

2024-01-21 06:33 UTC, merged

2024-01-21 19:51 UTC, CrystalP commented
no need to test the other PR with MariaDB 10.3, I set it up locally with docker and it works fine.