JSONRPC return custom error -32101 when an object is not found rathe…
xbmc/xbmc pull request #24555
Opened 2024-01-21 12:01 UTC by malard

## Description
JSONRPC returns InvalidParams when specifying an object that is simply missing from the database, the params are correct but the reference is not. 

## Motivation and context
So this provides are more intelligent response and allows the third party to determine between an error and a not found (akin to HTTP 400 and HTTP 404)

## How has this been tested?
Against a clean database with 1 movie discovered

{"jsonrpc": "2.0", "method": "VideoLibrary.GetMovieDetails", "params": { "movieid": 1, "properties": ["art"] }, "id": 55}

Returns correct data

{"jsonrpc": "2.0", "method": "VideoLibrary.GetMovieDetails", "params": { "movieid": 999, "properties": ["art"] }, "id": 55}

Returns

{"error":{"code":-32101,"message":"Invalid Object (Not Found in database)."},"id":55,"jsonrpc":"2.0"}

## What is the effect on users?
End users should not notice any difference, Application developers will be assisted with their debugging and can take advantage of this altered return to provide more contextual errors to the user.

If a developer is explicitly looking for error code -32602 then they will need to adjust their code to suit the new error code defined.

I do have an alternative proposal, which would be to preserve the error code but change the message in this scenario instead. This should be far less 'breaking'

## Screenshots (if appropriate):

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [X] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

I will update the Wiki accordingly if accepted

2024-01-21 12:29 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR24555-0001-54fabef463-changed-return-custom-error-32101-.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/29119/artifact/PR24555-0001-54fabef463-changed-return-custom-error-32101-.diff)
 - [PR24555.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/29119/artifact/PR24555.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2024-01-21 13:13 UTC, enen92 commented on xbmc/interfaces/json-rpc/VideoLibrary.cpp
> +    return InvalidObject; //Movie not found
mind adding a space after the comment marks?

2024-01-21 13:14 UTC, enen92 reviewed
I personally have nothing wrong with this but the json interface version needs a bump: https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/version.txt

Unsure if we're still in time for it considering the omega timeline. I guess that since we're still in beta and decided to have another beta it should be fine

2024-01-21 15:08 UTC, malard commented
i've changed the version to 13.4.1 as i don't believe this is a bug fix nor a major change (so treating it as a minor)
there were more cases of the comments not being to the same standard (so to speak) so touched those also

2024-01-21 15:35 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR24555-0001-54fabef463-changed-return-custom-error-32101-.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/29123/artifact/PR24555-0001-54fabef463-changed-return-custom-error-32101-.diff)
 - [PR24555-0002-db180f7dc9-changed-comments-to-be-consistent-.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/29123/artifact/PR24555-0002-db180f7dc9-changed-comments-to-be-consistent-.diff)
 - [PR24555.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/29123/artifact/PR24555.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2024-01-28 12:29 UTC, malard commented
unless anyone objects I will merge this tomorrow

2024-02-10 07:15 UTC, jenkins4kodi commented
@malard this needs a rebase

2025-02-09 08:26 UTC, ksooo requested changes, later dismissed
It seems the new error code is used solely for "not found in database" errors, and even the message contained in the error response is hard-coded for that exact case, thus the new code should be named after that, for example `NotFound` or even `NotFoundInDataBase`.

2025-08-12 22:00 UTC, garbear commented
This seems like a good feature. Any desire to rebase and get this merged?

2026-07-16 12:34 UTC, garbear commented
@malard Can this be rebased for inclusion in Beta 2?

2026-07-16 12:38 UTC, malard commented
I will do it tonight, I could probably get Claude to do a pass on this with supervision to fix up more gaps if you want?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Garrett Brown ***@***.***>
Sent: Thursday, 16 July 2026 13:34:52
To: xbmc/xbmc ***@***.***>
Cc: Martin Ellis ***@***.***>; Mention ***@***.***>
Subject: Re: [xbmc/xbmc] JSONRPC return custom error -32101 when an object is not found rathe… (PR #24555)

[https://avatars.githubusercontent.com/u/531482?s=20&v=4]garbear left a comment (xbmc/xbmc#24555)<https://github.com/xbmc/xbmc/pull/24555#issuecomment-4991866256>

@malard<https://github.com/malard> Can this be rebased for inclusion in Beta 2?

—
Reply to this email directly, view it on GitHub<https://github.com/xbmc/xbmc/pull/24555?email_source=notifications&email_token=AAEFI55V55E6W5YLCW72XM35FDDWZA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTIOJZGE4DMNRSGU3KM4TFMFZW63VHNVSW45DJN5XKKZLWMVXHJLDGN5XXIZLSL5RWY2LDNM#issuecomment-4991866256>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAEFI5ZVHPI7KAGFFL4TU6L5FDDWZAVCNFSNUABDKJSXA33TNF2G64TZHMYTEMJXGYYTIO2JONZXKZJ3GIYDSMRVGU2DKNZVUF3AE>.
Triage notifications, keep track of coding agent tasks and review pull requests on the go with GitHub Mobile for iOS<https://github.com/notifications/mobile/ios/AAEFI5ZIQHQUVLPYHCWLO4D5FDDWZA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTIOJZGE4DMNRSGU3KM4TFMFZW63VHNVSW45DJN5XKKZLWMVXHJKTGN5XXIZLSL5UW64Y> and Android<https://github.com/notifications/mobile/android/AAEFI5YTZZQYUIFHRN6GICT5FDDWZA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTIOJZGE4DMNRSGU3KM4TFMFZW63VHNVSW45DJN5XKKZLWMVXHJLTGN5XXIZLSL5QW4ZDSN5UWI>. Download it today!
You are receiving this because you were mentioned.Message ID: ***@***.***>

2026-07-16 13:20 UTC, garbear commented
Sure, that would be welcome. @kodiai please review

2026-07-26 21:48 UTC, garbear commented
Is this wanted for Beta 2? We got about a week until release.

2026-08-01 17:06 UTC, garbear commented
Last chance, do we bump to v23?

2026-08-01 17:27 UTC, malard commented
I am sorry, I don't have time to contribute right now

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Garrett Brown ***@***.***>
Sent: Saturday, 01 August 2026 18:06:52
To: xbmc/xbmc ***@***.***>
Cc: Martin Ellis ***@***.***>; Mention ***@***.***>
Subject: Re: [xbmc/xbmc] JSONRPC return custom error -32101 when an object is not found rathe… (PR #24555)

[https://avatars.githubusercontent.com/u/531482?s=20&v=4]garbear left a comment (xbmc/xbmc#24555)<https://github.com/xbmc/xbmc/pull/24555#issuecomment-5152467782>

Last chance, do we bump to v23?

—
Reply to this email directly, view it on GitHub<https://github.com/xbmc/xbmc/pull/24555?email_source=notifications&email_token=AAEFI53WVAPWQP7LSN4OAKT5HYPSZA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTKMJVGI2DMNZXHAZKM4TFMFZW63VHNVSW45DJN5XKKZLWMVXHJLDGN5XXIZLSL5RWY2LDNM#issuecomment-5152467782>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAEFI5675PXXLRSIVVPNE2D5HYPSZAVCNFSNUABDKJSXA33TNF2G64TZHMYTEMJXGYYTIO2JONZXKZJ3GIYDSMRVGU2DKNZVUF3AE>.
Triage notifications, keep track of coding agent tasks and review pull requests on the go with GitHub Mobile for iOS<https://github.com/notifications/mobile/ios/AAEFI52NQGTBPWHP2ELEQ5L5HYPSZA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTKMJVGI2DMNZXHAZKM4TFMFZW63VHNVSW45DJN5XKKZLWMVXHJKTGN5XXIZLSL5UW64Y> and Android<https://github.com/notifications/mobile/android/AAEFI56JP34XSKM7TBMFQOD5HYPSZA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTKMJVGI2DMNZXHAZKM4TFMFZW63VHNVSW45DJN5XKKZLWMVXHJLTGN5XXIZLSL5QW4ZDSN5UWI>. Download it today!
You are receiving this because you were mentioned.Message ID: ***@***.***>

2026-08-01 18:13 UTC, garbear commented
We understand. If the situation changes, we can retarget this to v22 RC 1, which will be the cuttof for any API bumps.

2026-08-05 23:05 UTC, malard commented
Rebased onto current master and reworked. This is now a single commit, +62/-31, and mergeable.

@ksooo — your review was right, and it changed the shape of this. `InvalidObject` was named and worded for the database case only, so I have dropped it in favour of a general **`NotFound` (-32098)** that also covers the VFS, PVR and add-ons rather than needing a near-duplicate code later. The hardcoded "Not Found in database" message is gone.

While reworking it I found the same problem in a worse form. `Player.Open` posts playback asynchronously and returns `ACK` before anything is attempted, so it reports success even when the file cannot be reached — a client gets "OK" and nothing plays. So there is a second status, **`Unavailable` (-32097)**, for a reference that is valid but whose content is unreachable. The two are deliberately distinct because the remedies are opposite: `NotFound` means discard the reference, `Unavailable` means keep it and retry when the storage returns. The PVR branches of `Player.Open` already returned `FailedToExecute` on failure; this brings the generic path into line with them.

Also picked up along the way: `AudioLibrary` had the same eight artist/album/song cases as `VideoLibrary` and was missed originally, so music and video now behave the same.

One deliberate choice worth flagging: the reserved-range comment is corrected from `-32099..-32000` to `-32100..-32000`. That is one code point more than JSON-RPC 2.0 reserves, but it matches what Kodi already does — `FailedToExecute` has been `-32100` for years — and it means no existing status has to move.

@garbear — you asked twice about getting this in and I did not have the time then. It is ready now if you would like to take a look. Verified by hand against a 1156 movie / 43 show library; the exact calls and responses are in the description, including the regression checks that malformed params still return `-32602` with their `error.data` intact and that reachable content still plays.

2026-08-06 11:47 UTC, merged