Fix some UB like memcpy(NULL, NULL, 0)
xbmc/xbmc pull request #25820
Opened 2024-10-11 10:31 UTC by hribz

## Description

There are some undefined behaviors like `memcpy(NULL, NULL, 0)` in current source code.

## Motivation and context

Fix #25819 

## How has this been tested?

Just some trivial change.

## What is the effect on users?

Eliminating undefined behaviors make program more stable.

## Screenshots (if appropriate):

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2024-10-11 10:33 UTC, enen92 commented on lib/libUPnP/Neptune/Source/Core/NptUtils.cpp
> +        if (data_size && separator_length) {
This is an external library, can you please add the .patch file as well?

2024-10-11 18:40 UTC, lrusak commented
The problem with this change is that is it valid to proceed if the memcpy is protected?

Should special handling be taken in that case that the non protected path gets taken or should we just throw an exception or trigger an assert?

2024-10-11 20:12 UTC, neo1973 requested changes

2024-10-11 20:12 UTC, neo1973 commented on xbmc/XBDateTime.cpp
> +  m_timeSpan.lowDateTime = 0;
It's simpler to use a delegating constructor like this IMO:
```cpp
CDateTimeSpan::CDateTimeSpan(int day, int hour, int minute, int second) : CDateTimeSpan()
{
  SetDateTimeSpan(day, hour, minute, second);
}
```

2024-10-11 20:12 UTC, neo1973 commented on xbmc-xrandr.c
> +    memcpy(dest->params, params, nparams * sizeof(XFixed));
Calling `malloc` with size 0 is implementation defined. Better change it to this for predictable behavior:
```cpp
static void set_transform(
    transform_t* dest, XTransform* transform, char* filter, XFixed* params, int nparams)
{
  dest->transform = *transform;
  dest->filter = strdup(filter);
  dest->nparams = nparams;
  if (nparams)
  {
    dest->params = malloc(nparams * sizeof(XFixed));
    memcpy(dest->params, params, nparams * sizeof(XFixed));
  }
  else
    dest->params = NULL;
}
```

2024-10-12 02:28 UTC, hribz commented
> The problem with this change is that is it valid to proceed if the memcpy is protected?
> 
> Should special handling be taken in that case that the non protected path gets taken or should we just throw an exception or trigger an assert?

The main issue with the relevant code lies in the assumption that when `count` is 0, `memcpy(dest, src, count)` will do nothing, hence `dest` or `src` can be NULL. However, even if `count` is 0, having `dest` or `src` as NULL constitutes undefined behavior (#25819 has more specific explaination).

Therefore, I think that protect the `memcpy` function can eliminate this undefined behavior while maintaining its original semantics.

2024-10-12 03:09 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR25820.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/31582/artifact/PR25820.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2024-10-22 12:28 UTC, neo1973 commented on xbmc/dbwrappers/mysqldataset.cpp
> +  std::string strResult = std::string(mysqlStrAccumFinish(&acc));
```suggestion
  std::string strResult = mysqlStrAccumFinish(&acc);
```

2024-10-22 12:29 UTC, neo1973 commented
Please remove the unnecessary "[Merge branch 'xbmc:master' into master](https://github.com/xbmc/xbmc/pull/25820/commits/73abb79eaea52f759d42228d000db18a6e947411)" commit.

2024-10-22 18:53 UTC, neo1973 commented
Jenkins build this please.

2024-10-22 19:54 UTC, neo1973 reviewed
The end result looks now good :+1:

What's not so nice are the commits, they are not structured properly. Please clean them up with one meaningful change per commit.

2024-10-23 02:18 UTC, hribz commented
> The end result looks now good 👍
> 
> What's not so nice are the commits, they are not structured properly. Please clean them up with one meaningful change per commit.

I'm not very familiar with git. Could you please help me check if the new commit complies with the standards? Thank you!

2024-10-23 19:36 UTC, neo1973 approved these changes
Thank you, looks good to me :slightly_smiling_face:

2024-10-27 13:58 UTC, merged