[DVDSubtitlesLibass] Do not load embedded fonts if override fonts is enabled
xbmc/xbmc pull request #25842
Opened 2024-10-16 21:41 UTC by LIJI32

## Description
Do not load embedded fonts if the user wants to override them with the user-selected font

## Motivation and context
Sometime between Kodi 19 and 21 a bug was introduced that allowed subtitles to bypass this font override setting if a font of the same name as the user-selected subtitle font was embedded.

## How has this been tested?
By painfully debugging Kodi and libass for hours to find this regression

## What is the effect on users?
Users will not have to suffer from disgustingly ugly fonts in their subtitles.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

2024-10-16 22:03 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR25842-0001-c2081b7af3-Do-not-load-embedded-fonts-if-the-.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/31636/artifact/PR25842-0001-c2081b7af3-Do-not-load-embedded-fonts-if-the-.diff)
 - [PR25842.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/31636/artifact/PR25842.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2024-10-17 06:33 UTC, CastagnaIT approved these changes
seem to have sense because fonts loaded from
FONT::FONTPATH::TEMP
come from ffmpeg workaround

2024-10-17 06:33 UTC, CastagnaIT commented on xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp
> +  bool overrideFont = settings->GetBool(CSettings::SETTING_SUBTITLES_OVERRIDEFONTS);
can you add const?
```suggestion
  const bool overrideFont = settings->GetBool(CSettings::SETTING_SUBTITLES_OVERRIDEFONTS);
```

2024-10-17 06:36 UTC, CastagnaIT requested changes

2024-10-17 06:36 UTC, CastagnaIT commented on xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp
>    const std::shared_ptr<CSettings> settings = CServiceBroker::GetSettingsComponent()->GetSettings();
you also forgot to move the CSettings above

2024-10-17 10:37 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR25842-0001-c2081b7af3-Do-not-load-embedded-fonts-if-the-.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/31638/artifact/PR25842-0001-c2081b7af3-Do-not-load-embedded-fonts-if-the-.diff)
 - [PR25842-0002-a8ae3a01e1-Update-xbmc-cores-VideoPlayer-DVDS.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/31638/artifact/PR25842-0002-a8ae3a01e1-Update-xbmc-cores-VideoPlayer-DVDS.diff)
 - [PR25842.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/31638/artifact/PR25842.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2024-10-17 10:58 UTC, jenkins4kodi commented
I've made some formatting changes to meet the current code style. The diffs are available in the following links:
 - [PR25842-0001-c2081b7af3-Do-not-load-embedded-fonts-if-the-.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/31639/artifact/PR25842-0001-c2081b7af3-Do-not-load-embedded-fonts-if-the-.diff)
 - [PR25842-0002-a8ae3a01e1-Update-xbmc-cores-VideoPlayer-DVDS.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/31639/artifact/PR25842-0002-a8ae3a01e1-Update-xbmc-cores-VideoPlayer-DVDS.diff)

For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

2024-11-20 22:09 UTC, neo1973 commented
Hi @LIJI32, could you please follow up on @CastagnaIT requests so that we can merge this? Thank you.

2024-11-22 06:40 UTC, CastagnaIT approved these changes
the commit title doesn't exactly follow the rules,
but since it's your first PR we can be more flexible

2024-11-23 08:16 UTC, merged